### ISSUE TITLE
Implement find

### ISSUE THREAD

**Issue by mcharsley** [uutils/coreutils#1013]
Would anyone have an issue with me adding an implementation for "find" to the project?

**Comment by wimh** [comment]
You are aware that "find" is not part of coreutils, but [GNU Find Utilities](https://www.gnu.org/software/findutils/)? (Just like "xargs", see #947).

**Comment by mcharsley** [comment]
Yes. It has been pointed out to me by several of my colleagues :-)

I note that the giuthub project is uutils/coreutils. As a complete noob at
github, would it make sense to create a new uutils/findutils project? Is
uutils a parent directory/project that can have multiple projects
underneath it?

thanks

Mark

**Comment by wimh** [comment]
uutils is a [github organisation](https://github.com/blog/674-introducing-organizations). You are not member of that organisation (neither am I), so you can't create projects underneath it. But as long as you are able to do the administration yourself, there is no need to do so. You can just create a new personal repository. If you keep it public, everybody else can clone it and send pull requests. In the future it would always be possible for an organisation like uutils to adopt that project.

You can copy code from other projects if you use the same (or an compatible) license. Just make sure to attribute the authors and source.

Please let me know if you need further assistance. After you have created mcharsley/findutils, I can [watch](https://help.github.com/articles/watching-repositories/) it, and we can discuss in an issue you create there.

**Comment by wimh** [comment]
Note that my previous comment is based on the assumption that "find" is out of scope for this project. I would expect it is, because "xargs" was also considered out of scope.

**Comment by mcharsley** [comment]
Cool. I'll reach out again when I've got slightly more written (it only
currently supports -name, -iname and -print).

thanks

Mark

**Comment by fbstj** [comment]
this can probably be closed thanks to [uutils/findutils](https://github.com/uutils/findutils)
