### ISSUE TITLE
`mkdir -p` fails when parent directory exists

### ISSUE THREAD

**Issue by KeenS** [uutils/coreutils#1017]
I tried to build (update) uutils with uutils and got this error.

```
$ mkdir -p /usr/bin
mkdir: cannot create directory '/': File exists
mkdir: cannot create directory '/usr': File exists
mkdir: cannot create directory '/usr/bin': File exists
```

**Comment by Minoru** [comment]
I'll fix this.

**Comment by Minoru** [comment]
Oh, sorry @KeenS, I didn't notice you're a contributor too—did you file the issue in order to submit a PR that fixes it later?

**Comment by KeenS** [comment]
No, I just issued, but would have fixed if no one worked for this issue. Thank you.
