### ISSUE TITLE
shuf doesn't group identical lines

### ISSUE THREAD

**Issue by kichristensen** [uutils/coreutils#1037]
In the native implementation shuf groups identical lines like this:

```
b
h
a
a
c
```

The implementation in Rust doesn't:

```
a
b
c
a
h
```

**Comment by FSMaxB** [comment]
Coreutils doesn't group identical lines either!

```
$ shuf -e a a b c h
h
a
b
a
c
```

Maybe you tried a few times and all the permutations you got happened to randomly have this property. It's not that unlikely to happen with such a small input.

**Comment by kichristensen** [comment]
You are totally correct. I'll close this issue again
