### ISSUE TITLE
Can't make install on osx

### ISSUE THREAD

**Issue by hackeryarn** [uutils/coreutils#1040]
I am trying to make install but I am getting the below error for all utils. I've tried on stable(1.17.0) and nightly(1.19.0).

```
.../coreutils/target/release/deps/yes: No such file or directory
```

when I look in `target/release/deps`, `yes` and others are there but with an identifier on the end. 
```
yes-b02caf29803c0e4b
```

**Comment by Arcterus** [comment]
Sorry for the lack of response.  The `Makefile` hasn't really been kept up-to-date, so the best way to install atm is probably through Cargo.  I'll try to update the `Makefile` when I have time.

**Comment by Arcterus** [comment]
This should be fixed now, but let me know if there's still an issue.
