### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by sean-** [uutils/coreutils#1047]
https://www.slideshare.net/SeanChittenden/universal-userland
https://github.com/sean-/BSDCan-2017

FYI, thank you.  This project received a lot of interest from likeminded folks at BSDCan this year.  I wasn't sure how else to pass along a thank you other than to open an issue that you can close at your leisure.  Thanks again, I'm anxious to see this project evolve (and begin contributing where I can).

**Comment by mattmacy** [comment]
https://github.com/uutils/coreutils/graphs/code-frequency indicates it's been pretty quiet this year. Why not just pick one of the unimplemented utilities or port regression tests for the GNU or BSD equivalents?

**Comment by sean-** [comment]
@mattmacy That's actually what I'm planning on doing.  Or more correctly, I'm going to shave off PRs for missing flags that do overlap with the BSD utilities.

**Comment by Arcterus** [comment]
I look forward to reviewing your pull requests :)
