### ISSUE TITLE
Move away from rust-crypto

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1055]
`rust-crypto` hasn't had any activity for almost a year now, so we should probably switch to `ring` or something similar for the utils that need crypto.

**Comment by Arcterus** [comment]
Actually scratch that.  Seems that `ring` does not support some of the checksums we need (like MD5, which they removed support for).  We still should probably switch away from `rust-crypto` though given that it's been pretty much abandoned.

**Comment by JuanPotato** [comment]
We could use the crates `md5`, `sha1`, `sha2`, and `sha3`. sha3 and sha2 are by the same people who made rust-crypto. md5 hasn't been updated in about a year while the rest have been updated about two months ago according to crates.io
