### ISSUE TITLE
Consider switching help argument from `-h` to `-?` or something

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1083]
There are a few utilities where `-h` means something other than "print out a help menu" in GNU coreutils.  For example, in `sort` it means "human-readable."  If we switch the help argument to `-?`, we can just alias whatever GNU uses for help to `-?`.

**Comment by mmstick** [comment]
Sounds like a good idea to me.

**Comment by bltnkl** [comment]
Should all these -h's(meaning help) rewritten as -?s ?

**Comment by Arcterus** [comment]
Yeah, at some point.  We need to keep `-h` as an alias for `-?` for any GNU utils that happens to implements `-h` as "help" though (not sure if there are any in GNU coreutils).

**Comment by ids1024** [comment]
In zsh, `?` is a wildcard, so it would have to be escaped, which is not ideal.

This is not an issue in Bash; I don't know about other shells.

**Comment by bltnkl** [comment]
@Arcterus, also, is it worth rewriting LONG_HELP, HELP, and similar as HELP?

**Comment by Arcterus** [comment]
@ids1024 ah, that’s true.  It doesn’t really have to be `-?` though; it just needs to be something that won’t conflict with the GNU options and makes sense.
