### ISSUE TITLE
Try to match the speed of GNU yes

### ISSUE THREAD

**Issue by kBite** [uutils/coreutils#1085]
When reimplementing GNU yes, please take into consideration it's speed: https://www.reddit.com/r/unix/comments/6gxduc/how_is_gnu_yes_so_fast/

It would be nice to see it matched by this project's reimplementation :)

**Comment by FSMaxB** [comment]
But who needs that? Is it worth making simple code less simple for something that is not required?

**Comment by kBite** [comment]
I'd consider it a "bonus challenge" or "side quest". Nothing what should be matched - ok, initial wording was misleading -, but could be seen as a "decorative feature": not practical, but fancy.

**Comment by Arcterus** [comment]
The pull request I just merged makes us close enough in speed, so I'm gonna close this.
