### ISSUE TITLE
Suggestion: don't test all supported platforms for PRs

### ISSUE THREAD

**Issue by skade** [uutils/coreutils#1102]
Currently, 6 targets are tested for PRs, some of which might have spurious failures (such as nightly breaking).

This wastes resources on travis-ci and makes the PR builds take extra long, and probably only catching a small number of errors.

I suggest reducing the number of matrix builds to `linux-stable` (and possibly, `linux-${current_supported_version}`, depending on the decision in #1101.

https://travis-ci.org/uutils/coreutils/builds/311332985

**Comment by Arcterus** [comment]
I personally think we should still test nightly, but would be fine with dropping beta (we could also drop stable if we're testing a minimum required version of the compiler).  Dropping the macOS targets is a no-go though.  There are enough differences between Linux and macOS that issues can pop up occasionally, which should ideally be caught by the test suite.
