### ISSUE TITLE
Implement dd.

### ISSUE THREAD

**Issue by bmusin** [uutils/coreutils#1121]
Hi. I'm currently porting OpenBSD's dd.
One third is done, various conv block transformations and copying is left.
Prototype will be up to 7th Jan.

**Comment by bltnkl** [comment]
Is it allowed to use features from nightly?

**Comment by Arcterus** [comment]
Great!  I don’t know if it’ll be helpful but I have some stuff [here](/Arcterus/coreutils/tree/src/dd/dd.rs) that you can use.  Also please do not use nightly features.

**Comment by bltnkl** [comment]
@Arcterus, should it adhere strictly to latest POSIX or copy GNU coreutils'  features?

**Comment by Arcterus** [comment]
It should copy the GNU extensions, but if you’d prefer to just implement POSIX for now that is fine as well.

Note that we should be checking the `POSIXLY_CORRECT` variable but haven’t done so yet, so if you want to hide the GNU extensions behind that, feel free to do so.

**Comment by donkey-hotei** [comment]
Is this actually closed? If so, has a successful port of `dd` been written and just not yet merged in?

**Comment by tertsdiepraam** [comment]
Implemented in #2474
