### ISSUE TITLE
Port of non-coreutils utilities.

### ISSUE THREAD

**Issue by bmusin** [uutils/coreutils#1125]
Hi.
Do you plan to port any other useful utilities that are not included in GNU coreutils package?
They may be beneficial to users, for example, what about `ping`?

**Comment by mpkh** [comment]
I think it could be done in separate repository

**Comment by Arcterus** [comment]
^

If you are interested in something I can set up a repository.

**Comment by E5ten** [comment]
@Arcterus I'd be interested in repositories for grep and sed, because all of the non-GNU implementations of sed are missing certain features such as --color and -P for grep and --follow-symlinks for sed. A rust implementation of gawk would also be very cool.

**Comment by sylvestre** [comment]
I think we should focus on getting all coreutils working with most/all options.

So, I think it is out of scope

**Comment by felipecrs** [comment]
It would be great to have uutils version of grep, so I could finally do `| grep` in Windows PowerShell, lol.

**Comment by sylvestre** [comment]
we started sed:
https://github.com/uutils/sed

don't hesitate to start grep :)
