### ISSUE TITLE
Why sphinx instead of rustdoc?

### ISSUE THREAD

**Issue by icefoxen** [uutils/coreutils#1141]
I'm just curious.  :-)

**Comment by Arcterus** [comment]
AFAIK rustdoc doesn't support man pages, but if I'm wrong I'd be willing to switch.  Sphinx just seemed to support most of what I thought was important out of the box (_e.g._ easy to read and write man pages and HTML documents).

**Comment by icefoxen** [comment]
Good reason!  Thanks.
