### ISSUE TITLE
du on mac is subtly different

### ISSUE THREAD

**Issue by bootandy** [uutils/coreutils#1155]
I have been able to get coreutils' du to give a different output to the standard du on my mac os: High Sierra. 

> 
> sudo ~/dev/rust/coreutils/target/release/uutils du -d 1 /private/var/db/ConfigurationProfiles/
> du: error: Operation not permitted (os error 1)
> 
> sudo du -d 1 /private/var/db/ConfigurationProfiles/
> 0	/private/var/db/ConfigurationProfiles//Settings
> 0	/private/var/db/ConfigurationProfiles//Setup
> du: /private/var/db/ConfigurationProfiles//Store: Operation not permitted
> 0	/private/var/db/ConfigurationProfiles/
> 
As you can see above coreutils' du exits on the first read error where as old du lists the error and then keeps working on the other files. 

Is this important enough to be investigated further? If this isn't important then just close this issue.

I'm happy to dig in to this a little more in the future.

**Comment by Arcterus** [comment]
Do you happen to have GNU coreutils installed via Homebrew or something?  If so, can you report what `gdu` does?  If it also continues after an error (pretty sure it does), this is indeed an issue that needs to be fixed.

**Comment by bootandy** [comment]
>  (master)bootandy:(0):~/dev/rust/dus$ sudo du -d 1 /private/var/db/ConfigurationProfiles/
> 0	/private/var/db/ConfigurationProfiles//Settings
> 0	/private/var/db/ConfigurationProfiles//Setup
> du: /private/var/db/ConfigurationProfiles//Store: Operation not permitted
> 0	/private/var/db/ConfigurationProfiles/

>  (master)bootandy:(0):~/dev/rust/dus$ sudo gdu -d 1 /private/var/db/ConfigurationProfiles/
> 0	/private/var/db/ConfigurationProfiles/Settings
> 0	/private/var/db/ConfigurationProfiles/Setup
> gdu: cannot access '/private/var/db/ConfigurationProfiles/Store': Operation not permitted
> 0	/private/var/db/ConfigurationProfiles/

gdu behaves the same as du.  coreutils's du is different. 

I can dig further into this soon as I'm writing my own du tool which is how I first noticed this.

**Comment by Arcterus** [comment]
The error is probably [here](https://github.com/uutils/coreutils/blob/master/src/du/du.rs#L94).  We should probably be just printing an error message and ignoring the entry if there's an error instead of crashing.

**Comment by bootandy** [comment]
yes I agree that looks correct - I can put together a pull request tomorrow and test it on my mac to see if it fixes it. Tricky to write a test for it though.

**Comment by bootandy** [comment]
after liberally sprinkling println! throughout the code it appears to be the safe_unwrap here: https://github.com/uutils/coreutils/blob/master/src/du/du.rs#L58 which is causing the problem.  I'm working on a fix.
