### ISSUE TITLE
du on mac does not calculate block size correctly

### ISSUE THREAD

**Issue by bootandy** [uutils/coreutils#1163]
> target/debug/du  -d 1 ../dus/src/test_dir/many/b
> 16	../dus/src/test_dir/many/b

> du ../dus/src/test_dir/many/b
> 32	../dus/src/test_dir/many/b

Fairly sure the block size is just half of what it should be on mac. 
Fix: Use the specific metadata functions that can be called for each OS.

https://doc.rust-lang.org/std/os/linux/fs/trait.MetadataExt.html

I can fix this.

**Comment by bootandy** [comment]
Using specific metadata functions will probably fix this too: https://github.com/uutils/coreutils/issues/1152

**Comment by Arcterus** [comment]
This seems to be for the default version of `du` on Macs, which is based on the BSD version (or maybe just straight up is the BSD version, not really sure).  We should be defaulting to this behavior when `POSIXLY_CORRECT` is set though (or, according to [this](https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html), when `DU_BLOCK_SIZE`, `BLOCK_SIZE`, or `BLOCKSIZE` are set), so it's still an issue.
