### ISSUE TITLE
du (on mac but probably all OS) does not track inodes

### ISSUE THREAD

**Issue by bootandy** [uutils/coreutils#1164]
Unlike original du, coreutils/du does not keep track of inodes.

This means coreutils will double count files which are hard linked

to hard link a file:
ln original copy

I can fix this.

**Comment by Arcterus** [comment]
Just a quick note, but can you add a test for all of these things to ensure they don't happen again?

**Comment by bootandy** [comment]
Well I can try but that could be very hard to do - Unless we run a virtual box with mac and another with linux etc. Maybe I can mock out the file system somehow - I'll look into how the other tests work - Can you link me to a 'favourite test' in this project that I can mimic ? thanks.

**Comment by Arcterus** [comment]
You can just configure tests so they only run if the user is on Linux or Mac or whatever.  You might want to look at some of the tests that deal with files, so maybe `tests/test_cp.rs` or `tests/test_rm.rs` or something.

**Comment by ids1024** [comment]
> Well I can try but that could be very hard to do

Why do you think it would be hard? I don't think git can manage hard links, but the test can call `std::fs::hard_link`.

**Comment by bootandy** [comment]
That's good to know - thank you I'll use that. 

I'm more worried about not being to test that it works on mac on linux and vica-versa.
