### ISSUE TITLE
Use threads in du

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1183]
I previously removed threading from `du` because the implementation was spawning a new thread for every directory (or maybe it was every file?).  Ideally, we should be using threads so we can work on multiple files/directories at once, just not in the way previous implementation did so.

**Comment by bootandy** [comment]
I tried this on my project: dust. It didn't bring a great performance boost and did make the code considerably more complex so I decided not to.

I'm not saying that it is not worth doing but please tame your expectations.
