### ISSUE TITLE
Inconsistency with GNU sort 

### ISSUE THREAD

**Issue by shaobo-he** [uutils/coreutils#1193]
Hi guys,

I noticed that there might be an inconsistency between sort and GNU's sort. For example,

```
$ echo -e "NaN\nNaN\n3.0\n2.0" | target/release/sort -n
2.0
3.0
NaN
NaN
$ echo -e "NaN\nNaN\n3.0\n2.0" | sort -n
NaN
NaN
2.0
3.0
```

Is this type of behavior expected or it doesn't matter?

Thanks.

**Comment by Arcterus** [comment]
`sort` should behave the same as the GNU version, so this is an issue.
