### ISSUE TITLE
expr overflows with large input

### ISSUE THREAD

**Issue by shaobo-he** [uutils/coreutils#1194]
Hi,

This is probably a known issue. For example,

```
$ target/release/expr 9223372036854775807 + 9223372036854775807
-2
```
, whereas GNU `expr` emits a correct error message.

```
$ expr 9223372036854775807 + 9223372036854775807
expr: +: Numerical result out of range
```

**Comment by Arcterus** [comment]
This is not really unexpected, but should be fixed nonetheless.  We should be using the `checked_` functions for mathematical expressions here, but probably are not.
