### ISSUE TITLE
run who tests on mac

### ISSUE THREAD

**Issue by bootandy** [uutils/coreutils#1255]
If we change this line to `eprintln` 

https://github.com/uutils/coreutils/blob/master/src/uucore/utmpx.rs#L247

(On mac: Weirdly the value for `res` is 1 but the call to `last_os_error` returns 0)

Then we can run the `who` tests against the mac as well as against linux. 

I made the change here but I don't know if it is a good idea. Feel free to comment. - This splits the tests into mac & not mac - I do not know how bsd will behave.

https://github.com/bootandy/coreutils/commit/24baf6d6bc63b7bff309c28718184987a1680f71

(mac requires to be tested against gwho not who - which is why mac has a 'g' added to the name)

**Comment by Arcterus** [comment]
Something like this seems fine (and that warning probably should use `eprintln!()`).  If we are going to call different utilities on different platforms, I think it would make more sense to do so in the testing framework than on a per-utility basis.  I'll need to figure out what exactly is happening on Macs with regards to the `utmpxname()` call.

**Comment by tertsdiepraam** [comment]
As far as I can tell, `who` tests are run on Mac since May 2021: https://github.com/uutils/coreutils/pull/2240.
