### ISSUE TITLE
insmod and rmmod

### ISSUE THREAD

**Issue by bachp** [uutils/coreutils#1272]
I'm currently implementing module loading and unloading for the linux kernel (see: https://github.com/nix-rust/nix/pull/930). One goal would be to have `inmod` and `rmmod` replacements based on that.

My question: Is it OK to add these to this repo? I don't think `insmod`/`rmmod` is part of GNU Coreutils. On the other hand busybox has them and I like to think of uutils as a busybox replacement.

What is the opinion of the maintainers on this topic?

**Comment by Arcterus** [comment]
I'd be willing to consider adding them, but I feel like we may want to just create an "extrautils" repo or something for utilities like those (though if we haven't done this by the time you or someone else finishes utilities like those I wouldn't be opposed to adding them to this repo).

**Comment by tertsdiepraam** [comment]
Like mentioned above, these utils would not fit in this repo (and communication has been a bit stale :) ).
