### ISSUE TITLE
rm: On Windows, rm -rf * doesn't do anything.

### ISSUE THREAD

**Issue by TheGoddessInari** [uutils/coreutils#1274]
It doesn't return an error, but also doesn't remove any files or directories.

**Comment by Arcterus** [comment]
This is probably due to Windows shells not expanding globs.  I’m not sure if we should expand the globs ourselves on Windows or just leave the behavior as is.

It should at least return an error on the glob right now because it’s not being expanded, so that is an issue.

**Comment by rivy** [comment]
This bugged me as well. So, I fixed it.

With just a small set of changes, localized to 'uucore', I was able to add command line globbing for windows targets to all the utilities.

I've just opened [PR#1281](https://github.com/uutils/coreutils/pull/1281) with the patches.

**Comment by rivy** [comment]
Fixed in  [PR#1281](https://github.com/uutils/coreutils/pull/1281).
This can be closed.

**Comment by Arcterus** [comment]
Thanks for reminding me!

**Comment by TheGoddessInari** [comment]
Actually, one problem with #1281 is that it doesn't use similar globbing rules. For instance, it unexpectedly deletes hidden directories, like `.git` when using a basic `rm -rf *`. That's pretty unexpected behavior. Just noticed this, but I suppose I should open a new issue.

**Comment by Arcterus** [comment]
@TheGoddessInari yeah, that is definitely an issue.  I also just noticed that `~` doesn't expand, which is another problem.  If you could open an issue that'd be greatly appreciated.
