### ISSUE TITLE
tee: handling `-` incorrectly

### ISSUE THREAD

**Issue by kubo39** [uutils/coreutils#1278]
```console
$ git rev-parse HEAD
07b01a85f9ea6fc8500440201453fbdeda1652d7
$ echo 0 | ./target/debug/tee - - - - - - - 
0
0
0
0
0
0
0
0
```

**Comment by Arcterus** [comment]
What does this do for you using the GNU version?

**Comment by kubo39** [comment]
GNU version 8.28 shows this.

```console
$ LANG=C tee --version| head -1
tee (GNU coreutils) 8.28
$ echo 0 | tee - - - - - - 
0
```

It seems that they [don't treat "-" specially](https://github.com/coreutils/coreutils/blob/2ed7c2867974ccf7abc61c34ad7bf9565489c18e/src/tee.c#L213) and [implicit uses stdout](https://github.com/coreutils/coreutils/blob/2ed7c2867974ccf7abc61c34ad7bf9565489c18e/src/tee.c#L206).

**Comment by Arcterus** [comment]
I'm testing on WSL, but it seems to me that 8.21 behaves the same as the current behavior, so I imagine this was a (somewhat) recent change.  Also, please don't look directly at the GNU code.  Doing so makes it difficult to say whether code in `uutils` is derived from the GNU version.
