### ISSUE TITLE
sync: --data and --file-system option

### ISSUE THREAD

**Issue by kubo39** [uutils/coreutils#1279]
- --data (sync only file data)
    - we can use `fdatasync()` except MacOS.
 - --file-system (sync just the files ystems that contains the files given as arguments)
    - we can use `syncfs()` only if Linux Kernel >= 2.6.39
    - otherwise, GNU coreutils uses `sync()`.
- When only files were given, GNU coreutils uses `fsync()`

**Comment by tertsdiepraam** [comment]
For reference, this was implemented in https://github.com/uutils/coreutils/pull/1639. So stalebot was right to close this :)
