### ISSUE TITLE
sort: panic on empty lines

### ISSUE THREAD

**Issue by xplorld** [uutils/coreutils#1282]
```
sh-3.2$ echo "11111111111111111111\n11111111111111111110\n" | sort -n

11111111111111111110
11111111111111111111
sh-3.2$ echo "11111111111111111111\n11111111111111111110\n" | ./uutils sort -n
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
sh-3.2$ echo "11111111111111111111\n11111111111111111110\n" | RUST_BACKTRACE=1 ./uutils sort -n
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: uu_sort::numeric_compare
  10: uu_sort::compare_by
  11: alloc::slice::merge_sort
  12: uu_sort::exec
  13: uu_sort::uumain
  14: uutils::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
```

**Comment by vks** [comment]
What is the expected output? GNU sort seems to return the unsorted input.

Note that you probably want to use the `-e` flag for echo, otherwise your escapes don't work. If you do that, uutils still panics, because there is an empty line which cannot be converted to a number. If you remove the trailing newline, uutils sorts as expected.

**Comment by xplorld** [comment]
> What is the expected output? GNU sort seems to return the unsorted input.
> 
> Note that you probably want to use the `-e` flag for echo, otherwise your escapes don't work. If you do that, uutils still panics, because there is an empty line which cannot be converted to a number. If you remove the trailing newline, uutils sorts as expected.

You are right. I use macOS whose echo seems different from GNU echo. This bug is still a thing, though. GNU sort sorts the two numbers, and outputs them reversely.

**Comment by cnd** [comment]
@xplorld may you test if patch has fixed that issue
