### ISSUE TITLE
hostid has vestigial Mode enum

### ISSUE THREAD

**Issue by NoTroop** [uutils/coreutils#1286]
The hostid program has a Mode enum that it is no longer using. Is there a reason it has been kept around? It compiles and functions identically without it. Here's the patch:

```diff
--- a/src/hostid/hostid.rs
+++ b/src/hostid/hostid.rs
@@ -20,12 +20,6 @@ static SYNTAX: &str = "[options]";
 static SUMMARY: &str = "";
 static LONG_HELP: &str = "";
-pub enum Mode {
-    HostId,
-    Help,
-    Version,
-}
-
 // currently rust libc interface doesn't include gethostid
 extern "C" {
     pub fn gethostid() -> c_long;
```

**Comment by Arcterus** [comment]
It seems like it's just leftover cruft from various changes over the years.  If you submit a pull request with this patch I'll merge it.
