### ISSUE TITLE
Community chat

### ISSUE THREAD

**Issue by samuela** [uutils/coreutils#1340]
It would be nice to have a gitter/discord/spectrum/slack community for the users and developers of this project. Personally I would find it especially helpful for organizing contributions, eg. I'd like to contribute to finishing `ls` but there's no record as to why it's not complete yet, who's working on it, what needs to be done, etc.

**Comment by cnd** [comment]
I vote for discord

**Comment by samuela** [comment]
That works for me. Who is currently leading/maintaining the project?

**Comment by cnd** [comment]
there are some people but @Arcterus seems like most active, ideally I'd wait for more responses but generally having at least his response is a must.

**Comment by samuela** [comment]
ok, roger that

**Comment by ArniDagur** [comment]
I second Discord

**Comment by samuela** [comment]
Any thoughts @Arcterus ?

**Comment by Arcterus** [comment]
I actually thought about setting up a Discord a while ago but got sidetracked, so I also vote for Discord lol.

**Comment by cnd** [comment]
@Arcterus will you create a server?

**Comment by Arcterus** [comment]
I'll see if I can get to it soon (most likely next week because I have a few deadlines before).  If someone really wants, they can make the server in the meantime and add me as an admin afterwards.

**Comment by samuela** [comment]
@Arcterus Ok, created rust-coreutils on discord: https://discord.gg/VrxQgNa. I have no idea how discord works, so just let me know once you accept the invite and I'll make you an admin or transfer ownership so that you can set it up.

**Comment by Arcterus** [comment]
I joined the server, so I'll work on getting it set up when I get admin access.  I'll leave this open until we add something to the top of the README mentioning the server.

**Comment by ArniDagur** [comment]
@samuela Do you mind giving @Arcterus administrator priviledges on the Discord server?

**Comment by Arcterus** [comment]
Added the Discord link to the README in #1362.  Closing.
