### ISSUE TITLE
Should we have a "--features bsd" or "--features posix"?

### ISSUE THREAD

**Issue by ArniDagur** [uutils/coreutils#1349]
Such a Cargo feature would be used in conjunction with conditonal compilation to disable GNU-specific functionality. Is this a good idea, or would this cause too much of a maintainance burden?

**Comment by Arcterus** [comment]
I'd be willing to add both (I have actually thought about doing so).  I'm not sure if it's better to use feature flags or just use environment variables (like `POSIXLY_CORRECT`).

**Comment by Arcterus** [comment]
My current thinking about this is that we should have both feature flags and a runtime switch (as another feature).  All of the features are enabled by default.  In the absence of the runtime switch feature, `bsd` and `gnu` become mutually exclusive (and one MUST be specified)
