### ISSUE TITLE
wc: Don't read() if we only need to count number of bytes

### ISSUE THREAD

**Issue by ArniDagur** [uutils/coreutils#1351]
[FreeBSD's wc.c](https://github.com/freebsd/freebsd/blob/master/usr.bin/wc/wc.c) simply fstats() the file, and if it is regular, returns st_size.

Using `strace`, we can see that GNU wc does something similar:

`strace /usr/bin/wc -c`:
```
openat(AT_FDCWD, "README.md", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=10675, ...}) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x1), ...}) = 0
write(1, "10675 README.md\n", 1610675 README.md
)       = 16
close(3)                                = 0
```
`strace /usr/bin/wc -c -l`:
```
openat(AT_FDCWD, "README.md", O_RDONLY) = 3
fadvise64(3, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
read(3, "uutils coreutils\n==============="..., 16384) = 10675
read(3, "", 16384)                      = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x1), ...}) = 0
write(1, "  358 10675 README.md\n", 22  358 10675 README.md
) = 22
close(3)                                = 0
```

**Comment by ArniDagur** [comment]
If the file is not regular, we should use `splice()` to count the number of bytes, instead of `read()`, if we're on Linux or Android.

**Comment by Arcterus** [comment]
If we are going to be using `splice` regularly, we should probably design a way for it to work on Windows and other Unix platforms as well.  I'd rather avoid treating Linux as special for all the utilities.

**Comment by ArniDagur** [comment]
New PR: https://github.com/uutils/coreutils/pull/1851

**Comment by ThatOneCalculator** [comment]
#1851 got merged! Should we close this now?
