### ISSUE TITLE
Refactor utilities

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1358]
We need to go through all the utilities (and associated code) and refactor them if they are suffering from age or inexperience writing Rust on the part of the original implementer.  This was brought up recently in #1342.  At the same time, we should focus on adding tests and checking for bugs.

- [ ] `arch`
- [ ] `base32`
- [ ] `base64`
- [ ] `basename`
- [ ] `cat`
- [ ] `chgrp`
- [ ] `chmod`
- [ ] `chown`
- [ ] `chroot`
- [ ] `cksum`
- [ ] `comm`
- [ ] `cp`
- [ ] `cut`
- [ ] `date`
- [ ] `dd`
- [ ] `dircolors`
- [ ] `dirname`
- [ ] `du`
- [x] `echo`
- [ ] `env`
- [ ] `expand`
- [ ] `expr`
- [ ] `factor`
- [ ] `false`
- [ ] `fmt`
- [ ] `fold`
- [ ] `groups`
- [ ] `hashsum`
- [ ] `head`
- [ ] `hostid`
- [ ] `hostname`
- [ ] `id`
- [ ] `install`
- [ ] `join`
- [ ] `kill`
- [ ] `link`
- [ ] `ln`
- [ ] `logname`
- [ ] `ls`
- [ ] `mkdir`
- [ ] `mkfifo`
- [ ] `mknod`
- [ ] `mktemp`
- [ ] `more`
- [ ] `mv`
- [ ] `nice`
- [ ] `nl`
- [ ] `nohup`
- [ ] `nproc`
- [ ] `numfmt`
- [ ] `od`
- [ ] `paste`
- [ ] `pathchk`
- [ ] `pinky`
- [ ] `printenv`
- [ ] `printf`
- [ ] `ptx`
- [ ] `pwd`
- [ ] `readlink`
- [ ] `realpath`
- [ ] `relpath`
- [ ] `rm`
- [ ] `rmdir`
- [ ] `seq`
- [ ] `shred`
- [ ] `shuf`
- [ ] `sleep`
- [ ] `sort`
- [ ] `split`
- [ ] `stat`
- [ ] `stdbuf`
- [ ] `sum`
- [ ] `sync`
- [ ] `tac`
- [ ] `tail`
- [ ] `tee`
- [ ] `test`
- [ ] `timeout`
- [ ] `touch`
- [ ] `tr`
- [ ] `true`
- [ ] `truncate`
- [ ] `tsort`
- [ ] `tty`
- [ ] `uname`
- [ ] `unexpand`
- [ ] `uniq`
- [ ] `unlink`
- [ ] `uptime`
- [ ] `users`
- [ ] `uucore`
- [ ] `uutils`
- [ ] `wc`
- [ ] `who`
- [ ] `whoami`
- [ ] `yes`

**Comment by ArniDagur** [comment]
A helpful human on the Rust IRC raised a few issues with the current `cat` implementation, which are relevant to this issue:
```                  
│20:33        arnidg ╡ Is there a better way to do this error handling so I don't have to duplicate the `eprintln!` code?                                                       │ arsnael
│                    ╡ https://github.com/uutils/coreutils/blob/bec661514119fa22f083282d2cd6c45ca4e41195/src/cat/cat.rs#L315-L328                                               │ artemisart-M
│20:38   Moongoodboy ╡ arnidg: lines 317-328? Seems fine to me.                                                                                                                 │ arturo-M
│20:38        arnidg ╡ all right :)                                                                                                                                             │ asd
│20:39   Moongoodboy ╡ I do see a few other things though                                                                                                                       │ astocko
│20:39        arnidg ╡ tell me                                                                                                                                                  │ astutecat
│20:39   Moongoodboy ╡ SYNTAX, SUMMARY, etc should be const, not static                                                                                                         │ ath
│20:40             ⤷ ╡ file paths should be in terms of OS strings and paths, not Rust strings (else you'll break if a user passes a valid path that isn't valid UTF-8)         │ Atomicbit-M
│20:41             ⤷ ╡ having the NumberingMode variants all start with 'Number' is redundant                                                                                   │ atonium-M
│20:41           --> ╡ Mary82 (Mibbit@moz-im5.ngc.202.85.IP) has joined #rust-beginners                                                                                         │ AtumT
│20:42   Moongoodboy ╡ there's a few instances of string literals being made owned that are non-ideal and seem unnecessary (e.g. lines 169...174)                               │ augustl
│20:42        Mary82 ╡ hola                                                                                                                                                     │ autra
│20:42   Moongoodboy ╡ (192...194)                                                                                                                                              │ avadacatavra
│20:44             ⤷ ╡ the get_input_type() thing is a race condition as written, and it could be eliminated altogether if you drop Unix socket support, which…                 │ avastmick-M
│20:44             ⤷ ╡ does it make sense to be able to `cat` Unix sockets? do other cat(1)s do that?                                                                           │ averell
│20:46             ⤷ ╡ your write_to_end() panics, which…panicking kinda gives ugly messages, and also doesn't tell the user which file the error occurred in                   │ avp42
│20:48        arnidg ╡ I'm not sure if other `cat`s support Unix sockets; most of the code is not written by me                                                                 │ awal
│20:49   Moongoodboy ╡ the match in write_nonprint_to_end() should probably use byte literals instead of decimal values                                                         │ awal-M
│20:49             ⤷ ╡ just some stuff I noticed. ^.^;                                                                                                                          │ awe
│20:50        arnidg ╡ Thanks a ton!                                                                                                                                            │ aweinstock
│20:50   Moongoodboy ╡ No problem~  
```

**Comment by Arcterus** [comment]
> │20:39   Moongoodboy ╡ SYNTAX, SUMMARY, etc should be const, not static

I already knew about this, which is why I usually ask people to change `static` to `const`.  Maybe I should add a section to `CONTRIBUTING.md` mentioning stuff like this.

> │20:40             ⤷ ╡ file paths should be in terms of OS strings and paths, not Rust strings (else you'll break if a user passes a valid path that isn't valid UTF-8)

The only reason we use `String` is that we still use `getopts` for most of the utilities.  Switching to `clap` (or manually handling command-line arguments, I guess) would go a long way to fixing these issues.  The best solution might be to build something on top of `clap` (_i.e._ rewrite the argument handling in `uucore` to use `clap`).

> │20:41             ⤷ ╡ having the NumberingMode variants all start with 'Number' is redundant

Good point.  Not sure if this is just from before there were set ideals for `enum` or what.

> │20:42   Moongoodboy ╡ there's a few instances of string literals being made owned that are non-ideal and seem unnecessary (e.g. lines 169...174)

This is probably from quick refactoring to fix the build after a Rust update when Rust was still pre-1.0.

> │20:44             ⤷ ╡ the get_input_type() thing is a race condition as written, and it could be eliminated altogether if you drop Unix socket support, which…                 │ avastmick-M
> │20:44             ⤷ ╡ does it make sense to be able to `cat` Unix sockets? do other cat(1)s do that?

I am pretty sure at least FreeBSD `cat` supports Unix sockets, so I'd prefer to keep the functionality (unless someone proves me wrong).

> │20:46             ⤷ ╡ your write_to_end() panics, which…panicking kinda gives ugly messages, and also doesn't tell the user which file the error occurred in

I think this is a leftover from long ago, but at least stuff like broken pipes shouldn't display anything as we have a custom panic handler.  Ideally we'd probably bubble up errors that can be handled by `mkmain.rs` and `src/uutils/uutils.rs`.
