### ISSUE TITLE
Considering switching CI

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1364]
I'm not really satisfied with Appveyor and Travis.  The builds are pretty slow, so I'm considering switching to Circle CI or Azure Pipelines or something.  There are a bunch of options [in this discussion](https://internals.rust-lang.org/t/which-ci-platform-should-rust-use/9322/17).

It might be best to just leave the macOS builds on Travis and switch Linux and Windows to something else, but I also don't really like having to maintain so many different types of CI.

Cirrus CI (which is what we now use for FreeBSD) support 8 Linux, 2 Windows, 2 FreeBSD, and 1 macOS build at the same time, so we could also just switch to that and call it a day.  I feel like it will still be too slow though for the Windows and macOS builds at least.

**Comment by samuela** [comment]
Another option these days is GitHub Actions. Here's what I'm using for rustybox: https://github.com/samuela/rustybox/blob/master/.github/workflows/rust.yml.

**Comment by rivy** [comment]
Here's a GitHub Action workflow that I designed for [`lsd`](https://github.com/Peltoche/lsd) ...
- [CICD.yml](https://github.com/rivy/rust.lsd/blob/a7b0ecdd022a061a59df41526cb7543e8ed82022/.github/workflows/CICD.yml)
- and the [merged PR](https://github.com/Peltoche/lsd/pull/308), for further explanation
