### ISSUE TITLE
Is `sh` in-scope for this project?

### ISSUE THREAD

**Issue by casey** [uutils/coreutils#1373]
A Bourne-compatible shell is a huge project, would make this version a viable busybox replacement for a lot of use cases.

I ask because I'm considering bundling busybox with a utility, and busybox's cross-platform story isn't the best.

Thank you!

**Comment by Arcterus** [comment]
It's out of scope for `coreutils`, but not for `uutils`.  In other words, I'd be happy to make a new project for `sh` under the `uutils` organization (but not a full `bash`-compatible shell, unless someone else wanted to take charge of that).

I have also considered creating an overarching project bundling `coreutils`, `findutils`, and any other eventual projects into one binary, but probably need more frequently active maintainers to do so.

**Comment by casey** [comment]
That seems totally reasonable.

I maintain [just](https://github.com/casey/just), which is mostly like Make, but which is just a command runner, and doesn't do anything build-system-ey.

The `just` binary itself is cross-platform, but it depends on `sh` and any system binaries that the user calls in their justfile.

To make the same justfiles work across unix and windows, one possibility I've been exploring is to bundle a busybox binary with just, so as long a justfile uses commands that come with busybox, they will mostly work across platforms.

However, busybox is in C, so I would be adding a big C dependency with uncertain stability guarantees and not-great cross-platform compilation, which I'm loathe to do.

In an ideal world, I could bundle `uutils/coreutils` and an `sh` written in Rust with Just, and have everything be in the same language and use the same build system.

 I'll close this issue, since it seems like it probably isn't actionable for a while.

**Comment by Arcterus** [comment]
That sounds like a neat idea.  I'm currently experimenting with making a (non-POSIX) shell in Swift for fun, but I might be able to port some of the code to Rust for a POSIX-compatible shell.

**Comment by casey** [comment]
That would be rad. Is your non-POSIX shell on github?

**Comment by Arcterus** [comment]
Not at the moment.  I'm still playing around with it to see which (if any lol) of my ideas are gonna pan out.  I think there's enough to get a decent start for a POSIX shell though, so I'll see if I can get something working.

**Comment by casey** [comment]
It's usually a bad idea to make a library that does the thing that you want to, instead of just making the thing you want to do, but I wonder if it would be possible to make a shell-support library that would do complex things like spawning processes with handles attached to pipelines. Nobody is going to agree on a common syntax for shells, but everyone seems to mostly agree on basic semantics, so it might be a useful base layer for multiple projects to build on 🧐
