### ISSUE TITLE
binary size is scary

### ISSUE THREAD

**Issue by Fiedzia** [uutils/coreutils#140]
I know its a rust issue, but looking at about 3MB for each binary, versus around 100KB for coreutils binaries on my system (ubuntu 14.04), I wonder if there is anything that can be done to cut it down.

**Comment by hexsel** [comment]
On the current version of the project, most binaries end up between 271kB - 471kB (stripping on, LTO off due to [this bug](https://github.com/rust-lang/rust/issues/28066).

Is there a need to make this any smaller?

**Comment by t0b1nux** [comment]
What about shipping a standard library for OS not having rust library and using dynamic linking ?

**Comment by nathanross** [comment]
see the issue above for more details on this issue, dynamic linking.

**Comment by abique** [comment]
I like the busybox idea.

**Comment by knight42** [comment]
duplicated #747
