### ISSUE TITLE
head: negative numbers broken

### ISSUE THREAD

**Issue by E5ten** [uutils/coreutils#1414]
`head -n -1` with no file argument results in `head: error: Argument to option 'n' missing`, and with a file argument (e.g. `head -n -1 file`) results in `head: error: invalid line count 'file': invalid digit found in string`. `head` should detect that the `-1` isn't an option despite the dash before it, but a negative argument to `-n` and correctly print all the lines in the file it is used on except the last.

**Comment by Arcterus** [comment]
Is `-c` also an issue?

**Comment by E5ten** [comment]
Yes

**Comment by sylvestre** [comment]
Fixed by #1510
