### ISSUE TITLE
idea: allow for JSON-RPC standards in the shell

### ISSUE THREAD

**Issue by vitiral** [uutils/coreutils#1417]
I worked on an open-source standard on a plane flight last weekend I call JSH. I have a MVP library in python at https://github.com/vitiral/jsh, but the library and CLI are both extremely simple+tiny and could just as easily be implemented in rust (or any language). Actually, rust was one of my primary use-cases, since serde is so awesome.

I am curious to know what the maintainers of this repo think about the standard in general. The overarching goals are to be able to make message passing simpler and enable "data pipe" style of data processing.

- Is it (or something like it) a good idea in general?
  - What changes would you make / ideas do you have?
- Could you see coreutils implementing something like this?

A possible further goal would be to develop a general json-driven shell, where shell primitives can handle json input/output (i.e. object access like a dictionary, for loops over list/object, etc) 
 and calling shell commands would by default use `--jsh-request` in a "hidden" way (that "new shell" could very well just be ipython with a library installed...)

Would love this community's thoughts!

**Comment by vitiral** [comment]
Obviously this would be behind a feature gate and add an optional dependency on `serde`.

**Comment by tertsdiepraam** [comment]
3 years later, I'll try to answer this question :). A shell with structured data is a great idea. [nushell](https://www.nushell.sh/) is a great example of one. However, I feel like it would not fit this particular project. As now, we would have to maintain 2 types of input and output for every util. Additionally, utils often print while writing to stdout for efficiency and don't store the whole output up front. This makes it harder to convert to something like JSON. So in short, a shell built from the ground up with structured data is great, but tacking it onto existing projects is not, in my opinion.

I'm closing this issue in favour of https://github.com/uutils/coreutils/issues/1806 where there has been more discussion around JSON input/output.
