### ISSUE TITLE
more should respect stdin, return, terminal size

### ISSUE THREAD

**Issue by bergey** [uutils/coreutils#1423]
- should accept display content on STDIN (and still get keyboard input from terminal)
- should detect terminal size, page by this amount
- should move by line (RETURN) or by page (SPACE)

Are there other features people need to start using `more` routinely?

**Comment by bergey** [comment]
Unless someone speaks up to say they're working on this already, I'll put together a PR.  Any preference on 1 PR or several?

**Comment by ArniDagur** [comment]
Thanks for your interest in contributing to the project! I doubt there's anyone working on this already. I'm personally fine with 1 PR if you put them in multiple commits, since these are uncontroversial changes, but @Arcterus's opinion may differ.
