### ISSUE TITLE
Use cargo-make instead of make

### ISSUE THREAD

**Issue by mmatous** [uutils/coreutils#1433]
While sifting through issues while trying to my solve my own issue with make, I noticed people facing all kinds of problems and generally being unhappy about GNU make. Maybe [cargo-make](https://sagiegurari.github.io/cargo-make/) could replace it?

**Comment by Arcterus** [comment]
After looking at it, I'm not sure it would solve many of the recurring issues with `make`.  It would probably be simpler to just rewrite the `Makefile` (especially some of the more flaky bits involving installation and such).
