### ISSUE TITLE
Feature requests: cp & mv progress bar

### ISSUE THREAD

**Issue by doronbehar** [uutils/coreutils#1455]
GNU's coreutils project has rejected this feature since day 1, see: https://lists.gnu.org/archive/html/coreutils/2015-09/msg00008.html . There's a [crafty patch written for it](https://github.com/mrdrogdrog/advcpmv) but today it failed me when I copied a directory with very special characters such as `[{[&d.*` it didn't know how to handle.

I was wondering whether you'd consider implementing this feature.

**Comment by ArniDagur** [comment]
I'd be open to this extension if it were opt in. Perhaps a command line flag such as `--progress-bar` could be used, similar to other tool's `--color` flag. An environment variable might work also.

@doronbehar Have you looked at https://github.com/tarka/xcp?

**Comment by doronbehar** [comment]
> Have you looked at https://github.com/tarka/xcp?

No :). Looks like an interesting project. It also has a progress bar included. Have you ever borrowed or considered borrowing some ideas from there? Seems they emphasised a lot on performance.

**Comment by doronbehar** [comment]
> Have you looked at https://github.com/tarka/xcp?

No :). Looks like an interesting project. It also has a progress bar included. Have you ever borrowed or considered borrowing some ideas from there? Seems they emphasised a lot on performance.

**Comment by doronbehar** [comment]
> Have you looked at https://github.com/tarka/xcp?

No :). Looks like an interesting project. It also has a progress bar included. Have you ever borrowed or considered borrowing some ideas from there? Seems they emphasised a lot on performance.

**Comment by doronbehar** [comment]
> Have you looked at https://github.com/tarka/xcp?

Seems like an interesting project, with progress bar and performance enhancments over GNU's coreutils. Have you ever borrowed or considered borrowing ideas from there?

**Comment by doronbehar** [comment]
Sorry for the duplicates :/ had some network issues.

**Comment by Arcterus** [comment]
I agree that it's got some good ideas.  Unfortunately, it's GPL, so at most we will be able to borrow ideas.  When `cp` is eventually refactored, we'll probably borrow some of them.

I think the progress bar has been mentioned before.  I am happy to add it as an optional flag (like `--progress-bar` as mentioned above).

**Comment by ycd** [comment]
There is [indicatif](https://github.com/mitsuhiko/indicatif) and [pb](https://github.com/a8m/pb), both licensed with MIT. It would be very easy to implement for mv and cp as far as i have seen. Only thing i'm concerned about they are going to increase the executable size, 

On the other hand features like this are joy to use, imagine having  [exa](https://github.com/ogham/exa) instead of `ls`, [procs](https://github.com/dalance/procs) instead of `ps`, `bat` instead of cat, `ripgrep` instead of grep on your brand-new OS, that would be freaking cool.
