### ISSUE TITLE
LICENSE incompatibility for `cloudabi` and `sha1` deps

### ISSUE THREAD

**Issue by rivy** [uutils/coreutils#1470]
`cloudabi` has the "BSD-2-clause" license, and `sha1` has the "BSD-3-clause" license.
Those licenses are quite close to MIT, except the "BSD"-type licenses don't allow sub-licensing which is arguably? a deal-breaker for licensing this repo as "MIT".

ref: <https://opensource.stackexchange.com/questions/217/what-are-the-essential-differences-between-the-bsd-and-mit-licences>
ref: <https://dwheeler.com/essays/floss-license-slide.html> @@ <http://archive.today/4QHQ0>
ref: <https://github.com/dtolnay/rust-faq#why-a-dual-mitasl2-license>

Thoughts about solutions?
Replace the dependencies with alternative, license-compatible versions?
Ask the authors to explicitly allow uutils to sub-license the crates as "MIT"?

**Comment by rivy** [comment]
```
$ cargo lichking check --all
 ERROR cargo_lichking::check > uutils cannot include package cloudabi, license BSD-2-Clause is incompatible with MIT
 ERROR cargo_lichking::check > uutils cannot include package sha1, license BSD-3-Clause is incompatible with MIT
 ERROR cargo_lichking::check > factor cannot include package cloudabi, license BSD-2-Clause is incompatible with MIT
 ERROR cargo_lichking::check > hashsum cannot include package sha1, license BSD-3-Clause is incompatible with MIT
 ERROR cargo_lichking::check > mktemp cannot include package cloudabi, license BSD-2-Clause is incompatible with MIT
 ERROR cargo_lichking::check > shred cannot include package cloudabi, license BSD-2-Clause is incompatible with MIT
 ERROR cargo_lichking::check > shuf cannot include package cloudabi, license BSD-2-Clause is incompatible with MIT
 ERROR cargo_lichking        > Incompatible license
```

```
$ cargo lichking list --all
CC0-1.0: dunce
MIT: advapi32-sys, ansi_term, arch, atty, base32, base64, basename, cat, chgrp, chmod, chown, chroot, cksum, clap, comm
, cp, cut, data-encoding, date, dircolors, dirname, du, echo, env, expand, expr, factor, false, fmt, fold, generic-arra
y, groups, hashsum, head, hostid, hostname, id, install, join, kernel32-sys, kill, libstdbuf, link, ln, logname, ls, mk
dir, mkfifo, mknod, mktemp, more, mv, nice, nix, nix, nl, nohup, nproc, number_prefix, numfmt, od, onig, onig_sys, past
e, pathchk, pinky, platform-info, printenv, printf, ptx, pwd, readlink, realpath, redox_syscall, redox_termios, relpath
, rm, rmdir, rust-ini, seq, shred, shuf, sleep, sort, split, stat, stdbuf, strsim, sum, sync, synstructure, tac, tail,
tee, term_grid, termion, termsize, test, textwrap, timeout, touch, tr, true, truncate, tsort, tty, uname, unexpand, uni
q, unlink, uptime, users, uucore, uutils, void, wc, who, whoami, wild, winapi, yes
BSD-2-Clause: cloudabi
BSD-3-Clause: sha1
ISC: rdrand
License specified in file (C:\Users\Roy\.cargo\registry\src\github.com-1ecc6299db9ec823\fuchsia-cprng-0.1.1\Cargo.toml\
LICENSE): fuchsia-cprng
Unlicense / MIT: aho-corasick, aho-corasick, byteorder, memchr, same-file, utf8-ranges, walkdir, winapi-util
MIT / Apache-2.0: backtrace, backtrace-sys, bit-set, bit-vec, bitflags, bitflags, block-buffer, byte-tools, cfg-if, chr
ono, cpp, cpp_common, cpp_macros, cpp_syn, cpp_synom, digest, either, failure, failure_derive, fake-simd, filetime, fnv
, getopts, glob, glob, half, hex, ioctl-sys, isatty, itertools, lazy_static, libc, md5, nodrop, num-integer, num-traits
, num_cpus, numtoa, quick-error, quote, rand, rand, rand, rand_core, rand_core, regex, regex-syntax, remove_dir_all, ru
stc-demangle, semver, semver-parser, sha2, sha3, syn, synom, tempdir, tempfile, thread_local, time, typenum, ucd-util,
unicode-width, unicode-xid, unix_socket, vec_map, walker, winapi, winapi-i686-pc-windows-gnu, winapi-x86_64-pc-windows-
gnu, xattr
```

**Comment by ArniDagur** [comment]
For the `sha1` crate, I'd replace it with the MIT/Apache2.0 licensed [`sha-1`](https://github.com/RustCrypto/hashes/tree/master/sha1) by RustCrypto. The former was last updated two years ago--the latter only 3 months ago.

**Comment by 0x326** [comment]
@rivy I'm not convinced BSD-2-clause and BSD-3-clause are actually incompatible with the MIT license. The references you provided don't seem to suggest incompatibility. The Stack Exchange answer even says "However, all these freedoms are implied by the BSD license, because all these activities can be considered 'use' and/or 'redistribution' of the software." 

Although I am not a lawyer, I think we're fine.

**Comment by sylvestre** [comment]
Yeah, I agree with @0x326 Seems very unlikely that it will ever be an issue

**Comment by Arcterus** [comment]
I don’t think it will be an issue, but we should replace at least the `sha1` crate.  I am tempted to drop the `sha1` and `sha2` crates and replace them with `ring`, but if we do we should probably drop the `rand` crate as well and switch to `ring`’s `rand` module.  `ring` also does not implement MD5, which, while understandable, is rather annoying for our purposes.  It also seems that SHA-3 isn’t available yet either.

I’m not sure how difficult it will be to drop `cloudabi`.  I’m still uncertain whether the license is truly incompatible, but If we can’t drop it (and determine that the license is indeed incompatible), asking them to sublicense the crate as MIT seems reasonable enough.

**Comment by nbraud** [comment]
> I am tempted to drop the `sha1` and `sha2` crates and replace them with `ring`

@Arcterus FYI, Brian Smith — the author of `ring` — has a tendency to yank unsupported versions from crates.io, which can be a giant pain for both project maintainers (who depend on `ring`), people wanting to use those projects, and people packaging them in Linux distros.

**Comment by sylvestre** [comment]
>  tendency to yank all but the latest version 

Being vaguely involved in NSS (Brian used to be too), I think this is the right and recommended approach for crypto libraries...

**Comment by Arcterus** [comment]
That is good to know.  I suppose my main concern about that is that we may be forced to bump the minimum required version of Rust on our end.
