### ISSUE TITLE
Add "Apache-2.0" license?

### ISSUE THREAD

**Issue by rivy** [uutils/coreutils#1471]
Should this project add the "Apache-2.0" license as a dual-license (for protection against "patent aggression")? "MIT/Apache-2.0" (equivalently, "MIT or Apache-2.0") is the license used by `rust` itself.

ref: https://opensource.stackexchange.com/questions/217/what-are-the-essential-differences-between-the-bsd-and-mit-licences
ref: https://dwheeler.com/essays/floss-license-slide.html @@ http://archive.today/4QHQ0
ref: https://github.com/dtolnay/rust-faq#why-a-dual-mitasl2-license

**Comment by Icy-Thought** [comment]
I would argue against this and rather argue in favor of adding a GPT license for the sake of retaining the work committed to this project instead of having it concealed by the works of proprietary software.

**Comment by djmattyg007** [comment]
I think a project like this will never gain traction without a GPL license. What is the incentive for people to donate their time when there is no assurance that big corporations must also do the same?

**Comment by sylvestre** [comment]
With more than 150 contributors, I think the ship has sailed for the license.
Sorry!
