### ISSUE TITLE
code coverage: Incorrect link

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1482]
From:
https://codecov.io/gh/uutils/coreutils/tree/master/src/uu

Try to see coverage info about echo.rs, it leads to a 404:
https://codecov.io/gh/uutils/coreutils/src/master/src/uu/echo/src/echo.rs

**Comment by sylvestre** [comment]
@rivy rings a bell ?

**Comment by rivy** [comment]
I believe this is fixed... <https://codecov.io/gh/uutils/coreutils/src/master/src/uu/base64/src/base64.rs> displays the correct code and coverage. And I still see the same both logged on and off.

Re-open if you still see a problem.

**Comment by rivy** [comment]
Re-opening... When logged in, I can see all pages.

But, when logged out, if I try to view a file that I haven't viewed recently *while logged in* than I get a "GitHub API: Forbidden" error.

I've opened a [discourse message](https://community.codecov.io/t/coverage-file-details-unavailable-unless-logged-in-public-repo/1380) about it.
