### ISSUE TITLE
mv cannot stat certain files

### ISSUE THREAD

**Issue by dilyn-corner** [uutils/coreutils#1489]
I am installing uutils similarly to busybox, with a bunch of symlinks pointing to uutils. 

Because of conflicts between busybox and uutils, these symlinks are not installed to /usr/bin/, but instead they can be found in /var/db/kiss/choices/. On attempting to `mv` any of these symlinks, I get an error: 

`mv: error: cannot stat 'foo': No such file or directory`

My hunch is that `mv` does not like that the file is a symlink. 

Here are my commands along with their output. The first two commands use busybox `mv`, the rest use uutils: 

```
> kiss a uutils-coreutils /usr/bin/basename

Swapping '/usr/bin/basename' from 'busybox' to 'uutils-coreutils'

> kiss a uutils-coreutils /usr/bin/mv

Swapping '/usr/bin/mv' from 'busybox' to 'uutils-coreutils'

> kiss a uutils-coreutils /usr/bin/cksum

Swapping '/usr/bin/cksum' from 'busybox' to 'uutils-coreutils' mv: error: cannot stat ‘uutils-coreutils>usr>bin>cksum’: No such file or directory

> ls -l /usr/bin/mv

lrwxrwxrwx 1 root root 6 May 1 02:23 /usr/bin/mv -> uutils

> ls -l /var/db/kiss/choices | grep cksum

busybox>usr>bin>cksum -> busybox
uutils-coreutils>usr>bin>cksum -> uutils
```

uutils-mv works fine in a different case, swapping busybox's `clear` for ncurses'. The reverse does not work. Presumably because the former is a symlink, and the latter is not.

Notably, it is unable to move /usr/bin/cksum (pointed at busybox) to /var/db/kiss/choices/busybox>usr>bin>cksum. One exists in /usr/bin/cksum (-> busybox), and the other in /var/db/kiss/choices/.

Simple tests return similar results:

```
>touch foo
> ln -s foo bar
> mv bar
mv: error: cannot stat 'bar': No such file or directory"
```

**Comment by sylvestre** [comment]
I am not sure I understand your problem.
I just tried to following from the master:
```
  ./target/debug/touch aze
  ./target/debug/ln -s aze bar2
  ./target/debug/mv bar2 foo

```and it works

**Comment by sylvestre** [comment]
No news from the reporter, closing
