### ISSUE TITLE
Update README and other documentation

### ISSUE THREAD

**Issue by rivy** [uutils/coreutils#1502]
Multiple areas of documentation need to be updated.

- [ ] README ~ various build methods (with requirements)
- [ ] README ~ available `cargo make` build targets (with requirements)
- [ ] README ~ alternate multi-binary names, naming prefixes, linking (both hard [recommended] and symbolic)
- [ ] requested commit message styling (ie, `fix(UUTIL) ...` or `maint/CICD ~ ...`)
  - `CATEGORY`, `CATEGORY/SCOPE`, or `CATEGORY(SCOPE)`
  - `:` OR `~` optional separator
  - categories: change ("Changes"), docs ("Documentation"), feat ("Features"), fix ("Fixes"), maint ("Maintenance") , perf ("Enhancements"), refactor ("Refactoring"), test ("Test Improvements"), update ("Dependency Updates")
    - aliases: add => change, added => change, bugfix => fix, build => maint, changed => change, chore => maint, feature => feat, fixed => fix, fixes => fix, refact => refactor, updated => update, upkeep => maint
- [ ] *planned* automated CHANGELOG based on commits format above (using [fork of git-chglog](https://github.com/rivy-go/git-changelog) ... still needs auto-stripping of prefix/suffix prior to use)

**Comment by Artoria2e5** [comment]
The README for `cp` can also use an update: it should get many flags checked as done.
