### ISSUE TITLE
`test_random_big()` fails (or hangs) randomly

### ISSUE THREAD

**Issue by rivy** [uutils/coreutils#1531]
Yes, I know it's ironic 😄 ... but it's periodically breaking the build.

- see <https://github.com/rivy/rs.coreutils/runs/725535494?check_suite_focus=true>
- see <https://github.com/rivy/rs.coreutils/runs/724178046?check_suite_focus=true>

Ping @nbraud ; any interest or thoughts?

**Comment by rivy** [comment]
`test_factor::test_random_...` should be changed to print the used random seed and allow setting that seed for reproducibility and investigation of failed tests.

**Comment by nbraud** [comment]
Oops, sorry, I missed this issue entirely, but this should have been fixed by #1529
