### ISSUE TITLE
Add b2sum support to hashsum

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1543]
GNU coreutils now has `b2sum`, so it needs to be added to `hashsum`.

**Comment by TheAlakazam** [comment]
Hey, I want to contribute to this. Can I be assigned to this task?

**Comment by sylvestre** [comment]
Sure, nobody is working on it currently.
Please make sure that you have tests too!

**Comment by Arcterus** [comment]
This was resolved in the referenced PR above.
