### ISSUE TITLE
Non-GNU/non-standard utilities?

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1548]
I am considering adding support for slightly modified versions (by which I mean set up to use `uumain` instead of `main`) of `ripgrep`, `fd`, etc.  These would not be built by default (at least at first), instead requiring a flag like `--extra` or something to be built.

I'm am effectively considering an expansion of the project's scope.  Rather than simply aiming for GNU-compatibility, we would aim to be *the* project to use if you want backwards-compatibility *and* fast modern versions of essential utilities.  This expansion would likely tie in with #1349 as well.

Thoughts?

**Comment by Arcterus** [comment]
Beyond just adding stuff like `exa` to the multicall binary, we could also have a feature flag that *replaces* `ls` with `exa`, be it at runtime or at compile-time (if you don't need backwards-compatibility).  Obviously `exa` is just an example here and is not the only program for which we might do this.

I'm less sure about this idea as it is more likely to break existing systems.

**Comment by sylvestre** [comment]
I am not sure about the "why"?

People who wants to use fd, ripgrep or exa are going to install them directly. fd and ripgrep are clearly very different from the GNU coreutils arguments.
I think the scope of coreutils is clear and well defined. Adding some extra things seems to me out of scope.

For now, I think we should focus our energy on completing the implementation of coreutils (missing binaries, missing options, inconsistency in the code base, too many clone()/unwrap()).

**Comment by lambda** [comment]
I have a different but related question about the scope of this project. Would this project include binaries which are standardized in POSIX/SUS, but not included in GNU coreutils, such as dc/bc? Or is it intended that those go in a separate project like the uutils/findutils?

**Comment by rivy** [comment]
I think any standard utilities (GNU, POSIX, or SUS) are fair game for inclusion. Initially, GNU-compatibility is a fair goal, but, given the cross-platform usefulness of `coreutils`, I think that any reasonably well-used standard utility will be a good edition. I think chaining the project to pure GNU-only is too restrictive, and we already have a few extensions to the utilities that go beyond the GNU standard.

**Comment by DiegoMagdaleno** [comment]
I would love the idea proposed by @Arcterus to add extra utils like exa and ripgrep, would make the command line experience even more amazing

**Comment by Sporesirius** [comment]
is there a decision yet?
Would love to see the idea proposed by @Arcterus

**Comment by sylvestre** [comment]
Yeah, the decision is "not right now".
Let's focus first on the GNU compat first. We can reevaluate later.

**Comment by tertsdiepraam** [comment]
Agreed. This is also mostly something that distributions can provide. It's not really our responsibility to package other applications. That being said, it could be interesting to explore whether we can fit more utilities into the multicall binary at some point (e.g. a combined multicall for coreutils and findutils and maybe even more). But the coreutils have priority :)
