### ISSUE TITLE
Add installation instructions with various distributions/packaging systems

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1551]
From briefly looking around, it looks like a few more Linux distributions/packaging systems have packaged `uutils` in their repositories since I last checked:
* Arch Linux (in community)
* Exherbo
* Homebrew (#1555 needs to be fixed)

We might also want indicate that `uutils` is preinstalled in Redox.

**Comment by sylvestre** [comment]
I have been working to get it in Debian & Ubuntu too
