### ISSUE TITLE
coreutils 0.0.1.1 fails to build

### ISSUE THREAD

**Issue by equal-l2** [uutils/coreutils#1555]
coreutils 0.0.1.1 cannot build from tarball with the error following:

```
% make
cargo build  --features "arch base32 base64 basename cat chgrp chmod chown chroot cksum comm cp cut df dircolors dirname du echo env expand expr factor false fmt fold groups hashsum head hostid hostname id install join kill link ln logname ls mkdir mkfifo mknod mktemp more mv nice nl nohup nproc numfmt od paste pathchk pinky printenv printf ptx pwd readlink realpath relpath rm rmdir seq shred shuf sleep sort split stat stdbuf sum sync tac tail tee test timeout touch tr true truncate tsort tty uname unexpand uniq unlink uptime users wc who whoami yes"  --no-default-features
    Updating git repository `https://github.com/uutils/uucore.git`
    Updating git repository `https://github.com/uutils/uucore.git`
error: failed to get `uucore` as a dependency of package `uu_arch v0.0.1 (/Users/hitoshi/test/coreutils-0.0.1.1/src/uu/arch)`

Caused by:
  failed to load source for dependency `uucore`

Caused by:
  Unable to update https://github.com/uutils/uucore.git?branch=canary#9ada3336

Caused by:
  revspec '9ada33368f1b8bfa3b39135a4a73c2b17d385b5f' not found; class=Reference (4); code=NotFound (-3)
make: *** [build-uutils] Error 101
```

**Comment by Arcterus** [comment]
Someone may have force-pushed to that branch and accidentally wiped the commit away.  I will check later to verify.  This issue shouldn’t occur again after #1544 is merged, which I expect will be accompanied shortly after by a version bump.  It may make more sense to wait until the version bump to change the Homebrew formula.

**Comment by rivy** [comment]
Fixed (commit restored and tagged as `0.0.4-canary` for preservation).

**Comment by equal-l2** [comment]
It still doesn't build. Backporting 54ada64 is required.
```
error: package ID specification `arch` matched no packages
```

**Comment by rivy** [comment]
@equal-l2 , I'll look at it further. But `0.0.1.1` is a fixed, published point, so I can't really backport anything into it. It will have to have a new release.

For the `0.0.1.1` release, `cargo make ...` is available as an alternate build recipe.

> Install `cargo-make` using `cargo install cargo-make`.

`cargo make` builds the multicall binary and `cargo make utils` to builds all of the individual utilities.

`cargo make help` can give you further insight, if needed.

**Comment by equal-l2** [comment]
Sorry for the poor writing, I was aware that we cannot add anything to `0.0.1.1`, which is already released. I'll wait for a new release.
