### ISSUE TITLE
`--chdir=DIR` in `env`

### ISSUE THREAD

**Issue by FelipeLema** [uutils/coreutils#1568]
Latest GNU coreutils have a useful (to me) feature of changing the "current" directory before running the command:

```
  -C, --chdir=DIR      change working directory to DIR
```
The way it works in GNU coreutils is that it changes to the fully-symlink-resolved path (think `readlink -f`) of the directory being provided. I personally prefer it to be "change to the exact path I'm providing, regardless of whether it is relative or not", but maybe someone has a different opinion about this.

**Comment by rivy** [comment]
Thanks for the note.
I'll look into it when I get some time.
If you'd like it sooner, PRs are welcome!

**Comment by FelipeLema** [comment]
I'll do a PR soon, then.
