### ISSUE TITLE
Feature parity with GNU head

### ISSUE THREAD

**Issue by chadbrewbaker** [uutils/coreutils#1581]
See this line and below. I ran the GNU head test suite against a uu_head binary and added failing unit test cases:
https://github.com/uutils/coreutils/blob/d878f3603835210532d027bffe272b9276add617/tests/by-util/test_head.rs#L90

```bash
echo -e "a" | uu_head # returns "a\n" not "a"
echo -e "abc" | uu_head -1c # barfs instead of returning "a"
echo -e "a\n" | uu_head -n 2048m # barfs instead of returning "a\n"
echo -e "x\0y" | uu_head  -z -n 1 # barfs instead of returning "x\0"
echo -e "x\0y" | uu_head  -z -n 2 # barfs instead of returning "x\0y"
echo -e "a\n" | uu_head  --bytes=-2 # barfs instead of returning ""
echo -e "a\nb\n" | uu_head  --lines=-0  # "" returns instead of "a\nb\n"
```

**Comment by FelipeLema** [comment]
It seems that these tests are already passing? Check [my build with the `[#ignore]`s removed](https://github.com/FelipeLema/coreutils/actions/runs/344415886)

**Comment by SuperSandro2000** [comment]
Related #1822

**Comment by jfinkels** [comment]
I just tested these examples. Taking into account the fact that `echo` appends a newline character, these are all working as expected. They match the output of GNU `head`, so I think this can be closed.
