### ISSUE TITLE
Parity with GNU coreutil environment variables.

### ISSUE THREAD

**Issue by chadbrewbaker** [uutils/coreutils#1582]
Shout out to @wgwoods for pointing this out. Behold the eye bleach that is use of environment variables in GNU coreutils: https://gist.github.com/chadbrewbaker/c4f1b170ecadae0abcbf285c1e374d26

A hand curated list of the first few.  We need to either support or ignore them and add failing unit tests accordingly.

split.c:483  "SHELL"
stty.c:1822 "COLUMNS"
wc.c:703 "POSIXLY_CORRECT"
cp.c:828 "POSIXLY_CORRECT"
printf.c:666 "POSIXLY_CORRECT"
tac.c:437 "TMPDIR"
df.c:1717 "POSIXLY_CORRECT"
df.c:1720 "DF_BLOCK_SIZE"
du.c:753 "DU_BLOCK_SIZE"
du.c:911 "TZ"
du.c:967 "TIME_STYLE"
stdbuf.c:132  "PATH", "_"
stdbuf.c:197  preload_env  #Need to research what this string expands to
date.c:508 "TZ"
mktemp.c:267  "TMPDIR"
mktemp.c:286  "TMPDIR"
echo.c:111 "POSIXLY_CORRECT"
dd.c:907  "POSIXLY_CORRECT"
sort.c:4209 "POSIXLY_CORRECT"
sort.c:4704 "TMPDIR"
pr.c:1061 "POSIXLY_CORRECT"
pr.c:1065 "TZ"
touch.c:400 "POSIXLY_CORRECT"
libstdbuf.c:140 "_STDBUF_E"
libstdbuf.c:141  "_STDBUF_I"
libstdbuf.c:142 "_STDBUF_O"
uniq.c:480 "POSIXLY_CORRECT"

**Comment by FelipeLema** [comment]
this should definitely be broken into several issues

I'm stating this because each tool needs to be analysed separately. As a sample, `split` requires the `--filter` CLI argument to use `SHELL` (which it currently doesn't have)
