### ISSUE TITLE
ptx hangs on large inputs in roff mode due to suboptimal algorithm

### ISSUE THREAD

**Issue by CreepySkeleton** [uutils/coreutils#1588]
[The recent study](https://arxiv.org/pdf/2008.06537.pdf) have fuzzed the hell out of coreutils. As collateral, they discovered that `ptx` effectively hangs on large inputs due to suboptimal processing algorithm:

> In Rust, ptx appeared to hang because of a N2 algorithm in
function format_roff_line. This function processes almost
every substring on the input line that ends with the last char-
acter. Since our input was a single line of 93,290,954 bytes, N2
is 8.7 × 1015. We ran this test case for 34 hours and it ﬁnished
22% of the input, so we estimate completion time in 155 hours.
While technically not a hang, this ran long enough that we
considered it one.

I also noticed that this function recompiles the same regex 4-5 times on each call. Unnecessary allocations are aplenty as well.

As a bit of realistic point of view, `ptx` is used by approximately nobody these days, so I'm not really sure if spending time on improving the program worth anything.

**Comment by rivy** [comment]
@CreepySkeleton , thanks for the report!

PRs welcome? :smile:
