### ISSUE TITLE
Intermittent test failures for `cp` tests under MacOS

### ISSUE THREAD

**Issue by rivy** [uutils/coreutils#1590]
### examples 

- https://github.com/uutils/coreutils/runs/964069370?check_suite_focus=true fails but https://github.com/uutils/coreutils/runs/964069084?check_suite_focus=true passes (same CI build)
- https://github.com/uutils/coreutils/runs/1017608668?check_suite_focus=true fails but https://github.com/uutils/coreutils/runs/1017608693?check_suite_focus=true passes (same CI build) and https://github.com/uutils/coreutils/runs/1017668015 passes (a rebuild of the same job, no code changes)

It looks to me like it could be race conditions between the various `cp` sub-tests.

**Comment by chadbrewbaker** [comment]
https://opensource.apple.com/tarballs/shell_cmds/shell_cmds-207.11.1.tar.gz is the latest XNU command line utilities but cp doesn't seem to be in there. https://github.com/NetBSD/src/blob/trunk/bin/cp/cp.c is probably close

Actually seems to be two errors. 

```bash
run: /Users/runner/work/coreutils/coreutils/target/x86_64-apple-darwin/debug/coreutils cp -r hello_dir_with_file/ hello_dir_new
thread 'test_cp::test_cp_recurse' panicked at 'assertion failed: result.success', /Users/runner/work/coreutils/coreutils/tests/by-util/test_cp.rs:124:5
```
https://github.com/uutils/coreutils/runs/964069370?check_suite_focus=true#step:10:904

```bash
run: /Users/runner/work/coreutils/coreutils/target/x86_64-apple-darwin/debug/coreutils cp hello_world.txt hello_dir/
thread 'test_cp::test_cp_with_dirs' panicked at 'assertion failed: result_to_dir.success', /Users/runner/work/coreutils/coreutils/tests/by-util/test_cp.rs:154:5
```
https://github.com/uutils/coreutils/runs/1017608668?check_suite_focus=true#step:11:904

Running the test suite hoses my shell in bash for starters, had to run a reset.

I was able to reproduce.
```bash
cargo test --features "cp" --no-default-features #Warmup build
for n in {1..5}; do cargo test --features "cp" --no-default-features; done
```
The following tests failed:
```bash
cp -r hello_dir_with_file/ hello_dir_new  #result.success failed test_cp.rs:124:5
cp hello_world.txt hello_dir/ # result_to_dir.success failed test_cp.rs:154:5
```

I'll trying repeating the failures under dtrace, and run OSX default cp under dtrace to see what the difference is in operating system calls.

**Comment by chadbrewbaker** [comment]
How to get at the test binaries:

```bash
./target/debug/coreutils cp #call binary directly
cargo test test_cp
#prints a test binary like target/debug/deps/tests-dfcdec9b424805e3
```
How to disable SIP on OSX so you can run dtrace: https://www.macworld.co.uk/how-to/mac/how-turn-off-mac-os-x-system-integrity-protection-rootless-3638975/

Blog post on running Dtrace on OSX, https://carol-nichols.com . Suggestion that you turn opt-level = 3 on for test builds.

```bash
[profile.test]
opt-level = 3
debug = true
```

For whatever reason errors aren't presenting themselves under sudo dtruss...

```bash
for n in {1..30}; do sudo dtruss ./target/debug/deps/tests-983e5e2dea773d29 test_cp 2> ${n}.trace ; done

```

Looking at the sytem calls, fclonefileat() is the only odd duck I see.  Rust added support for it in https://github.com/rust-lang/rust/pull/59883/files 

Here is what uu_cp is doing:
```bash 
stat64("/Users/myuser/github/coreutils/borkdir/bar.txt\0", 0x7FFEEEC145E0, 0x0)          = 0 0
stat64("/Users/myuser/github/coreutils/borkdir/bar.txt\0", 0x7FFEEEC145E0, 0x0)          = 0 0
stat64("forkdir/bar.txt\0", 0x7FFEEEC13240, 0x0)                 = -1 Err#2
open("/Users/myuser/github/coreutils/borkdir/bar.txt\0", 0x1000000, 0x1B6)               = 4 0
fstat64(0x4, 0x7FFEEEC127F0, 0x0)                = 0 0
fclonefileat(0x4, 0xFFFFFFFFFFFFFFFE, 0x7F96B2D04CE0)            = 0 0
close_nocancel(0x4)              = 0 0
````

Here is what MacOS /usr/bin/cp is doing:

```bash
stat64("forkdir/bar.txt\0", 0x7FFEEA5C1210, 0x0)                 = -1 Err#2
open("borkdir/bar.txt\0", 0x0, 0x0)              = 3 0
open("forkdir/bar.txt\0", 0x601, 0x81A4)                 = 4 0
fstatfs64(0x4, 0x7FFEEA5C08C8, 0x0)              = 0 0
fstat64(0x4, 0x7FFEEA5C08C8, 0x0)                = 0 0
fchmod(0x4, 0x8180, 0x0)                 = 0 0
read(0x3, "\0", 0x100000)                = 0 0
fchmod(0x4, 0x81A4, 0x0)                 = 0 0
fstat64_extended(0x3, 0x7F8482505ED8, 0x7F8482505FD0)            = 0 0
fstat64(0x4, 0x7FFEEA5C0790, 0x0)                = 0 0
fchmod(0x4, 0x1A4, 0x0)          = 0 0
__mac_syscall(0x7FFF69581E11, 0x52, 0x7FFEEA5C0710)              = -1 Err#93
flistxattr(0x4, 0x0, 0x0)                = 0 0
flistxattr(0x3, 0x0, 0x0)                = 0 0
fchmod(0x4, 0x1A4, 0x0)          = 0 0
close(0x3)               = 0 0
close(0x4)               = 0 0
```

Perhaps we should avoid use of fclonefileat() ?

**Comment by rivy** [comment]
@chadbrewbaker , thanks for the analysis!

I'm not sure how to translate this lower-level syscall information into a transformation of the rust code. Is this a bug in the `cp` code in this repo or a library problem? Any insight or suggestions so that we can test some changes?

Thanks.

**Comment by rivy** [comment]
@uutils/maintainers , this has become annoying. I'm now frequently having to restart failed CI testing which has no test failures other than these intermittent fails. It's causing a hitch in iteration and PR proposal evaluation.

I vote to disable these two tests on MacOS until some solution is implemented. Thoughts?

**Comment by sylvestre** [comment]
Works for me :+1:
