### ISSUE TITLE
uname -p should be implemented

### ISSUE THREAD

**Issue by kevinburkemeter** [uutils/coreutils#1636]
Nokogiri is a popular Ruby gem. Attempting to install it, it invokes both `uname` and `ls` from this coreutils library, which fail. You should be able to reproduce by running "gem install nokogiri" on a Mac.

```
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... error: Found argument '-p' which wasn't expected, or isn't valid in this context

USAGE:
    uname [OPTION]...

For more information try --help
```

And then later on...

```
checking for a BSD-compatible install... /Users/kevin/local/coreutils/bin/install -c
checking whether build environment is sane... configure: error: ls -t appears to fail.  Make sure there is not a broken
  alias in your environment
configure: error: newly created file is older than distributed files!
```

**Comment by kevinburkemeter** [comment]
I believe in particular it's attempting to compile and install libxml2 version 2.9.10.

**Comment by kevinburkemeter** [comment]
I don't know what your position on compatibility is, but to some extent you have to be compatible I think or so much software will break that it'll be very hard to keep trying this on an ongoing basis.

**Comment by sylvestre** [comment]
Please split different issues in different tickets.

Yeah, we should add the options.
https://github.com/uutils/coreutils/blob/master/src/uu/uname/src/uname.rs#L80-L84

please report a different issue for "ls -t" with more details . The option exists https://github.com/uutils/coreutils/blob/master/src/uu/ls/src/ls.rs#L151-L154 but might not be working as expected
