### ISSUE TITLE
ls: don't use colors if stdout is not a TTY

### ISSUE THREAD

**Issue by kevinburkemeter** [uutils/coreutils#1638]
Here is the relevant snippet in `configure`, at least on my Mac running Catalina

```
if (
   am_has_slept=no
   for am_try in 1 2; do
     echo "timestamp, slept: $am_has_slept" > conftest.file
     set X `ls -Lt "$srcdir/configure" conftest.file 2> /dev/null`
     if test "$*" = "X"; then
	# -L didn't work.
	set X `ls -t "$srcdir/configure" conftest.file`
     fi
     if test "$*" != "X $srcdir/configure conftest.file" \
	&& test "$*" != "X conftest.file $srcdir/configure"; then

	# If neither matched, then we have a broken ls.  This can happen
	# if, for instance, CONFIG_SHELL is bash and it inherits a
	# broken ls alias from the environment.  This has actually
	# happened.  Such a system could not be considered "sane".
	as_fn_error $? "ls -t appears to fail.  Make sure there is not a broken
  alias in your environment" "$LINENO" 5
     fi
     if test "$2" = conftest.file || test $am_try -eq 2; then
       break
     fi
     # Just in case.
     sleep 1
     am_has_slept=yes
   done
   test "$2" = conftest.file
   )
then
   # Ok.
```

I get the following error message when I attempt to compile this using coreutils `ls`

```
checking for a BSD-compatible install... /Users/kevin/local/coreutils/bin/install -c
checking whether build environment is sane... configure: error: ls -t appears to fail.  Make sure there is not a broken
  alias in your environment
configure: error: newly created file is older than distributed files!
Check your system clock
```

**Comment by sylvestre** [comment]
You should have a config.log with more information. Could you please have a look?
(more interesting that the configure source)

**Comment by kevinburkemeter** [comment]
I pulled out most of it, but here is the full thing.

```
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... error: Found argument '-p' which wasn't expected, or isn't valid in this context

USAGE:
    uname [OPTION]...

For more information try --help
powerpc-apple-darwin19.6.0
checking host system type... x86_64-apple-darwin19.6.0
checking for a BSD-compatible install... /Users/kevin/local/coreutils/bin/install -c
checking whether build environment is sane... configure: error: ls -t appears to fail.  Make sure there is not a broken
  alias in your environment
configure: error: newly created file is older than distributed files!
Check your system clock
```

**Comment by sylvestre** [comment]
Actually, the option "ls -t" has been implemented.
They are behaving differently
probably a bug on the rust/coreutils side

**Comment by kevinburkemeter** [comment]
I think it's the uname -p failing, which is causing some downstream part of the build to fail, ending in a misleading error message. You can reproduce by trying to compile libxml I believe.

**Comment by sylvestre** [comment]
Nope, I think there is a real problem. ls & coreutils/ls should return the same output.

**Comment by kevinburkemeter** [comment]
I figured out the problem here. `ls -t` is printing the output with ANSI escape sequences even when not printing to a TTY. That means that this if statement check fails:

<img width="526" alt="kevin@hyena: ~: rbenv:versions:2 7 2:lib:ruby:gems:2 7 0:gems:ffi-1 13 1:ext:ffi_c:libffi 2020-12-18 14-09-17" src="https://user-images.githubusercontent.com/51895701/102665927-a5c51f80-413a-11eb-9aed-13121b50b90e.png">

Because the left side has ANSI color sequences and the right side doesn't.

I can't reproduce this if I use BSD `ls` or even GNU coreutils `ls`. I can also fix the error by manually editing the `configure` file to read `ls --color=never -t ...` though of course I don't control the underlying software and I don't think that should be necessary.

**Comment by kevinburkemeter** [comment]
Here's the code it looks like so I'm confused as to how this is happening.

```
    let color = match options.opt_str("color") {
        None => true,
        Some(val) => match val.as_ref() {
            "always" | "yes" | "force" => true,
            "auto" | "tty" | "if-tty" => stdout_isatty(),
            /* "never" | "no" | "none" | */ _ => false,
        },
    };
```

If I do `ls | cat` I can see colors in my terminal. The `LS_COLORS` environment variable is not set.

**Comment by kevinburkemeter** [comment]
Oh, right, if I specify None I get colors. That's not good.
