### ISSUE TITLE
fmt has different limit on the width option compared to GNU coreutils

### ISSUE THREAD

**Issue by jaggededgedjustice** [uutils/coreutils#1704]
The gnu `fmt` command does not allow a value for width above 2500, and it will immediately return an error if one is given. for example with the GNU command you get 
```
fmt -w 2501
fmt: invalid width: ‘2501’: Numerical result out of range
```
I'm not sure if this should be treated as an error in this implementation, it depends on the level of compatibility that is desired. 

This causes a hang in the GNU tests, as the test runs `fmt -w 32768` without any input and expect it to return an error. If this is not considered a problem then something will need to be done with the gnu tests.

**Comment by sylvestre** [comment]
@jaggededgedjustice do you want to fix it or should I?

**Comment by jaggededgedjustice** [comment]
It'd be great if you can take care of this, while I'm working out if there are any other hangs.
