### ISSUE TITLE
cat does not check for output file being the same as the input file

### ISSUE THREAD

**Issue by jaggededgedjustice** [uutils/coreutils#1707]
The GNU cat implementation checks if the file being output to is the same as the input file. For example
```
echo x >out
cat out >>out 
cat: out: input file is output file
```

However the implementation in this repo doesn't run this check, which means it can be stuck in a infinite loop.

**Comment by Mikadore** [comment]
I'm working on this. GNU's implementation uses `fstat` to compare whether any input file is the same as the output file. I don't see any way to implement this cross-platform with the standard library. So - `fstat` for POSIX and for windows, after a short search`GetFinalPathNameByHandleA` seems to be the best fit.

**Comment by jfinkels** [comment]
This error seems to only happen when appending, not when writing:
```sh
$ echo x > out && cat out >> out
cat: out: input file is output file
```
Also, there is no error if the file is empty:
```sh
$ touch f && cat f >> f
```

**Comment by tertsdiepraam** [comment]
All cases mentioned in this issue now work correctly on master due to https://github.com/uutils/coreutils/pull/2554 from back in August.
