### ISSUE TITLE
numfmt should refuse to run with --header=0

### ISSUE THREAD

**Issue by jaggededgedjustice** [uutils/coreutils#1708]
GNU numfmt will refuse to run the `--header=0` as this would be equivalent to not specifying the ``header` option. The rust numfmt will wait for input (which causes a hang in a GNU test), and if given input will throw an unhelpful error message:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "This suffix is unsupported for specified unit"', /home/james/code/uutils/src/uu/numfmt/src/numfmt.rs:355:9
```

**Comment by chadbrewbaker** [comment]
I added the test case but 'cargo test' seems to be skipping tests/by-util/test_numfmt.rs.

**Comment by sylvestre** [comment]
@chadbrewbaker try with "cargo test --features feat_os_unix"

**Comment by chadbrewbaker** [comment]
cargo test --features "numfmt" worked. I don't see why --header=0 is an issue. A zero length header is equivalent to not having a header which is fine. At least on the unit test it didn't seem to hang. Is there a particular test in the GNU suite it is hanging on?

**Comment by jaggededgedjustice** [comment]
Yes, `tests/misc/numfmt.pl` has a check where it runs with `--header=0` and sends no input expecting an immediate error. The rust numfmt will instead wait for input, causing the test script to hang.
