### ISSUE TITLE
cp does not copy named pipes

### ISSUE THREAD

**Issue by jaggededgedjustice** [uutils/coreutils#1710]
If you try to copy a named pipe cp will fail with `cp: error: '<source>' -> '<dest>': the source path is not an existing regular file`. You can see this with the following test:

```
mkfifo /tmp/fifo
cp /tmp/fifo /tmp/fifo-cp &
echo test >/tmp/fifo 
```
This will not error with GNU cp, and will create `/tmp/fifo-cp` with the contents echoed into `/tmp/fifo`

**Comment by sylvestre** [comment]
Probably the same as 
https://github.com/rust-lang/rust/issues/79390

**Comment by jfinkels** [comment]
This seems to be fixed:
```
$ mkfifo fifo
$ ./target/debug/cp fifo fifo2 &
[1] 977284
$ echo test > fifo
$ cat fifo2
test
[1]+  Done                    ./target/debug/cp fifo fifo2
```
