### ISSUE TITLE
sort: implement '-t' flag

### ISSUE THREAD

**Issue by kevinburkemeter** [uutils/coreutils#1728]
The `-t` flag lets you specify the field separator to use when sorting values.

```
       -t, --field-separator=SEP
              use SEP instead of non-blank to blank transition
```

However, when I try to use it, I get:

```
error: Found argument '-t' which wasn't expected, or isn't valid in this context

USAGE:
    sort 0.0.3

Usage:
 sort [OPTION]... [FILE]...

Write the sorted concatenation of all FILE(s) to standard output.

Mandatory arguments for long options are mandatory for short options too.

With no FILE, or when FILE is -, read standard input.

For more information try --help
```

I ran into this when running `pyenv install -l` to list installed Python versions.

**Comment by mquellhorst** [comment]
I've been looking into this as a first bug to fix while I'm learning Rust.
I'm not that familiar with coreutils so I had to look up how the `-t` flag exactly works.

So far I've found the `-t` flag is being used in combination with the `-k` flag.
The `-k` isn't implemented either so implementing the `-t` flag would require both flags to be implemented.

Can someone verify this and/or bring up other use-cases of the `-t` flag?

**Comment by BartMassey** [comment]
Read closely, the [POSIX specification](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sort.html) of `sort` seems to support your analysis: `-t` is ignored except in dealing with `-k`.

**Comment by byronclark** [comment]
I can confirm that at least the command that led to this issue uses `-k` multiple times. The command being run is [currently](https://github.com/pyenv/pyenv/blob/master/plugins/python-build/bin/python-build#L1834):
```
LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n
```

**Comment by miDeb** [comment]
Working on this :-)

**Comment by miDeb** [comment]
This should work now: https://github.com/uutils/coreutils/pull/1996
