### ISSUE TITLE
chroot: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1732]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/chroot/src/chroot.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_chroot.rs (well, we should write some)

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by anth1y** [comment]
hey @sylvestre I'd love to take this on...
