### ISSUE TITLE
od: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1733]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/od/src/od.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_od.rs (well, we should write some)

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by pedrohjordao** [comment]
I will can take this one

**Comment by pedrohjordao** [comment]
Ok, I've tried my hand at this some, but the handling of the filename or filename and offsets is super weird to do using clap... I'll keep code up as far as i got on this branch if anyone wants to continue with it, I'm just not sure how much it is worth to be honest:

https://github.com/pedrohjordao/coreutils/tree/od-clap

**Comment by pedrohjordao** [comment]
Spoke too soon, things pretty much work out of the box
I have it mostly working I think, will open a PR soon

**Comment by Lothiraldan** [comment]
I think this issue can be closed now

**Comment by JnRouvignac** [comment]
It's been implemented as far as I can tell.
Please close it @sylvestre to avoid any confusion.
Thank you!

**Comment by sylvestre** [comment]
thanks
please contact me sylvestre@debian.org if you are looking for good first bug!

**Comment by JnRouvignac** [comment]
Thanks a lot, I will.
For the moment I am doing backlog grooming: go through the open ones and checking if they are still valid.
