### ISSUE TITLE
sleep: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1735]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/sleep/src/sleep.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_sleep.rs (well, we should write some)

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by arlyon** [comment]
Hi, gonna take a look at this one.

**Comment by sylvestre** [comment]
you will find others, if you need other good first bug, don't hesitate to contact me :)

**Comment by NotNorom** [comment]
> Hi, gonna take a look at this one. Edit nevermind just saw someone beat me to the punch.

Haha sorry, I just really like sleep(ing).

**Comment by NotNorom** [comment]
Okay, I think #1777 is good to go, but I don't get why the "CICD / MinRustV (ubuntu-latest, feat_os_unix) (pull_request)" test is failing, I used `cargo +1.33.0` during these commits so idk what's going on :D
