### ISSUE TITLE
nohup: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1736]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/nohup/src/nohup.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_nohup.rs (well, we should write some)

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by koleesch** [comment]
I think i want to work on this bug.

**Comment by koleesch** [comment]
Could you assign it to me?

**Comment by apatrushev** [comment]
Looks like it is duplicate of #1856 which is already closed.

**Comment by sylvestre** [comment]
oups, sorry
are you looking for good first bug?
