### ISSUE TITLE
timeout does not pass through exit code of command being run

### ISSUE THREAD

**Issue by jaggededgedjustice** [uutils/coreutils#1742]
The `timeout` command will not pass through the exit code of the command being run and instead will always exit '0' if the time out was not reached.
Example;
```
echo 'exit 10' >/tmp/test_timeout
./target/release/timeout 5 bash /tmp/test_timeout
echo $?
```
The `echo $?` should show '10'.

**Comment by Arcterus** [comment]
Let me know if the linked PR fixes the problem for you.

**Comment by jaggededgedjustice** [comment]
Yes, this is fixed
