### ISSUE TITLE
ptx: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1753]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/ptx/src/ptx.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_ptx.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by sudopluto** [comment]
ill think ill give this one a try this weekend
