### ISSUE TITLE
date: implement the set date

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1754]
https://github.com/uutils/coreutils/blob/bfc9e13f113f11be2762fe0f72d74628db88fd36/src/uu/date/src/date.rs#L234  isn't implemented.

It should be cross platform but starting with one platform first is fine.

Tests are in
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/tests/by-util/test_date.rs

**Comment by marcosatti** [comment]
I'm tackling this one if its not taken...

How is libc and winapi meant to be used here? I can see in uucore there is a public reexport but individual utilities are specifying their own copies anyway...
