### ISSUE TITLE
install: implement -C/--compare

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1756]
GNU man pages says:
```
       -C, --compare
              compare  each  pair of source and destination files, and in some
              cases, do not modify the destination at all
```

Code is in 
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/src/uu/install/src/install.rs

Tests in
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/tests/by-util/test_install.rs

**Comment by Goorzhel** [comment]
Starting work on a patch.
