### ISSUE TITLE
install: implement -D

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1757]
GNU man pages says:
```
       -D     create  all  leading  components of DEST except the last, or all
              components of --target-directory, then copy SOURCE to DEST
```

Code is in 
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/src/uu/install/src/install.rs

Tests in
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/tests/by-util/test_install.rs

**Comment by sivachandran** [comment]
@envp Are you still working on this? I just raised PR in `install`. It would be quick for me to make this change as well if you haven't started.

**Comment by envp** [comment]
Nope, no longer working on this. Feel free to take this up.

**Comment by sivachandran** [comment]
The changes are merged into master

**Comment by JnRouvignac** [comment]
It seems this issue has been fixed.
Can you close this issue to avoid confusion @sylvestre ?
Thank you!

**Comment by sylvestre** [comment]
thanks
please contact me sylvestre@debian.org if you are looking for good first bug!
