### ISSUE TITLE
install: implement -p/--preserve-timestamps

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1758]
GNU man pages says:
```
       -p, --preserve-timestamps
              apply access/modification times of SOURCE files to corresponding
              destination files

```

Code is in 
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/src/uu/install/src/install.rs

Tests in
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/tests/by-util/test_install.rs

**Comment by avr1** [comment]
I'd like to take a look at this!

**Comment by konomith** [comment]
I would like to implement this.
