### ISSUE TITLE
install: implement -s/--strip

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1759]
GNU man pages says:
```       
       -s, --strip
              strip symbol tables
```

This will probably require a new dependency (and some cross platform work)

As ride along,
```
       --strip-program=PROGRAM
              program used to strip binaries
```

should be implemented too

Code is in 
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/src/uu/install/src/install.rs

Tests in
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/tests/by-util/test_install.rs

**Comment by sivachandran** [comment]
Let me give a try

**Comment by sivachandran** [comment]
The changes are merged into master. The issue can be closed.

**Comment by sylvestre** [comment]
thanks :)
