### ISSUE TITLE
Implement dd

### ISSUE THREAD

**Issue by zvms** [uutils/coreutils#176]
I'm working on this.

**Comment by abbasfaisal** [comment]
Is anyone working on this? I want to take this up. @filipegoncalves @zvms

**Comment by filipegoncalves** [comment]
Nope, I never made any progress, other things got in between. From my side you can take it over.

**Comment by AgostonSzepessy** [comment]
Is anyone working on this? I'd like to try and implement it.

**Comment by abbasfaisal** [comment]
@AgostonSzepessy From my side you can take it over.

**Comment by wpbirney** [comment]
whats the status on this?
I would be interested in implementing this as dd is one of my favorite utils

**Comment by AgostonSzepessy** [comment]
@wpbirney You can take it over.

**Comment by Arcterus** [comment]
I'm gonna close this in favor of #1121, even though this was created first, as the other issue is tied to a pull request that implements part of `dd`.
