### ISSUE TITLE
cp: implement --parents

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1760]
GNU man pages says:
```
       --parents
              use full source file name under DIRECTORY
```

Code is in 
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/src/uu/cp/src/cp.rs

Tests in
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/tests/by-util/test_cp.rs

**Comment by siyopao** [comment]
Is it okay if I give this one a shot?
