### ISSUE TITLE
cp: implement --strip-trailing-slashes

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1761]
GNU man pages says:
```
       --strip-trailing-slashes
              remove any trailing slashes from each SOURCE argument
```

Code is in 
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/src/uu/cp/src/cp.rs

Tests in
https://github.com/uutils/coreutils/blob/8337179454d0c952746a980ee37a32340f510a46/tests/by-util/test_cp.rs

**Comment by billyb2** [comment]
Should this be closed?

**Comment by sylvestre** [comment]
Yeah, merci!

**Comment by billyb2** [comment]
No problem :)
