### ISSUE TITLE
rm: -d should match GNU's output

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1769]
with rm from GNU:
```
$ mkdir a
$ touch a/b
$ rm -d a
rm: cannot remove '/tmp/a': Directory not empty
```
With the Rust implementation:
```
$ mkdir a
$ rm -rf -v a
rm: error: removing '/tmp/a': Directory not empty (os error 39)
```

This will probably requires to update the `show_error` for all binaries (which is fine)

**Comment by siyopao** [comment]
Hello 👋 Just a quick question if that is okay: for this issue you would also like to remove the `(os error 39)` part as well?

**Comment by billyb2** [comment]
Hi @siyopao , where in the program is (os error 39) showing up?

**Comment by siyopao** [comment]
Hi @billyb2. In the Rust implementation it shows up at the end of `rm: error: removing '/tmp/a': Directory not empty (os error 39)`. The code is OS specific I assume (on Mac it is 66).

**Comment by siyopao** [comment]
Yeah, I just checked and it seems I am using the latest version of the master branch of this repo. The commit you are referencing is in your fork. You should make a PR here!

**Comment by billyb2** [comment]
Jaja, I already made one @siyopao at #1780 . Also my apologies, when you asked about removing the os error part, I thought you were referring to my fork, not the main repo.

**Comment by siyopao** [comment]
That's awesome 🚀
