### ISSUE TITLE
cp: provide --reflink on macOS

### ISSUE THREAD

**Issue by Artoria2e5** [uutils/coreutils#1773]
macOS has a similar file-cloning mechanic since APFS became a thing. An implementation for GNU Coreutils is at https://github.com/Artoria2e5/coreutils/commit/e25bfa5ec19123687704dad014870cf67fb27522.

Note that Apple in its infinite wisdom provides a syscall that takes the filename instead of the ioctl-on-fd approach that Linux and to an extent Windows ReFS uses. This... might make the code a bit messier and even racier.

**Comment by nthery** [comment]
I'm in the process of adding clonefile() to libc: https://github.com/rust-lang/libc/pull/2147.

**Comment by nthery** [comment]
clonefile() was added in macOS 10.12.

Do we want to maintain compatibility with pre-10.12?
If so, is there any prior art to invoke a syscall only if available?

I'm prototyping something with `libc::dlsym()` but I'm not sure if this is the Right Way to go.

**Comment by Artoria2e5** [comment]
That's a great question (lolsob). According to https://users.rust-lang.org/t/compile-rust-binary-for-older-versions-of-mac-osx/38695/3 Rust goes down to 10.7, but the policy might be different on uutils.

**Comment by nthery** [comment]
Thanks.  I'll stick to the `dlsym` approach for the time being.
