### ISSUE TITLE
The README does not correctly state the license of GNU Coreutils

### ISSUE THREAD

**Issue by ian-kelling** [uutils/coreutils#1783]
It says "GNU Coreutils is licensed under the GPL V3." It should say "GNU Coreutils is licensed under the GPL 3.0 or later." To understand this issue, you can read https://www.gnu.org/licenses/identify-licenses-clearly.en.html. GNU Coreutils authors care that their code is copyleft, it would be respectful if you linked to something explaining that, such as https://www.gnu.org/licenses/copyleft.en.html or https://www.gnu.org/philosophy/why-copyleft.en.html

**Comment by sylvestre** [comment]
Thanks for your interesting contribution to improve this project.
I fixed the wording:
https://github.com/uutils/coreutils/commit/5996bc340c1164658e5cc1e5dfa63835b46d86aa
