### ISSUE TITLE
I'd like to donate https://github.com/notriddle/diffutils to this project

### ISSUE THREAD

**Issue by notriddle** [uutils/coreutils#1787]
This probably isn't the right place to put this, but I'm not sure what the right place actually is.

https://github.com/notriddle/diffutils has implementations of GNU's diff formats (unified, context, and normal), and the other formats (ed, side-by-side) will be added once I find time to do them.

Any feedback before transferring ownership of the repo?

**Comment by sylvestre** [comment]
AFAIK, as diff isn't part of the coreutils, I am not sure it makes sense?!

**Comment by notriddle** [comment]
You're right. `find` isn't part of coreutils either, which is why it has its own repo. I would imagine diffutils would remain its own repo under this organization, just like findutils is.

The idea is to transfer it to this organization, to raise the bus factor beyond `1`.

**Comment by sylvestre** [comment]
How does it compare with the current version of diff ?
in term of features? thanks

**Comment by notriddle** [comment]
> How does it compare with the current version of diff ?

You mean the one in GNU diffutils? A tiny fraction of it. It only has an implementation of the `diff` command, and that implementation only covers the three patch formats (normal, context, unified), not the advanced stuff like recursion and side-by-side diffs.

What is in there generates diff files that work in GNU patch. It took a few days of trial-and-error to reverse engineer, because their documentation is... kinda vague about how patch files ought to be formatted when certain corner cases come up. What happens when you run with `-u0`, or you're adding lines to an empty file? The docs don't really seem to say anything about it, but patch and diff both support it, and the `diff` in notriddle/diffutils seems to do it correctly, too (at least, I ran it for a few days of feeding it fuzzer-generated inputs, and it round-tripped correctly).

**Comment by sylvestre** [comment]
@notriddle i would be interested to take it! is it still an option  ? :)
