### ISSUE TITLE
tee: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1793]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/tee/src/tee.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_tee.rs (need to add tests)

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by jhscheer** [comment]
I'm working on this.
