### ISSUE TITLE
nice: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1794]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/nice/src/nice.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_nice.rs (need to add tests)

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by jeckersb** [comment]
I'll take a stab at this

**Comment by Lothiraldan** [comment]
I think this issue can be closed as https://github.com/uutils/coreutils/pull/1810 was merged

**Comment by JnRouvignac** [comment]
Another one that can be closed @sylvestre .
I could do it myself, but I don't have the rights.
Thank you!
