### ISSUE TITLE
head crashes for binary input

### ISSUE THREAD

**Issue by sedrubal** [uutils/coreutils#1799]
Running

```bash
$ uu-head /dev/urandom
```

crashes with this error message

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }', /build/uutils-coreutils/src/coreutils-0.0.4/src/uu/head/src/head.rs:207:37

**Comment by Mikadore** [comment]
This is the line causing the issue:
```rust
            for line in reader.lines().take(count) {
```
`lines()` expects the input to be utf8 encoded. Imho the `head` method could be refactored  to
- work with binary input
- some perf improvements
WIll be working on a PR

**Comment by Arcterus** [comment]
@Mikadore this is resolved now, yeah?
