### ISSUE TITLE
head crashes for non existing files

### ISSUE THREAD

**Issue by sedrubal** [uutils/coreutils#1800]
Running

```bash
$ uu-head /does/not/exist
```

crashes and prints:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /build/uutils-coreutils/src/coreutils-0.0.4/src/uu/head/src/head.rs:148:44

A better readable error message would be better imho.

**Comment by Mikadore** [comment]
This is due to several uses of `unwrap`, the code states:
```
// TODO: handle errors on read
```
I'll make a new issue on just rewriting `head`
