### ISSUE TITLE
Rewriting `head`

### ISSUE THREAD

**Issue by Mikadore** [uutils/coreutils#1801]
I'm interested in rewriting head. The code is only ~200 lines, and I think it can be significantly improved upon.

Here are some relevant issues:
#1800
#1799
#1358

As well as more generally:
#1358

Objectives:
Resolve aforementioned issues, mainly error handling & handling unencoded binary data, and increase performance (e.g. the NLines implementation needlessly uses a vector)

**Comment by sylvestre** [comment]
With pleasure!
As ride along, don't hesitate to port it to clap

**Comment by Mikadore** [comment]
Will do :)

**Comment by SuperSandro2000** [comment]
Could you maybe also implement #1822 ? 😄

**Comment by Mikadore** [comment]
Sure!
