### ISSUE TITLE
autoconf thinks mkdir -p is not threadsafe

### ISSUE THREAD

**Issue by SuperSandro2000** [uutils/coreutils#1816]
I am currently trying uutils-coreutils as a replacement for gnu's coreutils and discovered the following difference:

autoconf thinks mkdir -p is not threadsafe:

```
checking for a thread-safe mkdir -p... ./install-sh -c -
```

This results in falling back to ``./install-sh -c -d``.

**Comment by sylvestre** [comment]
What is the test by autoconf?

**Comment by SuperSandro2000** [comment]
It checks the mkdir --version for known good implementations and if the a directory named ``--version`` exists. I think this is not an implementation problem of uutils.

https://git.savannah.gnu.org/cgit/autoconf.git/tree/lib/autoconf/programs.m4#n666

**Comment by sylvestre** [comment]
So, it is an feature request on the autoconf side.
could you please report it upstream?
thanks

**Comment by SuperSandro2000** [comment]
> could you please report it upstream?

They only have a mailing list and there are still other things not fully working to replace coreutils. So I pass for now.
