### ISSUE TITLE
tr does not handle escape sequences correct

### ISSUE THREAD

**Issue by SuperSandro2000** [uutils/coreutils#1817]
autoconf relies on the following snippet to generate a CRLF character:

```shell
echo X | tr X '\015'
```

which is broken in uutils-coreutils and returns a ``0``:

uutils-tr
```shell
$ echo X | tr X '\015' | /bin/xxd
00000000: 300a                                     0.
```

gnus tr:
```shell
echo X | tr X '\015' | /bin/xxd
00000000: 0d0a                                     ..
```

**Comment by cole-h** [comment]
This seems to stem from here:

https://github.com/uutils/coreutils/blob/2c09556964de74f685de382d92d41e1e4072c1bb/src/uu/tr/src/expand.rs#L52-L56

which only handles characters (e.g. it's only parsing the `0`, where it should be parsing the whole thing as an octal). This could be solved by making `unescape` take `&str` and then checking if the `&str` starts with `\` (and continue with that).

There would probably need to be "specialized" parsing for `\u` and `\x`, as well as octal (with support for those with and without leading octal numbers).
