### ISSUE TITLE
install: does not remove path from files

### ISSUE THREAD

**Issue by SuperSandro2000** [uutils/coreutils#1823]
While compiling python3 in nixpkgs I noticed that install does not properly work:

Python uses the similar commands to the following command autogenerated by autoconf to install files:
```
/store/7rj52iy8gvdwkrca5k35a7i4hhdgf90c-uutils-coreutils-0.0.4/bin/install -c -m 644 ./Lib/unittest/runner.py /nix/store/bg19k3h973swd0745mhhp5snzijz7hx3-python3-3.8.8/lib/python3.8/unittest
```

but install converts that to a wrong path and then prints that the directory does not exist:

```
install: error: cannot install './Lib/unittest/runner.py' to '/nix/store/bg19k3h973swd0745mhhp5snzijz7hx3-python3-3.8.8/lib/python3.8/unittest/./Lib/unittest/runner.py': the source path is not an existing regular file
```

A minimal reproduce is:

```
mkdir -p Lib/unittest lib/unittest
touch Lib/unittest/runner.py
install ./Lib/unittest/runner.py lib/unittest
install: error: cannot install './Lib/unittest/runner.py' to 'lib/unittest/./Lib/unittest/runner.py': No such file or directory (os error 2)
```

**Comment by nomius10** [comment]
High-five @DoBi, we were in sync 😄

**Comment by DoBi** [comment]
> High-five @DoBi, we were in sync smile

Yeah, I just noticed that.

I took a look at `cp`, because with it the copying works. I tried to use the some of the logic from there.
And I also added a test. But your solution looks more _clean_. Just a few lines instead of my bigger changes. :smile:

**Comment by nomius10** [comment]
@DoBi mind if I merge your test into my PR? I have to add one

**Comment by DoBi** [comment]
> @DoBi mind if I merge your test into my PR? I have to add one

Feel free to use it ;)
