### ISSUE TITLE
Failing test input to trigger panic in Args::collect_str

### ISSUE THREAD

**Issue by alastairreid** [uutils/coreutils#1845]
I was testing a bug-finding tool on coreutils and found an input that can trigger a panic in Args::collect_str

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "\xED\xFF"', /home/rust-verification-tools/coreutils/src/uucore/src/lib/lib.rs:73:38

The line before has the following comment so this is not the most interesting bug report in the world

> 72         // FIXME: avoid unwrap()

But, in case it is useful, here how to trigger the failure

> cd coreutils/src/uu/basename
> cargo run `printf '\xed\xff'`

I think this is an illegal UTF encoding?

ps In case you are interested, I am running the [KLEE symbolic execution tool](http://klee.github.io/) on basename. KLEE has been used to [look for bugs in the original GNU coreutils](https://www.doc.ic.ac.uk/~cristic/papers/klee-osdi-08.pdf) so I thought that it would be interesting to run it on your rewrite.

**Comment by sylvestre** [comment]
Excellent, please continue sending such bugs :)

**Comment by ChrisRega** [comment]
Would changing the unwrap call to unwarp_or_default solve this?

**Comment by sylvestre** [comment]
Or reject the parameter is invalid UTF :)

**Comment by alastairreid** [comment]
For what it's worth, clap seems to do one of two things:

- `return Err(Error::invalid_utf8(...))`
- `arg.to_str().expect(INVALID_UTF8)`

e.g., search for "utf8" within [src/parse/parser.rs](https://github.com/clap-rs/clap/blob/master/src/parse/parser.rs)

(I noticed this because the second option still 'panics' (eg when I tried 'mkdir') - and my tool is looking for ways to trigger a panic.)

**Comment by tertsdiepraam** [comment]
Since https://github.com/uutils/coreutils/pull/1852 is merged, I think this can be closed.
