### ISSUE TITLE
pathchk: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1854]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/pathchk/src/pathchk.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_pathchk.rs 

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by sivachandran** [comment]
Let me give it a shot.

**Comment by sivachandran** [comment]
@sylvestre How do I run the test? `cargo test` doesn't seem to run the above mentioned test.

**Comment by sylvestre** [comment]
@sivachandran probably ` cargo test --features feat_os_unix    `

**Comment by sivachandran** [comment]
Able to run the test with command `cargo test --features feat_os_unix test_pathchk`. Thanks!

**Comment by JnRouvignac** [comment]
Another one that can be closed @sylvestre. Thank you!
