### ISSUE TITLE
nohup: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1856]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/nohup/src/nohup.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_nohup.rs 

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by nomius10** [comment]
I'll take a stab at this
