### ISSUE TITLE
Tail doesn't acept negative values for `-n` or `-c`

### ISSUE THREAD

**Issue by jaggededgedjustice** [uutils/coreutils#1860]
The GNU tail utility allows negative values for the `-n` and `-c` options, these are treated as if they were positive numbers. For example:

```
$ echo 0123456789 >/tmp/test_tail
$ tail -c 5 /tmp/test_tail 
6789
$ tail -c -5 /tmp/test_tail
6789
```

**Comment by hubcio** [comment]
I will try to take care of that.
