### ISSUE TITLE
nl: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1864]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/nl/src/nl.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_nl.rs 

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by mathewduong** [comment]
Hi, I am new to rust and this project but I'd like to take a shot at this issue.

**Comment by sylvestre** [comment]
sure, please go ahead!

**Comment by LevitatingBusinessMan** [comment]
I am giving this issue a try

**Comment by LevitatingBusinessMan** [comment]
@sylvestre This can be closed now.

**Comment by sylvestre** [comment]
oui, merci :)
