### ISSUE TITLE
echo: Argument is treated as multiple arguments

### ISSUE THREAD

**Issue by DoBi** [uutils/coreutils#1873]
I just found out, that there is a different behaviour between the C-coreutils echo and the Rust version.

This command leads to an error, while working with the _C version_:

```
echo '"\n'CXXFLAGS=-g -O2'\n"'
```

It leads to this output:
```
echo '"\n'CXXFLAGS=-g -O2'\n"'
echo: error: Unrecognized option: 'O'
```

The expected output is:
```
echo '"\n'CXXFLAGS=-g -O2'\n"'
"\nCXXFLAGS=-g -O2\n"
```

It seems like the argument is somehow parsed wrong.

**Comment by alstolten** [comment]
I will give it a try.

**Comment by alstolten** [comment]
In https://github.com/uutils/coreutils/pull/1885 I created a failing test case for this. Unfortunately https://docs.rs/clap/2.33.3/clap/struct.Arg.html#method.allow_hyphen_values does not help.
