### ISSUE TITLE
implement pr - convert text files for printing

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1874]
The goal is to implement "pr" 
The work started here:
https://github.com/uutils/coreutils/pull/1327

I will require some rebasing but it should not be too hard.

**Comment by MaxSem** [comment]
I'm going to give it a try.

**Comment by JnRouvignac** [comment]
`pr` has been semi-implemented by #2300.
The name of this issue is now a bit misleading. Don't know if you want to close it or keep it.

**Comment by tertsdiepraam** [comment]
Agreed, issues about `pr` should now be about specific feature requests or bugs.
