### ISSUE TITLE
ls: implement indicator style

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#1881]
The following indicator style options should be available:
- `--indicator-style=none` (default)
- `-F`, `--indicator-style=classify`: append indicator (one of `*/=>@|`) to entries
- `--file-type`, `--indicator-style=file-type`: the same, but does not append `*`
- `-p`, `--indicator-style=slash`: only appends `/` to directories.

Currently, we only support the default and the `-F` flag, so support for the `--indicator-style`, `--file-type` and `-p` options should be added.

For the implementation of the options in `clap`, the implementation of the `--sort` and `--time` options can be used as examples.

**Comment by ricardoaiglesias** [comment]
I am currently working on implementing this.

**Comment by ricardoaiglesias** [comment]
Merged here: https://github.com/uutils/coreutils/commit/5f17719a59344066ae0b4adff51a7096d97a9b43

 Issue should be closed.

**Comment by sylvestre** [comment]
thanks!
