### ISSUE TITLE
mv -i hangs when trying to overwrite existing file, no prompt shown

### ISSUE THREAD

**Issue by kevinburkemeter** [uutils/coreutils#1889]
If `one.txt` and `two.txt` are files, and I do `mv one.txt two.txt` to overwrite two.txt with the contents of one.txt, the `mv` command hangs forever and does not overwrite the file or remove `one.txt`.

**Comment by ycd** [comment]
I'm not able to reproduce this on master branch. we also have a test for this case: https://github.com/uutils/coreutils/blob/b54f0b1ff20919b42de48f74c0265a889696d726/tests/by-util/test_mv.rs#L201-L214

**Comment by kevinburkemeter** [comment]
I just rebuilt on master and I'm able to reproduce. I am using Mac 10.15.7 if that makes a difference. I'm sure that I am using `mv` from this coreutils project.

**Comment by kevinburkemeter** [comment]
Aha - you need the `-i` flag, there's never any prompt shown.

**Comment by kevinburkemeter** [comment]
If I change `print!()` to `println!()` on line 383 of mv.rs, the prompt appears correctly
