### ISSUE TITLE
Rewrite `Why` section of README

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#1902]
Every time our project gets posted to Reddit or Hacker News or whatever, people complain about the README (and the license, but pretty sure that ship has long since sailed).  Specifically they complain about this bit:
> However, those projects are either old and abandoned, are hosted on CVS (which makes it more difficult for new contributors to contribute to them), are written in platform-specific C, or suffer from other issues.

I don’t really think it’s wrong per se, but we should think about rewording it.  In particular, I’ve seen quite a few complaints about the “old and abandoned” part and “platform-specific C” (since people love to complain about Rust not supporting esoteric architectures and thus interpret “platform” as “architecture”).

**Comment by sylvestre** [comment]
Yeah, good point. I think we could just write "Using a safe and modern language". This is good enough.

@Arcterus are you going to submit a PR or should I?

**Comment by Arcterus** [comment]
I don’t think I’ll be able to until late this evening (it’s currently noon here).  If you have time before that, you should probably do it.

**Comment by sylvestre** [comment]
done:
https://github.com/uutils/coreutils/pull/1903
