### ISSUE TITLE
stdbuf: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1930]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/stdbuf/src/stdbuf.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_stdbuf.rs 

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by joppich** [comment]
I am working on this.
