### ISSUE TITLE
csplit: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1931]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/csplit/src/csplit.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_csplit.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by sivachandran** [comment]
I'm going to work on this

**Comment by sivachandran** [comment]
This is done and merged in commit 9151410d08bdf332a7edca93518810278aad5568
