### ISSUE TITLE
shuf: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1933]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/shuf/src/shuf.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_shuf.rs 

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by siyopao** [comment]
I would like to try this if that is okay?
