### ISSUE TITLE
timeout: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1934]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/timeout/src/timeout.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_timeout.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by ricardoaiglesias** [comment]
I can handle this.

**Comment by ricardoaiglesias** [comment]
This can be closed, I think.

**Comment by sylvestre** [comment]
yeah, merci!
