### ISSUE TITLE
more: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1936]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/more/src/more.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_more.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by k0ur0x** [comment]
I'm working on this.
