### ISSUE TITLE
shred: move from getopts to clap

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#1938]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/shred/src/shred.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_shred.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by ajanicij** [comment]
I am working on this.

**Comment by sylvestre** [comment]
It seems that @ajanicij isn't working on it anymore. So, it is free :)
