### ISSUE TITLE
du does not check device number (and Stat struct doesn't have it!)

### ISSUE THREAD

**Issue by Artoria2e5** [uutils/coreutils#1969]
When looking at #1788, I realized that the current implementation of `du` does not check for `metadata.dev()` before considering files a duplicate. This may generate some very wrong results when the inode number on one drive happens to match the inode number on another -- the number is only unique on a filesystem level, so it is important to remember which device you are operating on.

I recommend also checking for other uses of `ino` in the repo when making a fix.

**Comment by Arcterus** [comment]
I'm considering resurrecting my multi-threaded `du` implementation, so if someone else doesn't beat me to the punch, I'll try to handle this issue while working on that.

**Comment by paulotten** [comment]
On unix(likes) device id is available by calling [.dev()](https://doc.rust-lang.org/std/os/unix/fs/trait.MetadataExt.html#tymethod.dev) on [metadata](https://github.com/uutils/coreutils/blob/090d29496a016c81d437ecb61fa8e401c51d7856/src/uu/du/src/du.rs#L74).

On windows device id is available as the [VolumeSerialNumber](https://docs.rs/winapi/0.2.8/x86_64-pc-windows-gnu/winapi/fileapi/struct.FILE_ID_INFO.html) on [file_info](https://github.com/uutils/coreutils/blob/090d29496a016c81d437ecb61fa8e401c51d7856/src/uu/du/src/du.rs#L157).

I'd turn [inode](https://github.com/uutils/coreutils/blob/090d29496a016c81d437ecb61fa8e401c51d7856/src/uu/du/src/du.rs#L66) into a struct that contains the current inode/file id value and the new device id value.

---

I was thinking of taking this issue but I'm fine leaving it for @Arcterus if he wants it. Either way the above should be the meat of the issue.

**Comment by Arcterus** [comment]
You can take it if you'd like.  I'll just fold your changes into my branch later.

**Comment by paulotten** [comment]
I'll take it.
