### ISSUE TITLE
Implement chmod

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#198]

**Comment by retep998** [comment]
The `chmod` utility implemented as is uses the `chmod` function, which is an entirely useless function on Windows as it doesn't do any sort of permissions at all. Instead it just checks for the `_S_IWRITE` flag and then sets the `FILE_ATTRIBUTE_READONLY` flag on the file accordingly. That's it.

**Comment by knight42** [comment]
Already implemented.
