### ISSUE TITLE
Possible GNU bug in sort -hu?

### ISSUE THREAD

**Issue by electricboogie** [uutils/coreutils#1985]
I've been adding tests to sort and one keeps hitting and error that I cannot explain.  In the relevant part, for sort -hu here is the output I get:

For GNU:

```
7800900K
100M
2G
.2T
```

For uutils:

```
100M
2G
7800900K
.2T
```

As far as I know, 7800900K is ~7.8G and is larger than 2G and should be sorted below 2G and 100M.  Does anyone know better?  Thanks.

**Comment by jaggededgedjustice** [comment]
I agree that GNU sort is not sorting the numbers correctly. [Having a look at the code](https://github.com/coreutils/coreutils/blob/e3766c5db176ca7abbb8212d5b0b7862fb98a5be/src/sort.c#L1974) I think it sorts according to the multiplier (K/M/G/...) and only compares numbers for equal multipliers. Looking at the `strnumcmp` function there isn't anything that handles converting numbers to the same scale and comparing that.

My own testing agrees with that, as a number with the 'K' suffix will always be treated as lower than one with the 'M' suffix regardless of the numerical value they represent.

**Comment by miDeb** [comment]
This is documented here: https://www.gnu.org/software/coreutils/manual/html_node/sort-invocation.html
> Sort numerically, first by numeric sign (negative, zero, or positive); then by SI suffix (either empty, or ‘k’ or ‘K’, or one of ‘MGTPEZY’, in that order; see Block size); and finally by numeric value. This option sorts values that are consistently scaled to the nearest suffix, regardless of whether suffixes denote powers of 1000 or 1024,

This avoids having to decide whether to interpret K as 1000  or 1024 (i.e. as a [binary prefix](https://en.wikipedia.org/wiki/Binary_prefix)). We are interpreting it as 1000, which I think is the right thing. Still, it might be unexpected in some cases.
