### ISSUE TITLE
Time to bump the minimum Rust version?

### ISSUE THREAD

**Issue by MaxSem** [uutils/coreutils#1987]
Latest version of IntelliJ IDEA's Rust plugin shows a warning:

> Rust 1.40.0 is no longer supported. It may lead to unexpected errors. Consider upgrading your toolchain to at least 1.41.0

Perhaps, it's time to bump the requirements a bit?

**Comment by sylvestre** [comment]
fyi, I bumped it from 1.33 => 1.40 less than a week ago:
https://github.com/uutils/coreutils/pull/1909
