### ISSUE TITLE
[bug] ln -s option not supported

### ISSUE THREAD

**Issue by dr460nf1r3** [uutils/coreutils#2022]

**Comment by sylvestre** [comment]
you will have to be more specific ?!

On my system:
```
 ./target/debug/coreutils touch a && ./target/debug/coreutils ln -s a b && ./target/debug/coreutils ls -al a b
-rw-r--r-- 1 sylvestre sylvestre 0 2021-04-03 18:17 a
lrwxrwxrwx 1 sylvestre sylvestre 1 2021-04-03 18:17 b -> a
```

**Comment by dr460nf1r3** [comment]
Sorry. Created in iso using garuda-tools which uses Calamares with uutils instead of coreutils. Installation fails because the ln command cant be executed properly. [Here](https://github.com/calamares/calamares/blob/db51e813fbf0f0d286aaa429df157deb7834462e/src/modules/machineid/Workers.cpp#L176) is the line of the source code containing the command.

**Comment by sylvestre** [comment]
Please provide actual details to reproduce this locally.

Thanks

**Comment by dr460nf1r3** [comment]
Well, the only way to reproduce this would probably be attempting the install with Calamares in a vm? I can provide you an iso for this purpose.. if there is another way to get you logs or something let me know.

**Comment by sylvestre** [comment]
You will need to be more clear if you want a concrete action.
You don't even provide an error message...

**Comment by dr460nf1r3** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/12834713/113491146-d4d78500-94ce-11eb-9f93-71acbea8a8d3.png)

I did another Installation in Calamares debug mode, that is pretty much the only thing it gives as output. The Calamares module in question is linked above. 
The iso used to install is [this one](https://builds.garudalinux.org/iso/community/dr460nized-dev/210403/garuda-dr460nized-dev-linux-zen-210403.iso), in case you want to replicate what I did.
Its clearly the uutils implementation being the issue as I tested another install, same iso with gnu coreutils installed which worked flawlessly. Im sorry for being this vague. :/

**Comment by sylvestre** [comment]
Sorry but we will need more information do to anything and I don't even know what is Calamares :/

**Comment by Arcterus** [comment]
Isn't it some distro installer?

**Comment by dr460nf1r3** [comment]
Calamares is in fact a distro installer. I linked the [GitHub](https://github.com/calamares/calamares) above already, didnt you take a look at this?

**Comment by Arcterus** [comment]
Are you sure the issue is actually `ln`?  Unless I'm misinterpreting things, the error you posted seems to indicate that `systemd-machine-id-setup` is getting called with itself as an argument, which causes it to error.  If you're sure it's `ln`, then what is the type of file being linked that causes the error?  At the moment, the line you linked just says Calamares uses `ln -sf`, which doesn't provide much info (unless the problem is it's failing to clobber another file?).
