### ISSUE TITLE
Replace os::args() by os::args_as_bytes()

### ISSUE THREAD

**Issue by mahkoh** [uutils/coreutils#203]
Under linux you can have non-utf8 filenames, e.g.,

``` c
#include <fcntl.h>
#include <unistd.h>

int main(void)
{
    int fd = creat("test\xf0\x90\x80test", 0644);
    write(fd, "hello\n", 6);
    close(fd);
}
```

When you try to cat this file with gnu cat you get

```
$ cat test$'\360'$'\220'$'\200'test                     
hello
```

When you try to cat this file with uutils cat you get

```
$ ~/rust/coreutils/cat/cat test$'\360'$'\220'$'\200'test
cat: test�test: no such file or directory (No such file or directory)
```

That's because args() has replaced the invalid sequence by �.

**Comment by tertsdiepraam** [comment]
This can be closed as we've moved to using `clap` for argument handling.
