### ISSUE TITLE
This repo got hit by the crypto mining on action

### ISSUE THREAD

**Issue by reggaemuffin** [uutils/coreutils#2031]
Right now all our CI is queued behind a pr from a (by now banned) user that mines crypto on github actions:

https://github.com/uutils/coreutils/actions/runs/719170957

Someone with permissions to do so should stop the runs

some context:

https://www.bleepingcomputer.com/news/security/github-actions-being-actively-abused-to-mine-cryptocurrency-on-github-servers/

So far I am not aware of how to prevent this other than detecting it manually

**Comment by sylvestre** [comment]
Thanks
" You have successfully requested the workflow to be canceled. "

**Comment by sylvestre** [comment]
the account seems to be disabled
https://github.com/brianbarnatt7/

**Comment by sylvestre** [comment]
I am curious, where did you see the queue?

**Comment by reggaemuffin** [comment]
You can always view the queue under https://github.com/uutils/coreutils/actions
