### ISSUE TITLE
du - time 0.1 is outdated

### ISSUE THREAD

**Issue by paulotten** [uutils/coreutils#2043]
as per https://deps.rs/repo/github/uutils/coreutils

**Comment by paulotten** [comment]
I'll take this issue.

time 0.2 is a complete rewrite with an almost entirely different api, so I'm looking at just switching to the latest version of chrono.

**Comment by sylvestre** [comment]
Yeah, we are using time 0.1 in other places too (like ls, stat or install)
Would you be interested in doing the same?
thanks
