### ISSUE TITLE
mknod: move from getopts to clap

### ISSUE THREAD

**Issue by ycd** [uutils/coreutils#2051]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/mknod/src/mknod.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_mknod.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by rethab** [comment]
Can I take this one @ycd ?

**Comment by ycd** [comment]
sure, please go ahead :)

**Comment by rethab** [comment]
@ycd here's the PR: https://github.com/uutils/coreutils/pull/2056
