### ISSUE TITLE
unlink: move from getopts to clap

### ISSUE THREAD

**Issue by ycd** [uutils/coreutils#2052]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/unlink/src/unlink.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_unlink.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by nthery** [comment]
I'd like to give it a go.

**Comment by ycd** [comment]
sure, please go ahead :)

**Comment by ycd** [comment]
Awesome, thanks @nthery, we can close this @sylvestre :)
