### ISSUE TITLE
chown <user>: file is not working

### ISSUE THREAD

**Issue by DoBi** [uutils/coreutils#2060]
I recently noticed that the command `chown` is not working correctly.
When executing `chown <user>: file.txt` the command succeeds without any error, but not the user nor the group is changed.

I think this behaviour should be covered by the test `test_chown_myself_second`, but there only the succeed is checked, not the change of the user.

I sadly don't know how this could be checked in the tests nor how the group is determined just from the username :cry:. Maybe somebody else could solve this.

**Comment by jhscheer** [comment]
I'm working on this.

**Comment by jhscheer** [comment]
> When executing `chown <user>: file.txt` the command succeeds without any error, but not the user nor the group is changed.

Afaik only the user should be changed in this case.

> I think this behaviour should be covered by the test `test_chown_myself_second`, but there only the succeed is checked, not the change of the user.

The test would be to check if the owner really changed. However this is tricky since afaik only superuser can change ownership to another user. This cannot be done in the test environment.

> I sadly don't know how this could be checked in the tests nor how the group is determined just from the username 😢. Maybe somebody else could solve this.

I did a workaround to test for this issue. See the commit.

**Comment by jhscheer** [comment]
>> When executing chown <user>: file.txt the command succeeds without any error, but not the user nor the group is changed.

> Afaik only the user should be changed in this case.

I just read in the manpage that the group is indeed also changed: 
`If a colon but no group name follows the user name, that user is made the owner of the files and the group of the  files  is  changed  to  that user's login group.`
From what I read in the code so far, `uu_chown` is not doing that right now.

Also I noticed that the behavior for a single colon is wrong:
`If only a colon is given, or if the entire operand is empty, neither the owner nor the group is changed.`
```bash
$ chown -v : file.txt 2>out_err ; echo $? ; cat out_err
ownership of 'file.txt' retained
0
$ target/debug/chown --verbose : file.txt 2>out_err ; echo $? ; cat out_err
1
chown: invalid user: ':'
```
wrong message, wrong stdout/stderr, wrong return code :(
