### ISSUE TITLE
bug: sort -u and sort -n

### ISSUE THREAD

**Issue by cbjadwani** [uutils/coreutils#2062]
The current implementation of `sort -u` seems to have a bug due to an incorrect reading of GNU sort documentation.

https://github.com/uutils/coreutils/blob/9ae4928b7b4f43495921fe8ac6128ea226d20dbd/src/uu/sort/src/sort.rs#L717-L719

Numbers should not be used for comparison/deduping if `-n` is not specified.

This shows the issue in current implementation:

```
$ cat sort-u-test.txt
zzz
aaa
bbb
bbb

$ sort -u sort-u-test.txt
aaa
bbb
zzz

$ ./target/debug/sort -u sort-u-test.txt
aaa
```

There are other issues with detecting/extracting the leading numeric part of a line when `-n` is used. Following shows one case:

```
$ printf 'aa\n-10 bb\n-10 aa\n' | sort -n -u
-10 bb
aa

$ printf 'aa\n-10 bb\n-10 aa\n' | ./target/debug/sort -n -u
-10 bb
-10 aa
aa
```

**Comment by miDeb** [comment]
Working on a fix

**Comment by electricboogie** [comment]
Yes, I noticed this yesterday.  It should already be fixed for this example case.  Let me do some tests.

**Comment by electricboogie** [comment]
This one is on me.  Kudos to @miDeb on the quick fix.

**Comment by electricboogie** [comment]
And @cbjadwani, appreciate your pointing this out.
