### ISSUE TITLE
DU tests consistently fail locally on Manjaro machine

### ISSUE THREAD

**Issue by Gilnaa** [uutils/coreutils#2066]
Most du tests fail locally on my Linux machine due to incorrect directory sizes.
```
---- test_du::test_du_basics_subdir stdout ----
current_directory_resolved:
run: /home/gilad/repos/coreutils/target/debug/coreutils du subdir/deeper
thread 'test_du::test_du_basics_subdir' panicked at 'assertion failed: `(left == right)`
  left: `"4\tsubdir/deeper\n"`,
 right: `"8\tsubdir/deeper\n"`', /home/gilad/repos/coreutils/tests/by-util/test_du.rs:55:9

---- test_du::test_du_d_flag stdout ----
current_directory_resolved:
run: /home/gilad/repos/coreutils/target/debug/coreutils du -d 1
thread 'test_du::test_du_d_flag' panicked at 'assertion failed: `(left == right)`
  left: `"16\t./subdir\n20\t./\n"`,
 right: `"28\t./subdir\n36\t./\n"`', /home/gilad/repos/coreutils/tests/by-util/test_du.rs:159:9

---- test_du::test_du_hard_link stdout ----
current_directory_resolved:
run: /home/gilad/repos/coreutils/target/debug/coreutils ln subdir/links/subwords.txt subdir/links/sublink.txt
run: /home/gilad/repos/coreutils/target/debug/coreutils du subdir/links
thread 'test_du::test_du_hard_link' panicked at 'assertion failed: `(left == right)`
  left: `"12\tsubdir/links\n"`,
 right: `"16\tsubdir/links\n"`', /home/gilad/repos/coreutils/tests/by-util/test_du.rs:131:9

---- test_du::test_du_soft_link stdout ----
current_directory_resolved:
run: /home/gilad/repos/coreutils/target/debug/coreutils ln -s subdir/links/subwords.txt subdir/links/sublink.txt
run: /home/gilad/repos/coreutils/target/debug/coreutils du subdir/links
thread 'test_du::test_du_soft_link' panicked at 'assertion failed: `(left == right)`
  left: `"12\tsubdir/links\n"`,
 right: `"16\tsubdir/links\n"`', /home/gilad/repos/coreutils/tests/by-util/test_du.rs:99:9
```

Note that GNU `du` report the same sizes as uutils, so it seems like the values hardcoded in the test suite are not true for all linux installs.
Not sure what affects these sizes. I'm using Manjaro Linux with kernel 5.10 and ext4.

Not sure how to fix the test. Ideally we could just equate to actual GNU du output, but I'm not sure we can assume it exists on the machine running the tests.

Maybe not worth fixing.

**Comment by Gilnaa** [comment]
IIRC the directory size is 4KiB for most if not all Linux installations I've ever touched.
I wonder what machines in GitHub Actions have different values for Linux.

**Comment by jhscheer** [comment]
These tests also fail on my linux box (5.11.11-200.fc33.x86_64).
> Not sure how to fix the test. Ideally we could just equate to actual GNU du output, but I'm not sure we can assume it exists on the machine running the tests.

I also think dynamically taking reference values from the local `du`, provided that `du` is available, is a better option than hard coded reference values only. (If `du` is not available, falling back to the hard coded values would be my choice.)
