### ISSUE TITLE
tests/cat: `test_no_options_big_input` takes more than 6 hours on Windows

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#2079]
Recent tests on the CI for Windows have been cancelled because they take over 6 hours. I did some digging in the [logs](https://pipelines.actions.githubusercontent.com/Tv5Yv5nIzIhWaMo3xdKzjIorSSIlfCwnxr6L52Y7lKBOTZPJ76/_apis/pipelines/1/runs/3127/signedlogcontent/26?urlExpires=2021-04-16T15%3A10%3A13.6218426Z&urlSigningMethod=HMACV1&urlSignature=qYByjxLLfqgnwokX1NmsSwq14ECBEPHF8fb3uf6YTmg%3D) and found that the culprit is `test_cat::test_no_options_big_input`, which generates a line like this:
```
test test_cat::test_no_options_big_input has been running for over 60 seconds
```
and no line with `ok`. This also happened when running locally with Wine.

This test was added 6 days ago, which was also when these problems started.

**Comment by sylvestre** [comment]
oh, excellent. I was looking into this right now :)
Let's ignore that then! 

Probably caused by https://github.com/uutils/coreutils/pull/2020
@ArniDagur wdyt you?

**Comment by ArniDagur** [comment]
I encounter this on MacOS and Linux if I increase the size of the largest input:
```diff
diff --git a/tests/by-util/test_cat.rs b/tests/by-util/test_cat.rs
index f9c959a2..179bb9c8 100644
--- a/tests/by-util/test_cat.rs
+++ b/tests/by-util/test_cat.rs
@@ -44,6 +44,7 @@ fn test_no_options_big_input() {
         96 * 1024,
         112 * 1024,
         128 * 1024,
+        256 * 1024,
     ] {
         let data = vec_of_size(n);
         let data2 = data.clone();
```
My guess is that there's something wrong with the way we pipe large input into the child processes in the test framework.

**Comment by tertsdiepraam** [comment]
@ArniDagur I can confirm that it also hangs on my machine for `256 * 1024`.
I also ran an example from the `std::process::Command` docs and the GNU `cat` for that size and it also hangs:
```rust
let data = vec_of_size(256 * 1024);
let mut prog = std::process::Command::new("/usr/bin/cat")
    .stdin(std::process::Stdio::piped())
    .stdout(std::process::Stdio::piped())
    .spawn()
    .unwrap();

{
   prog.stdin
       .as_mut()
       .expect("failed to get stdin")
       .write_all(&data)
       .expect("failed to write to stdin");
}

let output = prog.wait_with_output().expect("failed to wait on child");
assert_eq!(output.stdout.as_slice(), data);
```
I'm thinking this is some platform limitation, possibly related to `/proc/sys/fs/pipe-max-size`? I'm not really an expert on these kinds of things, so I might be wrong. This `bash` line seems to work though and that should do the same thing (I think):
```bash
printf 'a%.0s' {1..262144} | cat
```
So maybe it is a Rust limitation/bug?

The example from the docs is here: https://doc.rust-lang.org/std/process/index.html#handling-io

Found a similar issue here (without an answer): https://users.rust-lang.org/t/writing-large-inputs-to-stdin-of-a-child-process-fails/50270

**Comment by ArniDagur** [comment]
I think it could be because unlike your bash example, there is no reader on the other side to empty the pipe we're writing to in the tests. After the pipe fills up, the writes block forever and our program hangs.
