### ISSUE TITLE
`ls`: ignore leading period when sorting by name

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#2101]
The GNU `ls` ignores the leading period when sorting by name. However, hidden files still get sorted before non-hidden files with the same name, so `.a` always appears before `a`.

Here is an example:

```bash
$ touch a b .a .b
$ ls -A            # GNU
.a  a  .b  b
$ uu-ls -A         # current uutils
.a  .b  a  b
```

Code is here:\
https://github.com/uutils/coreutils/blob/master/src/uu/ls/src/ls.rs

Tests are here:\
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_ls.rs

**Comment by ricardoaiglesias** [comment]
Just verifying, all this would take is changing the `sort_entries` function's `Sort::Size` branch to split into two "buckets" (with dot and without dot), sort each bucket, and then join them, right? 
If so, I can tackle this.

**Comment by tertsdiepraam** [comment]
@ricardoaiglesias If I understand you correctly I think that would lead to our current sorting right? In the example above, this would lead to a bucket with `.a .b` and a bucket with `a b` and joining them then gives `.a .b a b`.

One way this might be implemented is to sort by a tuple of type `(String, bool)` representing `(name_without_leading_period, has_leading_period)`.

**Comment by ricardoaiglesias** [comment]
Oh sorry. I misinterpreted the examples you gave.
Yeah, you're correct. I can get something done.

**Comment by tertsdiepraam** [comment]
Nice! Looking forward to it!

**Comment by ricardoaiglesias** [comment]
PR Here: https://github.com/uutils/coreutils/pull/2112

**Comment by ricardoaiglesias** [comment]
This issue can be closed.
