### ISSUE TITLE
basename: move from getopts to clap 

### ISSUE THREAD

**Issue by ycd** [uutils/coreutils#2117]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/basename/src/basename.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_basename.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by bashi8128** [comment]
Let me give it a shot

**Comment by ycd** [comment]
sure please go ahead
