### ISSUE TITLE
kill: move from getopts to clap

### ISSUE THREAD

**Issue by ycd** [uutils/coreutils#2122]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/kill/src/kill.rs

Tests (definitely need some):
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_kill.rs 

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by nthery** [comment]
I can take this.
