### ISSUE TITLE
who: move from getopts to clap

### ISSUE THREAD

**Issue by ycd** [uutils/coreutils#2124]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/who/src/who.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_who.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by jhscheer** [comment]
I'm working on this.
