### ISSUE TITLE
base32: move from getopts to clap

### ISSUE THREAD

**Issue by ycd** [uutils/coreutils#2128]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/base32/src/base_common.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_base32.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by ricardoaiglesias** [comment]
I can take this.

**Comment by ycd** [comment]
Great work, closing this due #2131
