### ISSUE TITLE
base64: move from getopts to clap

### ISSUE THREAD

**Issue by ycd** [uutils/coreutils#2129]
Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/base64/src/base_common.rs

Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_base64.rs

As example:
https://github.com/uutils/coreutils/commit/9081e120d6b866c94679d9e29c7bdb17ccccb4d0

**Comment by ricardoaiglesias** [comment]
I can take this (It's very similar to `base32`, so it shouldn't be too bad).

**Comment by ycd** [comment]
resolved with #2137
