### ISSUE TITLE
 ls -a --color=tty not formatting properly 

### ISSUE THREAD

**Issue by 0kalekale** [uutils/coreutils#2132]
![image](https://user-images.githubusercontent.com/31927746/116062060-4906e200-a6a3-11eb-9c5e-6c4278981581.png)

first one is gnu coreutils and the second is uutils coreutils.

**Comment by sylvestre** [comment]
which version of coreutils do you use? git repo ?

**Comment by 0kalekale** [comment]
i built from master just a while ago

**Comment by sylvestre** [comment]
@tertsdiepraam landed https://github.com/uutils/coreutils/pull/2099 
maybe it fixed the issue

**Comment by 0kalekale** [comment]
acctually i think that #2099 might have introduced this bug, when i built from master #2099 had already been merged, so i decided to build from v0.0.6, and well it works just fine 
 
![image](https://user-images.githubusercontent.com/31927746/116070743-b53a1380-a6ac-11eb-86e3-43bf9af12cfe.png)

pic; first is coreutils v0.0.6 and second one is coreutils built from master with #2099 merged

**Comment by tertsdiepraam** [comment]
Interesting! I'll look if I can reproduce this and fix it. What OS, shell and terminal are you using? Is it only `--color=tty` or also `--color` and `--color=always`?

**Comment by tertsdiepraam** [comment]
Nevermind, I reproduced it 😄
