### ISSUE TITLE
ls: show device details

### ISSUE THREAD

**Issue by cbjadwani** [uutils/coreutils#2140]
Add support to show device major and minor numbers and type (block/char).

Example:

```
$ ls -l /dev/input/event* | head -5
crw-rw---- 1 root input 13, 64 Apr 26 14:27 /dev/input/event0
crw-rw---- 1 root input 13, 65 Apr 26 14:27 /dev/input/event1
crw-rw---- 1 root input 13, 74 Apr 26 14:27 /dev/input/event10
crw-rw---- 1 root input 13, 75 Apr 26 14:27 /dev/input/event11
crw-rw---- 1 root input 13, 76 Apr 26 14:27 /dev/input/event12
```

The 'c' in `crw-rw----` is for the type of device and `13, 76` are major and minor numbers of the device.

**Comment by tertsdiepraam** [comment]
@sylvestre GitHub closed this automatically, but it hasn't been implemented yet

**Comment by jlc-christie** [comment]
Is the only issue with this the major device number? Type and minor seem to be working fine. I will create a quick PR for that fix now.

**Comment by tertsdiepraam** [comment]
Actually, I'm not sure. I think I might have put the reopen request on the wrong issue😄 Your fix is interesting though, because shifting by 8 works for me, so is it dependent on platform?

**Comment by jlc-christie** [comment]
Ah that is interesting. It must be, tried to find some info but couldn't find anything concrete. I'm on aarch64 macOS, the stat command is also giving me some strange results for device files.

**Comment by tertsdiepraam** [comment]
I _think_ I found it based on:
- https://linux.die.net/man/2/stat
- https://linux.die.net/man/3/major
We need the `major` function in `libc`: https://docs.rs/libc/0.2.94/libc/fn.major.html. This works on my machine:
```
let major = unsafe { uucore::libc::major(dev) } as u8;
let minor = unsafe { uucore::libc::minor(dev) } as u8;
```
Could you try that on mac as well?

**Comment by tertsdiepraam** [comment]
> For some reason I can't use the major and minor funcs from libc?

Interesting, it looks like those functions not defined for Mac. That's too bad.

> I don't see any reason why we couldn't use this logic without calling the unsafe libc func? Unless I'm missing something?

I'm guessing that the logic should be different on different systems so this might not solve it, but it's worth a shot!

I did some more digging and this is what `exa` does (they just ignore the issue):
```rust
// In C-land, getting the major and minor device IDs is done with
// preprocessor macros called `major` and `minor` that depend on
// the size of `dev_t`, but we just take the second-to-last and
// last bytes.
f::Size::DeviceIDs(f::DeviceIDs {
    major: device_ids[6],
    minor: device_ids[7],
})
```

Also here's a StackOverflow answer that we might be able to translate: https://stackoverflow.com/questions/35392291/how-to-convert-between-a-dev-t-and-major-minor-device-numbers. Honestly, I think it's okay to just implement a version that works for Linux and Mac and add fixes for other systems later.

**Comment by SteveLauC** [comment]
> Ah good find. For some reason I can't use the major and minor funcs from libc? Maybe being feature-gated out for some reason? 

These two functions have been added in libc

**Comment by tertsdiepraam** [comment]
@SteveLauC Thanks for contributing that to `libc`!

So to summarize, we now have this for:

- [x] Linux
- [x] Mac
- [x] Android
- [x] iOS
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] NetBSD
- [ ] Redox (Do they have major and minor device numbers?)

And the way we can enable this for more platforms is by contributing to `libc`?

**Comment by SteveLauC** [comment]
That's exactly what I am doing right now, see [rust-lang/libc#2999](https://github.com/rust-lang/libc/pull/2999) 😃

**Comment by SteveLauC** [comment]
It seems that redox does not support this. I searched their libc impl and didn't find those functions

**Comment by tertsdiepraam** [comment]
Awesome!
