### ISSUE TITLE
wc: unexpected leading space when reporting two or more numbers for a given file

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#2173]
What happens now (using uutils `wc`):
```
$ echo "hello" > /tmp/test.txt && ./target/debug/coreutils wc -lc /tmp/test.txt
 1 6 /tmp/test.txt
```
(Notice the extra leading space in the output.)

What I expected (using GNU `wc`):
```
$ echo "hello" > /tmp/test.txt && wc -lc /tmp/test.txt
1 6 /tmp/test.txt
```

**Comment by jhscheer** [comment]
Which `wc` were you testing with?

I tried `wc` from coreutils 8.32 and got this output:
```
$ echo "hello" | wc -lc
      1       6
```

So the fix should be to add more whitespaces, not less?

**Comment by jfinkels** [comment]
For some reason, the output format when reading from `stdin` differs from the output format when reading from a file.
```sh
$ echo "hello" > /tmp/test.txt && wc -lc /tmp/test.txt
1 6 /tmp/test.txt
$ echo "hello" | wc -lc
      1       6
```
I was referring only to the output format when reading from a file.

**Comment by jfinkels** [comment]
By the way, I am testing on Ubuntu 18.04, with `wc` 8.28.
