### ISSUE TITLE
test_ls::test_ls_styles failure

### ISSUE THREAD

**Issue by chadbrewbaker** [uutils/coreutils#2187]
Commit 34b9809223ac5d260fa9931da6206597bf49865a

cargo/rustc 1.53.0-nightly (0ed318d18 2021-04-23)

apple aarch64

failures:

---- test_ls::test_ls_styles stdout ----
current_directory_resolved: 
touch: /var/folders/vy/1f7ldlk14z77k1t9rk0b_wzr0000gn/T/.tmpRtec0E/test
run: /Users/crb002/github/meta_coreutils/coreutils/target/debug/coreutils ls -l --time-style=full-iso
thread 'test_ls::test_ls_styles' panicked at 'assertion failed: re_full.is_match(&result.stdout_str())', /Users/crb002/github/meta_coreutils/coreutils/tests/by-util/test_ls.rs:703:5

**Comment by tertsdiepraam** [comment]
I can't reproduce this, sadly (I'm not on mac, maybe that's the difference). Could you share some sample output of `target/debug/coreutils ls -l --time-style=full-iso`?
