### ISSUE TITLE
wc: fails to append a dash to output line when a dash is given on the command-line

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#2188]
Environment: Ubuntu 18.04, GNU `wc` version 8.28

`wc` is failing to append a dash to the output line when a dash is given on the command-line to represent reading from `stdin`.

What happens now: no difference when calling `wc` with and without a dash
```sh
$ cat tests/fixtures/wc/alice_in_wonderland.txt | ./target/debug/coreutils wc -clmw
   5  57 302 302
$ cat tests/fixtures/wc/alice_in_wonderland.txt | ./target/debug/coreutils wc -clmw -
   5  57 302 302
```

What I expected to happen: GNU prints the dash as the "name" of the file
```
$ cat tests/fixtures/wc/alice_in_wonderland.txt | wc -clmw
      5      57     302     302
$ cat tests/fixtures/wc/alice_in_wonderland.txt | wc -clmw -
      5      57     302     302 -
```

(There are also two issues with the spacing, those issues are represented in issues #2173 and #2186.)

**Comment by nthery** [comment]
I'm working on a fix.
