### ISSUE TITLE
Implement sort

### ISSUE THREAD

**Issue by yincrash** [uutils/coreutils#219]
I'm working on this

**Comment by palaviv** [comment]
I am working on adding more options to sort.

**Comment by alsuren** [comment]
I have a patch to implement --stable in https://github.com/alsuren/coreutils/tree/sort--stable , but this is my first rust project, so there are a few things wrong with it. Should I create a PR out of my WIP branch now, or should I write some tests first (and work out how to avoid calling String::cmp twice as many times as necessary when someone calls `yes | head | sort`) before I submit the PR?

**Comment by nathanross** [comment]
@alsuren I added a line item in your commit there about the issue you were looking to work out. 

You don't need to add tests to submit implementation additions or fixes, just submit it when you're ready.

**Comment by alsuren** [comment]
@nathanross: I added test and submitted PR (https://github.com/uutils/coreutils/pull/932). Thanks for the help.
