### ISSUE TITLE
Build Instructions on Windows

### ISSUE THREAD

**Issue by BrendanBuono** [uutils/coreutils#220]
As Windows does not come with make, and configuring it can be complicated, Window build instructions should be included in the README

**Comment by NickMcAvoy** [comment]
Considering a major goal of the project is easily running on Windows, the dependency on msys or cygwin is a little disappointing. I'd love it if `cargo` was all I needed.

**Comment by nathanross** [comment]
@NickMcAvoy cargo is all that is needed, however you have successfully identified an issue that the README needs to be updated to reflect that MSVC builds can work as well. (If you click the appveyor badge on the repository page, you can see the tests for windows MSVC Rust are passing just as much as those for Windows GNU Rust).

As you likely know, use of MSVC requires installing the [Microsoft Visual C++ Build Tools 2015](http://landinghub.visualstudio.com/visual-cpp-build-tools).

Feel welcome to file the issue or pull request regarding the need to update the README for this.
