### ISSUE TITLE
test_ls::test_ls_styles failing on  aarch64-apple-darwin

### ISSUE THREAD

**Issue by chadbrewbaker** [uutils/coreutils#2215]
commit 620a5a5df6b1ca

It fails a regex after running this command.

```bash
coreutils/target/debug/coreutils ls -l --time-style=full-iso
thread 'test_ls::test_ls_styles' panicked at 'assertion failed: re_full.is_match(&result.stdout_str())', 
```
https://github.com/uutils/coreutils/blob/620a5a5df6b1cad6c8279c1b1aef80e401b14c51/tests/by-util/test_ls.rs#L703

I did notice that GNU ls under Linux is giving a different file ordering of AaBbCcDd .. instead of ABCD... abcd ...

**Comment by tertsdiepraam** [comment]
Would you mind sharing the output of `ls -l --time-style=full-iso` on that system? You're right about the sort order, the change in order was discussed here: https://github.com/uutils/coreutils/issues/2149. I am working on a separate crate that should be able to sort based on locale soon :)

Is this a duplicate issue of https://github.com/uutils/coreutils/issues/2187 or is it something new?

**Comment by chadbrewbaker** [comment]
My eyeball didn't see anything wrong at the regex level. Seemed to be the same print format on linux. I'll instrument the assert to print the string on failure, I expect it is getting garbage due to a race condition.

**Comment by chadbrewbaker** [comment]
Is there other examples of printing an assert on failure? If I am doing it here, I might as well submit a PR for other asserts that are non-informational.

**Comment by chadbrewbaker** [comment]
https://rubular.com FTW! Bug in the regex, sending a PR.
