### ISSUE TITLE
Proposal: Implement `Author` section in `--help` docs

### ISSUE THREAD

**Issue by blesson3** [uutils/coreutils#2230]
## Summary and Motivation

I think it would be interesting to have the `Author` section listed in the `--help` docs for each utility. Each person contributing to the utility would be listed under that utility's `Author` section in `--help`. As far as I can tell, this would follow the GNU standard for coreutils. The extra attribution may provide additional incentive for contribution.

GNU `cp` example:
```
$ cp --help
...
AUTHOR
       Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.
...
```

Would love to hear the community's thoughts. I would be interested in leading development of this feature if the community decides to move ahead with this.

#### Using Git

We could capture the authors of each utility (sorted by number of commits) automatically using the following git oneliner during builds in `build.rs`: `git shortlog -n -s -e -- src/uu/cp | tr -s '[:blank:]' ' ' | cut -d ' ' -f 3-`

example for the `cp` utility in this repo:
```
$ git shortlog -n -s -e -- src/uu/cp | tr -s '[:blank:]' ' ' | cut -d ' ' -f 3-
Sylvestre Ledru <sylvestre@debian.org>
Roy Ivy III <rivy.dev@gmail.com>
Reto Hablützel <rethab@protonmail.ch>
Nicolas Thery <nthery@gmail.com>
Edward Betts <edward@4angle.com>
John Eckersberg <jeckersb@redhat.com>
Mekka <mekka@mekka-tech.com>
Alex Lyon <arcterus@mail.com>
Nicolas Thery <nicolas.thery@mathworks.fr>
Sylvestre Ledru <sledru@mozilla.com>
Neculai Balaban <balabanneculai920@gmail.com>
Benjamin Fox <benjaminfox@hey.com>
Chad Brewbaker <crb002@gmail.com>
Craig Pastro <siyopao@gmail.com>
```

One major downside would be that users may be added to the `Author` section unknowingly and may want their name removed (for whatever reason). One (terrible) solution is to have a name/email blacklist that you must update to be excluded from the `Author` sections. The `Cargo.toml` `authors` key (whitelist) would solve this issue.

#### Using Cargo.toml

We could use `Cargo.toml`'s `authors` key to extract authorship for each utility. This requires you to add your name explicitly to the utility's `Cargo.toml`, but it solves the issue of some people not wanting their name listed.

This seems to be the path of least resistance for implementation, but does not provide retroactive authorship attribution. Past contributors would need to be added to the `Cargo.toml` file (do they even want to be?).

### Handling in Source (after we know authorship)

We could use one of the following mediums to capture authorship in `build.rs`:
1. use environment variables to store authorship (ex. `UUTILS_CP_AUTHORS="..."`) at build time, read in source by using the `env!` macro
1. write to text files that are included at build time by using the `include!` macro in source
1. if using `Cargo.toml:authors` => we could use `clap`'s built in macro [`crate_authors!`](https://docs.rs/clap/2.33.3/clap/macro.crate_authors.html)

Once we have the authors in source, it would be trivial to add to the `--help` output by using `clap`'s [`App.after_help`](https://docs.rs/clap/2.33.3/clap/struct.App.html#method.after_help) fn for each utility.

## Questions:
- do we include each author's name+email or just their name?
- do we sort each author by the number of commits (per util) they've made? or alphabetically?
- if using the `git` method: do we include commits to each utility's `Cargo.toml`? If not, then we can use the `<util>/src/` dir for extracting authorship
- do we include `uucore{,_procs}` commit authors by default to each utility's `Author` section?

## Other Thoughts

This concept could also be extended to add the following `--help` sections standard in each GNU util:
- `REPORTING BUGS`
- `COPYRIGHT`
- `SEE ALSO`

Implementation of these sections is out of scope for this issue, but discussion is welcome.

**Comment by miDeb** [comment]
> if using the git method: do we include commits to each utility's Cargo.toml? If not, then we can use the <util>/src/ dir for extracting authorship

AFAIK the author field in Cargo.toml is being deprecated.

As a contributor I'm fine with adding my name to the help output, but **definitely** not my email. Could you just explain shortly what the benefits of adding names to help output would be? I don't really think it's useful information for our users (possibly the list could be quite large), and for development purposes there's git blame anyways.

Maybe a good indication of whether contributors want their name on their code could be to look at whether they added their name to the copyright section on top of each file?

**Comment by sylvestre** [comment]
Sorry but I am not a fan for the author list :(

For a few reasons:
* doesn't provide any value for the users
* It is a lot of work to maintain
* from when do you become author? rustfmt? 10 lines? 
* the list is already available on github https://github.com/uutils/coreutils/graphs/contributors
or https://www.openhub.net/p/rust-coreutils/contributors?sort=latest_commit

I think the GNU rational is becoming from the time where CVS where not as great as they are now about keeping authorship.

So, except if you have significant argument, it would be a wontfix for me :(
Sorry

**Comment by blesson3** [comment]
Totally makes sense. Those are good points that I had not considered. Do either of you have any thoughts on adding the `REPORTING BUGS` section mentioned above?

Seems like that section provides the most value to users who have a problem, but don't know where to go for help. On the flip-side, your assumed audience (at this stage) are primarily developers who know where to go for issues anyway. In that case, this additional section is unneeded fluff.

@miDeb @sylvestre Feel free to close this issue if this discussion ceases to provide value.

**Comment by miDeb** [comment]
`REPORTING BUGS` sounds like an useful addition, given that https://aur.archlinux.org/packages/coreutils-hybrid/ exists and it could help people understand where the utility is actually coming from (maybe also because not everybody knows what's part of coreutils, and might try to look up the individual subcommands first)

**Comment by sylvestre** [comment]
Cool stuff the arch thing :)

@blesson3 Thanks for this interaction. it is a pleasure :)
