### ISSUE TITLE
touch: different output from gnu

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2256]
FAIL: tests/touch/fail-diag

GNU:
`touch: cannot touch '/no-such-dir/file': No such file or directory`

us:
`touch: warning: cannot touch '/no-such-dir/file': No such file or directory (os error 2)`

**Comment by Gilnaa** [comment]
If we want to get rid of the `(os error 2)` we need to stop using  `impl Display for std::io::Error`.
In an ideal world we could have called `error_string` which is used internally, but it's private to `std`.

If we want to solve the general case, we can probably [copy](https://stackoverflow.com/a/40720007) the function,or just call strerr ourselves from `libc`.

Alternatively we can try to strip that part, but that's fragile.

Willing to do either; what do you think?

**Comment by tertsdiepraam** [comment]
We've solved this kind of issue so far like in this PR: https://github.com/uutils/coreutils/pull/2281

It's not very clever, but it works. If you have any ideas how to improve the error handling in all utils, I'd be interested to see what you come up with!
