### ISSUE TITLE
rmdir: different output from gnu

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2258]
with
https://github.com/coreutils/coreutils/blob/master/tests/rmdir/symlink-errors.sh

GNU:
`rmdir: failed to remove 'fl/': Not a directory`

us:
`rmdir: error: reading directory 'fl/': Not a directory (os error 20)`

**Comment by pyaillet** [comment]
For anyone wanting to work on this issue, it seems the `error:` part has already been fixed on master.
I was searching to fix the latter part `(os error 20)` and traced it back to [here](https://github.com/rust-lang/rust/blob/master/library/std/src/io/error.rs#L583).

I guess we should use `sys::os::error_string` on the error code, but I don't know how to extract it from [here](https://github.com/uutils/coreutils/blob/master/src/uu/rmdir/src/rmdir.rs#L118)

**Comment by sylvestre** [comment]
merged in
https://github.com/uutils/coreutils/pull/2305
