### ISSUE TITLE
rm: different output from gnu

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2261]
with
https://github.com/coreutils/coreutils/blob/master/tests/rm/d-2.sh

GNU:
`rm: cannot remove 'd': Directory not empty`

us:
`rm: error: cannot remove 'd': Directory not empty`

**Comment by tertsdiepraam** [comment]
Probably fixed by https://github.com/uutils/coreutils/pull/2277, right?

**Comment by ycd** [comment]
Yup, we can close this.
