### ISSUE TITLE
Bump MSRV to 1.43

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#2282]
I'd love to see the `more` rewrite (https://github.com/uutils/coreutils/pull/2109) get merged. Unfortunately, there seems to be a bug in `crossterm` that was fixed in a version that is only compatible with Rust 1.43.0 (see https://github.com/uutils/coreutils/pull/2109#issuecomment-846422417). Therefore, I think we should bump the MSRV to 1.43.0.

Other drivers:
- Using attributes on `if` expressions is nice for platform-specific code.
- Rust 1.42 introduced the new `Cargo.lock` format, so (I think) we won't have to do `cargo +1.40.0 update` anymore.

**Comment by sylvestre** [comment]
sure, let's do it
we have enough good reasons

**Comment by miDeb** [comment]
Also, Rust 1.42 introduced the `matches!` macro. There's been more than one occasion where I wanted to use it :)
