### ISSUE TITLE
`sort` should delete intermediate files on SIGINT

### ISSUE THREAD

**Issue by miDeb** [uutils/coreutils#2294]
When terminating `sort` with `^C` while it is doing external sorting (i.e. it stored intermediate files to /tmp/ or a user-specified directory), these intermediate files are not deleted.
This is because the temporary directory is deleted when `TempDir` is dropped. Rust doesn't unwind when receiving `SIGINT`, so  `drop` is never run.

**Comment by hbina** [comment]
Is it okay to introduce a cross-platform library like https://crates.io/crates/ctrlc? Or do you have have something else in mind?

**Comment by miDeb** [comment]
Thanks for pointing out this crate, I didn't have anything else in mind. I wanted to wait for the error handling pr to land before starting work on this.
