### ISSUE TITLE
chroot uses undocumented `clap` properties

### ISSUE THREAD

**Issue by rivy** [uutils/coreutils#2304]
In the `chroot` conversion from `getopts` to `clap` (f60790dd41), it appears that we're now using undocumented parts of `clap` (specifically some hidden properties of `ArgMatches` and `MatchedArg` in chroot.rs#L96-L112)

<https://github.com/uutils/coreutils/blob/f60790dd411fbdc85a77eef24faab5c34422b00b/src/uu/chroot/src/chroot.rs#L96-L112>

Obviously, we prefer to avoid private, undocumented properties, but we should at least document why were using them and possibly a plan to refactor using public methods/properties.

There is some discussion about adding a public method to [iterate over `ArgMatches`](https://github.com/clap-rs/clap/issues/1206) but it looks currently unresolved.

@ycd (committer), could you explain the need/rationale and maybe add a ToDO or FixME comment, please? Apologies if you've already had this discussion, but I could find any reference to it in the [PR discussion](https://github.com/uutils/coreutils/pull/1792). Thanks!

**Comment by ycd** [comment]
Hey @rivy, i wasn't aware of the fact that i'm using undocumented features, apologies for that. 

Sure i can refactor that.
