### ISSUE TITLE
cp Too many open files (os error 24)

### ISSUE THREAD

**Issue by SuperSandro2000** [uutils/coreutils#2312]
I get the following error when copying the [vim source package](https://github.com/vim/vim/releases/tag/v8.2.2567) in nixpkgs

```
cp -pr --reflink=auto -- /nix/store/dvh1x2m7gvp1iv5jjlvrf5ry5g3ay23k-source source
cp: error: '/nix/store/dvh1x2m7gvp1iv5jjlvrf5ry5g3ay23k-source/src/INSTALL' -> 'source/src/INSTALL': Too many open files (os error 24)
```

The smalled reproduced I came up with is ``cp -r --reflink=auto -- /nix/store/dvh1x2m7gvp1iv5jjlvrf5ry5g3ay23k-source source`` with this tarball [dvh1x2m7gvp1iv5jjlvrf5ry5g3ay23k-source.zip](https://github.com/uutils/coreutils/files/6566667/dvh1x2m7gvp1iv5jjlvrf5ry5g3ay23k-source.zip).

**Comment by miDeb** [comment]
Thanks for the bug report! I will submit a fix soon.
