### ISSUE TITLE
`pr`: some tests are racy

### ISSUE THREAD

**Issue by miDeb** [uutils/coreutils#2329]
This probably only happens on slower CI machines, here's an example for that: https://github.com/uutils/coreutils/pull/2328/checks?check_run_id=2720656712#step:8:1659.
The problem is that the test checks for the current time to show up in the output, with the precision of a minute. This check is executed after the program ran, and the program might have used an earlier time.

**Comment by tertsdiepraam** [comment]
Yeah, I thought that might be an issue. I will try to fix them tomorrow.

**Comment by tertsdiepraam** [comment]
Well, still not quite right: https://github.com/uutils/coreutils/runs/2741384091 reopening :)

**Comment by tertsdiepraam** [comment]
Well, still not quite right: https://github.com/uutils/coreutils/runs/2741384091 reopening :)

**Comment by miDeb** [comment]
There seems to be a similar problem in the tests for `pinky`: https://github.com/uutils/coreutils/pull/2338/checks?check_run_id=2739362262.

Should I open a separate issue?
