### ISSUE TITLE
Converting absolute to relative symlink errors with ``No such file or directory``

### ISSUE THREAD

**Issue by SuperSandro2000** [uutils/coreutils#2335]
When nixpkgs tries to convert absolute symlinks to relative ones this currently fails with the deletion of the symlink. Tested on current master with https://patch-diff.githubusercontent.com/raw/uutils/coreutils/pull/2330.diff applied.

```ShellSession
$ touch ed
$ result/bin/uutils-ln -s ed red
$ result/bin/uutils-ln -snrf ed red
ln: No such file or directory (os error 2)
$ lsd -lah red
lsd: red: No such file or directory (os error 2).
```

After the error the original symlink is deleted.

**Comment by miDeb** [comment]
Thank you for the bug report! The bug was that we were incorrectly computing the relative path when the destination was a symlink.
