### ISSUE TITLE
Improving error handling for all utilities

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#2336]
I'd like to start some discussion on error handling and how we can improve it.

# Current situation
Currently, the util is simply run and returns an `i32` containing an error code, which is then used as exit code. The util itself is then responsible for printing any errors for the user.

In my opinion, there are a couple of problems with this:
- There is a lot of `return 0;` and codes for collecting and combining status codes in the utils. For example patterns like this:
```rust
let exit_code = 0;
for file in files {
    let code = foo(file);
    exit_code |= code;
}
return exit_code;
```
- It prohibits the use of `?` in the `uumain` functions.
- By extension it discourages idiomatic handling of errors in other functions, because they also often just return `i32`.
- All utils have their own formats for common errors. We are of course actively fixing these by checking against the GNU tests, but there is still a lot of manual work and a lot of room for (spelling) mistakes,

# Proposed solution
We could move toward making a `uucore::Error` type like this (with just a few examples implemented):
```rust
enum Error {
    BadUsage,
    PermissionDenied(Path),
    // more common errors here
    CustomMsg { msg: String, code: i32 },
    Code(i32),
}
```

So the signature of `uumain` then becomes:
```rust
fn uumain(uumain(args: impl uucore::Args) -> Result<(), uucore::Error>
```
The main function generated by `uucore_procs::main` would then be responsible for printing the error message and returning the corresponding exit code.

That type could then also provide a method to print an error message for the utils. So this:
```rust
show_error!("'{}': Permission denied", file.display());
```
would become something like this:
```rust
eprintln!("{}", uucore::Error::PermissionDenied(path));
// or
uucore::Error::PermissionDenied(path).print(); // or show(), display(), etc.
```

Finally we could provide automatic conversion from `ClapResult` to our return type, to make the messages for invalid or missing arguments match GNU more closely. This would allow us to use more of `clap`'s capabilities. For example, this is taken from a recent PR:
```rust
// clap provides .conflicts_with / .conflicts_with_all, but we want to
// manually handle conflicts so we can match the output of GNU coreutils
if (matches.is_present(options::CSH)
    || matches.is_present(options::C_SHELL)
    || matches.is_present(options::SH)
    || matches.is_present(options::BOURNE_SHELL))
    && matches.is_present(options::PRINT_DATABASE)
{
    show_usage_error!(
        "the options to output dircolors' internal database and\nto select a shell \
    return 1;
}
```

Since `?` calls `into()` implicitly, the usage of `clap` with custom error messages would then just be:
```rust
fn uumain(uumain(args: impl uucore::Args) -> Result<(), uucore::Error> {
    let matches = App::new(...)
        .arg(...)
        .arg(...)
        .get_matches_from_safe(args)?;
    ...
}
```

I would love to hear what everyone's thoughts on this are. Note that the solution above is purely for getting the discussion started (I don't even think lifetimes work out in the `enum`) and it is quite possible that the type will need to be significantly more complex.

So my questions are:
- Is this useful or is it too complex?
- Do you think it's worth it to refactor everything (although maybe this can also be done incrementally)?
- Are there any situations where this would not work?
- Are there utilities with incompatible errors? Such as one utils returning `Bad Usage` with code `1` and another with code `2`.

**Comment by miDeb** [comment]
I think this is a great idea, and very useful! I think it would be useful to implement `from()` for the most common errors we might encounter, such as io errors, utf-8 etc.
Some quick ideas:
>  Such as one utils returning Bad Usage with code 1 and another with code 2.

`sort` is such a utility, it returns 2 for almost any error. We could allow utilities to override the conversion from an error enum variant to the error code. (I'm thinking we could have a `Utility` trait that every utility implements, with some default implementations)

- Instead of using a `CustomMsg { msg: String, code: i32 },`, we could use something more like `Custom(Box<dyn CustomError>)`, and require each `CustomError` object to be able to tell us the error message/code. Usage could look like this:
```rust
enum SortError {
   Disorder { line: usize },
}

impl CustomError for SortError {
  fn error_code(&self) -> i32 {
    match self {
      Disorder { .. } => 1
  }
  fn error_message(&self) -> String {
     todo!()
  }
}
```
Otherwise I think it encourages to create a String message the moment the error occurs. I think this pattern would also be a bit better if we want to localize error messages at some point.

- This is probably a bit off-topic, but I don't particularly like `crash!()` and `crash_if_err!()`, because they immediately exit without running destructors. That's causing bugs in `sort` I need to fix, because I didn't think of that when implementing. I think we should use this proposed error mechanism for expected errors and just panic if there's an unespected error.

**Comment by tertsdiepraam** [comment]
I agree completely! For some more inspiration, I'm looking at `ripgrep`. They do a few interesting things there:
- They have a global `AtomicBool` to determine the final exit code. That would make the handling of non-fatal errors a lot easier. (We would adapt this to be an `AtomicI32`.
- They indeed implement `From` on common errors.
- Their global result type is just `Result<T, Box<dyn std::error::Error>>`, which is extremely flexible.

Based on this, I would propose use `Result<(), Box<dyn UError>>` where `UError` is:
```rust
trait UError : std::error::Error {
    fn error_code(&self) -> i32;
}
```

The `Display` trait would then be used to print the message, like normal Rust errors.

Then we provide a bunch of common types that implement this trait in `uucore` and any utility can then implement this for custom errors. The errors in `uucore` could then by convention include a method `with_code` that changes the return code (for utilities like `sort`).

Additionally, we have that `AtomicI32` that we return if `Ok(())` is returned from `uumain` and we could provide methods/macros to set it.

**Comment by miDeb** [comment]
Here's a slightly different proposal: I think it would be beneficial if the common errors are enum variants, so that it is easier for utilities to override the error code and/or messages in one place.
So, I'd propose a `Result<(), Box<UError>>` where `UError` is:
```rust
enum UError {
  Common(UCommonError),
  Util(Box<dyn UUtilError>)
}
```
UCommonError would be a big enum with all common errors, and `UUtilError` a trait like the one you proposed. So what I'm proposing is basically using trait objects for utility-specific errors and an enum for common errors.

I propose the following way for utilities to override the default exit codes:
- Have a method `map_custom_exit_code` on `UError` that allows to pass a function that returns the exit code for a given `UCommonError` variant.
- `uumain` could look like this:
```rust
fn uumain(args: impl uucore::Args) -> Result<(), Box<UError>>{
  actual_main(args).map_custom_exit_code(exit_code_mapper)
}

fn exit_code_mapper(error: UCommonError) -> i32 {
  match error {
     _ => todo!(),
  }
}
```

Regardless of what we decide for I'd introduce a type alias for the result type. In this proposal that would be
```rust
type UResult<T> = Result<T, Box<UError>>;
```
so that you can write `UResult<Type>` instead of `Result<Type, Box<UError>>` for the return type.

**Comment by tertsdiepraam** [comment]
> UCommonError would be a big enum with all common errors

I'm currently trying to implement this (even with an almost identical name). The only difference is that I'm using the trait I proposed for both common and custom errors. I thought that would be a little bit more ergonomic. I'll put that up as a draft PR soon. My current approach is this:
- A `UError` trait that extends `Error` with a `code` method.
- A `CommonError` `enum` for the common errors.
- A `CommonErrorWithCode` type that you can create with the `with_code` method on `CommonError`.
- An `ExitCode` type that doesn't print anything when returned but only returns an exit code. 
- A `set_exit_code` function that sets the exit code for if `Ok(())` is returned (based on `ripgrep`).

> Have a method map_custom_exit_code on UError that allows to pass a function that returns the exit code for a given UCommonError variant.

This is an interesting idea. I can see that it would be annoying to put `with_code` on all your errors but rather define them in one place. What would be result after applying that `map`? It can't be the `enum`, because that does not explicitly contain the exit code. Would it map to a third enum variant `CommonWithCode` or maybe custom `UError::Util`? Also, what type is it implemented on? We can't implement it on `Result`, so I think it would at least be something like:
```rust
fn uumain(args: impl uucore::Args) -> Result<(), Box<UError>>{
  actual_main(args).map_err(|e| e.map_custom_exit_code(exit_code_mapper))
}
```

I would love to eventually make `UResult` a struct containing a status code and an optional message. On which we could then implement `map_custom_exit_code`. Unfortunately, the `Try` trait hasn't been stabilized yet, so we wouldn't be able to use `?` on it for a long time.

With the additional `enum`, I'm worried that constructing errors might become too verbose. It would be something like:
```rust
Err(UError::Common(CommonError::PermissionDenied(path)))
```

I guess that we could make convenience methods on `UError` to mitigate this a bit, but then it would still be quite verbose for custom errors.

> Regardless of what we decide for I'd introduce a type alias for the result type.

Agreed!

**Comment by miDeb** [comment]
> This is an interesting idea. I can see that it would be annoying to put with_code on all your errors but rather define them in one place. What would be result after applying that map? It can't be the enum, because that does not explicitly contain the exit code. Would it map to a third enum variant CommonWithCode or maybe custom UError::Util? Also, what type is it implemented on? We can't implement it on Result, so I think it would at least be something like:

- The return type could be a `UError`. It could use the `UError::Custom` variant to put a struct that stores the exit code and message.
- I think we can put it on `Result` if we use traits.

> With the additional enum, I'm worried that constructing errors might become too verbose. It would be something like:

Again, traits help us here. By implementing the `From` trait we can replace much of the boilerplate with an `into()`.
Here's a very simple implementation: (Note that there is not much boilerplace in `map_custom_exit_code`, `Err(ErrorWithCodeAndMessage { code, message }.into())` is not very verbose imho)
```rust
use std::{error::Error, fmt::Display};

enum UError {
    Common(UCommonError),
    Custom(Box<dyn UCustomError>),
}

trait UCustomError: Error {
    fn error_code(&self) -> i32;
}

enum UCommonError {}

#[derive(Debug)]
struct ErrorWithCodeAndMessage {
    code: i32,
    message: String,
}

impl Display for ErrorWithCodeAndMessage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}

impl Error for ErrorWithCodeAndMessage {}
impl UCustomError for ErrorWithCodeAndMessage {
    fn error_code(&self) -> i32 {
        self.code
    }
}

type UResult<T> = Result<T, Box<UError>>;

trait UErrorTrait {
    fn map_custom_exit_code(self, mapper: fn(&UCommonError) -> (i32, String)) -> Self;
}
impl<T> UErrorTrait for UResult<T> {
    fn map_custom_exit_code(self, mapper: fn(&UCommonError) -> (i32, String)) -> Self {
        match &self {
            Err(e) => match e.as_ref() {
                UError::Common(e) => {
                    let (code, message) = mapper(e);
                    Err(ErrorWithCodeAndMessage { code, message }.into())
                }
                _ => self,
            },
            _ => self,
        }
    }
}

impl<E: UCustomError + 'static> From<E> for Box<UError> {
    fn from(v: E) -> Self {
        Box::new(UError::Custom(Box::new(v) as Box<dyn UCustomError>))
    }
}

impl From<UCommonError> for Box<UError> {
    fn from(v: UCommonError) -> Self {
        Box::new(UError::Common(v))
    }
}
```

Something else: Do all utilites print their name in front of every error message?

**Comment by tertsdiepraam** [comment]
Awesome! I didn't think of using a trait for that. I'll try to incorporate that into what I was working on and put up a draft PR tomorrow.

**Comment by tertsdiepraam** [comment]
@miDeb How do you think we should approach wrapping errors from the standard library? For example, let's say we want to wrap the `Permission denied` error. The `io::Result` contains only an error code from the underlying OS error. Therefore, we would somehow need to provide the `Path` for the `UError/UResult`, so that we can print it later.

Additionally, we need to give it some sort of format string that specifies the "action", because different utils use different descriptions and sometimes even multiple descriptions in the same util:
```
touch: cannot touch 'test': Permission denied
touch: setting times of 'test': Permission denied
head: cannot open 'test' for reading: Permission denied
```

I can think of a few approaches:
- Provide a method on `UResult` that takes an `io::Result`, a `&'static str` and a `&Path`, but this is quite verbose. Usage would be:
```rust
UResult::from_io(File::create(path), "cannot touch {}", &path);
```
- Alternatively, we could implement `From<(std::io::Result, &'static str, &Path)>`?
```rust
(File::create(path), "cannot touch {}", &path).into();
```
- Implement `From<std::io::Result>` and make an additional method for the message:
```rust
File.create(path).into().message("cannot touch {}", &path);
```
- A fancy proc macro that wraps the functions that return `io::Result`, so you could write
```rust
uresult!(File::create(path), "cannot touch {}");
```
which is cool, but I imagine also quite fragile and cumbersome to create and maintain, because it would get the path from the argument to the given function.
- We just create a function which returns a `&'static str` based on the `ErrorKind` of the `io::Error`, and leave the creation of the error up to the util. So `ErrorKind::PermissionDenied` just maps to `"Permission Denied"`. At least the message is then standardized.
- We wrap the functions and types we need in `uucore`. So maybe a `create_file` function or even a `create` function in a `File` (or `UFile`?) module. We could generate these pretty easily with macros, I think. We would have to keep adding any new function that we start using though. It also makes it harder to work with `io::Result` if you don't want to convert or want to convert later. It doesn't feel quite right. It would look something like:
```rust
use uucore::File;
...
File::create(path);
```

I'm not really happy with any of these options (not even sure if all are possible), so other approaches are definitely welcome!

**Comment by miDeb** [comment]
> Implement From<std::io::Result> and make an additional method for the message:

We could allow giving context to any error by having a method on `UResult`.
The syntax could look like this:
```rust
File.create(path).into().failed_operation_message(|| format!("cannot touch {}", path))?;
```
It takes a closure so that it doesn't allocate a String even on success, and there has to be a macro invocation somewhere because we can't pass format strings to functions.
`failed_operation_message` could return a `UCommonError` variant like `WithContext { context: String, inner: UCommonError }`
Maybe that would work?

Alternatively we could leave it up to each utility to define their own custom errors for such failures.
They could use `map_err()` to create their own error from the io error, maybe like this:
```rust
File.create(path).map_err(|error| TouchError::Create { file_name: path, inner: error }?;
```
