### ISSUE TITLE
Implement `rm  ---presume-input-tty`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2345]
` --presume-input-tty` is an undocumented option of `rm`.

https://bug-coreutils.gnu.narkive.com/AMUZEL4V/rm-p
     
 ```
             It is relatively difficult to ensure that there is a tty on stdin.
            Since rm acts differently depending on that, without this option,
            it'd be harder to test the parts of rm that depend on that setting. 
```

GNU testsuite:
`2021-06-04T19:17:12.4465259Z +error: Found argument '--presume-input-tty' which wasn't expected, or isn't valid in this context`

It should not be visible in rm in clap

**Comment by hbina** [comment]
`--presume-input-tty` basically makes this possible, right?

```bash
coreutils on  master [?] is 📦 v0.0.6 via 🦀 v1.52.1 
❯ touch test

coreutils on  master [?] is 📦 v0.0.6 via 🦀 v1.52.1 
❯ echo "test" | rm --presume-input-tty
rm: unrecognized option '--presume-input-tty'
Try 'rm --help' for more information.
```

**Comment by zacchiro** [comment]
> GNU testsuite:
> `2021-06-04T19:17:12.4465259Z +error: Found argument '--presume-input-tty' which wasn't expected, or isn't valid in this context`

Are you sure this is the correct test suite output?

I'm asking because in GNU coreutils the flag is actually `---presume-input-tty`, with *three* dashes:
```
$ rm -presume-input-tty
rm: invalid option -- 'p'
Try 'rm --help' for more information.
$ rm --presume-input-tty
rm: unrecognized option '--presume-input-tty'
Try 'rm --help' for more information.
$ rm ---presume-input-tty
rm: missing operand
Try 'rm --help' for more information.
```
which is also confirmed in the GNU coreutils source code:
```
 /tmp/coreutils-8.32 $ rgrep presume-input-tty
tests/rm/dir-no-w.sh:rm ---presume-input-tty unwritable-dir < /dev/null > out-t 2>&1 && fail=1
tests/rm/dangling-symlink.sh:rm ---presume-input-tty dangle symlink & pid=$!
tests/rm/deep-2.sh:rm ---presume-input-tty -r x < no > out || fail=1
tests/rm/interactive-once.sh:  rm ---presume-input-tty -I file1-* < in-n >> out 2>> err || fail=1
tests/rm/interactive-once.sh:  cat in-y in-n | rm ---presume-input-tty -I file3-* >> out 2>> err || fail=1
tests/rm/isatty.sh:rm ---presume-input-tty f > out 2>&1 & pid=$!
src/rm.c:  {"-presume-input-tty", no_argument, NULL, PRESUME_INPUT_TTY_OPTION},
```
(in case you're wondering about the last line, all other long flags are without leading "-" and get prefixed by "--", resulting in "---" for that specific flag)

Also, in the context of Rust coreutils, am I correct in assuming it would be good enough for this flag to be a noop (without failing due to it being an unknown option, of course)?

**Comment by sylvestre** [comment]
Salut Stefano! 

Yeah, as always, you are correct ;) Three dashes!
https://github.com/coreutils/coreutils/search?q=%22---presume-input-tty%22&type=code

> Also, in the context of Rust coreutils, am I correct in assuming it would be good enough for this flag to be a noop (without failing due to it being an unknown option, of course)?

Yeah, probably

@hbina maybe ? :) I am not sure we want to support this :)
It sounds risky and probably not really used
