### ISSUE TITLE
`touch`: mismatch of GNU output in case of error

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2346]
https://github.com/coreutils/coreutils/blob/master/tests/touch/fail-diag.sh#L27

```
2021-06-04T19:18:39.5556668Z -touch: cannot touch '/no-such-dir/file': No such file or directory
2021-06-04T19:18:39.5557700Z +touch: warning: cannot touch '/no-such-dir/file': No such file or directory (os error 2)
```

STR=
```
file=/no-such-dir/file    
touch $file
```

Should be something like:
https://github.com/uutils/coreutils/blob/31875a241fc1b1c3582b8e876cf3c44d1145d468/src/uu/touch/src/touch.rs#L210-L213

**Comment by Foryah** [comment]
I can try to take care of this one. I tested on local this seems to do the trick:
```
show_error!("cannot touch '{}': {}", path, "No such file or directory");
```
The error message from the `File::create` has that ` (os error 2)` part and my thought process was that it's faster to just use the correct string than to do some string manipulation and get rid of that part. Do you agree? 

Also do I need to write any tests for this or the existing tests are good enough?

**Comment by tertsdiepraam** [comment]
Thank you! I agree with your solution, that seems to be the way to go about this for now. If there are no tests for this error yet, it would be great if you could add one!

**Comment by sylvestre** [comment]
thanks :)
