### ISSUE TITLE
`more` cuts off last line of input when more than one page of output

### ISSUE THREAD

**Issue by mitchellmebane** [uutils/coreutils#2348]
Running current `master` on Debian Unstable in WSL2, with both CMD and Windows Terminal.  I think this is probably a bug in `more` as opposed to WSL2, since it seems to calculate the terminal height correctly, but I don't have a native Linux install available right now to test with.

Easy repro (replace 60 with some number higher than your current terminal # of rows):

```
for i in {1..60..1}; do echo "$i"; done
```

vs

```
for i in {1..60..1}; do echo "$i"; done | target/debug/coreutils more
```

The last line should be 60 (or whatever you put in the for loop).

**Comment by mitchellmebane** [comment]
Actually, it happens even when the number of lines is exactly the terminal height,  In that case, it exposes an additional difference between coreutils `more` and util-linux `more`: util-linux `more` pages the output, coreutils `more` just cuts off one line but doesn't page the output.

**Comment by hbina** [comment]
It simply crashes for me lol

```
   Compiling coreutils v0.0.6 (/Users/hbina/git/coreutils)
    Finished dev [unoptimized + debuginfo] target(s) in 10.04s
     Running `target/debug/coreutils more`
[2K
1

2

3

4

5

6

7

8

9

10

11

12

13

14

15

16

17

18

19

20

21

22

23

[7m--More--(38%)[0mthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Other, error: "Failed to initialize input reader" })', src/uu/more/src/more.rs:235:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tertsdiepraam** [comment]
Thanks for the report and the easy repro! I think I fixed it.
