### ISSUE TITLE
`du --threshold=SIZE` isn't implemented

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2352]
```
       -t, --threshold=SIZE
              exclude  entries  smaller  than  SIZE  if  positive,  or entries
              greater than SIZE if negative
```
it should have also `--th` as alias

Code is in:
https://github.com/uutils/coreutils/blob/master/src/uu/du/src/du.rs
tests in:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_du.rs

**Comment by siebenHeaven** [comment]
Hello - can I give this a shot?
