### ISSUE TITLE
`cp --preserve` without argument isn't supported

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2353]
According to GNU, no argument means:
```
       --preserve[=ATTR_LIST]
              preserve the specified attributes (default: mode,ownership,time‐
              stamps),
```

On our side:
```
$ cp --preserve
error: The argument '--preserve <ATTR_LIST>...' requires a value but none was supplied

```

Code:
https://github.com/uutils/coreutils/blob/master/src/uu/cp/src/cp.rs
Tests:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_cp.rs

**Comment by urohit011** [comment]
Can I take this one?

**Comment by tertsdiepraam** [comment]
Sure! You'll probably need something similar to this for the argument parsing: https://github.com/uutils/coreutils/pull/2213#issuecomment-846583710

**Comment by urohit011** [comment]
Thanks @tertsdiepraam

**Comment by sylvestre** [comment]
Smart!

**Comment by urohit011** [comment]
Hi, I think we should go ahead with @hbina's pull request.
