### ISSUE TITLE
Missing "-k" / sort by column flag to SORT 

### ISSUE THREAD

**Issue by sadaaithal** [uutils/coreutils#2372]
Sort by column using the `-k` flag is a good to have

**Comment by miDeb** [comment]
This feature is already implemented on the master channel :)
If you want, you could confirm that it works correctly for your use case (there were some bugs in the past, so just to make sure)

**Comment by sadaaithal** [comment]
@miDeb  
ive just built coreutils and can confirm that -k works as expected. 
thank you!
