### ISSUE TITLE
Use `UResult` in all utils

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#2464]
With https://github.com/uutils/coreutils/pull/2355 getting merged, we can start moving all utils to use `UResult`/`UError`. When this is done, the temporary `gen_uumain` macro can be incorporated into `main` and be removed.

Documentation for the error handling can be found in the `uucore::error` module in rustdoc format. The current implementation is not considered final, so feel free to suggest changes.

Examples of utils that use `UResult`:
- `ls`
- `mkdir`
- `mktemp`
- `touch`

Utils:
- [x] `arch`
- [x] `base32`
- [x] `base64`
- [x] `basename`
- [x] `cat`
- [x] `chcon`
- [x] `chgrp`
- [x] `chmod`
- [x] `chown`
- [x] `chroot`
- [x] `cksum`
- [x] `comm`
- [x] `cp`
- [x] `csplit`
- [x] `cut`
- [x] `date`
- [x] `dd`
- [x] `df`
- [x] `dircolors`
- [x] `dirname`
- [x] `du`
- [x] `echo`
- [x] `env`
- [x] `expand`
- [x] `expr`
- [x] `factor`
- [x] `false`
- [x] `fmt`
- [x] `fold`
- [x] `groups`
- [x] `hashsum`
- [x] `head`
- [x] `hostid`
- [x] `hostname`
- [x] `id`
- [x] `install`
- [x] `join`
- [x] `kill`
- [x] `link`
- [x] `ln`
- [x] `logname`
- [x] `ls`
- [x] `mkdir`
- [x] `mkfifo`
- [x] `mknod`
- [x] `mktemp`
- [x] `more`
- [x] `mv`
- [x] `nice`
- [x] `nl`
- [x] `nohup`
- [x] `nproc`
- [x] `numfmt`
- [x] `od`
- [x] `paste`
- [x] `pathchk`
- [x] `pinky`
- [x] `pr`
- [x] `printenv`
- [x] `printf`
- [x] `ptx`
- [x] `pwd`
- [x] `readlink`
- [x] `realpath`
- [x] `relpath`
- [x] `rm`
- [x] `rmdir`
- [x] `seq`
- [x] `shred`
- [x] `shuf`
- [x] `sleep`
- [x] `sort`
- [x] `split`
- [x] `stat`
- [x] `stdbuf`
- [x] `sum`
- [x] `sync`
- [x] `tac`
- [x] `tail`
- [x] `tee`
- [x] `test`
- [x] `timeout`
- [x] `touch`
- [x] `tr`
- [x] `true`
- [x] `truncate`
- [x] `tsort`
- [x] `tty`
- [x] `uname`
- [x] `unexpand`
- [x] `uniq`
- [x] `unlink`
- [x] `uptime`
- [x] `users`
- [x] `wc`
- [x] `who`
- [x] `whoami`
- [x] `yes`

**Comment by jfinkels** [comment]
I believe I have created a pull request for each remaining program.

**Comment by jfinkels** [comment]
I used `USimpleError` in most places in order to limit the time I would spend on this work. That's an area for future improvement.

**Comment by tertsdiepraam** [comment]
Awesome! I'll try to keep this list updated as they get merged. Regarding `USimpleError`, that's fine. Sometimes it might even be the best choice or it can be refactored later.

**Comment by sylvestre** [comment]
This is a superbe achievement, bravo!

**Comment by tertsdiepraam** [comment]
All merged and checked! Amazing work!

**Comment by jfinkels** [comment]
Excellent!
