### ISSUE TITLE
`executable!()` should return the real executable name

### ISSUE THREAD

**Issue by miDeb** [uutils/coreutils#2470]
- We should print the first command line argument (the executable name) when printing error messages.
This means that when you rename the `ls` utility to `uu-ls`, the error message should no longer say `ls: <error>` but `uu-ls <error>`.
- Another case where the real executable name should be used are the `USAGE` strings.
- However, the real executable name should *not*  be used for `--version. In this case the utility name should be printed.

I'm already working on this, but if this doesn't look right please let me know :)

**Comment by rivy** [comment]
Agreed.

I realized that the USAGE and warning/error strings were not adapting to variant names a bit ago. When looking at it, I noticed that the `executable!()` macro really returns the utility name, not the executable. 

I've started a local branch to refactor it into `util_name()!` and started adding a function that returns the actual executable name, for the various needs that you listed.

I'll probably have something done over the weekend, unless you want to tackle it instead?

**Comment by miDeb** [comment]
> I've started a local branch to refactor it into util_name()! and started adding a function that returns the actual executable name, for the various needs that you listed.

That's what I've done until now as well. Right now I was running into the problem that some tests expect the utility name in error messages, but the real executable name is an absolute path to the binary...
I'm obviously happy to let you do the work, but if you want me to help just let me know.

**Comment by miDeb** [comment]
FYI my wip branch was https://github.com/miDeb/coreutils/tree/real-exe-name, but you're probably mostly at the same point.

**Comment by rivy** [comment]
> That's what I've done until now as well. Right now I was running into the problem that some tests expect the utility name in error messages, but the real executable name is an absolute path to the binary...

GNU tests? Or our project tests?

And I was pondering how best to handle `show_error!()`, `show_warning!()`, etc.

**Comment by miDeb** [comment]
> GNU tests? Or our project tests?

Project tests. I haven't checked GNU tests yet, but they should be fine.

> And I was pondering how best to handle show_error!(), show_warning!(), etc.

You can always get the executable name again by calling `std::env::args().next().unwrap()`. That's what I basicall did: I replaced the logic in `executable!()` with that and added `util_name!()` to get the crate/utility name.

**Comment by rivy** [comment]
> You can always get the executable name again by calling `std::env::args().next().unwrap()`. That's what I basicall did: I replaced the logic in `executable!()` with that and added `util_name!()` to get the crate/utility name.

That works well for the individual utilities, but not the busybox-type binary. And that looks like it's the basis of a lot of the project testing errors after this change.

I rebuilt a branch based on your initial commit at https://github.com/rivy/rs.coreutils/commits/147e15fce52fde22dcd17024b13273a6b1a51b39 if you want to take a look.

**Comment by miDeb** [comment]
So just so I understand this correctly, if we're being executed as `/path/to/coreutils ls` the executable name should be `ls`, the *second*  command line arg? I could imagine doing an ugly workaround by checking the `CARGO_PRIMARY_PACKAGE` environment variable at compile time to decide whether to read the first, or the second argument if the first is `coreutils`.

**Comment by miDeb** [comment]
Alternatively we could add a static variable where we store the binary name. I've explored that at first but then I thought we could get away with a simpler implementation.
That basically was a lazy static Mutex that contains a string (the executable name).

**Comment by tertsdiepraam** [comment]
Maybe there could be a function `executable()` that's created by the `main!` macro and has a special implementation for the busybox-style binary? The `main` macro then looks at the first arg and the busybox-style macro looks at the second. Maybe that's a bit too much magic in the macro though.

**Comment by miDeb** [comment]
It turns out that that's not enough because even with the busybox binary the first argument could be the executable name. I think I have a working implementation now. It sets the executable name in the generated main functions or in the coreutils main function. I'll open a PR.

**Comment by rivy** [comment]
> So just so I understand this correctly, if we're being executed as `/path/to/coreutils ls` the executable name should be `ls`, the _second_ command line arg? I could imagine doing an ugly workaround by checking the `CARGO_PRIMARY_PACKAGE` environment variable at compile time to decide whether to read the first, or the second argument if the first is not a utility name.

Yeah, it's even a bit more complicated than that since we're trying to give the user an actual command line that can be used directly.

The executable for `/path/to/coreutils ls` to use for suggestions (eg, usage) would be `/path/to/coreutils ls` with `ls` as the util name.

**Comment by miDeb** [comment]
> The executable for `/path/to/coreutils ls` to use for suggestions (eg, usage) would be `/path/to/coreutils ls` with `ls` as the util name.

So for errors should we only print `ls: `, or also 
`/path/to/coreutils ls: `?

**Comment by rivy** [comment]
> So for errors should we only print `ls: `, or also
> `/path/to/coreutils ls: `?

I implemented it as the latter. I think the full executable

**Comment by miDeb** [comment]
@rivy did you have a chance to continue this? I was doing something else the last few weeks but now I'd like to come back to this and make it work :)

**Comment by rivy** [comment]
@miDeb , 

Unfortunately, my time has been claimed by another local COVID patient surge over the last few weeks. So, I haven't had any real time to devote to this yet. However, I did just rebase some prior work (with some additions tonight). It's still a bit rough, needing a few fixes and some commit polish. But, hopefully, I should be able to devote some time to it by this weekend.

The current working branch is [`x.rf`](https://github.com/rivy/rs.coreutils/tree/x.rf) at commit <https://github.com/rivy/rs.coreutils/commit/92a8ffc67e6dcdedb11c94c8a60048eded52c114>.

I'll try to have something for you to examine and critique by this weekend.

**Comment by rivy** [comment]
@miDeb , it's up for a look.

**Comment by miDeb** [comment]
Thanks! Sorry if I stressed you because of this, and I hope you're doing well.

**Comment by rivy** [comment]
> Thanks! Sorry if I stressed you because of this, and I hope you're doing well.

No worries! This doesn't stress me... stress is from the other work. This is what I do for relaxation! 😄
