### ISSUE TITLE
tr with complement and squeeze-repeats options doesn't behave as expected

### ISSUE THREAD

**Issue by fdanis-oss** [uutils/coreutils#2485]
It seems that `tr` fails to change characters when used with both `-c` (--complement) and `-s` (--squeeze-repeats) options

gnu-coreutils:
```
$ echo -n "test with 3 spaaces++" | tr -c -s 'a' '_'
_aa_
```
uutils-coreutils:
```
$ echo -n "test with 3 spaaces++" | cargo run -- tr -c -s 'a' '_'
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/coreutils tr -c -s a _`
test with 3 sp_ces++
```

or

gnu-coreutils:
```
$ echo -n "test with 3 spaaces++" | tr -c -s 'A-Za-z0-9---_' '_'
test_with_3_spaaces_
```
uutils-coreutils:
```
$ echo -n "test with 3 spaaces++" | cargo run -- tr -c -s 'A-Za-z0-9---_' '_'
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/coreutils tr -c -s A-Za-z0-9---_ _`
test with 3 spaaces++
```

**Comment by hbina** [comment]
Skimming through the code, I think its "half-baked". Many functionalities aren't implemented and I think it's quite hard to extend the functionality as it is so I am thinking of reworking it. However, I don't have many experience with `tr` so I don't know all the use-case and edge-cases that I need to test. Hopefully the existing test is "good enough".

**Comment by jhscheer** [comment]
Thanks for mentioning this.
I see what's wrong an I'm working on a fix.

@hbina I agree this would benefit from a rework. In addition to our test cases, there are also the test cases from GNU's testsuite, i.e. misc/tr-case-class.sh and misc/tr.pl

**Comment by fdanis-oss** [comment]
@jhscheer Thanks for the fix

fyi, it still fails on my second test: `echo -n "test with 3 spaaces++" | cargo run -- tr -c -s 'A-Za-z0-9---_' '_'` returns `test_with_3_spaaces__` instead of `test_with_3_spaaces_`
