### ISSUE TITLE
basename: -a argument coming after filename should be treated as suffix to remove, but isn't

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#2535]
GNU version 8.28:
```
$ basename a-a -a
a
```
uutils version:
```
$ ./target/debug/coreutils basename a-a -a
a-a
```

I think GNU `basename` treats "-a" not as a flag but as the second positional argument.

**Comment by miDeb** [comment]
I'd solve this by specifying `allow_hyphen_values(true)` for the `files` parameter. However, `allow_hyphen_values(true)` does not work with positional arguments, see https://github.com/clap-rs/clap/issues/1437. We'll probably have to wait until this issue is resolved...

**Comment by sylvestre** [comment]
@jfinkels @miDeb seems that it is fixed if you want to have a look :)

**Comment by niyaznigmatullin** [comment]
PR #3736 should solve the issue

**Comment by sylvestre** [comment]
thanks!
