### ISSUE TITLE
Cat Windows 10 does not work 

### ISSUE THREAD

**Issue by Quackdoc** [uutils/coreutils#2601]
when building on windows 10 trying to run cat gives this error
```

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: Uncategorized, message: "Incorrect function." }', src\uu\cat\src/cat.rs:375:71
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Lertsenem** [comment]
Hello, when is this fix planned for release? I'm using version 0.0.8 and the error is still occuring.

**Comment by sylvestre** [comment]
We are all volunteers. Nothing planed AFAIK.

Don't hesitate to give it a try to fix it!

**Comment by Lertsenem** [comment]
I realize that, sorry I was not trying to sound harsh. I just read in the thread that the patch was ready and the line

> [...] linked a pull request that will close this issue on 28 Aug 

made me wonder if I had missed a release or if the bug had been fixed but then reappeared somehow. :)

**Comment by tertsdiepraam** [comment]
That PR has indeed been open for a long time, but it looks good. @Lertsenem, could you maybe check whether that PR fixes the issue for you? I think most maintainers are on Linux so it's hard to validate.

**Comment by Lertsenem** [comment]
I'd like too, but this is unfortunately a work PC and I don't have the opportunity to build anything on it. Hence my wait for the release. :/

**Comment by tertsdiepraam** [comment]
Alright, I might be able to test it this weekend then.

**Comment by tertsdiepraam** [comment]
I've tested the PR and it does indeed fix this issue. I think it can be merged!
