### ISSUE TITLE
uniq: missing support for deprecated -f syntax

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#2617]
Similar to #2507. The `-f <num>` option to `uniq` has a deprecated syntax, `-<num>`. See https://www.gnu.org/software/coreutils/manual/html_node/uniq-invocation.html For example,
```
$ printf "a a\nb a\n" | uniq -1
a a
```

**Comment by Leviticoh** [comment]
how did it go?
i'd like to try if no one is working on it

**Comment by sylvestre** [comment]
sure, please do :)

**Comment by angus-lherrou** [comment]
> how did it go?
> i'd like to try if no one is working on it

yes, go for it—I fully do not remember what I ended up doing haha

**Comment by sylvestre** [comment]
it works now :)
