### ISSUE TITLE
kill: Argument parsing is broken for -<sig number> 

### ISSUE THREAD

**Issue by sedrubal** [uutils/coreutils#2645]
Normal kill can handle

```sh
$ kill -<SIG NUMBER> <PID>
$ # e.g.
$ kill -USR1 1337
```

but uu-kill fails:

```sh
$ uu-kill -USR1 1337
error: Found argument '-USR1' which wasn't expected, or isn't valid in this context

USAGE:
    kill [OPTIONS]... PID...

For more information try --help
```

**Comment by oeble** [comment]
Hello, I would like to implement this, can you assign it to me?

I have already take a look at it. Is it ok if I go little bit further? There is a few behavior around this that does not seems to follow the gnu kill behavior. For instance, in my opinion ` kill -<sig>` should only work if the signal is the first parameter. The usage sentence could also be improved around this.

**Comment by oeble** [comment]
I have pushed a pull request, I hope this is fine.
