### ISSUE TITLE
chroot: thread 'main' panicked

### ISSUE THREAD

**Issue by NintendEthan** [uutils/coreutils#2687]
gnu chroot works fine but whenever i use uu-chroot:
`$ uu-chroot ~/chroot`
`thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/eef/repos/coreutils/src/uu/chroot/src/chroot.rs:82:32
note: run with "RUST_BACKTRACE=1" environment variable to display a backtrace`

**Comment by blyxxyz** [comment]
Hmm. Seems that it should be running `"$SHELL" -i` or `/bin/sh -i` by default, but instead it just assumes you've passed a specific command and crashes if you didn't.

So as a workaround you can try `uu-chroot ~/chroot /bin/sh -i`.

**Comment by NintendEthan** [comment]
running `uu-chroot ~/chroot /bin/sh -i` just causes it to complain that argument -i wasn't expected and running `uu-chroot ~/chroot /bin/sh` complains that:
 `chroot: Cannot exec: No such file or directory (os error 2)` even though the binary exists and is executable:
`$ ~/chroot/bin/sh --version`

`GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`
