### ISSUE TITLE
Implement join

### ISSUE THREAD

**Issue by vincent23** [uutils/coreutils#271]

**Comment by kuzminva** [comment]
I don't see source code of join when do a "git clone'. Does it mean it have never been reviewed and submitted to main?

**Comment by Arcterus** [comment]
Yes, because apparently the output differed from GNU's `join`, so changes were requested.  Nothing happened after that though (and it's been two years), so if someone wants to update the pull request and fix the output order I'd definitely be willing to merge the code.
