### ISSUE TITLE
[Question] Testing in the CI

### ISSUE THREAD

**Issue by m-carrasco** [uutils/coreutils#2715]
Hi,

After reading the code, I understand that all these [triples](https://github.com/uutils/coreutils#targets-that-compile) are compiled in the CI but not necessarily tested. For instance, coreutils is cross-compiled for `arm-unknown-linux-gnueabihf` but those binaries are not tested. Is this what actually happens? 

My purpose is to gain a general knowledge of how projects test their binaries for multiple architectures. 

Thanks in advance!

Kind regards,
Manuel.

**Comment by tertsdiepraam** [comment]
Hi! That is indeed what happens. A couple of different platforms are tested in the CI (Ubuntu, Mac, Windows and FreeBSD). Specifically, these architectures are tested in the CI:
- `arm-unknown-linux-gnu`
- `aarch64-unknown-linux-gnu`
- `x86_64-unknown-linux-gnu`
- `i686-unknown-linux-gnu`
- `i686-unknown-linux-musl`
- `x86_64-unknown-linux-musl`
- `x86_64-apple-darwin`
- `i686-pc-windows-gnu`
- `i686-pc-windows-msvc`
- `x86_64-pc-windows-gnu`
- `x86_64-pc-windows-msvc`
- `x86_64-unknown-freebsd`

For the other architectures, there is only a list that checks whether the utils compile: https://github.com/uutils/coreutils#targets-that-compile

Hope that answers you question (even though the response is very late 😄)

**Comment by m-carrasco** [comment]
> Hope that answers you question (even though the response is very late 😄)

Yes, it does and it is really appreciated!
