### ISSUE TITLE
Should we add a Rust jc?

### ISSUE THREAD

**Issue by chadbrewbaker** [uutils/coreutils#2756]
https://github.com/kellyjonbrazil/jc is a utility for parsing output of common CLI tools into JSON - this saves a lot of work attempting to parse with head/cut/awk/sed.

Thoughts?

Having jc would make many integration tests easier to write in the shell. The parsers could be modular for those that want something other than JSON output.

**Comment by sylvestre** [comment]
For now, the goal is to provide an

**Comment by sylvestre** [comment]
For now, the goal is to provide a dropped-in replacement of the GNU coreutils.
As we still have a lot of work to achieve that, I don't think it is reasonable to extend the initial goal.

Moreover, if users want jc, they can install jc themselves :)

So, sorry but closing
