### ISSUE TITLE
Please switch to the GPL as your software license

### ISSUE THREAD

**Issue by eyalroz** [uutils/coreutils#2757]
Hello @sylvestre , @rivy et alia,

First, congratulations on taking up the worthy endeavor of another coreutils implementations.

I would like to ask you to consider switching the license of this project to GPL.

One can have a long philosophical argument about the merit of GPL-style vs MIT/BSD-style licenses in general - and I suppose there are strong arguments from both sides - but I believe that for this kind of project, the scale is in favor of making it GPL. Among the reasons would be:

1. An MIT license would allow for differently-licensed and possibly closed-source variants. With application software, this has benefits/usefulness; for something like coreutils - such fragmentation, and the potential of weird custom coreutils with a commercial closed-source license, will IMHO have little or no benefits but will be detrimental to cross-platform usage and development work which may have to account for that.
2. It would be useful, IMHO, if the choice between Rust coreutils and GNU coreutils would not be about the license but about technical considerations.
3. Better potential, again IMHO, for cross-polination with GNU coreutils if the licenses are fully compatible or identical. More specifically: You could copy/adapt GNU coreutils code if and where appropriate (GNU coreutils can already do that in the other direction).

**Comment by sylvestre** [comment]
Hello

First, thanks for your tone. It is nicely phrased and constructive!

The license has been decided way before my time. I am 0 interest in starting a license debate (I care if the license is DFSG - Debian Free Software Guidelines) and spend time on it. I would rather use my limited time to make rust/coreutils ready for production.

Moreover, as we don't have any copyright assignment, it would be a lost of work to get sign off from everyone to relicense this software. I am pretty sure that some people have stronger feeling than I do about this!

Please also see:
https://github.com/uutils/coreutils/issues/834
https://github.com/uutils/coreutils/issues/1471

So, sorry but won't fix!

**Comment by eyalroz** [comment]
@sylvestre : Sorry for missing #834. Actually, I believe you would not need a relicensing. I will edit the opening comment of this issue to clarify what I mean.

**Comment by sylvestre** [comment]
ok, make more sense. :)

However, it would certainly trigger some conversations that I don't have time or motivation for. Sorry.

**Comment by Vaporeon** [comment]
I searched for this issue for licence clarification.
A disappointing outcome. MIT offers zero permission guarantees for second generation users of this software.

Farewell.

**Comment by sylvestre** [comment]
I locked the conversation as some uninteresting comments were made.
