### ISSUE TITLE
sed missing from coreutils?

### ISSUE THREAD

**Issue by JordyScript** [uutils/coreutils#2759]
Awesome project! Is it just me, or is sed missing from this reimplementation? I don't see it mentioned in the README, but it is my understanding that sed is part of the GNU coreutils.

**Comment by sylvestre** [comment]
sed isn't part of the coreutils:
https://www.gnu.org/software/sed/

But just like findutils, it could be reimplemented here:
https://github.com/uutils/

**Comment by Gitoffthelawn** [comment]
Would love to see `sed` implemented as a separate repo like `findutils`.

**Comment by sylvestre** [comment]
We started the work. See
https://github.com/uutils/sed/
