### ISSUE TITLE
`echo` not taking literal strings

### ISSUE THREAD

**Issue by lain-ke** [uutils/coreutils#2764]
When running `echo "Test\n"` it does what it should, output _Test_ and a line break, but when running `echo 'Test\n'` it does exactly the same thing instead of outputting _Test\n_.

**Comment by tertsdiepraam** [comment]
Hi! Thank you for the report!

I don't think that a program can do different things based on whether it's input is doubly quoted or single quoted. So my guess is that your shell is doing the expansion (are you using the `fish` shell by any chance?). By default, `echo` is not supposed to interpret escape sequences (see the [GNU manual](https://www.gnu.org/software/coreutils/manual/html_node/echo-invocation.html). If you want to escape characters you need to pass the `-e` flag to `echo`.

**Comment by lain-ke** [comment]
Oh, sorry for my lack of knowledge! 
Thanks for your answer.
BTW my shell is `ksh` on OpenBSD.
