### ISSUE TITLE
ls: Improve Error Handling

### ISSUE THREAD

**Issue by kimono-koans** [uutils/coreutils#2785]
I've been trying to improve the error handling of 'ls' and have made some progress in describing and printing the errors, but I'm stuck trying to understand how/when uucore decides to print an error message.  All stderr messages print before stdout messages, which is undesirable for 'ls.'  

What is the best way to get interleave stdout and stderr output like GNU ls?

I'm sure this is a rookie mistake, but @tertsdiepraam could you assist?

**Comment by tertsdiepraam** [comment]
Hi! I confirmed the behaviour that you described. I don't think the uucore error functions contribute to this problem. There is a loop like this (simplified a bit), which I think is the culprit of this:

```rust
for loc in &locs {
    let p = PathBuf::from(loc);
    let path_data = PathData::new(p, None, None, &config, true);

    if path_data.md().is_none() {
        show_error!(
            "cannot access {}: No such file or directory",
            path_data.p_buf.quote()
        );
        set_exit_code(1);
        continue;
    }
    files.push(path_data);
}
sort_entries()
display_entries()
```
(see [here](https://github.com/uutils/coreutils/blob/f2f582aa142f4b719fc4fe9032930fae163c56ef/src/uu/ls/src/ls.rs#L1300-L1329) for the full loop)

After which the files get sorted and only afterwards get printed. `show_error` is simply a an `eprintln` which prepend the name of the util, so these are equivalent:
```rust
eprintln("ls: {}", "error");
show_error("{}", "error");
```

For more information on the error handling, you could take a look at the [documentation](https://docs.rs/uucore/0.0.10/uucore/error/index.html) or just post your questions here.

**Comment by tertsdiepraam** [comment]
> understand how/when uucore decides to print an error message.

I guess I should expand on this a little bit. If an error is passed to `show_error`, it is printed immediately. The only "magic" thing that happens is that errors that are returned from `uumain` a printed at the end (this is done by the `gen_uumain` proc macro, the source of which is [here](https://docs.rs/uucore_procs/0.0.7/src/uucore_procs/lib.rs.html#89-116))

**Comment by kimono-koans** [comment]
Thanks.  "What 'magic'?" was exactly the information I was wondering about.  I tried rewriting certain ingest procedures as iterative and still didn't have any luck, and became convinced there was some magic.  I'll check back if I need any further help.

**Comment by kimono-koans** [comment]
Thank you!  The level of magic was exactly what I was wondering about.  I think I tracked it down -- looks like we just need to do a buffer flush after an item is displayed!

**Comment by tertsdiepraam** [comment]
I think has been resolved by https://github.com/uutils/coreutils/pull/2809
