### ISSUE TITLE
Move to Clap 3

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#2838]
We've been waiting for this for a long time: Clap 3 has been released ([announcement](https://epage.github.io/blog/2021/12/clap3/))!

I think we can start porting the utils to Clap 3. Now, this *should* be fairly simple. However, some flags have changed meaning so we should test the changes thoroughly, especially with some complex arguments.

One of the features that we've been waiting for is [`AppSettings::InferLongArgs`](https://docs.rs/clap/latest/clap/enum.AppSettings.html#variant.InferLongArgs) which should be turned on for (almost?) all utils to match GNU behaviour. Glancing the docs, I think the `wrap_help` and `cargo` features should be enabled by default for all utils.

Before porting a util, please be sure to check out the [Clap 2 to 3 migration guide](https://github.com/clap-rs/clap/blob/v3.0.0/CHANGELOG.md#migrating) in the changelog.

Clap now also has the derive feature. We could try this out with some smaller utils, but we should only use this if we can fully match the functionality of the builder API.

# Resources
- [Documentation](https://docs.rs/clap/latest/clap/)
- [Migration guide](https://github.com/clap-rs/clap/blob/v3.0.0/CHANGELOG.md#migrating)

**Comment by sylvestre** [comment]
@tertsdiepraam did you try to port one ?
thanks

**Comment by tertsdiepraam** [comment]
Not yet. I have exams coming up but after that I hope to port a few

**Comment by tertsdiepraam** [comment]
I've just realized this is slightly more complicated than I thought. Because we call the clap apps from the utils in the `coreutils` binary, all clap versions must be the same, so we have to do all of them at the same time...

I think the best way to do this is to open a separate branch and update them there.

**Comment by sylvestre** [comment]
Bravo for this achievement :)
