### ISSUE TITLE
Base16?

### ISSUE THREAD

**Issue by QMHTMY** [uutils/coreutils#2860]
I'm wondering if it is possible to add a base16?

**Comment by sylvestre** [comment]
Can you please why ?
thanks

**Comment by tertsdiepraam** [comment]
If you need `base16` encoding, you can use `basenc --base16`. So you can create an alias in your shell like this
```bash
alias base16="basenc --base16"
```

**Comment by QMHTMY** [comment]
Thanks! @tertsdiepraam
