### ISSUE TITLE
seq: eliminate special handling of -0.0

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#2870]
The `seq` program contains a lot of code for representing and displaying floating point negative zero (`-0.0f32`, for example). It should be possible to eliminate some of this code once the minimum supported version of Rust reaches v1.52.0 or greater. See the comments in pull request #2698 for more information.

Pull request #2869 proposes increasing the minimum version to v1.54.0, so that would allow this change.

See https://github.com/rust-lang/rust/pull/78618 for information on the relevant feature of Rust.

**Comment by tertsdiepraam** [comment]
The MSRV is now 1.54, so this is unblocked.

**Comment by palaster** [comment]
This can be closed because of this #3056
