### ISSUE TITLE
Update the time crate to 0.3

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2884]
We are currently using 0.1 and it has some issues.
We should update to version 0.3

Must be updated at least in these crates:
```
Cargo.toml
src/uu/install/Cargo.toml
src/uu/touch/Cargo.toml
src/uucore/Cargo.toml
```

**Comment by tertsdiepraam** [comment]
Some interesting context here: `time` has a vulnerability in version 0.1, see:
- https://rustsec.org/advisories/RUSTSEC-2020-0071.html
- https://github.com/uutils/coreutils/pull/2879

I also wonder whether this security issue might be related to
- https://github.com/uutils/coreutils/issues/1750

At least it's worth checking whether that last issue is fixed once we have upgraded.

**Comment by g-k** [comment]
Started looking for migration docs for this. The [changelog](https://github.com/time-rs/time/blob/main/CHANGELOG.md) says versions before 0.2.7 are in release notes and [the oldest release with notes is 0.2.0](https://github.com/time-rs/time/releases?page=4) which refs https://github.com/time-rs/time/issues/190.

**Comment by tertsdiepraam** [comment]
So, I also started searching, found their book, and got excited when I found this page: https://time-rs.github.io/book/migration/0.3.html

But it's empty 😄 Looks like we just have to rely on the documentation and tests for this migration.

![image](https://user-images.githubusercontent.com/11643477/150654612-52fb1260-f4f2-4417-ba7f-6f258fb123c8.png)

**Comment by sylvestre** [comment]
cargo audit:

```
Crate:         time
Version:       0.1.43
Title:         Potential segfault in the time crate
Date:          2020-11-18
ID:            RUSTSEC-2020-0071
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:      Upgrade to >=0.2.23

```

**Comment by g-k** [comment]
OK! I started working on this and have `fsext.rs` in uucore updated.

coreutils uses the [`time::tm`](https://docs.rs/time/0.1.43/time/struct.Tm.html) for times and [`time::Timespec`](https://docs.rs/time/0.1.43/time/struct.Timespec.html) timestamps. [Per this comment](https://github.com/time-rs/time/issues/190#issuecomment-557258376) they were removed in time >0.1.

I'm going to switch the places coreutils relies on those structs to [chrono](https://docs.rs/chrono/0.4.19/chrono/), which is "aims to be a feature-complete superset of the time library" and coreutils already uses elsewhere but it'll likely require some changes to non-test code in `touch`.

**Comment by sylvestre** [comment]
@g-k are you still working on it? thanks

**Comment by g-k** [comment]
I'd like to finish this but I haven't worked on it recently. Other people should feel free to finish it.

I started working on this in https://github.com/uutils/coreutils/compare/main...g-k:2884-time-0.3?expand=1 running with `RUSTFLAGS="--cfg unsound_local_offset"`. That branch also includes changes to stop using chrono to fix the CVE, but fixing that might be better to fix in a separate PR. The chrono team is working on or fixed the issue, so maybe it's easier to do both now. I also think the unsoundness from the CVE is unlikely to impact utils in this project, since I don't think the utils are multithreaded or run long enough to see changes to the relevant env vars.

**Comment by sylvestre** [comment]
> I'd like to finish this but I haven't worked on it recently. 

Do you have an eta? :)
