### ISSUE TITLE
uucore(memo): replace calls err_conv() with use of Result

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#2917]
Replace calls to the `err_conv()` function, which calls `std::process:exit()`, with uses of `Result` instead:

https://github.com/uutils/coreutils/blob/f1dde86f9bb49887ac26093f1fc70410749d4243/src/uucore/src/lib/features/tokenize/sub.rs#L23-L26

This would make it possible for calling code (like `printf`) to decide how to handle errors.

**Comment by ndd7xv** [comment]
Hello! Is it OK if I work on this?

**Comment by tertsdiepraam** [comment]
Yeah, go ahead!

**Comment by jfinkels** [comment]
Fixed by #3112.
