### ISSUE TITLE
ls: add support for `--zero` option

### ISSUE THREAD

**Issue by jtracey** [uutils/coreutils#2929]
GNU's `ls` now supports a `--zero` option, where line endings are null bytes instead of newlines. This feature is tested in the `tests/ls/zero-option` GNU test.

**Comment by tertsdiepraam** [comment]
For reference, the description from the GNU docs:
```
‘--zero’
    Output a zero byte (ASCII NUL) at the end of each line, rather than a newline.
    This option enables other programs to parse the output even when that output
    would contain data with embedded newlines. This option is incompatible with
    the --dired (-D) option. This option also implies the options --show-control-chars,
    -1, --color=none, and --quoting-style=literal (-N).
```
Source: https://www.gnu.org/software/coreutils/manual/html_node/General-output-formatting.html
