### ISSUE TITLE
conflicting names with built-in Windows programs

### ISSUE THREAD

**Issue by jftuga** [uutils/coreutils#2952]
These Windows programs have naming conflicts with `uutils/coreutils`:

* `C:\Windows\system32\hostname.exe`
* `C:\Windows\system32\more.com`
* `C:\Windows\system32\sort.exe`
* `C:\Windows\system32\whoami.exe`
* `date` -  built into `cmd.exe`
* `echo` - built into `cmd.exe`
* `mkdir` - built into `cmd.exe`

Since you typically want `C:\Windows\system32` to be one of the first entries in your `PATH`, this will create a conflict when copying `coreutils.exe` to `sort.exe` and also when trying to use `echo.exe` since it is built into `cmd.exe`. -- *as well as the other programs listed*

In the past, I resolved this by renaming other versions of similar programs distributed by [UnxUtils](http://unxutils.sourceforge.net/) to `gsort.exe`, `gecho.exe`, etc.  I simply chose the `g` prefix as shorthand for `gnu`. I tried doing this for `uutils/coreutils` by copying `coreutils.exe` to `gsort.exe` for example, but understandably the program did not run as expected.

I am wondering if something could be done to address this conflict.  A fix does not necessarily have to allow for `coreutils.exe` programs to be correctly run if they start with a `g` prefix.  Any letter would do but I am also open to other solutions as well.

Thank you for your time.

**Comment by tertsdiepraam** [comment]
If you install the utils with make you can give it a prefix:
```
make PROG_PREFIX=PREFIX_GOES_HERE install
```
So you could give it the prefix `u` for instance by doing
```
make PROG_PREFIX=u install
```
 Does that solve your issue?

All the utils should also still work when you rename them, though, if you have them compiled separately. So renaming `sort.exe` to `usort.exe` wouldn't be a problem. With the multicall binary you'd need to set some alias in your shell (I'm not sure how do to that on Windows)

**Comment by tertsdiepraam** [comment]
For example, here I have built `ls.exe` for Windows, and renamed it manually to `uls.exe` (on Linux using Wine, but should work on Windows as well):
```shell
target/x86_64-pc-windows-gnu/debug
❯ ./ls.exe
build  deps  examples  incremental  libuu_ls.d  libuu_ls.rlib  ls.d  ls.exe

target/x86_64-pc-windows-gnu/debug
❯ mv ls.exe uls.exe

target/x86_64-pc-windows-gnu/debug
❯ ./uls.exe
build  deps  examples  incremental  libuu_ls.d  libuu_ls.rlib  ls.d  uls.exe
```

**Comment by jftuga** [comment]
I was just using the prebuilt binaries provided under [releases](https://github.com/uutils/coreutils/releases).

I will try your suggestion and report back my results.  Thank you for looking into this.

**Comment by tertsdiepraam** [comment]
It will build individual binaries, so it should work!

**Comment by tertsdiepraam** [comment]
That looks like the prefix didn't work, right? I'll look into that

**Comment by jftuga** [comment]
> That looks like the prefix didn't work, right? I'll look into that

No, after renaming the files, they work as expected.
