### ISSUE TITLE
test_test::test_file_is_not_executable - fails on WSL

### ISSUE THREAD

**Issue by water-ghosts** [uutils/coreutils#2958]
`test_test::test_file_is_not_executable` expects the command `test ! -x regular_file` to succeed. The test assumes that a new file will be non-executable, but that assumption does not hold on Windows Subsystem for Linux. When WSL interacts with the Windows file system, new files **are** executable, so `touch new_file && test ! -x new_file` exits with status code 1. This "feature" of WSL is discussed here: https://github.com/Microsoft/WSL/issues/936

I'm not sure if it's worth fixing this, since it's an edge case that only affects the tests, not the utility itself. But I did run into this while trying to test the code locally, and it took me a while to track down, so it's at least a source of confusion. If nothing else, it might be worth highlighting this in a comment or documentation for other contributors using WSL,

**Comment by bolshoytoster** [comment]
@water-ghosts because microsoft is unlikely to change this, the best workaround would probably be to just add `#[cfg(not(windows))]` to the `test_test::test_file_is_not_executable` test.

**Comment by tertsdiepraam** [comment]
> the best workaround would probably be to just add #[cfg(not(windows))] to the test_test::test_file_is_not_executable test.

I agree, sounds like the util is behaving correctly here. However, if this only occurs in WSL and not Windows itself it should probably be checked with the `uucore::os::is_wsl1` or `uucore::os::is_wsl2` macros. @water-ghosts do you happen to know whether this occurs on both WSL versions?

**Comment by bolshoytoster** [comment]
@tertsdiepraam 
> do you happen to know whether this occurs on both WSL versions?

I believe it would occur on both versions since it's an issue with NTFS.

**Comment by tertsdiepraam** [comment]
Thanks! I'll try to make a PR to fix this.
