### ISSUE TITLE
`test_ls_long` has become flaky

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#2969]
Examples:
```
 ---- test_ls::test_ls_long stdout ----
current_directory_resolved: 
touch: /tmp/.tmpV9Ajtt/test-long
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls -l test-long
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --long test-long
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --l test-long
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils ls --format=long test-long
thread 'test_ls::test_ls_long' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Other, message: "Bad file descriptor" }', library/std/src/process.rs:1828:21
```
From https://github.com/uutils/coreutils/runs/4997142203?check_suite_focus=true

```
 ---- test_ls::test_ls_long stdout ----
current_directory_resolved: 
touch: /tmp/.tmp7l53Co/test-long
run: /target/x86_64-unknown-linux-gnu/debug/coreutils ls -l test-long
run: /target/x86_64-unknown-linux-gnu/debug/coreutils ls --long test-long
run: /target/x86_64-unknown-linux-gnu/debug/coreutils ls --l test-long
run: /target/x86_64-unknown-linux-gnu/debug/coreutils ls --format=long test-long
run: /target/x86_64-unknown-linux-gnu/debug/coreutils ls --for=long test-long
thread 'test_ls::test_ls_long' panicked at ''lr-x------ 1 1001 121 64 Jan 30 ' does not contain '-rw-rw-r--'', tests/common/util.rs:386:9
```
From https://github.com/uutils/coreutils/runs/4997006061?check_suite_focus=true

I could have something to do with https://github.com/uutils/coreutils/pull/2936

**Comment by sylvestre** [comment]
`Bad file descriptor` very useful :)

**Comment by tertsdiepraam** [comment]
@sylvestre I have a hypothesis for this, but I don't really know whether it makes sense and how to fix it:

`test_ls_long` uses `umask` to get reproducible results for the permissions. Is it possible that this interferes with similar `umask` calls in other tests? That is, the permissions of the process are changed by another thread running another test. I think this would explain the second example.

To fix this, I could change it to a regex check instead of checking the exact permissions? The first failure has me stumped though :)

**Comment by sylvestre** [comment]
yeah, it might be the case. Relaxing the test sounds great!
