### ISSUE TITLE
cp: Suffix parsing inconsistencies between GNU and uutils

### ISSUE THREAD

**Issue by water-ghosts** [uutils/coreutils#2985]
```
touch file
cp --suffix -v file new
```

Possibly related to #2535, GNU parses this as "use the suffix `-v`", while uutils parses this as two separate flags. GNU successfully creates a new file called `new-v`, but uutils fails with the message `error: The argument '--suffix <SUFFIX>' requires a value but none was supplied`.

**Comment by tertsdiepraam** [comment]
Thanks for reporting this! The linked PR should fix it
