### ISSUE TITLE
cp: -t overwrites data if called with a file, not a directory

### ISSUE THREAD

**Issue by water-ghosts** [uutils/coreutils#2986]
```
printf '123' > file
printf '456' > dir
cp -t dir file && cmp dir file
```

`cp -t` expects two arguments: a directory to copy into, and a file to copy. If the first argument is a directory, uutils has the correct behavior. If the first argument is a file, GNU will detect this and fail with the message `cp: target 'dir' is not a directory`, but uutils will erase the data in `dir` and replace it with a copy of `file`. Effectively, uutils treats `cp -t first second` as equivalent to `cp second first` if `first` and `second` are both files.

**Comment by shoriminimoe** [comment]
I created #3027 to address this. 

Using the example from the issue description:
```sh
$ printf 123 >file
$ printf 456 >dir
$ ./target/debug/coreutils cp -t dir file
error: Invalid value for '--target-directory <target-directory>': must specify a directory

For more information try --help
$ cmp file dir
file dir differ: byte 1, line 1
```
