### ISSUE TITLE
cp: Support directory overwrites with "-drT"

### ISSUE THREAD

**Issue by water-ghosts** [uutils/coreutils#2987]
```
mkdir dir
mkdir dir2
test -d dir && cp -drT dir dir2
```

GNU copies `dir`, so all files that existed in `dir` now also exist in `dir2`. uutils fails with the message: `cp: cannot overwrite directory 'dir2' with non-directory`, even though `dir` is in fact a directory.

**Comment by water-ghosts** [comment]
Digging into this a bit further, `-d` is an alias for `--no-dereference --preserve=links`, and it's the `--preserve=links` argument that makes the difference here. `cp -rT --preserve=links dir dir2` succeeds on GNU and fails on uutils. `--no-dereference` has no effect.

**Comment by cakebaker** [comment]
Closing this ticket as I think this issue is fixed and there is no longer an error message. Unfortunately, there is still an issue with `-rT` I described in https://github.com/uutils/coreutils/issues/5457
