### ISSUE TITLE
`expr` doesn't have any help

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2988]
https://uutils.github.io/coreutils-docs/user/utils/expr.html is empty

**Comment by hbina** [comment]
Do you want to just copy the description from GNU for these?

**Comment by sylvestre** [comment]
no, please use the BSD's wording :)

**Comment by crazystylus** [comment]
I have used the same wording from this section [expr.rs](https://github.com/uutils/coreutils/blob/main/src/uu/expr/src/expr.rs#L81) of code for consistency.
Please let know if any changes need to made the wordings.
