### ISSUE TITLE
`false` help page could be improved

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#2989]
https://uutils.github.io/coreutils-docs/user/utils/false.html
at least a description + the version number

**Comment by ndd7xv** [comment]
Hello! May I please take this issue?

**Comment by rivy** [comment]
Sure! Step right up... 😃

**Comment by ndd7xv** [comment]
I see that someone completed a more comprehensive PR that fixes this issue, so I'll see if there's another PR that I can address.
