### ISSUE TITLE
Disable serde feature of exacl once a new version is released

### ISSUE THREAD

**Issue by bjorn3** [uutils/coreutils#3004]
This should improve build times a bit. See https://github.com/byllyfish/exacl/pull/97.

**Comment by tertsdiepraam** [comment]
Looking at the [current version](https://github.com/byllyfish/exacl/blob/87a3ad283a3edef8970c55e5c3c770bff8886ff7/Cargo.toml) of `exacl`, `serde` is not longer enabled by default, so this issue has resolved itself.
