### ISSUE TITLE
dd: should allow multiple instances of arguments but doesn't

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3009]
GNU dd
```
$ printf '' | dd status=none status=noxfer
0+0 records in
0+0 records out
```

uutils dd
```
$ printf '' | ./target/debug/dd status=none status=noxfer
error: The argument '--status=<LEVEL>' was provided more than once, but cannot be used multiple times

USAGE:
    dd [OPTIONS]

For more information try --help
```

This issue appears in a test case in the GNU test suite file `tests/dd/misc.sh`.

**Comment by tertsdiepraam** [comment]
For anyone is interested in picking this up: we usually solve this using clap's [`AppSettings::AllArgsOverrideSelf`](https://docs.rs/clap/latest/clap/enum.AppSettings.html#variant.AllArgsOverrideSelf) or passing the arguments themselves to [`Arg::overrides_with`](https://docs.rs/clap/latest/clap/struct.Arg.html#method.overrides_with)

**Comment by iovanom** [comment]
Can I try to take this as my first issue?

**Comment by tertsdiepraam** [comment]
Sure! Go ahead!

**Comment by iovanom** [comment]
I've added the PR for this issue.
