### ISSUE TITLE
dd: does not respect -- as an option list delimiter

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3010]
The GNU version of dd supports using `--` as a delimiter in the option list; see https://www.gnu.org/software/coreutils/manual/html_node/Common-options.html. The uutils version of dd does not seem to respect that delimiter with its positional arguments.

GNU dd:
```
$ printf "" | dd -- of=outfile
0+0 records in
0+0 records out
0 bytes copied, 7.754e-05 s, 0.0 kB/s
```

uutils dd:
```
$ printf "" | ./target/debug/dd -- of=outfile
error: Found argument '--of=outfile' which wasn't expected, or isn't valid in this context

        If you tried to supply `--of=outfile` as a value rather than a flag, use `-- --of=outfile`

USAGE:
    dd [OPTIONS]

For more information try --help
```

This is causing a failure in one of the GNU test cases in `tests/dd/misc.sh`.

**Comment by tertsdiepraam** [comment]
I believe this can be done in clap by setting [`AppSettings::TrailingVarArg`](https://docs.rs/clap/latest/clap/enum.AppSettings.html#variant.TrailingVarArg). There is also `Arg::last` but that *requires* the use of `--`.

**Comment by tertsdiepraam** [comment]
Okay my previous comment was way off :). `dd` has a weird set of arguments. It has only two flags (`--help` and `--version`) and the rest of the arguments are positional in the format `flag=value`. The way that we deal with this is clever but strange. Essentially, we loop over all arguments and put `--` in front of them and then let clap do the parsing. This mostly works, but there are a few weird effects. First of all, everything after `--` must be a positional argument, so we don't get the right argument parsing. Additionally, it leads to weird error messages like this, where clap reports the arguments with `--`, even though those are not present:
```
❯ cargo run --features unix -- dd ofsdf=outfile
error: Found argument '--ofsdf' which wasn't expected, or isn't valid in this context

        Did you mean '--of'?

        If you tried to supply `--ofsdf` as a value rather than a flag, use `-- --ofsdf`

USAGE:
    --dd --of=<FILE>

For more information try --help
```
So ultimately, I think we should move away from this weird parsing to some custom parsing.
