### ISSUE TITLE
Conflicting recommended VS Code extensions

### ISSUE THREAD

**Issue by Toxaris** [uutils/coreutils#3017]
I opened the repository for the first time in VS Code and installed all recommended extensions. Then I got the following warning:

![image](https://user-images.githubusercontent.com/961451/151974901-00438bc7-3ac3-449d-9587-eacef8215f1f.png)

The comments in the `.vscode/extensions.json` suggest that I can use them together:

https://github.com/uutils/coreutils/blob/a764fdfb8e35e3307d89fc451ae93c8e90e5deaa/.vscode/extensions.json#L5-L8

Should I choose one of these extensions? Which?

**Comment by sylvestre** [comment]
Rust analyzer is amazing!

**Comment by Toxaris** [comment]
Cool. I can send a PR against the `extensions.json`.

**Comment by tertsdiepraam** [comment]
That would be great!
