### ISSUE TITLE
`basenc`, `base64` and `base32` have an `ABOUT` that's formatted differently than the other utils.

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#3022]
For example:
```rust
static ABOUT: &str = "
 With no FILE, or when FILE is -, read standard input.

 When decoding, the input may contain newlines in addition to the bytes of
 the formal alphabet. Use --ignore-garbage to attempt to recover
 from any other non-alphabet bytes in the encoded stream.
";
```
should be:
```rust
// Note the backslash here to remove the first newline
//                    |
//                    V
static ABOUT: &str = "\
With no FILE, or when FILE is -, read standard input.

When decoding, the input may contain newlines in addition to the bytes of
the formal alphabet. Use --ignore-garbage to attempt to recover
from any other non-alphabet bytes in the encoded stream.
";
```

The difference is the backslash and leading spaces.

Discovered here: https://github.com/uutils/coreutils/pull/3014#issuecomment-1027175034

**Comment by RishiKumarRay** [comment]
so we have to just add the backslash?

**Comment by tertsdiepraam** [comment]
And remove the leading spaces, but yes, it's very straightforward!

**Comment by RishiKumarRay** [comment]
@tertsdiepraam can you assign me , I would like raise PR for this?

**Comment by tertsdiepraam** [comment]
You can just open the PR with the text "Closes #3022" in the description and it will show up as a PR that closes this issue

**Comment by RishiKumarRay** [comment]
@tertsdiepraam i cannot see any leading space here in the code , which space you are talking about

**Comment by tertsdiepraam** [comment]
```rust
static ABOUT: &str = "
 With no FILE, or when FILE is -, read standard input.
```
The spaces at the start of each line. The `static` and `With` don't line up. The same goes for the other lines.

**Comment by tertsdiepraam** [comment]
Ah you already got it, nice!

**Comment by RishiKumarRay** [comment]
thanks,  got it , please review this PR @tertsdiepraam
