### ISSUE TITLE
`realpath` should not accept symlinks to non-existent absolute paths

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#3036]
Minimal reproducible code:

```shell
❯ ln -s /this/file/does/not/exist foo

# GNU
❯ realpath foo
realpath: foo: No such file or directory

# uutils
❯ realpath foo
/this/file/does/not/exist
```

Discovered by @hbina on [discord](https://discord.com/channels/563860080668442635/938409071080529920/938411738804662273)

**Comment by hbina** [comment]
This is caused by PathBuf replacing the entire path with the absolute path provided by the symlink. I think the solution is to simply use a Vec of paths, then collect them at the end, because we clearly do not want this behavior.

See: https://doc.rust-lang.org/stable/std/path/struct.PathBuf.html#method.push

**Comment by tertsdiepraam** [comment]
I'm not sure that's the solution. As far as I can tell, `resolve` is doing its job just fine and even returning an error. It seems like `canonicalize` is discarding the error:
```rust
match resolve(&result) {
    Err((path, _)) if miss_mode == MissingHandling::Missing => result = path,
    Err((_, e)) => return Err(e),
    Ok(path) => {
        result = path;
    }
}
```

**Comment by tertsdiepraam** [comment]
I think it should only discard the error if the `path` is the same as `result` (i.e. no symlinks have been followed)

**Comment by hbina** [comment]
`resolve` actually does not fail here, `fs::read_link` will happily return the symlink path. There should simply be another check before finally returning the result.

**Comment by tertsdiepraam** [comment]
That happens automatically because of the loop. It will call `symlink_metadata`, then that will return an error
