### ISSUE TITLE
df: fails to print filesystem when argument is .

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3065]
`df` is able to find my root filesystem if I run it without any other arguments:
```
$ ./target/debug/df | grep ubuntu
/dev/mapper/vgubuntu-root 248618848256  94480936960 154137911296   38% /               
```
but if I run `df .`, it does not print my root filesystem
```$ ./target/debug/df .
Filesystem          1k-blocks         Used    Available  Use% Mounted on 
```
Contrast this with GNU df:
```
$ df .
Filesystem                1K-blocks     Used Available Use% Mounted on
/dev/mapper/vgubuntu-root 242791844 92266552 138122400  41% /
```

**Comment by crazystylus** [comment]
I think there is more to this issue. I have verified, if I have a disk mounted at `/root` and I have a folder `/root/docs` then `df /root/docs` should print the details `/root`. And similarly if docs folder doesn't exist, it should pop an error No such file or directory.

But in both cases output here is empty
