### ISSUE TITLE
`shuf` utility is not really random

### ISSUE THREAD

**Issue by salsifis** [uutils/coreutils#3098]
I compiled `coreutils` on Windows with `cargo +nightly install coreutils`.

Then I downloaded a list of English words, which is a text file in which lines are sorted in lexicographical order. Line endings are `\n` if that helps, file is pure ASCII, and contains 84099 lines.

When I run `coreutils shuf -n 15 dictionary.txt` multiple times, I observe a pattern. Here are four distinct outputs of this command :

```
run 1          + run 2         + run 3         + run 4
SEMPITERNAL    | OBJECTS       | STOCKPILED    | RAMSGATE
RECRIMINATIONS | HERACLEIDAN   | RITORNELL     | ASSESSORSHIPS
MECHANICALS    | DANDILY       | CHARMLESS     | CUPCAKES
HYLOISTS       | GRATULATION   | LYME          | NIGERIA
ETYMOLOGISES   | CURRENCY      | COTELETTES    | CONSIGNIFY
FRICASSEE      | CORELLAS      | BLEPHAROSPASM | FLITTER
APOSTOLISED    | ATELIERS      | ALGUAZIL      | CHAMAELEONS
BRACKET        | COMPULSION    | BLUNKETT      | BLURBS
ANNOUNCER      | BADMAN        | ASEPTATE      | ANGLEPOISES
ABAND          | ABSOLUTELY    | BARRETOR      | ASSIBILATING
ACTUARY        | ARAFAT        | ALBINESS      | ALLOMORPH
ANONYMOUS      | ANTIQUARIANS  | ABLATORS      | ANTIMODERNISTS
ALBUMENIZE     | ACCURSEDNESS  | ADEEMS        | ALIMENT
AGGRESSING     | ACCOMPLISHES  | ALARUMING     | ABELIA
ABSTEMIOUSNESS | ADDITIONS     | ABERRATION    | ABYSSOPELAGIC
```

As is observable:
* The first outputted lines seem to be random
* The following lines have a high probability to begin with an A or a B.
It seems that the probability to choose a word from the beginning of the input file increases with time. But that’s not the case. If I run with longer output (30) I can observe a mix of words from the very beginning of the file and the very end:

```
BEFRINGED
ADDICT
HYDROPHYTONS
EMBOUCHURES
DESCENSIONS
DISPROPORTIONALLY
BLOODSTREAM
CICINDELA
APPULSE
AFRIKAANS
AMARYLLIDACEAE
ACHIEVE
ADMONITOR
ALERTING
ACCOSTING
ADMINICLES
ABRAXASES
ABUSAGES
ABDICATIONS
ABSCONDENCES
ABANDONEDLY
ABBREVIATIONS
ZYMOLOGICAL
AARONICAL
ABAND
ZYMOID
AARDWOLVES
ZYMITE
ABA
AARDVARK
```

**Comment by tertsdiepraam** [comment]
Very interesting! Thank you for the report! It looks like it's doing its own mapping from `usize` into the range `(0, len(input)-1)`, which doesn't work correctly. Instead it should probably just use the [`gen_range`](https://docs.rs/rand/latest/rand/trait.Rng.html#method.gen_range) function from `rand`.

**Comment by anastygnome** [comment]
> Very interesting! Thank you for the report! It looks like it's doing its own mapping from `usize` into the range `(0, len(input)-1)`, which doesn't work correctly. Instead it should probably just use the [`gen_range`](https://docs.rs/rand/latest/rand/trait.Rng.html#method.gen_range) function from `rand`.

Maybe #3001 could help
