### ISSUE TITLE
wc: incorrect field alignment and width when file and stdin input

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3105]
`wc` fails to indent appropriately when there is a single column of counts with multiple rows of input, one of which represents input from stdin. 

uutils wc:
```
$ (printf 'aa' > infile) && (printf 'bbbbbbbbbb' | ./target/debug/wc -c infile -)
2 infile
10 -
12 total
```

GNU wc:
```
$ (printf 'aa' > infile) && (printf 'bbbbbbbbbb' | wc -c infile -)
      2 infile
     10 -
     12 total
```

Note this indentation should not happen when stdin is not one of the input files:
```
$ (printf 'aa' > infile) && (wc -c infile infile )
2 infile
2 infile
4 total
```

**Comment by jfinkels** [comment]
Also, note that the counts should be aligned right, regardless of whether stdin is one of the input files.

GNU wc:
```
$ (printf 'aa' > f1) && (printf 'bbbbbbbbbb' > f2) && wc -c f1 f2
 2 f1
10 f2
12 total
```

uutils wc:
```
$ (printf 'aa' > f1) && (printf 'bbbbbbbbbb' > f2) && ./target/debug/wc -c f1 f2
2 f1
10 f2
12 total
```

**Comment by tertsdiepraam** [comment]
That is a good point, this shouldn't be understood as indentation, but right aligning values where am arbitrary width is chosen for the stdin, because we don't know how big the counts of stdin and the files after stdin are when printing the first files.

**Comment by emrebayrm** [comment]
Hi, I have been checking the issue, I found that this change would be enough. but there was a comment that seems like it was done intentionally and commented by @jfinkels, I guess. can you provide the reason/requirement about this if statement.
`
diff --git a/src/uu/wc/src/wc.rs b/src/uu/wc/src/wc.rs
index a07877e0..6efb18cc 100644
--- a/src/uu/wc/src/wc.rs
+++ b/src/uu/wc/src/wc.rs
@@ -487,7 +477,7 @@ fn wc(inputs: &[Input], settings: &Settings) -> UResult<()> {
     //
     // If we only need to display a single number, set this to 0 to
     // prevent leading spaces.
-    let max_width = if settings.number_enabled() <= 1 {
+    let max_width = if settings.number_enabled() < 1 {
         0
     } else {
         max_width(inputs)
`

**Comment by jfinkels** [comment]
The comment says it:
```
     // If we only need to display a single number, set this to 0 to
     // prevent leading spaces.
```
Contrast the output when displaying three columns vs. displaying one column:
```
$ printf "%0.sa" {1..1000} > infile
$ wc infile
   0    1 1000 infile
$ wc -c infile
1000 infile
```

**Comment by cakebaker** [comment]
It seems to have been fixed in the meantime as the examples work fine, hence I close this ticket.
