### ISSUE TITLE
"clean" target calls itself recursively

### ISSUE THREAD

**Issue by kevinburke** [uutils/coreutils#3114]
On my machine the "clean" target tries to cd in to the docs directory and run "make clean". However there's no "clean" target in the Makefile and no GNUMakefile in that directory. As a result make and gmake get stuck in a recursive loop which ends up crashing my terminal.

**Comment by tertsdiepraam** [comment]
That's unfortunate, I'll make a clean target for the docs.

This also made me wonder, are we using any GNU extensions to make or can we use a regular Makefile?
