### ISSUE TITLE
chmod: fails to enable read mode bit with -R option

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3118]
uutils chmod fails to assign the requested mode bits when the `-R` option is given. For example:
```sh
$ mkdir -p a/b
$ chmod a-r a/b  # using GNU chmod to ensure these two lines work
$ chmod a-r a
$ ./target/release/chmod -R u+r a  # using uutils chmod
$ ls -ld a a/b
drwx-wx--x 3 jeffrey jeffrey 4096 Feb 11 21:50 a
d-wx-wx--x 2 jeffrey jeffrey 4096 Feb 11 21:50 a/b
```
Notice that the `a/b` directory does not have the "read" bit set, even though we requested that it be enabled.

When I replace the `/target/release/chmod -R` command with GNU `chmod -R`, I get the following output:
```
drwx-wx--x 3 jeffrey jeffrey 4096 Feb 11 21:51 a
drwx-wx--x 2 jeffrey jeffrey 4096 Feb 11 21:51 a/b
```
as expected.

(A call to `chmod -R u+rwx` appears in the GNU test suite setup file `tests/init.sh`, so this issue is causing at least one other test to fail that I know about [`tests/mkdir/p-3.sh`]. You can work around this issue by changing `chmod` to `/usr/bin/chmod` in the `tests/init.sh` file.)

**Comment by benkwokcy** [comment]
This might be fixed, I followed the commands and the read bit was set using coreutils.

**Comment by jfinkels** [comment]
Cool, thanks for checking up on it. And it looks like the GNU test file `tests/mkdir/p-3.sh` is currently passing as well. Closing as fixed.
