### ISSUE TITLE
Update the onig crate to 6.3.1?

### ISSUE THREAD

**Issue by alextibbles** [uutils/coreutils#3125]
coreutils expr is reported[1] as using out-dated onig:
`onig = "~4.3.2"`
Major version is now 6[2].

https://github.com/uutils/coreutils/commit/e977e29d6a6cc1eec1d6230e9167c325cf37353f references avoiding a dependency on rust 1.31+. According to README, rust 1.54+ is required by coreutils, so this seems

Suggest that the dependency moves to ~6.3. Are there any issues with this approach?

[1] https://deps.rs/repo/github/uutils/coreutils
[2] https://docs.rs/onig/latest/onig/index.html

**Comment by sylvestre** [comment]
I think we can give it a try. @alextibbles do you want to give it a try?

**Comment by alextibbles** [comment]
There were some dependency changes in onig onig_sys and its usage of bindgen which complicated this.
https://github.com/uutils/coreutils/pull/3136
