### ISSUE TITLE
`b2sum` is missing

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#3162]
GNU has the `b2sum` utility to check BLAKE2 digests ([docs](https://www.gnu.org/software/coreutils/manual/html_node/b2sum-invocation.html#b2sum-invocation)) and we don't have it yet.

Utilities that check digests are generated from `hashsum` in `build.rs`. We already support the `--b2sum` flag for `hashsum`, so this should be fairly easy.

We already support more hashing algorithms than GNU[^1], so I think we should also add `b3sum`, while we're at it.

Relevant parts of the source code are:
- [hashsum.rs](../blob/main/src/uu/hashsum/src/hashsum.rs)
- [build.rs](../blob/main/build.rs):
https://github.com/uutils/coreutils/blob/1a7e5c4cc52721c83e3b28a3a94c346377df22de/build.rs#L99-L128

[^1]: GNU does not support the SHA3 algorithms. Support for those algorithms is often provided by other packages like [sha3sum](https://man.archlinux.org/man/community/sha3sum/sha3-224sum.1.en).

**Comment by palaster** [comment]
Going to work on this one
