### ISSUE TITLE
`dir` and `vdir` are missing

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#3163]
From the GNU docs:
> dir is equivalent to ls -C -b; that is, by default files are listed in columns, sorted vertically, and special characters are represented by backslash escape sequences. 

([source](https://www.gnu.org/software/coreutils/manual/html_node/dir-invocation.html))

> vdir is equivalent to ls -l -b; that is, by default files are listed in long format and special characters are represented by backslash escape sequences.

([source](https://www.gnu.org/software/coreutils/manual/html_node/vdir-invocation.html))

Instead of making entirely separate utilities, we should probably just make these shorthands for `ls` much like how `hashsum` and `test` are set up.

**Comment by tertsdiepraam** [comment]
For this approach, the GNU decoded project might be helpful: https://www.maizure.org/projects/decoded-gnu-coreutils/ls.html.

It explains that GNU uses a `mode` variable that is set to either `ls`, `dir` or `vdir`, which changes the behaviour of the program.

**Comment by gmnsii** [comment]
Do the changes made by the `dir` or `vdir` invocations need to be overwritable ? For example `dir` is a shortcut for `ls -C -b` but can you overwrite `-C` using something like `dir -l` ?
