### ISSUE TITLE
`tr`: Incorrect parsing of the repeat count in `[c*n]`

### ISSUE THREAD

**Issue by cbjadwani** [uutils/coreutils#3168]
In `tr`, character repetition (`[c*n]`) is always being parsed as octal.  But as mentioned in [GNU docs](https://www.gnu.org/software/coreutils/manual/html_node/Character-sets.html) for 'Repeated characters':
> If n begins with ‘0’, it is interpreted in octal, otherwise in decimal.

GNU tr:
```
$ /usr/bin/tr '[a*9]' 'b' <<< 'ab'
bb
```

uutils tr:
```
$ ./target/debug/tr '[a*9]' 'b' <<< 'ab'
./target/debug/tr: invalid repeat count '9' in [c*n] construct
```

**Comment by DevSabb** [comment]
The manual says that the given number is octal if it starts with zero. But in uu_tr, the number is considered octal by default.

https://man7.org/linux/man-pages/man1/tr.1.html
https://www.gnu.org/software/coreutils/manual/html_node/Character-sets.html#index-repeated-characters

https://github.com/uutils/coreutils/blob/38bcafb7c298cf2ac16ebf2fcdb514def4f266c2/src/uu/tr/src/operation.rs#L283-L287

Is it okay if I take a stab at this?

**Comment by DevSabb** [comment]
Below is the place where the repeated characters are parsed. I can look into this if its okay. 

https://github.com/uutils/coreutils/blob/38bcafb7c298cf2ac16ebf2fcdb514def4f266c2/src/uu/tr/src/operation.rs#L283-287
