### ISSUE TITLE
split should support the -t/--separator option

### ISSUE THREAD

**Issue by wodin** [uutils/coreutils#3192]
```
‘-t separator’
‘--separator=separator’

    Use character separator as the record separator instead of the default newline character (ASCII LF). To specify ASCII NUL as the separator, use the two-character string ‘\0’, e.g., ‘split -t '\0'’.
```

Additionally, it would be useful to support multiple character separators, e.g. '\r\n'

**Comment by tertsdiepraam** [comment]
Thank you for the report!

> Additionally, it would be useful to support multiple character separators, e.g. '\r\n'

I agree that this might be useful, but it's worth noting that GNU does not support multi-character separators.
