### ISSUE TITLE
add spell checker to pre-commit hooks?

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3198]
It would save time on my pull requests, and save us some cloud compute time when I submit pull requests with simple typos :grimacing:

**Comment by tertsdiepraam** [comment]
Do you have the spell checker installed in your editor? That already helps a lot

**Comment by crazystylus** [comment]
If you are using `vim/neovim`, [ALE](https://github.com/dense-analysis/ale) recently added support for cspell as linter for Rust.

**Comment by jfinkels** [comment]
Not much appetite for this, closing the issue for now. Thanks for the feedback :+1:
