### ISSUE TITLE
rm: bug with trailing backslash on windows 

### ISSUE THREAD

**Issue by amrbashir** [uutils/coreutils#3200]
I have a bad habit of providing options at the end of the command:
```
rm .\some-directory\ -rf
```
and since I use <kbd>Tab</kbd> to autocomplete	the path in powershell, it will add trailing backslash, and will interpret the `-rf` as part of the path.
```
rm: cannot remove '.\some-directory\ -rf': No such file or directory
```

It works fine if I removed the trailing backslash.

**Comment by amrbashir** [comment]
tried to track this down a bit, and it looks like it is an issue with using `clap::App::get_matches_from` with `wild::args_os()`. using `clap::App::get_matches()` parses the args correctly.

**Comment by amrbashir** [comment]
Opened an upstream issue https://gitlab.com/kornelski/wild/-/issues/7

**Comment by tertsdiepraam** [comment]
@amrbashir  Thank you! Let's hope it gets fixed!
