### ISSUE TITLE
Tests colocated with utils code don't run as part of CI

### ISSUE THREAD

**Issue by dgunay** [uutils/coreutils#3260]
I looked at the output of #3158 's CI and noticed that the test I wrote in `touch.rs` does not actually run as part of CI and does not count as code coverage for the error branch it tests: https://app.codecov.io/gh/uutils/coreutils/blob/main/src/uu/touch/src/touch.rs

**Comment by tertsdiepraam** [comment]
In the linked PR, I checked whether we run the tests at all (also outside codecov) and turns out we don't. Definitely something we should fix!
