### ISSUE TITLE
*.github/dependabot.yml* spams all forks

### ISSUE THREAD

**Issue by rivy** [uutils/coreutils#3326]
While testing a PR, I've updated my fork main to sync with 'uutils/coreutils/main', which includes the addition of *.github/dependabot.yml*.

And now, my fork is getting bombarded with Dependabot spam.

> Unresolved issue at <https://github.com/dependabot/dependabot-core/issues/2804> and <https://github.com/dependabot/dependabot-core/issues/2198>

@sylvestre , @tertsdiepraam , can we just remove this?

Maybe we could use the [`renovate` bot](https://docs.renovatebot.com) (see [comment](https://github.com/dependabot/dependabot-core/issues/2198#issuecomment-1060010064))?

**Comment by tertsdiepraam** [comment]
Oof that's a big oversight in dependabot. I've started to like dependabot, so I would like to keep using something for this. `renovate` looks like a good alternative. I think it's worth giving that a shot.

**Comment by sylvestre** [comment]
indeed, we should do it. I do see the value of these tools. we should not blinding auto update but having a tool to keep version up to date it quite valuable.
