### ISSUE TITLE
all: return code for invalid options

### ISSUE THREAD

**Issue by DevSabb** [uutils/coreutils#3331]
ref: #3320 

Edit: Though the below described issue fails the gnu test `tests/misc/usage_vs_getopt.sh`, it does not mark it in ERROR state as I originally thought. I have created another issue #3333 which is causing the test to be marked in ERROR state.

This issue will potentially fix the gnu test failure `tests/misc/usage_vs_getopts`. At least, this is one of the issue why the test is in ERROR state.

The gnu utils exits with error code 1 when there is a argument mismatch. uutils does not in some (may be all) cases.

gnu
```
> b2sum --thisoptiondoesnotexist
b2sum: unrecognized option '--thisoptiondoesnotexist'
Try 'b2sum --help' for more information.
> echo $?
1

```

uutils
```
> ./target/release/b2sum --thisoptiondosenotexist
error: Found argument '--thisoptiondosenotexist' which wasn't expected, or isn't valid in this context

        If you tried to supply `--thisoptiondosenotexist` as a value rather than a flag, use `-- --thisoptiondosenotexist`

USAGE:
    b2sum [OPTIONS] [FILE]...

For more information try --help
> echo $?
2

```

**Comment by sylvestre** [comment]
I am working on this

**Comment by sylvestre** [comment]
I think we have some incorrect parsing/different output :)
 
many thanks for opening this bug 
are you doing it for the other ERROR ?

**Comment by DevSabb** [comment]
I am going through them randomly. I'll create issues for the ones I find at least one of the cause for ERROR.

**Comment by sylvestre** [comment]
Interesting, it is clap's internal number:
https://docs.rs/clap/latest/src/clap/error/mod.rs.html#108
https://github.com/clap-rs/clap/blob/1f17d9e8ba5b64baca9e2d49c1b097b167bf4df6/src/util/mod.rs#L23=

**Comment by sylvestre** [comment]
Small world:
https://github.com/clap-rs/clap/issues/3426 ;)

**Comment by tertsdiepraam** [comment]
The discussion here might also be relevant https://github.com/uutils/coreutils/issues/3102 (it's the issue that led me to create that issue on clap)

**Comment by sylvestre** [comment]
I think we are good now
