### ISSUE TITLE
uudoc should have a better error message

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3354]
```
$ cargo install coreutils 
[...]
   Installing /home/sylvestre/.cargo/bin/uudoc

$ ~/.cargo/bin/uudoc
Downloading tldr archive
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Is it interesting to install uudoc by default?

**Comment by cakebaker** [comment]
Closing this ticket as the download feature has been removed in https://github.com/uutils/coreutils/pull/3415 and there is a warning shown with download instructions if the tldr archive is not installed.
