### ISSUE TITLE
b3sum/hashsum lacks --no-names argument

### ISSUE THREAD

**Issue by pothos** [uutils/coreutils#3360]
The `--no-names` argument of the official b3sum utility is very handy for only returning the hashsum as output, without the filename.

```
$ echo | b3sum --no-names
295192ea1ec8566d563b1a7587e5f0198580cdbd043842f5090a4c197c20c67a
```

For the b3sum utility this argument should be supported. For hashum in general it would be quite useful as well.

**Comment by pothos** [comment]
Filed a PR

**Comment by tertsdiepraam** [comment]
Thank you! It should be noted that b3sum is not part of GNU coreutils and hence there are only other implementations that fill that gap. They have slightly different options and `--no-names` does not appear in any of the GNU utils. However, I do think it might be nice to add this anyway.

**Comment by sylvestre** [comment]
Is there any coreutils implementation with this option?

**Comment by tertsdiepraam** [comment]
I can't find any. But the `b3sum` util is from https://github.com/BLAKE3-team/BLAKE3 and is probably becoming the standard util, so it would be nice to have compatibility with that.

**Comment by sylvestre** [comment]
OK, sounds good :)
I will just add a comment that we should document it
