### ISSUE TITLE
cp: implement --sparse option

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3362]
The `--sparse` option to `cp` is not implemented yet. This is an option that controls whether an optimization is applied in storing the file on the filesystem, so if we just want to get things running, it probably suffices for us to just add this argument and ignore it.

GNU cp:
```sh
$ touch a && cp --sparse=always a b
# no output
```

uutills cp
```sh
$ touch a && ./target/release/cp --sparse=always a b
./target/release/cp: Option 'sparse' not yet implemented.
```

**Comment by sylvestre** [comment]
I think it is now done
