### ISSUE TITLE
dd: error message on empty arg does not match GNU

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3363]
The error message printed when `dd` is given an argument of, for example, `bs=` does not match that of GNU `dd` and is less clear anyway.

GNU dd:
```sh
$ dd bs=
dd: invalid number: ‘’
```

uutils dd:
```sh
$ ./target/release/dd bs=
./target/release/dd: Unrecognized byte multiplier -> 
```

**Comment by Fuchczyk** [comment]
Message displayed when executing `dd iflag=` is:
```
dd: invalid input flag: ‘’
Try 'dd --help' for more information.
```
Should rust implementation also display `Try 'dd...`?

**Comment by jfinkels** [comment]
I think you are referring to the following difference between GNU dd and uutils dd; if so then yes, let's match GNU dd in this case as well:

GNU dd:
```
$ dd iflag=
dd: invalid input flag: ‘’
Try 'dd --help' for more information.
```

uutils dd:
```
$ ./target/debug/dd iflag=
./target/debug/dd: Unrecognized iflag=FLAG or oflag=FLAG -> 
```
