### ISSUE TITLE
Anyone working on ls yet?

### ISSUE THREAD

**Issue by kureikain** [uutils/coreutils#34]
Hi,

I would like to get my hand dirty on `ls` stuff? but not sure if someone is working on it yet

**Comment by marinintim** [comment]
@kureikain, so how is it going?

**Comment by nathanross** [comment]
@marinintim we'd love to have someone take the lead on the remaining work of ls, as most of it is yet unimplemented, and currently no one is actively working on implementing features for it.

As an aside, this particular issue is a duplicate to #126 , it looks like we just haven't gotten around to closing this, so I'll do that now. If you'd like to notify people that you're making continuous changes / PRs for ```ls```, make a comment on #126 when you can.
