### ISSUE TITLE
CI: warn if the size of a binary increases by more than X %

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3404]
Currently, we only look at build size after the PR ( https://github.com/uutils/coreutils-tracking#binary-size-evolution )

We should monitor this in the CI. For this, we should update:
https://github.com/uutils/coreutils/blob/main/.github/workflows/CICD.yml#L529-L536=

And keep track of the individual size of the binary ( like https://github.com/uutils/coreutils-tracking/blob/main/gnu-full-result.json )
and compare if this is significantly increase (ex: > 5%) and trigger a warning.

**Comment by miles170** [comment]
I have some questions

1. `SIZE=$(du -s target/size-release/usr/local/bin/|awk '{print $1}')`

Shouldn't we skip the `[` (tests) binary?

2. `SIZE_MULTI=$(du -s target/size-multi-release/usr/local/bin/|awk '{print $1}')`

Shouldn't we only estimate the coreutils size? (`du -s target/size-multi-release/usr/local/bin/coreutils`)
