### ISSUE TITLE
`df`: `--block-size` does not accept sizes with a suffix

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#3416]
`df` currently only seems to handle sizes specified in bytes without any suffixes:
```
❯ df --block-size=3K
df: invalid --block-size argument
```
But with GNU it works:
```
❯ df --block-size=3K
Filesystem     3K-blocks      Used Available Use% Mounted on
...
```

Discovered by @gmnsii in https://github.com/uutils/coreutils/pull/3414#issuecomment-1100827763

**Comment by jfinkels** [comment]
Even worse, it accepts the argument but does nothing with it currently: #3082.
