### ISSUE TITLE
"Run GNU tests" on main fails to complete for the last few days 

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3439]
Not sure why it is failing
Example:
https://github.com/uutils/coreutils/runs/6136181919?check_suite_focus=true#logs=
it is a timeout issue but not sure why

`The hosted runner: GitHub Actions 3 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
`

**Comment by tertsdiepraam** [comment]
I've been investigating this too. I discussed this in the #help channel on Discord. I couldn't figure out what it was yet though.

**Comment by tertsdiepraam** [comment]
@jhscheer also noticed that the GNU testsuite sometimes starts using up all RAM until the terminal crashes. That might be related, but I couldn't reproduce that locally. The earliest fail I could find was https://discord.com/channels/563860080668442635/967372686193999872/967392675064074290.

**Comment by jhscheer** [comment]
On my local machine, the last tests that run before everything crashes are:
``` bash
sort-spinlock-abuse.sh
stat-nanoseconds.sh
```

**Comment by sylvestre** [comment]
we reverted the regressor. See
https://github.com/uutils/coreutils/pull/3442
