### ISSUE TITLE
mktemp: fails to respect given template path

### ISSUE THREAD

**Issue by TymanWasTaken** [uutils/coreutils#3440]
On arch linux, aur packages use mktemp while building packages, and it works fine while using GNU mktemp but not the uutils mktemp. If you use the uutils mktemp and try to build an aur package (`yay` for example) it gives an error like `mktemp: failed to create file via template './usr/bin/yay.XXXXXX': No such file or directory (os error 2) at path "/tmp/./usr/bin/yay.zIwKvU"`
I believe that is because uutils tries to add a /tmp/ before the path (`/tmp/./usr/bin/yay.zIwKvU`) which causes errors like that one.

**Comment by jfinkels** [comment]
Good catch. Here's a test case that demonstrates the issue.

GNU mktemp:
```sh
$ mkdir -p d && mktemp d/XXX
d/XdO
```

uutils mktemp:
```sh
$ mkdir -p d && ./target/debug/mktemp d/XXX
./target/debug/mktemp: failed to create file via template 'd/XXX': No such file or directory (os error 2) at path "/tmp/d/FTB"
```

**Comment by jfinkels** [comment]
Even when there is no directory in the template name, it assumes that the file should be created in the `/tmp` directory, but that's not the correct behavior:
```sh
$ mktemp XXX
hqA
$ target/debug/mktemp XXX
/tmp/LJr
```
