### ISSUE TITLE
Completions for paths are broken (on Zsh at least)

### ISSUE THREAD

**Issue by equal-l2** [uutils/coreutils#3503]
# Summary
The completion does nothing when a path is expected.

Example with `ls`:
```shell
$ ls <Press Tab to trigger the completion>
```
The above results in nothing.

# Solution
Add `value_hint` to the code (the example below is from `ls.rs`):
```diff [ls.rs]
            .arg(
                Arg::new(options::PATHS)
                    .multiple_occurrences(true)
                    .takes_value(true)
                    .allow_invalid_utf8(true)
+                   .value_hint(clap::ValueHint::AnyPath),
            )
```
(I use `AnyPath` because `ls` accepts both files and directories, but `FilePath` and `DirPath` are available if only either of them should be accepted. See [the document of ValueHint](https://docs.rs/clap/latest/clap/enum.ValueHint.html) for detail.)

# You know the solution, why the issue then?
I cannot exhaustively fix the problem because I don't know which command in uutils accepts paths, so I need help.

**Comment by tertsdiepraam** [comment]
Thank you! Looks like a perfect solution! We don't have a comprehensive list of all arguments that accept paths or the other variants of value hints. Maybe we can put a list of utils in this issue and tick them of one by one (or in batches) in separate PRs.

**Comment by tertsdiepraam** [comment]
@equal-l2 I went ahead and did all utils in one go. Feel free to check out and give feedback on the PR!
