### ISSUE TITLE
Speed up CI/CD using a build cache 

### ISSUE THREAD

**Issue by Narasimha1997** [uutils/coreutils#3540]
Right now all the CI/CD tasks invoked for each PR is executed from the beginning, because the GitHub workflow starts from the initial state and lacks knowledge of previous state. A complete CI/CD run takes around 1-2 hours during peak hours and thus it limits the volume of changes one can do w.r.t to time. 

As you know cargo stores indexes and build artifacts locally and is intelligent enough to identify what had changed since to make sure it only rebuilds changed artifacts without touching other artifacts. Same applies crate dependencies as well. We can cache the build using a remote volume or some kind of a cache which can be mounted back to the actions container. There is a repo on GitHub which already provides such a support: 

[Check this out](https://github.com/actions/cache/blob/main/examples.md)

**Comment by tertsdiepraam** [comment]
Interesting! We're already using some caching using [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache). Does the approach you suggested have significant benefits this one?

**Comment by Narasimha1997** [comment]
Hi, @tertsdiepraam 

I had a look at the tool this project is using - I think it's good. The tool I suggested is a more generalized one. So I think the current tool you are using looks good! 

Closing this issue.
