### ISSUE TITLE
Can this replace gnu in Arch? 

### ISSUE THREAD

**Issue by PublicVoidUpdate** [uutils/coreutils#3549]
I'm trying to find a replacement for gnu utils without deleting important programs such as pacman of XFCE. I tried busybox but my implementation didn't work as it disabled the vm's Ethernet and therefore pacman couldn't be compiled

**Comment by sylvestre** [comment]
I am not sure I understand what you mean.
GNU is providing a lot of things.
Here, we are aiming at replacing a fraction of this called Coreutils.
Pacman is an arch specific package (and afaik, not related to XFCE).
