### ISSUE TITLE
df: df-output.sh fails because of error message generated by clap

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#3572]
`df-output.sh` (from the GNU coreutils test suite) tests, for example, whether `df -i --output` causes a "mutually exclusive options" error and shows a corresponding error message.

With uutils df, clap is used to handle mutually exclusive options. And it generates an error message that's different than what the GNU coreutils test suite expects.

I see two ways to resolve this issue: simply ignore `df-output.sh`, or handle mutually exclusive options manually without clap.

**Comment by tertsdiepraam** [comment]
There is a third option (which I prefer in this case), which is to replace the text that GNU expects with the text we print. We've already done this for a few utils at the end of `util/build-gnu.sh`.

**Comment by cakebaker** [comment]
Fixed in https://github.com/uutils/coreutils/pull/5452
