### ISSUE TITLE
`dd` `test_bytes_oseek_bytes_trunc_oflag` flaky test on MacOS

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#3581]
I feel like I've seen this failure a lot recently, always in the MacOS CI (both nightly and stable Rust):
```
 ---- test_dd::test_bytes_oseek_bytes_trunc_oflag stdout ----
current_directory_resolved: 
run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils dd oseek=8 oflag=seek_bytes bs=2 count=0
thread 'test_dd::test_bytes_oseek_bytes_trunc_oflag' panicked at 'failed to write to stdin of child: Broken pipe (os error 32)', tests/common/util.rs:1091:21
```

For example:
- https://github.com/uutils/coreutils/runs/6665576089?check_suite_focus=true
- https://github.com/uutils/coreutils/runs/6622659165?check_suite_focus=true
- https://github.com/uutils/coreutils/runs/6650219163?check_suite_focus=true

**Comment by sylvestre** [comment]
One more occurrence: 
https://github.com/uutils/coreutils/runs/6864217593?check_suite_focus=true
