### ISSUE TITLE
ls: " is not taken in consideration when building table

### ISSUE THREAD

**Issue by AndreasBrostrom** [uutils/coreutils#3584]
![image](https://user-images.githubusercontent.com/13811113/171403867-ac92b185-9d73-43e0-bee0-31a9897ee245.png)

```bash
$ coreutils --help
coreutils 0.0.14 (multi-call binary)
$ echo $SHELL
/bin/fish
~ 
$ cat .config/fish/conf.d/00_aliases.fish
alias ls='ls --color=auto'
alias ll='ls -alF'
alias lsl='ls -lF'
alias la='ls -A'
alias lsa='la'
alias l='ls -CF'
alias lr='ls -ltrh'
alias lra='ls -ltrha'
alias dir='dir --color=auto'
alias dir='ls -l'
alias vdir='vdir --color=auto'
```

**Comment by tertsdiepraam** [comment]
This is due to locale, we follow the C locale in all sorting at the moment. Recently, work gas started on a Unicode collator (read: sorter) has started in the ICU4X project. My hope is that we can use that to fix the sorting in the near future.

**Comment by tertsdiepraam** [comment]
Herre is where this was originally discussed: https://github.com/uutils/coreutils/issues/2149

**Comment by AndreasBrostrom** [comment]
Ignoring the sorting then in this thread
symbol `"` is not taken in consideration.

**Comment by tertsdiepraam** [comment]
Yeah, that's indeed something we should fix. What's going on with the `'.moonchild productions'` folder? Does it have quotes in the name and then GNU doesn't quote it, but we do quote it with an additional `"`? (This is apart from the spacing that is messed up)

**Comment by tertsdiepraam** [comment]
Oof that's bad hahahaha. Thanks for the report!

**Comment by tertsdiepraam** [comment]
The linked PR should fix this issue. Feel free to test it out and provide feedback! Note that this is not yet entirely compatible with GNU, because GNU inserts an additional space for all non-quoted names if any name is quoted, but at least it is not double quoted and nicely lined up.

**Comment by AndreasBrostrom** [comment]
Works fine!
![image](https://user-images.githubusercontent.com/13811113/173349810-b919e209-528c-405e-9fbd-7120225884d1.png)
