### ISSUE TITLE
urm self-documenation is misconfigured.

### ISSUE THREAD

**Issue by bdmorin** [uutils/coreutils#3668]
I was including /home/linuxbrew/.linuxbrew/share/fish/vendor_completions.d/urm.fish in my fish shell, and found this error;

```
> source /home/linuxbrew/.linuxbrew/share/fish/vendor_completions.d/urm.fish
complete: Too many arguments

/home/linuxbrew/.linuxbrew/share/fish/vendor_completions.d/urm.fish (line 5):
complete -c urm -s i -l prompt before every removal
^
from sourcing file /home/linuxbrew/.linuxbrew/share/fish/vendor_completions.d/urm.fish


5: complete -c urm -s i -l -d 'prompt before every removal'
```
The -l requires an option here's my fix.
```
complete -c urm -s i -l prompt -d 'prompt before every removal'
```

However I'm assuming the completions are auto-generated
![image](https://user-images.githubusercontent.com/476219/175569069-bed98eec-9280-48a3-8e12-908d086440bf.png)

It seems something in the urm code has `before every removal` in the incorrect place, it should be aligned with the column on the right.

I tried to find it in the code, but I'm no rust developer yet.

```
> brew info uutils-coreutils
uutils-coreutils: stable 0.0.14 (bottled), HEAD

> urm --version
urm 0.0.14
```

Thanks!

**Comment by tertsdiepraam** [comment]
The completions are indeed autogenerated by `clap-complete`. If you can find a minimal, easy to reproduce example of this problem, we could open an issue there.
