### ISSUE TITLE
Fix 'wc' gnu test-suite compatibility

### ISSUE THREAD

**Issue by gkalas8** [uutils/coreutils#3678]
The wc utility is using the os_display crate's quotation function to produce quoted filenames on its output. This implementation produces slightly different values than the GNU wc's implementation. Both are valid. Sadly the automated tests will only pass using GNU's notation.
The following example demonstrates the difference.
Filename: 'a\nb' (https://github.com/coreutils/coreutils/blob/master/tests/misc/wc-files0.sh#L44) .
GNU output : 'a'$'\n''b'
uu_wc (os_display) output: $'a\nb'

The ls util implements its own quotation logic in src/uu/ls/quoting_style.rs . This implementation, with the right configuration may produce the GNU compatible output.
In addition, when in files0 mode GNU wc will never align columns. This needs to be mirrored in uu_wc as well.

Tasks:
* Following advice on the #coreutils discord channel move the implementation from ls to uucore.
* Use this quotation system in wc instead of os_display.
* Do not align columns at all when in files0 mode.

**Comment by gkalas8** [comment]
Yes, i just pushed the patch.
https://github.com/cakebaker/coreutils/pull/62

**Comment by tertsdiepraam** [comment]
We'll close the issue once the PR has been merged ;p
