### ISSUE TITLE
FreeBSD: the CI should fail when the build fails or the tests are failing

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3779]
In the CI, for example here:
https://github.com/uutils/coreutils/runs/7686143875?check_suite_focus=true

the tests are failing:
https://github.com/uutils/coreutils/issues/3778

And the build was failing:
https://github.com/uutils/coreutils/issues/3733

but they were both green in the CI

**Comment by miles170** [comment]
I'm working on this.

**Comment by xtqqczze** [comment]
@sylvestre Seems like this needs reopening: https://github.com/uutils/coreutils/pull/14533#issuecomment-5654994079
