### ISSUE TITLE
Implement stat

### ISSUE THREAD

**Issue by wr0112358** [uutils/coreutils#378]
I'm working on this.

**Comment by divkakwani** [comment]
Are you still working on it? I'd like to take it up if you aren't.

**Comment by wr0112358** [comment]
Hi,
I was almost finished, but did not have the time to keep up with the rust
changes.

It's yours.

On Tue, Apr 28, 2015 at 8:25 AM, Divyanshu Kakwani <notifications@github.com

**Comment by knight42** [comment]
#893
