### ISSUE TITLE
`chroot -c` error's out when it should run what is supplied after

### ISSUE THREAD

**Issue by Lunarequest** [uutils/coreutils#3783]
currently `chroot` is incompatible with the GNU chroot as when `-c some_command`. This break compatibility with scripts like pmbootstrap

**Comment by sssemil** [comment]
Hey, I can work on this.

**Comment by sylvestre** [comment]
sure, please go ahead :)

**Comment by sssemil** [comment]
So [this is the line](https://gitlab.com/postmarketOS/pmbootstrap/-/blob/master/pmb/chroot/root.py#L72) where it breaks, correct?

**Comment by Lunarequest** [comment]
> So [this is the line](https://gitlab.com/postmarketOS/pmbootstrap/-/blob/master/pmb/chroot/root.py#L72) where it breaks, correct?

Exactly
