### ISSUE TITLE
cksum: implement `--untagged`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3811]
Used by `tests/misc/sm3sum.pl`

```
--untagged
    create a reversed style checksum, without digest type
```

**Comment by sylvestre** [comment]
Note that Debian doesn't have a recent enough version of GNU/coreutils:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017354

**Comment by oliviacrain** [comment]
I'll have some time tonight to look at this!
