### ISSUE TITLE
`install` should not fail when target directory doesn't exist

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3814]
```
#export C=./target/debug/coreutils
rm -rf dir1 no-dir2

file=file
echo foo > $file

mkdir dir1
touch dir1/file1
$C install -D "$PWD/dir1/file1" $file -t "$PWD/no-dir2/"

```

With GNU, it works without issue.
With Rust, uncomment the first line:
`install: target '/home/sylvestre/dev/debian/coreutils/no-dir2/' is not a directory`

Tested by GNU in:
`tests/install/create-leading.sh`

**Comment by bruecke** [comment]
I've been working on fixing this. Will open a PR soon,

**Comment by ImperatorStorm** [comment]
Should be closed, fixed in https://github.com/uutils/coreutils/pull/3950 back in September.

**Comment by sylvestre** [comment]
Thanks
