### ISSUE TITLE
`stty`: Implement `--file` / `-F`

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#3863]
From the GNU manual:
```
‘-F DEVICE’
‘--file=DEVICE’
     Set the line opened by the file name specified in DEVICE instead of
     the tty line connected to standard input.  This option is necessary
     because opening a POSIX tty requires use of the ‘O_NONDELAY’ flag
     to prevent a POSIX tty from blocking until the carrier detect line
     is high if the ‘clocal’ flag is not set.  Hence, it is not always
     possible to allow the shell to open the device in the traditional
     manner.
```

**Comment by VorpalBlade** [comment]
I'm working on this (seemed like a nice & easy first issue)

**Comment by VorpalBlade** [comment]
By the way, `O_NONDELAY` as mentioned in the stty docs is not a thing. It should be `O_NONBLOCK`: 
* `grep -R O_NONDELAY /usr/include` returns nothing.
* Running `strace /bin/stty -F /dev/pts/0` shows it open the pts as O_NONBLOCK and readonly.

I have implemented this actual behaviour.

**Comment by VorpalBlade** [comment]
This can now be closed I believe.

**Comment by tertsdiepraam** [comment]
Indeed! (For later reference: this was fixed by https://github.com/uutils/coreutils/pull/4401)
