### ISSUE TITLE
Agregate the root GNU testsuite results

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3884]
We have currently 73 skipped tests, they are probably because of that.

**Comment by niyaznigmatullin** [comment]
Just for the information, there are also tests that are skipped when running as root

**Comment by sylvestre** [comment]
Good point
we could parse the test to create a list of tests containing `require_root_`

**Comment by xxyzz** [comment]
The current test script "util/run-gnu-test.sh" already tests these root tests, but it's only enabled on GitHub Actions:

https://github.com/uutils/coreutils/blob/1054c5c365d05ecbdc0d0a73344e468827c47970/util/run-gnu-test.sh#L45-L47

**Comment by jfinkels** [comment]
This came up in https://github.com/uutils/coreutils/pull/3880#issuecomment-1229461270

**Comment by xxyzz** [comment]
Root tests are tested in GitHub CI. If you search "skip-seek-past-dev" in the CI log, it's at the end of the log, but this test is skipped because other reason: https://github.com/uutils/coreutils/runs/8177093173?check_suite_focus=true#step:10:37091
