### ISSUE TITLE
`cp -a` has a different behavior that GNU's

### ISSUE THREAD

**Issue by kevinburkesegment** [uutils/coreutils#3886]
```
#export C=./target/debug/coreutils
rm -rf dir1 dir2
mkdir dir1 dir2
touch dir1/file
$C cp -a dir1/. dir2
stat dir2/file
```

With GNU, dir2/file exists. With our implementation, `dir2/file` doesn't. Instead, the file `dir2/dir1/file` is created

**Comment by sylvestre** [comment]
Please provide a reproducer. Rebuilding a full program isn't ideal

**Comment by kevinburkesegment** [comment]
okay

```
$ cat Cargo.toml
[package]
name = "kevinburke-test-issue-3886"
version = "0.0.1"

[dependencies]
rdkafka = { version = "0.28.0", default-features = false}
```

```
$ cat src/main.rs
fn main() {
    println!("geeks for geeks");
}
```

**Comment by stefins** [comment]
Seems like the issue is with the dot (.) in the path name!

**Comment by sylvestre** [comment]
You should provide a test case like https://github.com/uutils/coreutils/issues/3813

```
./target/debug/coreutils cp -a tests/. /tmp/23aze
```
works on my system.

**Comment by kevinburkesegment** [comment]
Sorry, as I said at the beginning:

> I tried reproducing by running that exact command given in the "Running command" line, but I was unable to reproduce when running directly, which is also a little confusing.

I was thinking you'd be interested in knowing about a case where GNU coreutils and uutils coreutils behavior differs. I've tried my best to produce a reasonable test case. If I knew exactly what the problem was I would fix it.

**Comment by niyaznigmatullin** [comment]
I think it panicked here: https://github.com/fede1024/rust-rdkafka/blob/master/rdkafka-sys/build.rs#L21

Seems like `"cp -a librdkafka/. /Users/kevinburke/src/github.com/kevinburkesegment/k8s-repro/cargo/target/release/build/rdkafka-sys-58ae7d01e1b63d03/out"` didn't copy the contents of `librdkafka`, so it can't find `configure` inside `out`: https://github.com/fede1024/rust-rdkafka/blob/master/rdkafka-sys/build.rs#L165

The testcase is:

```
mkdir dir1 dir2
touch dir1/file
cp -a dir1/. dir2
stat dir2/file
```

The uutils copies `dir1`, but GNU copies `dir1`'s contents

**Comment by kevinburkesegment** [comment]
Thank you!

**Comment by sylvestre** [comment]
Indeed, thanks. I cleanup the bug to keep the essential information

**Comment by dmatos2012** [comment]
Hi, I would like to work on this issue. Already asked on the discord and could try a solution, hope thats ok :)

**Comment by sylvestre** [comment]
sure, please give it a try :)
