### ISSUE TITLE
cp: --reflink with no argument should be assumed --reflink=always

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#3984]
The `--reflink` command line option to `cp` takes an optional argument (`always`, `auto`, or `never`, with `always` being the default) but it can be used without an argument. uutils cp does not allow this type of usage, but should

GNU cp v8.30:
```
$ touch f && cp --reflink f g
cp: failed to clone 'g' from 'f': Operation not supported
```

uutils cp:
```
$ touch f && ./target/debug/cp --reflink f g
./target/debug/cp: invalid argument 'f' for 'reflink'
```

This is similar to an issue with `mktemp --tmpdir`, described here: https://github.com/uutils/coreutils/blob/4b517a361de7dfda90f6d131b822ef0704d1e2b9/src/uu/mktemp/src/mktemp.rs#L172-L178

**Comment by sssemil** [comment]
Can confirm. Working on this.

**Comment by sssemil** [comment]
Hm, so I can add ` .default_missing_value("auto")` but then it still tries to take the file name as an argument. But I can also then set ` .require_equals(true)`, however it will fail if nothing is specified because `=` is required. It looks like there's no softer version of `require_equals` in clap.

**Comment by tertsdiepraam** [comment]
Maybe this can be of help? This is how we did the `--color` argument for `ls`.

https://github.com/uutils/coreutils/blob/043c009a413edeb45013a73817dd5d303a162635/src/uu/ls/src/ls.rs#L1428-L1436

**Comment by sssemil** [comment]
@tertsdiepraam that works, thanks! Will make a PR now.
