### ISSUE TITLE
cp: interactive mode messages differ from those of GNU cp

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#4023]
The prompts and responses from the interactive copy command `cp -i` are different in uutils cp versus GNU cp.

GNU cp v8.30
```
$ touch a b && cp -i a b
cp: overwrite 'b'? n
```
(I typed the character "n" and pressed Enter. Also, this message is printed to stderr, not stdout.)

uutils cp:
```
$ touch a b && ./target/release/cp -i a b
./target/release/cp: overwrite 'b'?  [y/N]: n
./target/release/cp: Not overwriting 'b' at user request
```

The relevant file in the GNU test suite would be `tests/cp/cp-i.sh`, but it doesn't actually verify the content of these messages.

**Comment by sssemil** [comment]
I can work on this.
