### ISSUE TITLE
Upgrade to Clap 4

### ISSUE THREAD

**Issue by andrewbaptist** [uutils/coreutils#4024]
There are some significant API changes with [Clap 4](https://epage.github.io/blog/2022/09/clap4/). Because of the multi-call binary, this requires a "global" change to clap 4 in order to make this happen. I haven't dug deeply into this, but just looking at one utility (split), a fair number of changes are required to make this happen.  There are also a lot of good reasons to upgrade, so it will likely happen eventually.

Do we want to try and attempt this across the code base. How is a project like this done?

**Comment by sylvestre** [comment]
See https://github.com/uutils/coreutils/pull/3991 ;)

**Comment by andrewbaptist** [comment]
awesome - I missed that!
