### ISSUE TITLE
checksum tools stop on first failure (differs from GNU)

### ISSUE THREAD

**Issue by chenxiaolong** [uutils/coreutils#4042]
With uutils' checksum tools (like sha256sum), the program exits immediately when encountering the first error. This affects both the checksum generation (no args) and validation (`-c`) modes. This differs from GNU's implementations, which try to process every file before exiting.

For example:

```bash
echo 1 > file_1
echo 2 > file_2
sha256sum file_1 file_2 > checksums
rm file_1

echo "GNU output:"
sha256sum -c checksums
echo

echo "uutils output:"
coreutils sha256sum -c checksums
echo
```

returns:

```
GNU output:
sha256sum: file_1: No such file or directory
file_1: FAILED open or read
file_2: OK
sha256sum: WARNING: 1 listed file could not be read

uutils output:
sha256sum: failed to open file: No such file or directory

```

**Comment by dmatos2012** [comment]
Hi, I would like to give this a try :), if thats not a problem!

**Comment by ankush** [comment]
@sylvestre this issue should be closed?

**Comment by sylvestre** [comment]
I guess @dmatos2012 you agree ? :)

**Comment by dmatos2012** [comment]
I would agree as well :)
