### ISSUE TITLE
"mktemp -d --tmpdir" not working

### ISSUE THREAD

**Issue by Ecordonnier** [uutils/coreutils#4075]
The man page of mktemp specifies that "mktemp -d --tmpdir" should create a tmp directory either in $TMPDIR if this variable exists, or in "/tmp" otherwise.

>        -p DIR, --tmpdir[=DIR]
>              interpret TEMPLATE relative to DIR; if DIR is not specified, use $TMPDIR if set, else /tmp

 This works with GNU coreutils mktemp:

```
$ /usr/bin/mktemp --version
mktemp (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering and Eric Blake.
$ /usr/bin/mktemp -d --tmpdir
/tmp/tmp.FVe2z7mDyv
```

This does not work with uutils-coreutils (tested with release 0.0.16):
```
# mktemp --version
mktemp 0.0.16
# unset TMPDIR
# mktemp -d --tmpdir 
error: The argument '--tmpdir <DIR>' requires a value but none was supplied

For more information try --help
```

Using the TMPDIR variable also does not work with uutils-coreutils 0.0.16:

```
# export TMPDIR=/tmp/foobar
# mkdir -p /tmp/foobar
# mktemp -d --tmpdir 
error: The argument '--tmpdir <DIR>' requires a value but none was supplied

For more information try --help
```

**Comment by dmatos2012** [comment]
Hi. I would like to give this a shot :)

**Comment by sylvestre** [comment]
please give it a try :)

**Comment by Ecordonnier** [comment]
Which process are you using? Should I close this ticket now that https://github.com/uutils/coreutils/pull/4091 has been merged? Or will you close the ticket when the next release is shipped?

**Comment by sylvestre** [comment]
yeah, we close it now :)

**Comment by Ecordonnier** [comment]
I tested the fix and it is working well. The only caveat I found is this error message which is better in the GNU version in my opinion:

```
coreutils$ ./target/release/coreutils mktemp --tmpdir foobar
mktemp: failed to create file via template 'foobar/tmp.XXXXXXXXXX': No such file or directory
GNU version:
coreutils$ mktemp --tmpdir foobar
mktemp: too few X's in template ‘foobar’
```

Note that for the version without tmpdir, the error messages are the same in both versions:
```
GNU version:
coreutils$ mktemp foobar
mktemp: too few X's in template ‘foobar’

coreutils$ ./target/release/coreutils mktemp foobar
mktemp: too few X's in template 'foobar'
```

It is not strictly related with the original ticket, though, and it is questionable if it is even worth fixing, so I'll copy this to a new ticket.
