### ISSUE TITLE
`test_cp_parents_2_dirs` fails on android

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4079]
```

---- test_cp::test_cp_parents_2_dirs stdout ----
current_directory_resolved: 
mkdir_all: /data/data/com.termux/files/usr/tmp/.tmpLVaxT2/a/b/c
mkdir: /data/data/com.termux/files/usr/tmp/.tmpLVaxT2/d
run: /data/data/com.termux/files/home/coreutils/target/debug/coreutils cp -a --parents a/b/c d
thread 'test_cp::test_cp_parents_2_dirs' panicked at 'Command was expected to succeed.
stdout = 
 stderr = cp: Permission denied (os error 13)
', tests/common/util.rs:176:9

```

test introduced in:
https://github.com/uutils/coreutils/commit/ac3fcca6c04f324d5de97efc92712f9960fef5aa

cc @jfinkels

**Comment by sssemil** [comment]
Looking into this.

**Comment by sssemil** [comment]
After a bit more digging, looks like `Xattr` is the one causing the permission denied error here.

**Comment by sssemil** [comment]
Here is a simpler test case that you can run in an Android emulator in Termux:
```
touch ~/a
cp -a ~/a ~/b
# no error
```

```
touch ~/a
./coreutils/target/debug/coreutils cp -a ~/a ~/b
# permission denied
```

This is probably because of selinux attributes, but I'm not sure.

**Comment by sssemil** [comment]
Something else that is interesting. When we specify `-a` the `preserve_xattr` is set to treu, but this doesn't set the `require_preserve_xattr` to true. But, if we do `--preserve=xattr`, the `require_preserve_xattr` is set to true. Then, when I run `cp --preserve=xattr ~/a ~/b` on this AVD, I get `cp: cannot preserve extended attributes, cp is built without xattr support`.

**Comment by tertsdiepraam** [comment]
Interesting! I think we should match GNU behaviour as much as possible. One thing I'm curious about, is it possible too build cp with xattr support and what is the behaviour then?

**Comment by sssemil** [comment]
@tertsdiepraam looking at https://github.com/coreutils/coreutils/blob/master/src/copy.c#L1427-L1432:
```
    if (preserve_xattr)
    {
      if (!copy_attr (src_name, source_desc, dst_name, dest_desc, x)
          && x->require_preserve_xattr)
        return_val = false;
    }
```
If we select `-a`, we set `preserve_xattr` to true, and `require_preserve_xattr` remains at false. Then, when copy attribute fails, since the `require_preserve_xattr` is set to false, we do not get an error. So, I guess I would ignore the error in case of `-a` but not if `--preserve=xattr` is set. I think this calls for a few additional test cases.

I will try building GNU cp with xattr enabled on android.

**Comment by jtracey** [comment]
Again, this is because of #3477.
