### ISSUE TITLE
build: Add darwin-arm64 as a build target

### ISSUE THREAD

**Issue by jurgen-kluft** [uutils/coreutils#4104]
Is it possible to add this as an extra build target for M1 Macs?

**Comment by sylvestre** [comment]
sure, don't hesitate to add it :)

**Comment by jurgen-kluft** [comment]
Added a pull request.

**Comment by jurgen-kluft** [comment]
@sylvestre How do I run Mac aarch64 on a compatible Mac OS image. The image it is being run on is x64 so that will fail running an aarch64 build.

**Comment by sylvestre** [comment]
Dunno, sorry :)

**Comment by dzbarsky** [comment]
https://github.com/uutils/coreutils/pull/5523

**Comment by cakebaker** [comment]
Closing this ticket, fixed in https://github.com/uutils/coreutils/pull/5523
