### ISSUE TITLE
`mv` progress bar

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#4128]
We currently have a progress bar for `cp`, but not for `mv`. Usually, `mv` is quite fast and does not require a progress bar, but it becomes slow when moving files across disks. Another reason to include the progress bar is for symmetry with `cp`.

**Notes**

- The progress bar for `cp` can be used as a model for this.
- `cp` currrently uses the `-g`/`--progress` flags to activate the progress bar.
- Some functionality for this should probably be shared between `mv` and `cp` and could be added to `uucore`.
- Calculating the initial size of the files to be moved will add a bit of overhead.
- We'll have to see when we want to activate the progress bar and what should be displayed because it's a bit more complicated than for `cp`. If no "full" move is necessary, for instance, we might not want to display the size of the files but only how many files we have to move. Or in this case we never show a progress bar.

Originally requested by @doronbehar in #1455

See also #3903 where the progress bar for `cp` was added.

**Comment by trasua** [comment]
hi, I want to work on this.

**Comment by ctsk** [comment]
Heya o/ I've started some work on this last week :sweat_smile: I've pushed my WIP to https://github.com/ctsk/coreutils/tree/mv-progress-bar

**Comment by idwer** [comment]
@tertsdiepraam support for this seems to be added in 00bbe2463911462bf5a6bd8fbcbbc462dacc72c3

**Comment by sylvestre** [comment]
yes, thanks
