### ISSUE TITLE
sort: accept multiple, compatible sort options

### ISSUE THREAD

**Issue by ht990332** [uutils/coreutils#4129]
I am trying to compile glibc from git branch 2.35. I am seeing a flood of:

sort: failed to parse key '2n,2n': options '-nn' are incompatible

**Comment by sylvestre** [comment]
could you please provide a small test case to reproduce the issue ?
thanks

**Comment by ht990332** [comment]
> could you please provide a small test case to reproduce the issue ? thanks

I do not know how to do that. Can a uutils developer try it please?

**Comment by sylvestre** [comment]
Sorry but not, it isn't practical to debug coreutils with "please rebuild X"...

please reopen once you have a test case showing the issue

**Comment by ht990332** [comment]
> Sorry but not, it isn't practical to debug coreutils with "please rebuild X"...
> 
> please reopen once you have a test case showing the issue

Could you at least give me details on what I should do? What would a test case entail exactly?
Not everyone is a software developer.

**Comment by miDeb** [comment]
Reproduction: `sort -k 2n,2n`. I sadly don't have time to further investigate this issue, but it looks like we should accept multiple options if they are compatible (in this case they're even the same option). The relevant source code is located here: https://github.com/uutils/coreutils/blob/81a2abc0944888f03b5d2d9bf878b2b851140c8b/src/uu/sort/src/sort.rs#L460
