### ISSUE TITLE
Remove `#[macro_use]` and `extern crate` and replace with normal `use`

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#4149]
We have some `#[macro_use]` on `extern crate` attributes, which are no longer necessary, since we can use normal `use` statements to import macros since Rust 1.30 and we no longer have to write `extern crate`.

In total we have 60 occurrences of `#[macro_use]` and 110 occurrences of `extern crate` in the codebase. Most of them are just importing a few error handling macros like `show!` or `show_warning!`.

**Comment by miles170** [comment]
I would like to work on this.
