### ISSUE TITLE
Swatinem/rust-cache is causing warnings in the CI

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#4154]
We see the following warning in the CI:
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

We already fixed the warnings in our own yaml files (https://github.com/uutils/coreutils/pull/4098), but `rust-cache` is still generating some.

According to https://github.com/Swatinem/rust-cache/pull/83, updating to v2 should fix the issue, but we need to check for breaking changes.

**Comment by tertsdiepraam** [comment]
Oh this one might also be partially solved by this upgrade:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Swatinem/rust-cache@v1, actions-rs/toolchain@v1
```

**Comment by miles170** [comment]
I also found out that `actions-rs/toolchain@v1` should come before `Swatinem/rust-cache@v1` since `rust-cache` uses the `rustc` version as its cache key.
