### ISSUE TITLE
tee: Remove deprecated retain_mut dependency when MSRV is >= 1.61.0

### ISSUE THREAD

**Issue by oliviacrain** [uutils/coreutils#4190]
The [`retain_mut` crate](https://crates.io/crates/retain_mut) is a dependency of the `uu_tee` crate. The functionality provided by `retain_mut` was [stabilized in the standard library](https://github.com/rust-lang/rust/pull/95491) earlier this year in the 1.61.0 release. As a result, the maintainer of `retain_mut` has marked the crate as deprecated and no longer maintains it. 

We should remove the dependency and use the standard library's functionality in `uu_tee` crate once we bump the MSRV to 1.61.0 or later. I don't think this presents a pressing reason to raise the MSRV. This is just a reminder to remove the dependency when the time comes.

**Comment by jfinkels** [comment]
Related to #3555

**Comment by tertsdiepraam** [comment]
Yeah, we can probably do this after the next release, which is when we usually bump MSRV. Thanks for making an issue for it!

**Comment by cakebaker** [comment]
This ticket can be closed, it has been implemented in https://github.com/uutils/coreutils/commit/bf8e9333f6a40469efb4e142b67ce9cc8255b265 .

**Comment by tertsdiepraam** [comment]
Indeed! I forgot that we also had an issue for it, thanks!
