### ISSUE TITLE
cp: --preserve attribute list should allow unambiguous prefixes

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#4192]
GNU cp infers the unambiguous value for an attribute name from a prefix given in the values for the `--preserve` option, but uutils cp does not.

GNU cp v8.30:
```sh
$ touch f && cp --preserve=t f g
# succeeds with no output
```

uutils cp:
```sh
$ touch f && ./target/debug/cp --preserve=t f g
error: 't' isn't a valid value for '--preserve [<ATTR_LIST>...]'
  [possible values: mode, ownership, timestamps, links, xattr, all]

For more information try '--help'
```

The same thing happens with `--preserve=ti`, `tim`, `time`, etc.

This is related to #2931, but that was about the option name (i.e. `--pr`, `--pre`, `--pres`, etc.).

This issue appears in GNU test file `tests/mv/hard-2.sh`.

**Comment by tertsdiepraam** [comment]
Does the same behaviour apply to other options as well or is it just `--preserve`?

**Comment by jfinkels** [comment]
Yes, it does apply to other options as well. And it applies to other coreutils as well. For example, `od --endian=b` is an unambiguous prefix for `--endian=big`.

**Comment by tertsdiepraam** [comment]
Good to know!

**Comment by jfinkels** [comment]
This seems fixed now.
