### ISSUE TITLE
Extract date mgmt to `uucore`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4207]
extract this to `uucore`, since it can be used in `date` as well. We could also make an issue for that after this PR of course.

_Originally posted by @tertsdiepraam in https://github.com/uutils/coreutils/issues/4193#issuecomment-1332089757_

**Comment by tertsdiepraam** [comment]
I think there's now 2 issues for this :) https://github.com/uutils/coreutils/issues/4205.

Closing this one.
