### ISSUE TITLE
`tests`: Add possibility to set timeout for tests.

### ISSUE THREAD

**Issue by Joining7943** [uutils/coreutils#4226]
I noticed during the writing of tests for `tail` which use plain `UCommand::run_no_wait` that these tests are prone to run forever. If this happens (it's not often, but if so), this test makes the CI hang for a very long time, delaying other CI runs and also destroys the test output of all tests since `cargo` is killed forcibly, somewhen. Such tests could be easily categorized as failed after 1 - 5 minutes.

The [ntest crate](https://crates.io/crates/ntest) adds some helper macros, for example to apply a `timeout` via attribute for a test. I also like the `test_case` macro which provides a nicer way to setup tests with multiple cases.

I would love to make use of `ntest` (or something similar) in some tests. As far as I'm concerned I'm currently interested in the `tail` tests, but I think it could be of use in other utils, too. If there's nothing speaking against it, I could create a pr adding `ntest` to the `dev-dependencies`.

**Comment by tertsdiepraam** [comment]
I like the timeout macro so this might indeed be nice to have. I'm also curious if we can put a timeout in `UCommand`/`UChild`?

**Comment by Joining7943** [comment]
> I like the timeout macro so this might indeed be nice to have.

yeah this would be great. I want to add, that I also tried the [rstest crate](https://crates.io/crates/rstest) after `ntest`. `rstest` also provides a timeout macro among some other useful helpers around parametrized tests and setting up fixtures. The `rstest` crate looks a little bit more advanced in my opinion than `ntest` which tries to be simplistic and lightweight. Concerning the timeout macro `rstest` accepts a `Duration` where `ntest` accepts an integer for milliseconds. Setting up parameterized tests with `rstest` was also more elaborate in my opinion. Overall, `rstest` looked more future-proof to me than `ntest`.

> I'm also curious if we can put a timeout in UCommand/UChild

For the runtime of the whole child process or only for specific functions in `UChild` like `wait` and `kill`? I think the latter would be managable, but the first could indeed be difficult to implement.

**Comment by Joining7943** [comment]
@tertsdiepraam I tried around a bit and would have a solution to set a timeout for `UChild::wait` (and `wait_with_output`) and improve the timeout for `kill`. Together with the `timeout` macro, for example from `rstest`, this should satisfy most (or maybe even all?) needs for timeouts in tests. If interested I can open a pr.

**Comment by tertsdiepraam** [comment]
That sounds great!
