### ISSUE TITLE
`rm` hangs indefinitely with named pipes

### ISSUE THREAD

**Issue by BuriedInTheGround** [uutils/coreutils#4246]
## Environment

- OS: NixOS 23.05.20221226.1eb875e (Stoat) x86_64
- uutils version: 0.0.16

## What did you do

I was trying to remove a named pipe (FIFO) file using the `rm` utility.

```
$ mkfifo myfifo

$ ls -l
total 0
prw-r--r-- 1 simone users 0 Dec 28 23:38 myfifo

$ rm --version
rm 0.0.16

$ rm myfifo
^C

$ ls -l
total 0
prw-r--r-- 1 simone users 0 Dec 28 23:38 myfifo
```

## What did you expect to see

The removal of the aforementioned named pipe (FIFO) file.

## What did you see instead

The execution of `rm` hung indefinitely, and I had to stop it (with `Ctrl+C`).

Note that, when trying with the `rm` utility provided within GNU coreutils version 9.1 the removal operation happens instantly.

```
$ ls -l
total 0
prw-r--r-- 1 simone users 0 Dec 28 23:38 myfifo

$ /nix/store/q6my4sv2vnddq5iyh12xfjvrnjrlq8cs-coreutils-full-9.1/bin/rm --version
rm (GNU coreutils) 9.1
Packaged by https://nixos.org
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Rubin, David MacKenzie, Richard M. Stallman,
and Jim Meyering.

$ /nix/store/q6my4sv2vnddq5iyh12xfjvrnjrlq8cs-coreutils-full-9.1/bin/rm myfifo

$ ls -l
total 0
```

**Comment by tertsdiepraam** [comment]
Thanks for the report! I'm not sure how it was fixed, but for me this behaviour only shows up before https://github.com/uutils/coreutils/commit/6245029445fc781fd22f508ef28c8835230c57c1. Could you check whether it works for you on `main`? I do think we need a test for this to make sure we don't regress back to this behaviour in the future.

**Comment by BuriedInTheGround** [comment]
I just tried on `main` and it works as expected! Though, I'm not good at Rust, so I won't be able to help add a test for this. I'll leave this issue open as a reminder. Thank you for reviewing my issue!

**Comment by tertsdiepraam** [comment]
No worries, I made a test in the linked PR. Thanks for verifying that it works on `main`!
