### ISSUE TITLE
`ci/tests`: Run cargo test with RUST_BACKTRACE

### ISSUE THREAD

**Issue by Joining7943** [uutils/coreutils#4250]
Is there any drawback running the tests with backtrace in the CI? I think, the backtrace would be helpful information, especially because we run most of the assertions in `tests/common/util.rs` and in case of intermittent failures.

**Comment by sylvestre** [comment]
yeah, would be great, don't hesitate to add it

**Comment by Joining7943** [comment]
ok, I'll give it a try

**Comment by tertsdiepraam** [comment]
In addition to this, I think we could add `#[track_caller]` to the assertion functions in `tests/common/util.rs` so we get better messages even without `RUST_BACKTRACE`.

**Comment by Joining7943** [comment]
That's nice. Didn't knew such an attribute existed. I'm adding it in the associated pr #4251.

**Comment by tertsdiepraam** [comment]
I just opened a PR already :)

**Comment by Joining7943** [comment]
oh ok. sorry haven't seen it. I'll remove the last commit.
