### ISSUE TITLE
`tests/util`: `UCommand`: Use `Stdio::null` as default `stdin` for the spawned child process

### ISSUE THREAD

**Issue by Joining7943** [uutils/coreutils#4257]
I stumbled over this during the write of `UChild` and wondered if it wouldn't be better to use `Stdio::null` as default for the `stdin` of the `Child` instead of `Stdio::piped`. I left two `TODOs` in `tests/commond/util.rs`, although the `TODO` description isn't appropriate anymore.

Firstly, I think it's counterintuitive that each spawned `Child` in a test case has a `stdin` pipe per default. The default situation in a shell is also to not have a pipe. So, if not explicitly asked to build a pipe to the child process `stdin` (for example with `UCommand::pipe_in` or `UCommand::set_stdin`) `Stdio::null` should be used. Secondly, there *shouldn't* be any deadlock situations anymore because of piped input, but it's still safer to not use pipes if not necessary.

Maybe around 10 tests would be affected by that change and would need an additional `set_stdin(Stdio::piped)` in the `UCommand` builder. On the other hand a lot of tests in `tests_tail` use `set_stdin(Stdio::null)` which would become redundant.

**Comment by tertsdiepraam** [comment]
That seems to make sense!

**Comment by Joining7943** [comment]
Ok, I'll create a PR for it.
