### ISSUE TITLE
docs: missing bars on test coverage page

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#4276]
On https://uutils.github.io/user/test_coverage.html, the bar for the "split" tests is missing:

![Screenshot_20230112_test_coverage](https://user-images.githubusercontent.com/26196/212005380-5f6ebe62-e424-42c0-b8f8-4ee9649ae3c0.png)

The problem is probably caused by invalid data in `gnu-full-result.json` on lines 573 and 576: https://github.com/uutils/coreutils-tracking/blob/main/gnu-full-result.json#L573. Line 573 contains `shell-init:` instead of `PASS` or `FAIL`, and on line 576 `PASS` is prefixed with many numerical digits.

**Comment by cakebaker** [comment]
In the meantime, the bar for the "misc" tests is missing, too. It's probably because of [line 307](https://github.com/uutils/coreutils-tracking/blob/main/gnu-full-result.json#L307): it contains `+nice:` instead of `PASS` or `FAIL`.

**Comment by sylvestre** [comment]
Fun
I guess it should not be hard to fix
