### ISSUE TITLE
Bump MSRV to 1.64?

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#4286]
With a new release tagged, we have the opportunity to bump the MSRV again.

With [1.61](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html) we would get:
- `retain_mut`, which unblocks https://github.com/uutils/coreutils/issues/4190
- The `Termination` trait which might simplify the `uumain` proc macro.

With [1.62](https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html):
- `#[derive(Default)]` for enums

With [1.63](https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html):
- Scoped threads

With [1.64](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html):
- Workspace inheritance, which will simplify the dependencies.
- [os::unix::process::CommandExt::process_group](https://doc.rust-lang.org/stable/std/os/unix/process/trait.CommandExt.html#tymethod.process_group)

With [1.65](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html):
- `let ... else` (though this still breaks rustfmt)

With [1.66](https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html)
- `..=X` ranges
- `Duration::try_from_secs_{f32, f64}`

I think workspace inheritance would be a big improvement for this project, so I would propose to bump directly to 1.64.

**Comment by sylvestre** [comment]
sure, let's do it :)
