### ISSUE TITLE
The utf-8 crate is unmaintained

### ISSUE THREAD

**Issue by SimonSapin** [uutils/coreutils#4289]
This is to let you know that I’ve archived https://github.com/SimonSapin/rust-utf8, the source repository for https://crates.io/crates/utf-8 which https://crates.io/crates/uu_wc depends on. No action is required as I’m not planning the yank the crate, and it’s small enough that it’s possibly bug-free. However if at some point you still need changes in it, you’ll be better off copying relevant code into your own repository.

**Comment by sylvestre** [comment]
ok, merci Simon :)

**Comment by n0bml** [comment]
I'm an experienced developer and I've been learning Rust.  If there's no one else already working on this I'd like to take a stab at it.

**Comment by tertsdiepraam** [comment]
@n0bml What would you like to change? Do you want to change `wc` to use a different library or do you want to incorporate the code from this crate into uutils?

**Comment by n0bml** [comment]
@tertsdiepraam I hadn't gotten that far yet.  I was thinking of incorporating the code from the create into uutils as Simon mentioned.  I'm open to whatever is best for the project and have no strong feelings either way.

**Comment by tertsdiepraam** [comment]
Alright, let's see how much code from that crate we need and try to incorporate that!

**Comment by stefins** [comment]
@n0bml Are you still working on this issue?

**Comment by n0bml** [comment]
@stefins yes but some critical problems at my day job have eaten up my free time.  Hopefully they'll be done soon and I can get back to this soon.  If there's a need for it to be faster I'm ok with someone taking it over and I'll find another way to contribute.

**Comment by stefins** [comment]
Ok fine. You can work on this. Let me know in the thread if this can't be
handled by you.
Thanks :)
