### ISSUE TITLE
Implement df

### ISSUE THREAD

**Issue by lllShamanlll** [uutils/coreutils#431]
I'd like to work on this.

**Comment by Detegr** [comment]
Any progress? If not, I could take a shot at this. It seems that there will have to be different implementations for fetching the mountpoints as Linux, OS X and Windows all have different OS level APIs for reading them. Coreutils have additional support for different unixes but I think that's a bit overkill as Rust is only supported on Linux and OS X at the moment. Maybe FreeBSD as AFAIK Rust runs on that but is not officially supported?

**Comment by framlog** [comment]
It seems no progress yet. I'm glad to work on it.

**Comment by sylvestre** [comment]
It has been implemented
