### ISSUE TITLE
q: how to cross compile single package

### ISSUE THREAD

**Issue by loeffel-io** [uutils/coreutils#4318]
Hey, just a question - i am not a rust user but i try to compile the single binaries for `base32` (linux-amd64 and darwin-arm64)

Why i can't run? 

```
cargo build -p uu_base32 --release --features macos
cargo build -p uu_base32 --release --features unix
```

Thanks 🙏

**Comment by tertsdiepraam** [comment]
Okay I hope I'm understanding correctly. The `--features` have no impact on what platform the binary is for, instead they are part of the project itself to specify which utils work on which platforms. To specify the target, you need `--target` with some target triple. For example:
```
cargo build --target=aarch64-unknown-linux-gnu -p uu_base32 --release
cargo build --target=x86_64-apple-darwin -p uu_base32 --release
```

Note that you need the toolchains for these targets installed.

**Comment by loeffel-io** [comment]
Thank you very much for this explanation
