### ISSUE TITLE
discord invitation is invalid

### ISSUE THREAD

**Issue by howjmay** [uutils/coreutils#4334]
As the title, the invitation of discord is invalid. 

BTW another extra question is I saw there are some commands that don't exist in GNU coreutils doc. Like `env -f`. I can't find the `-f` option in the document which is the following link.
https://www.gnu.org/software/coreutils/manual/html_node/env-invocation.html#env-invocation

May I ask where does the option come from?

**Comment by tertsdiepraam** [comment]
What discord invitation are you talking about? The ones in the README and the docs seem to work for me.

**Comment by howjmay** [comment]
I was using the one in readme. Once I clicked it, I am directed to this page 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/13924801/217893357-6626e521-43db-40f4-8493-1b71513c188d.png">

**Comment by howjmay** [comment]
> About the `env` option, I just made a PR to document it: #4331 :)
> 
> In general, we try to document them on this page: https://uutils.github.io/user/extensions.html

Thank you! 
So may I interpret it as, basically coreutils is totally the same as GNU coreutils. The only differences are listed in this page 
docs/src/extensions.md

**Comment by tertsdiepraam** [comment]
Does this link work? https://discord.gg/AkXMzywXZ4

> So may I interpret it as, basically coreutils is totally the same as GNU coreutils. The only differences are listed in this page
docs/src/extensions.md

That's what we aim for, but there are missing features and bugs of course. We treat almost any difference with GNU as a bug.

**Comment by tertsdiepraam** [comment]
Some people have entered the Discord server in the meantime, so I'm gonna assume that this is not our fault and close this issue. Otherwise you could look here: https://support.discord.com/hc/en-us/articles/360001556852-Invalid-Invite-Links
