### ISSUE TITLE
`which cat` still gives `/bin/cat` after installation

### ISSUE THREAD

**Issue by AndyJado** [uutils/coreutils#4336]
how do I use it..

**Comment by tertsdiepraam** [comment]
How did you install it? The directory that you installed it in needs to be in the `$PATH` variable before `/bin`.

**Comment by AndyJado** [comment]
oh I see..

`Usage: coreutils [function [arguments...]]`

---


what you say if `README.md` looks more like this, 

```markdown
## installation

$ cargo install coreutils

## Usage

$ ~/.cargo/bin/coreutils
```
