### ISSUE TITLE
Replace `num_cpus` crate with `std::thread::available_parallelism`

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#4351]
`nproc` uses the `num_cpus` crate, but this functionality has been added to `std` in the form of [`std::thread::available_parallelism`](https://doc.rust-lang.org/stable/std/thread/fn.available_parallelism.html). I suggest we move over. I _think_ there's no problem in doing this, though there are slight differences between `num_cpus` and `std`: https://github.com/seanmonstar/num_cpus/issues/119.

**Comment by rgasnix** [comment]
Can I work on this ?

**Comment by tertsdiepraam** [comment]
Yeah go ahead!
