### ISSUE TITLE
Panic in `timeout` with some multi-byte characters when parsing duration (instead of error)

### ISSUE THREAD

**Issue by fwip** [uutils/coreutils#4353]
Reproduction: First, build timeout. Then run: `./target/debug/timeout 10€ echo "this will panic"`
```
thread 'main' panicked at 'byte index 4 is not a char boundary; it is inside '€' (bytes 2..5) of `10€`', src/uucore/src/lib/parser/parse_time.rs:54:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This comes from uucore's `parse_time`: https://github.com/uutils/coreutils/blob/main/src/uucore/src/lib/parser/parse_time.rs#L54
A similar panic might be present in `sleep` or `du`, as they also call parse_time. A fix could be to switch from bracket-slicing to `string.get(..len-1)` and then handle the `None` case explicitly. Alternately, you could use the approach used in `parse_time`, where you loop through the leading ascii numbers and then check the remainder of the string.

Related: I found this bug via cargo-fuzz, it looks like there's been some activity in #1147 about this.

**Comment by sylvestre** [comment]
@fwip 
> Related: I found this bug via cargo-fuzz, it looks like there's been some activity in https://github.com/uutils/coreutils/issues/1147 about this.

Cool, would it be possible to share your code to add it in https://github.com/uutils/coreutils/pull/4389 ?

**Comment by fwip** [comment]
Sure, the 3 fuzz targets I wrote were:

```rust
#![no_main]

use libfuzzer_sys::fuzz_target;
use uucore::parse_glob;

fuzz_target!(|data: &[u8]| {
    if let Ok(s) = std::str::from_utf8(data) {
        _ = parse_glob::from_str(s)
    }
});
```

```rust
#![no_main]

use libfuzzer_sys::fuzz_target;
use uucore::parse_size::parse_size;

fuzz_target!(|data: &[u8]| {
    if let Ok(s) = std::str::from_utf8(data) {
        _ = parse_size(s);
    }
});
```

```rust
#![no_main]

use libfuzzer_sys::fuzz_target;
use uucore::parse_time;

fuzz_target!(|data: &[u8]| {
    if let Ok(s) = std::str::from_utf8(data) {
        _ = parse_time::from_str(s);
    }
});
```

You can feel free to use them as you like. 👍
