### ISSUE TITLE
chmod fails to change permissions if files missing

### ISSUE THREAD

**Issue by OH-AU** [uutils/coreutils#4355]
This behaviour is different to the GNU utilities:
Tested with coreutils ver. 0.0.17

In a directory that contains only .py files (and therefore no .sh files)
chmod u+x *.sh *.py

Rust reports: chmod: cannot access '*.sh': No such file or directory
and does NOT change the execute bit on any files.

gnu reports: /usr/bin/chmod: cannot access '*.sh': No such file or directory
but DOES change the permissions of existing .py files

**Comment by tertsdiepraam** [comment]
Thanks! Should be a good first issue. We just need to print the error and continue execution instead of returning with the error. The easiest reproduction is:
```bash
$ touch b
$ chmod u+x a b
```

**Comment by dmatos2012** [comment]
Will give this a try, seems pretty easy :). Have done bit similar for another issue
