### ISSUE TITLE
Move help strings to markdown files

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#4368]
After https://github.com/uutils/coreutils/issues/2816 and https://github.com/uutils/coreutils/pull/3180, we can move all the help strings to markdown files.

Below is a list of utils that need to be converted. Let's see if GitHub's task lists are useful here. All of them should be considered good-first-issues.

If you want to pick one up, for now just create a PR and we'll update this list.

Note that some utils (like `who`) have platform-specific help texts. We should probably leave those until we have a good solution for that.

- [x] arch (https://github.com/uutils/coreutils/pull/4373)
- [x] base32 (https://github.com/uutils/coreutils/pull/3180)
- [x] base64 (https://github.com/uutils/coreutils/pull/3180)
- [x] basename (https://github.com/uutils/coreutils/pull/4391)
- [x] basenc  (https://github.com/uutils/coreutils/pull/4417)
- [x] cat (https://github.com/uutils/coreutils/pull/4375)
- [x] chcon (https://github.com/uutils/coreutils/pull/4437)
- [x] chgrp (https://github.com/uutils/coreutils/pull/4461)
- [x] chmod (https://github.com/uutils/coreutils/pull/4392)
- [x] chown (https://github.com/uutils/coreutils/pull/4450)
- [x] chroot (https://github.com/uutils/coreutils/pull/4468)
- [x] cksum (https://github.com/uutils/coreutils/pull/4516)
- [x] comm (https://github.com/uutils/coreutils/pull/4443)
- [x] cp (https://github.com/uutils/coreutils/pull/4372)
- [x] csplit (https://github.com/uutils/coreutils/pull/4474)
- [x] cut (https://github.com/uutils/coreutils/pull/4568)
- [x] date (https://github.com/uutils/coreutils/pull/4458)
- [x] dd (https://github.com/uutils/coreutils/pull/3938)
- [x] df (https://github.com/uutils/coreutils/pull/4434)
- [x] dircolors (https://github.com/uutils/coreutils/pull/4435)
- [x] dirname (https://github.com/uutils/coreutils/pull/4444)
- [x] du (https://github.com/uutils/coreutils/pull/4384)
- [x] echo (https://github.com/uutils/coreutils/pull/4471)
- [x] env (https://github.com/uutils/coreutils/pull/4472)
- [x] expand (https://github.com/uutils/coreutils/pull/4551)
- [x] expr (https://github.com/uutils/coreutils/pull/4158)
- [x] factor (https://github.com/uutils/coreutils/pull/4562)
- [x] false (https://github.com/uutils/coreutils/pull/4553)
- [x] fmt (https://github.com/uutils/coreutils/pull/4430)
- [x] fold (https://github.com/uutils/coreutils/pull/4552)
- [x] groups (https://github.com/uutils/coreutils/pull/4554)
- [x] hashsum (https://github.com/uutils/coreutils/pull/4563)
- [x] head (https://github.com/uutils/coreutils/pull/4564)
- [x] hostid (https://github.com/uutils/coreutils/pull/4575)
- [x] hostname (https://github.com/uutils/coreutils/pull/4473)
- [x] id (https://github.com/uutils/coreutils/pull/4585)
- [x] install (https://github.com/uutils/coreutils/pull/4469)
- [x] join (https://github.com/uutils/coreutils/pull/4583)
- [x] kill (https://github.com/uutils/coreutils/pull/4395)
- [x] link (https://github.com/uutils/coreutils/pull/4423)
- [x] ln (https://github.com/uutils/coreutils/pull/4424)
- [x] logname (https://github.com/uutils/coreutils/pull/4587)
- [x] ls (https://github.com/uutils/coreutils/pull/4454)
- [x] mkdir (https://github.com/uutils/coreutils/pull/4403)
- [x] mkfifo (https://github.com/uutils/coreutils/pull/4506)
- [x] mknod (https://github.com/uutils/coreutils/pull/4529)
- [x] mktemp (https://github.com/uutils/coreutils/pull/4547)
- [x] more (https://github.com/uutils/coreutils/pull/4589)
- [x] mv (https://github.com/uutils/coreutils/pull/4590)
- [x] nice (https://github.com/uutils/coreutils/pull/4591)
- [x] nl (https://github.com/uutils/coreutils/pull/4477)
- [x] nohup (https://github.com/uutils/coreutils/pull/4415)
- [x] nproc (https://github.com/uutils/coreutils/pull/4579)
- [x] numfmt (https://github.com/uutils/coreutils/pull/3180)
- [x] od (https://github.com/uutils/coreutils/pull/4406)
- [x] paste (https://github.com/uutils/coreutils/pull/4650)
- [x] pathchk (https://github.com/uutils/coreutils/pull/4651)
- [x] pinky (https://github.com/uutils/coreutils/pull/4701)
- [x] pr (https://github.com/uutils/coreutils/pull/4678)
- [x] printenv (https://github.com/uutils/coreutils/pull/4485)
- [x] printf (https://github.com/uutils/coreutils/pull/4705)
- [x] ptx (https://github.com/uutils/coreutils/pull/4422)
- [x] pwd (https://github.com/uutils/coreutils/pull/4455)
- [x] readlink (https://github.com/uutils/coreutils/pull/4770)
- [x] realpath (https://github.com/uutils/coreutils/pull/4429)
- [x] relpath (https://github.com/uutils/coreutils/pull/4491)
- [x] rm (https://github.com/uutils/coreutils/pull/4413)
- [x] rmdir  (https://github.com/uutils/coreutils/pull/4412)
- [x] runcon (https://github.com/uutils/coreutils/pull/4774)
- [x] seq (https://github.com/uutils/coreutils/pull/4779)
- [x] shred (https://github.com/uutils/coreutils/commit/015de7293183b238127849af2bc62e32c1d61c19)
- [x] shuf (https://github.com/uutils/coreutils/pull/4421)
- [x] sleep (https://github.com/uutils/coreutils/pull/4411)
- [x] sort (https://github.com/uutils/coreutils/pull/4808)
- [x] split (https://github.com/uutils/coreutils/pull/4785)
- [x] stat (https://github.com/uutils/coreutils/pull/4367)
- [x] stdbuf (https://github.com/uutils/coreutils/pull/4792)
- [x] stty (https://github.com/uutils/coreutils/pull/4797)
- [x] sum (https://github.com/uutils/coreutils/pull/4799)
- [x] sync (https://github.com/uutils/coreutils/pull/4800)
- [x] tac (https://github.com/uutils/coreutils/pull/4394)
- [x] tail (https://github.com/uutils/coreutils/pull/4426)
- [x] tee (https://github.com/uutils/coreutils/pull/4425)
- [x] test (https://github.com/uutils/coreutils/pull/4816)
- [x] timeout (https://github.com/uutils/coreutils/pull/4806)
- [x] touch (https://github.com/uutils/coreutils/pull/4581)
- [x] tr (https://github.com/uutils/coreutils/pull/4805)
- [x] true (https://github.com/uutils/coreutils/pull/4703)
- [x] truncate (https://github.com/uutils/coreutils/pull/4456)
- [x] tsort (https://github.com/uutils/coreutils/pull/4829)
- [x] tty (https://github.com/uutils/coreutils/pull/4837)
- [x] uname (https://github.com/uutils/coreutils/pull/4476)
- [x] unexpand (https://github.com/uutils/coreutils/pull/4704)
- [x] uniq (https://github.com/uutils/coreutils/pull/4681)
- [x] unlink (https://github.com/uutils/coreutils/pull/4675)
- [x] uptime (https://github.com/uutils/coreutils/pull/4518)
- [x] users (https://github.com/uutils/coreutils/pull/4570)
- [x] wc (https://github.com/uutils/coreutils/pull/4453)
- [x] who (https://github.com/uutils/coreutils/pull/4549)
- [x] whoami (https://github.com/uutils/coreutils/pull/4519)
- [x] yes (https://github.com/uutils/coreutils/pull/4390)

**Comment by zleyyij** [comment]
It doesn't appear to be possible to Convert to Issue with my permissions, I checked on multiple browsers and proved that it was working on a project where I have sufficient perms.

**Comment by tertsdiepraam** [comment]
Oh I hoped that would be possible. That's too bad. I'll figure out some other way to track this. In the meantime you can just create a PR and I'll update the list manually.

**Comment by tertsdiepraam** [comment]
We could just accept PRs that mention the utils they update and then we manually update, but that's not a great solution. Also, with a project like this, we get situations like this quite often, so I'd like to find a better solution. @sylvestre any ideas?

**Comment by cakebaker** [comment]
What should be the order of the sections inside the markdown files? Currently half of the files use

```
Usage
About
...
```
and the other half:
```
About
Usage
...
```

**Comment by tertsdiepraam** [comment]
Hmm good question. Both will work, but I think I prefer usage first, because that's also how it shows up in `clap` and in the online docs. Maybe we should even change the macro for the usage to parse the code block directly below the title, so you can write:
````md
# numfmt
```
numfmt [OPTION]... [NUMBER]...
```

## About

Convert numbers from/to human-readable strings
````

Do you have a preference one way or the other?

**Comment by tertsdiepraam** [comment]
Ah I see, that would require a separate macro for the about text I suppose. I like that it enforces a strict format. Do you want to implement that?

**Comment by cakebaker** [comment]
Yes.

**Comment by sylvestre** [comment]
Looks like we are good ?! :)
cc @tertsdiepraam

**Comment by tertsdiepraam** [comment]
Wow, that's great! Thanks everyone!

**Comment by sylvestre** [comment]
yeah, bravo :)
