### ISSUE TITLE
Migrate from `atty` to `is-terminal`

### ISSUE THREAD

**Issue by Joining7943** [uutils/coreutils#4377]
`cargo deny` gives an advisory warning about `atty` and it doesn't look like this will be fixed anytime soon because the `atty` crate doesn't seem to be actively maintained anymore.

`is-teminal` in contrast is maintained, is a port of `atty` with this bug fixed and has some additional features. It looks like the better choice and although the api is different, migrating `uutils` should not be a too big task. It's changing a line with `atty::is(atty::Stream::Stdout)` to `std::io::stdout().is_terminal()` (or other streams).

**Comment by tertsdiepraam** [comment]
Also `is-terminal` is already a dependency of clap, so it's already part of our dependency graph.

**Comment by rgasnix** [comment]
If someone isn't already working on it, I'm interested to work on this issue.

**Comment by Joining7943** [comment]
Sure, you can go ahead as far as I'm concerned.
