### ISSUE TITLE
Unsound local offset bug when installing from sources, but not on build.

### ISSUE THREAD

**Issue by Ygg01** [uutils/coreutils#4489]
> error: The `unsound_local_offset` flag was removed in time 0.3.18. If you need this functionality, see the `time::util::local_offset::set_soundness` function.
>    --> C:\Users\omitted\\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.3.20\src\lib.rs:138:1
>     |
> 138 | / compile_error!(
> 139 | |     "The `unsound_local_offset` flag was removed in time 0.3.18. If you need this fu...
> 140 | |      see the `time::util::local_offset::set_soundness` function."
> 141 | | );
>     | |_^

Cargo: `v1.68.0`
Rust: rustc 1.68.0 (2c8cc3432 2023-03-06)
Windows 10

**Comment by cakebaker** [comment]
What do you mean with "installing from sources, but not on build"? What command(s) do you use? For some reason the version of the `time` crate in the error message is newer than what is defined in `Cargo.lock`.

**Comment by Ygg01** [comment]
I ran the following commands:
```sh
git clone https://github.com/uutils/coreutils
cd coreutils
cargo build --release # passed
cargo install --path . # returned the error
```

**Comment by samueltardieu** [comment]
You must  use `cargo install --path . --locked` if you want to honor `Cargo.lock`. I'll open a PR with a fix to the `README.md`.

**Comment by tertsdiepraam** [comment]
Yep @samueltardieu is right, that is indeed the fix and the readme change sounds good. Another question: did you try to build and install it separately? Because that shouldn't be necessary but that might be unclear in the readme.

**Comment by Ygg01** [comment]
@tertsdiepraam yeah I did, although command `cargo install --path . --locked` still gets the same failure.
