### ISSUE TITLE
fuzzing on date: `date -I @` triggers a panic

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4494]
Found with the fuzzer introduced in https://github.com/uutils/coreutils/pull/4389
```
$ ../target/debug/coreutils date -I@
thread 'main' panicked at 'Invalid format: @', src/uu/date/src/date.rs:118:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by shanmukhateja** [comment]
I ran the same on GNU `date` and I see this.

```
$ date -I@
date: invalid argument ‘@’ for ‘--iso-8601’
Valid arguments are:
  - ‘hours’
  - ‘minutes’
  - ‘date’
  - ‘seconds’
  - ‘ns’
Try 'date --help' for more information.
```

@sylvestre What should the correct response be in this case?

**Comment by sylvestre** [comment]
at least 
```
date:` invalid argument ‘@’ for ‘--iso-8601’
```
would be great

**Comment by shanmukhateja** [comment]
So do I just update the String in panic! or is there a something more you'd like me to add?

**Comment by shanmukhateja** [comment]
@sylvestre I noticed the panic is placed inside the `impl` for `Iso8601Format` enum.  I went ahead and updated the error message to look like GNU's `date`.

After the change, the output is as follows:

**Failed case:**
```sh
$ target/debug/date -I@    
thread 'main' panicked at 'date:` invalid argument `@` for '--iso-8601'', src/uu/date/src/date.rs:118:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Success case:**
```sh
target/debug/date -Ihours
2023-03-12T11+05:30
```

**Comment by tertsdiepraam** [comment]
Note that the comment on this panic says that this case should have been handled by clap, but it wasn't. So probably we need to add a value parser to the argument in clap.
