### ISSUE TITLE
 Add `file` Command-Line Utility.

### ISSUE THREAD

**Issue by basicfunc** [uutils/coreutils#4509]
As a user of the `uutils/coreutils` package, I have noticed that it does not include a `file` command-line utility, which is a basic part of many other Unix-like operating systems, and could be useful to windows users too. The `file` utility is used to determine the type of a file based on its contents, and is an essential tool for working with various types of files.

Therefore, I propose that a `file` command-line utility be added to the `uutils/coreutils` package, along with appropriate documentation and testing. This would improve the usability and completeness of `uutils/coreutils` package itself , and make it more consistent with other Unix-like systems.

I have created a small implementation of the "file" utility myself, which I would be happy to contribute to the project. However, I believe that this is a basic utility that should be included as part of the `uutils/coreutils` package, and not left up to third-party contributions.

My [implementation](https://github.com/basicfunc/file) of `file` can be tracked here.

**Comment by basicfunc** [comment]
Yes you're right. I apologize for the mistake in my previous response. You are correct that the `file` command is not part of the GNU Core Utilities.
But it is still a standard tool that is typically installed on almost all Unix-based systems So won't this be a useful thing to add?

**Comment by sylvestre** [comment]
sure, happy to take in the uutils org next to https://github.com/uutils/findutils
