### ISSUE TITLE
CI: linting and formatting checks for FreeBSD

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#4513]
Currently, we only lint for Linux, Mac and Windows, but not for FreeBSD. We do test on FreeBSD, but we don't run clippy and rustfmt.

This makes us miss some warnings: https://github.com/uutils/coreutils/pull/4512

**Comment by sylvestre** [comment]
@miles170 would you like to do it?

**Comment by sylvestre** [comment]
i think we should create a new task for this. not reusing the current build/test on freebsd

**Comment by miles170** [comment]
I can handle this.

**Comment by miles170** [comment]
@sylvestre Add two tasks `Style/lint and Format/style`, or just one?

**Comment by sylvestre** [comment]
as we have intermittent issues with freebsd, maybe merge them?
