### ISSUE TITLE
Checksum-related commands not found on macOS M1

### ISSUE THREAD

**Issue by ivaquero** [uutils/coreutils#4517]
I installed `uutils-coreutils` using `homebrew`, most commands work well except checksum-related commands like `sha*sum` and `md5sum` not found.

I am not sure the problem is on `coreutils` side or `homebrew` side.

OS: macOS Monterrey (M1 chip)
coreutils version: 0.017

**Comment by sylvestre** [comment]
It is probably a homebrew issue.
