### ISSUE TITLE
date should return error status on unparseable date

### ISSUE THREAD

**Issue by dfandrich** [uutils/coreutils#4525]
This invocation should return an error status and not the *But it failed!* message, but that's not what it does (on 0.0.17 on Alpine x86_64):
```
~ # uutils-date -d foo && echo But it failed!
uutils-date: invalid date 'foo'
But it failed!
```
date should return an error status when the `-d` string can't be parsed, just like GNU coreutils, Busybox, FreeBSD and Solaris already do.

**Comment by tertsdiepraam** [comment]
Thanks! Seems like we were returning 1 in a lot of other cases, but missed this one :)
