### ISSUE TITLE
Fix `usage of wildcard import` found by clippy pedantic

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4531]
I wish clippy had a --fix for that but it isn't the case (yet?)

```
[...]
warning: usage of wildcard import
 --> tests/by-util/test_whoami.rs:6:5
  |
6 | use crate::common::util::*;
  |     ^^^^^^^^^^^^^^^^^^^^^^ help: try: `crate::common::util::{TestScenario, expected_result, is_ci, whoami}`
  |
[...]
```
To reproduce:
`cargo +nightly clippy --features unix --allow-dirty --fix -- -W clippy::pedantic`

**Comment by tertsdiepraam** [comment]
Rust analyzer has an assist called `expand_glob_import` that could help out here.

https://rust-analyzer.github.io/manual.html#assists-code-actions

**Comment by cakebaker** [comment]
I was able to auto-fix it with `cargo clippy --fix --allow-dirty -- -W clippy::wildcard_imports`
