### ISSUE TITLE
`date -f /` is doing an infinite loop on `Is a directory`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4539]
Found with the fuzzer introduced in https://github.com/uutils/coreutils/pull/4389

`target/debug/coreutils date -f / `
runs forever.

strace shows 

```
read(3, 0x561efbdd70e0, 8192)           = -1 EISDIR (Is a directory)
read(3, 0x561efbdd70e0, 8192)           = -1 EISDIR (Is a directory)
read(3, 0x561efbdd70e0, 8192)           = -1 EISDIR (Is a directory)
```
while `date -f /`  on  GNU returns immediately without any message (which might be a bug)

**Comment by shanmukhateja** [comment]
@sylvestre I'd like to give this a try.

**Comment by tertsdiepraam** [comment]
This issue is related: https://github.com/rust-lang/rust/issues/64144 (but they seem reluctant to change the behaviour)

**Comment by shanmukhateja** [comment]
Yes, I agree. It is definitely related to Files not returning when accessing a directory.

**Comment by tertsdiepraam** [comment]
We should probably check our entire codebase for this, basically every time we call `BufReader::lines()` this issue could be present.

**Comment by tertsdiepraam** [comment]
Okay, I actually don't think this is a footgun anymore. The problem is actually on our side, because we explicitly ignore the errors, which obviously doesn't get us the right behaviour. This would fix it for instance:
```diff
             DateSource::File(ref path) => {
                 file = File::open(path).unwrap();
                 let lines = BufReader::new(file).lines();
-                let iter = lines.filter_map(Result::ok).map(parse_date);
+                let iter = lines.map_while(Result::ok).map(parse_date);
                 Box::new(iter)
             }
             DateSource::Now => {
```
