### ISSUE TITLE
`test '(' foo --1 ` should not panic

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4556]
Working on a fuzzer for test:

```
$ ./target/debug/coreutils test '(' foo --1
thread 'main' panicked at 'expected ‘)’', src/uu/test/src/parser.rs:145:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

GNU returns:
```

$ LANG=C /usr/bin/test '(' foo --1
/usr/bin/test: 'foo': binary operator expected
```

See also:
https://github.com/uutils/coreutils/issues/4555

**Comment by leon3s** [comment]
Hey looking at the code and the commentaries this require to rewrite some function to handle a `Result` you want a custom `ParserError` ? or you prefer the use `ErrorKind::Custom` ?

**Comment by sylvestre** [comment]
I guess custom parser error would be nicer, no ? :)

**Comment by leon3s** [comment]
Sure
