### ISSUE TITLE
`dircolors` on a folder causes an infinite loop

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#4573]
Similar to https://github.com/uutils/coreutils/issues/4539, with a very similar cause.

These two lines found with `rg -F ".filter_map(Result::ok)"` ignore errors and make the iterators which makes the iterators get stuck in an infinite loop:
```
uu/dircolors/src/dircolors.rs
142:        result = parse(fin.lines().filter_map(Result::ok), &out_format, files[0]);
147:                result = parse(fin.lines().filter_map(Result::ok), &out_format, files[0]);
```

GNU just seems to ignore the error:
```shell
$ dircolors src
LS_COLORS='';
export LS_COLORS 
```

See https://github.com/uutils/coreutils/issues/4539#issuecomment-1479217834 for a possible way to fix this.

**Comment by cakebaker** [comment]
@clanghans thanks for the hint :)
