### ISSUE TITLE
`chown -v --from=42 43` isn't showing a message

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4615]
With GNU:
```
$ touch f
$ chown -v --from=42 43 f
ownership of 'f' retained as sylvestre
```

Nothing is showed with our implementation

To run it:
` fakeroot bash util/run-gnu-test.sh   tests/chown/basic.sh `

**Comment by MehSalhi** [comment]
I would love to contribute to this project and tackle this issue. I might need some time to understand the general structure and ask a few questions.
