### ISSUE TITLE
CICD: [CAMetalLayer nextDrawable] returning nil because device is nil

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#4625]
The "Test Android Builds" job often fails and in the logs there are a lot of errors like:

```
2023-03-25 01:54:45.442 qemu-system-x86_64[6098:21646] [CAMetalLayer nextDrawable] returning nil because device is nil.
```

**Comment by sylvestre** [comment]
I also see:
  process didn't exit successfully: `/data/data/com.termux/files/home/coreutils/target/debug/deps/tests-b6e0f0a5ea3141df` (signal: 31, SIGSYS: bad system call)

**Comment by jtracey** [comment]
The "cargo is not installed" error was because of a dependency error with rust and libllvm 16. It was resolved yesterday in https://github.com/termux/termux-packages/pull/15876, so that should be fixed now with a clean cache (and indeed, I see the latest CICD runs don't encounter that). No idea what the other two issues are caused by though.

**Comment by jtracey** [comment]
Ah, the issue with the CAMetalLayer warnings appears to be https://github.com/actions/runner-images/issues/6365 (note the last comment:
>The issue caused by the low performance of the runner hosts it is reproduced locally it and does not depends on the software configuration. It is expected to be solved with the hardware upgrade.

That just leaves the SIGSYS errors.

**Comment by cakebaker** [comment]
Closing this ticket as the issue no longer appears.

**Comment by sotengboy** [comment]
> Closing this ticket as the issue no longer appears.

Did you fix that error? Please explain it to me. I got the exact same error.

**Comment by cakebaker** [comment]
@sotengboy unfortunately I don't know what exactly fixed the issue :| Maybe it helps to have a look at our [workflow](https://github.com/uutils/coreutils/blob/main/.github/workflows/android.yml) and compare it with yours. Hope that helps.
