### ISSUE TITLE
`date -f dates.txt` is failing

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4657]
```
$ echo "2023-03-27 08:30:00" > dates.txt
$ echo "2023-04-01 12:00:00" >> dates.txt
$ echo "2023-04-15 18:30:00" >> dates.txt

$ ./target/debug/coreutils date -f dates.txt "+%Y-%m-%d %H:%M:%S"
date: invalid date '2023-03-27 08:30:00'
date: invalid date '2023-04-01 12:00:00'
date: invalid date '2023-04-15 18:30:00'
```
With GNU:
```
2023-03-27 08:30:00
2023-04-01 12:00:00
2023-04-15 18:30:00
```

**Comment by tertsdiepraam** [comment]
I think that the date parsing in `touch` is more advanced than in `date`. If we share that implementation this could be fixed quite easily. (They share implementations in GNU too)

**Comment by Benjscho** [comment]
Time parsing in `date` and `touch` is provided by [`parse-datetime`](https://github.com/coreutils/gnulib/blob/master/lib/parse-datetime.y) - which is a yacc implementation of parsing. Seems as though the main parsing order is as described [here](https://github.com/coreutils/gnulib/blob/master/lib/parse-datetime.y#L610-L658). Should be possible to implement parsing in the same order and features either through `if let Ok()` parse success matching (as is currently done in `touch` and your PR @tertsdiepraam), or potentially a yacc parser using [grmtools](https://github.com/softdevteam/grmtools). 

I'm going to look into providing a lib function that provides this kind of loose parsing and returns a DateTime object, will see if I can make something that can drop in to `date`. It could then be tested against `gnulib/tests/test-parse-datetime.c`. I'm guessing it would be best to avoid any further dependencies, so I'll try the first approach of result based successes.

**Comment by tertsdiepraam** [comment]
Sounds good! As a general precaution, keep this line of the contribution guidelines in mind:

> uutils is original code. It cannot contain code from existing GNU or Unix-like utilities, nor should it link to or reference GNU libraries.

We have to copy the functionality without copying the code. Not looking directly at the code but only the documentation and observed behaviour is the best way to ensure that you don't (accidentally) copy it.

**Comment by Benjscho** [comment]
Thanks, that's a good reminder! I'll steer clear from the implementation.

**Comment by Benjscho** [comment]
Opened a PR that fixes this: https://github.com/uutils/coreutils/pull/4917
