### ISSUE TITLE
mv: -i shouldn't show error message if overwriting is declined

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#4724]
Setup:
```
$ mkdir example
$ touch a
$ cp a example/
```

With GNU mv:
```
$ mv a example/ -i
mv: overwrite 'example/a'? n
$ echo $?
1
```

With uutils mv:
```
$ cargo run mv a example/ -i
mv: overwrite 'example/a'? n
mv: cannot move 'a' to 'example/a': 
$ echo $?
1
```
It works fine if I specify the filename:
```
$ cargo run mv a example/a -i
mv: overwrite 'example/a'? n
$ echo $?
1
```

**Comment by sylvestre** [comment]
hmm, i am a bit confused @cakebaker 
See:
https://github.com/uutils/coreutils/pull/4630
and
https://github.com/uutils/coreutils/issues/4627

**Comment by sylvestre** [comment]
@cakebaker see upstream recent change:
https://github.com/coreutils/coreutils/commit/7a69df88999bedd8e9fccf9f3dfa9ac6907fab66

https://github.com/uutils/coreutils/pull/4731 is reverting my fix

**Comment by cakebaker** [comment]
The patch is incorrect, I added a test case in https://github.com/uutils/coreutils/pull/4731#issuecomment-1504914884
