### ISSUE TITLE
`ci`: Run shellcheck and shfmt on shell scripts in the `util` directory

### ISSUE THREAD

**Issue by Joining7943** [uutils/coreutils#4752]
Both, `shellcheck` and `shfmt` are well established tools to lint and format shell scripts. If we would run these tools in a ci job on all the scripts in the `util` directory, we would improve the readabiltiy (shfmt) and reduce common errors (shellcheck) of shell scripts.

**Comment by sylvestre** [comment]
great idea!

**Comment by tertsdiepraam** [comment]
Yeah I like it too! I thought we already had shellcheck, but it seems like I just suggested adding it to the CI (https://github.com/uutils/coreutils/pull/3013), but seems like it wasn't actually implemented.

**Comment by Joining7943** [comment]
Great!

**Comment by starccy** [comment]
Hi, I'd love to do some work to add this workflow.

**Comment by cakebaker** [comment]
@starccy: sure, go ahead :)
