### ISSUE TITLE
mv: -i -n should have different behavior than -n -i if target exists

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#4795]
When using both `-i/--interactive` and `-n/--no-clobber`, GNU mv only uses the argument that comes last if the target exists.

```
$ touch aa.txt
$ touch bb.txt
$ mv aa.txt bb.txt -i -n  # ignores -i
mv: not replacing 'bb.txt'
$ mv aa.txt bb.txt -n -i  # ignores -n
mv: overwrite 'bb.txt'?
```

With uutils mv, `-n/--no-clobber` "wins" in both cases:

```
$ touch aa.txt
$ touch bb.txt
$ cargo run mv aa.txt bb.txt -i -n
mv: not replacing 'bb.txt'
$ cargo run mv aa.txt bb.txt -n -i
mv: not replacing 'bb.txt'
```

**Comment by shinhs0506** [comment]
Looks like we just default to -n
https://github.com/uutils/coreutils/blob/a97199f72a0f3d19b7ab1dc4492ccab399a3902f/src/uu/mv/src/mv.rs#L219-L232
