### ISSUE TITLE
`pwd -P` reports incorrect results

### ISSUE THREAD

**Issue by LucasLarson** [uutils/coreutils#4855]
I’m on macOS Ventura 13.4 (22F62) using uutils-coreutils via Homebrew on iTerm2 and see different `pwd -P` results when using `uutils` instead of macOS’s default or GNU’s `coreutils`:

```console
$ mkdir /tmp/dir
$ ln -s /tmp/dir /tmp/link
$ cd /tmp/link

# GNU coreutils via Homebrew
$ ${HOMEBREW_PREFIX:-/usr/local}/opt/coreutils/libexec/gnubin/pwd -P
> /tmp/dir

$ /bin/pwd -P
> /tmp/dir

# Z Shell’s built-in implementation
$ zsh -c 'builtin pwd -P'
> /tmp/dir

# uutils-coreutils
# reports the symlinked directory
$ ${HOMEBREW_PREFIX:-/usr/local}/opt/uutils-coreutils/libexec/uubin/pwd -P
> /tmp/link
```

**Comment by ELginas** [comment]
Could not reproduce on Ubuntu 22.04. Seems to be MacOS issue?
```
el@ether:~$ mkdir /tmp/dir
el@ether:~$ ln -s /tmp/dir /tmp/link
el@ether:~$ cd /tmp/link
el@ether:/tmp/link$ pwd -P
/tmp/dir
el@ether:/tmp/link$ coreutils pwd -P
/tmp/dir
```

**Comment by LucasLarson** [comment]
You’re right. This is actually an issue with `POSIXLY_CORRECT`, which I had set to `1`.

When I unset it, then all the results match on both macOS and Ubuntu.

But this is unexpected behavior:
1. `POSIXLY_CORRECT` doesn’t change GNU’s `pwd -P` output on macOS or Ubuntu
1.  POSIX prescribes the behavior uutils’ `pwd -P` appears to have performed until [`3cb1b9466a`](https://github.com/uutils/coreutils/commit/3cb1b9466ab4fc5ab8b5032d84a49eec7ea33017)

**Comment by ELginas** [comment]
Even with `POSIXLY_CORRECT=1` set couldn't reproduce on Ubuntu 22.04.
```
el@ether:~$ mkdir /tmp/dir
el@ether:~$ ln -s /tmp/dir /tmp/link
el@ether:~$ cd /tmp/link
el@ether:/tmp/link$ pwd -P
/tmp/dir
el@ether:/tmp/link$ POSIXLY_CORRECT=1 pwd -P
/tmp/dir
el@ether:/tmp/dir$ coreutils pwd -P
/tmp/dir
el@ether:/tmp/dir$ POSIXLY_CORRECT=1 coreutils pwd -P
/tmp/dir
```

**Comment by tertsdiepraam** [comment]
Alright, thanks!

**Comment by LucasLarson** [comment]
What a pleasurable and speedy bug-reporting experience. Thank you all.
