### ISSUE TITLE
Add ebfe to uutils members

### ISSUE THREAD

**Issue by Heather** [uutils/coreutils#487]
because he is top 1 commiter in this moment and actively support the project :heart_decoration:

**Comment by Seldaek** [comment]
Oh I thought I did this already.. Will do yes, welcome @ebfe

**Comment by Seldaek** [comment]
Actually an invitation has been sent already, it just needs to be accepted at https://github.com/uutils

**Comment by ebfe** [comment]
> Actually an invitation has been sent already, it just needs to be accepted at https://github.com/uutils

Indeed. I've somehow missed the invitation mail.

Thanks everyone.
