### ISSUE TITLE
Use rust-argparse for argument parsing

### ISSUE THREAD

**Issue by tailhook** [uutils/coreutils#488]
Any chances that you would like to use http://github.com/tailhook/rust-argparse for argument parsing?

It supports types, required options, help message formatting out of the box. And overall more expressive in my opinion. I believe it would simplify command-line parsing in many utilities.

**Comment by Arcterus** [comment]
I don't like that it requires boxing everything. :/

**Comment by tailhook** [comment]
Well, it doesn't require boxing "everything". It requires boxing the "action" because that's a way in rust to get the pointer to an object that implements trait.

Anyway what specifically you don't like? The need to write `Box::new()`? (which is a little more verbose than "box something" I was using in previous versions of rust :( ). It may be possible to use generic there, but I guess using boxed pointers inside the library is inevitable.

**Comment by Arcterus** [comment]
Sorry, that's what I mean by everything.  I probably should have been more clear.

I haven't really looked through this enough to know what I think of it, but I'd rather use stack allocated memory than heap allocated memory when possible.  I'll try to take a more in-depth look at it later.

**Comment by tailhook** [comment]
@Arcterus, by the way while porting to rust alpha2 I removed boxing around argument types, and configuring argument parser looks a little less verbose now. (However, we need a collection of options to have robust parser and to generate nice help, so I don't believe it's possible to keep everything on the stack :) )

**Comment by ctjhoa** [comment]
@Arcterus what about https://github.com/docopt/docopt.rs ?
