### ISSUE TITLE
uu-head -c does not match gnu head -c behaviour

### ISSUE THREAD

**Issue by Dialga** [uutils/coreutils#4964]
```
$ head -c 1g < /dev/urandom > urand1g
head: invalid number of bytes: ‘1g’
$ head -c 1gB < /dev/urandom > urand1g
head: invalid number of bytes: ‘1gB’
$ head -c 1giB < /dev/urandom > urand1g
head: invalid number of bytes: ‘1giB’
$ head -c 1G < /dev/urandom > urand1g
$ head -c 1GB < /dev/urandom > urand1g
$ uu-head -c 1g < /dev/urandom > urand1g
$ uu-head -c 1gB < /dev/urandom > urand1g
$ uu-head -c 1giB < /dev/urandom > urand1g
$ du urand1g
1.1G    urand1g
```
Funnily uu-head works here but not gnu head, so this could be a bug in gnu head?
Otherwise this misfeature is not bug for bug compatible with gnu head.
I do note that lowercase g is missing on this line:
https://github.com/coreutils/coreutils/blob/b841f111de3e7f21c838b2e3ad2d886c21791916/src/head.c#LL913C18-L913C18

**Comment by tertsdiepraam** [comment]
Please don't link to the GNU code; for license reasons we have to base our implementation on tests and docs.

Based on [these docs](https://www.gnu.org/software/coreutils/manual/html_node/head-invocation.html), GNU indeed does not support lowercase `g`.

**Comment by Dialga** [comment]
Ok, since uutils is working as I expected here, but not coreutils head, I consider this an non-issue. But this discrepancy is worth noting.
