### ISSUE TITLE
sort: migrate from ouroboros to self_cell

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#4971]
The author of `ouroboros` recommends in https://github.com/joshua-maros/ouroboros/issues/88 to migrate to `self_cell` because of a fundamental soundness problem:

> TL;DR: Ouroboros has a soundness problem. A fix has been attempted but it was also unsound. Currently the compiler does not actually produce unsound machine code, but it may begin doing so at any point in the future. Migrate code to use [self_cell](https://github.com/Voultapher/self_cell) instead.

**Comment by tertsdiepraam** [comment]
It might also be worth checking if we can get rid of the self-references in general. However, that would be a much larger change.
