### ISSUE TITLE
`od: --skip-bytes argument '0x20E' too large`

### ISSUE THREAD

**Issue by TheDcoder** [uutils/coreutils#4981]
I apologize in advance for creating such a vague and incomplete issue, I basically have no idea how `od` works but it is [erroring out](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/issues/196#note_102416) when used in Arch Linux's `mkinitcpio` tool.

```
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
==> Using default configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux -g /boot/initramfs-linux.img --microcode /boot/intel-ucode.img
od: --skip-bytes argument '0x20E' too large
==> ERROR: invalid kernel specified: '/boot/vmlinuz-linux'
```

`mkinitcpio` is written in bash script and the problematic `od` call is specifically on this [line](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/blob/59f9d06e03c7cec1f097e2e1eeb574a65bce7c05/functions#L149):
```
offset="$(od -An -j0x20E -dN2 "$1")" || return
```

Everything works fine when GNU coreutils are used.

**Comment by sylvestre** [comment]
on my system:
```
$ od -An -j0x20E -dN2  "a"
od: --skip-bytes argument '0x20E' too large
```

**Comment by TheDcoder** [comment]
@sylvestre Thanks, now I understand that this error is only emitted when the input is not as large as `--skip-bytes`. However I repeated this experiment with GNU coreutils and got a similar error:
```
$ gnu-od -An -j0x20E -dN2  "a"
od: cannot skip past end of combined input
```

So there seems to be more to the issue...

**Comment by tertsdiepraam** [comment]
I think this bit is to blame: 

https://github.com/uutils/coreutils/blob/07c538f090327dbfe51da5341c786742dcec5eaa/src/uu/od/src/parse_nrofbytes.rs#L45-L49

We might be interpreting the E as exabytes instead of 15 😄

**Comment by TheDcoder** [comment]
@tertsdiepraam Great find! Now we just need someone to fix it, I would've submitted a PR if I knew how to code in Rust :slightly_smiling_face:

**Comment by sylvestre** [comment]
@TheDcoder probably an easy way to start ;)

**Comment by TheDcoder** [comment]
@sylvestre Indeed! I'll start reading "the book" and hopefully I'll get competent enough to fix this during the weekend :)
