### ISSUE TITLE
`cp`: Usage of `--recursive` multiple times

### ISSUE THREAD

**Issue by TheDcoder** [uutils/coreutils#5027]
It seems GNU coreutils doesn't mind if the user uses the recursive argument multiple times, this leads to incompatibility with our implementation since we reject it:

```
error: the argument '--recursive' cannot be used multiple times
```

I found this issue while using this [script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=visual-studio-code-bin#n68) which calls `cp` like this:
```bash
cp -r "${srcdir}/${_pkg}/"* "${pkgdir}/opt/${_pkgname}" -R
```

I'm not sure why it's being used like that but it works with GNU coreutils.

This issue might be more widespread as I expect other GNU utils to follow the same lenient behavior regarding arguments which set a flag.

**Comment by TheDcoder** [comment]
Turns out it was just a mistake (and not some obscure feature):

> [dcelasun](https://aur.archlinux.org/account/dcelasun) commented on [2023-07-03 11:55 (IST)](https://aur.archlinux.org/packages/visual-studio-code-bin#comment-922269)
> @TheDcoder it's just a mistake, I'll fix it in the next release. Keep in mind that coreutils (the GNU one) is mandatory for AUR packages. Third party reimplementations are unsupported. It's on them to be compatible with GNU, bug for bug.

I agree with the last statement, we should silently ignore errors like this to maintain compatibility.

**Comment by tertsdiepraam** [comment]
Yeah basically all flags in coreutils do this. In clap, we generally fix this by allowing them to override themselves, which should be turned on already. So I'm not sure what's going on there. Good catch!
