### ISSUE TITLE
`cp --preserve=links -R -H`  doesn't keep the inodes

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5031]
```
rm -rf a b c
touch a
ln -s a b
mkdir c
./target/debug/coreutils cp --preserve=links -R -H a b c
a_inode=$(ls -i c/a|sed 's,c/.*,,')
b_inode=$(ls -i c/b|sed 's,c/.*,,')
echo "$a_inode" = "$b_inode"
```

a_inode & b_inode should be the same
they aren't with our implementation

GNU test: tests/cp/link-preserve.sh

**Comment by tommady** [comment]
Hello, may I have the chance to give it a try?

Thank you

**Comment by sylvestre** [comment]
sure, just try to submit a PR :)

**Comment by sylvestre** [comment]
@tommady well done :)
I looked at the next failure in link-preserve.sh and opened if you are still interested:
https://github.com/uutils/coreutils/issues/5308
