### ISSUE TITLE
`split -1 in` should be accepted

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5033]
```
touch in
./target/debug/coreutils split -1 in
```
=> 
```
error: unexpected argument '-1' found

  tip: to pass '-1' as a value, use '-- -1'
```

It should be equivalent to `-a 1`

**Comment by tertsdiepraam** [comment]
Oh no, another shorthand?? 😄

**Comment by sylvestre** [comment]
yeah :/ Do you know what is the best way to manage it now ? :)

**Comment by tertsdiepraam** [comment]
Not really, because every util has it's own version of it. Looking at some notes I took for my own argument parser, I noted that split allows the shorthand to appear in clusters of other short arguments. And they don't have it marked as deprecated and are using it actively in the examples: https://www.gnu.org/software/coreutils/manual/html_node/split-invocation.html

**Comment by tertsdiepraam** [comment]
Ah, so it works like `uniq`. This input:
```
split -x200x1 Cargo.lock LOCK
```
works like it's `-a 2001`. With `uniq` we decided to handle it like `fold`, where the number should be separate from the rest of the arguments. We could do the same here.

**Comment by zhitkoff** [comment]
do you guys mind if I tackle this one?

**Comment by tertsdiepraam** [comment]
Absolutely! It might be a tricky one, but don't let that stop you :)

**Comment by zhitkoff** [comment]
This is a bit more complicated than supporting `split -1 in` use case. The `-1` obsolete option could also be found inside combined short options, like following (all below are valid and work with GNU `split`) 
`split -1dxe file` which means `split -l 1 -d -x -e file`
`split -ex23d file` which means `split -e -x -l 23 -d file`
etc
Might need to refactor, so I will close pull request #5170 for now and resubmit a new one with code that would handle this broader use case.

**Comment by tertsdiepraam** [comment]
I'd be fine with both cases. I think this is one of those cases where we just support what we can and hope that is satisfies everyone's use case. We've already spent so much time on these features 😄
