### ISSUE TITLE
Documentation: document modules

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5066]
display, encoding, os, etc aren't documented here:
https://uutils.github.io/dev/uucore/index.html

**Comment by Its-Just-Nans** [comment]
updated links

https://docs.rs/uucore/latest/uucore/


https://docs.rs/uucore/latest/uucore/display/index.html
https://docs.rs/uucore/latest/uucore/io/index.html
https://docs.rs/uucore/latest/uucore/os/index.html
https://docs.rs/uucore/latest/uucore/shortcut_value_parser/index.html
