### ISSUE TITLE
Documentation: document functions `args_os`, `set_utility_is_second_arg`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5069]
Some functions aren't documented here:
https://uutils.github.io/dev/uucore/index.html#functions

**Comment by allaboutevemirolive** [comment]
Error 404: File not found

**Comment by tertsdiepraam** [comment]
You can see it on docs.rs. I should get these docs back up 😅

**Comment by Its-Just-Nans** [comment]
https://docs.rs/uucore/latest/uucore/fn.args_os.html
https://docs.rs/uucore/latest/uucore/fn.get_utility_is_second_arg.html
https://docs.rs/uucore/latest/uucore/fn.set_utility_is_second_arg.html

**Comment by Its-Just-Nans** [comment]
I fix this can be closed ?
Or there is something to me done ?

**Comment by sylvestre** [comment]
I think we are good, thanks
