### ISSUE TITLE
ci: ShellScript/Format from the CheckScripts workflow fails to push commit

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#5119]
I don't know whether this is a one-time issue or a general problem because the `CheckScripts` workflow rarely runs. And running `ShellScript/Format` is even rarer. The only time it ran and tried to push a change was in https://github.com/uutils/coreutils/actions/runs/5660338720 and it failed with:
```
Error: To https://github.com/uutils/coreutils
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
Done
Pushing to https://github.com/uutils/coreutils
error: failed to push some refs to 'https://github.com/uutils/coreutils'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by tertsdiepraam** [comment]
Do we even want it to change the PR? I'm not really a fan of CI that changes the PR?
