### ISSUE TITLE
`split` should ignore values for `-d` and `-x` and support `--numeric-suffixes` and `--hex-suffixes` without values 

### ISSUE THREAD

**Issue by zhitkoff** [uutils/coreutils#5171]
GNU manpage for split:

>       -d     use numeric suffixes starting at 0, not alphabetic
> 
>        --numeric-suffixes[=FROM]
>               same as -d, but allow setting the start value
> 
>        -x     use hex suffixes starting at 0, not alphabetic
> 
>        --hex-suffixes[=FROM]
>               same as -x, but allow setting the start value

It works without specifying the value (defaults to 0 in each case). And it looks like for `-d` and `-x` options the value should not be present at all. Tested on Debian 11 and if value is specified for these, i.e. `-d7` - it is ignored and it is still set to `0`

For `uutils` the following currently fail:

`coreutils split  -d  Cargo.lock`
split: invalid suffix length: 'Cargo.lock'

and
`coreutils split  --numeric-suffixes  Cargo.lock`
split: invalid suffix length: 'Cargo.lock'

and 
`coreutils split  -x  Cargo.lock`
split: invalid suffix length: 'Cargo.lock'

and
`coreutils split  --hex-suffixes  Cargo.lock`
split: invalid suffix length: 'Cargo.lock'

Also, `uutils` version allows and uses values for `-d` and for `-x` and does not ignore them as GNU `split` does

**Comment by tertsdiepraam** [comment]
Good catch! We've fixed this in other utils by splitting the short and long options into separate `clap` args.

**Comment by zhitkoff** [comment]
Sure thing, I will work on it
