### ISSUE TITLE
Evaluate if jwalk could replace walkdir

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5176]
https://crates.io/crates/jwalk

we are using walkdir, maybe we would be faster with jwalk?
at least in:
src/uu/cp/Cargo.toml
src/uu/rm/Cargo.toml

hyperfine is great to test performances

**Comment by tertsdiepraam** [comment]
It'd be great if it would also fix https://github.com/uutils/coreutils/issues/2949

**Comment by Benjscho** [comment]
Looking into this now, created a benchmark script to test `rm` performance, baseline test against MacOs `rm`, not sure if Mac uses Gnu `rm`:

```
$ ./src/uu/rm/benchmark.sh ../linux-backup
    Finished release [optimized] target(s) in 0.13s
Benchmark 1: rm -rf tmp_d
  Time (mean ± σ):      8.830 s ±  0.248 s    [User: 0.078 s, System: 4.973 s]
  Range (min … max):    8.505 s …  9.225 s    10 runs

Benchmark 2: target/release/coreutils rm -rf tmp_d
  Time (mean ± σ):      8.825 s ±  0.399 s    [User: 0.075 s, System: 4.102 s]
  Range (min … max):    8.239 s …  9.344 s    10 runs

Summary
  target/release/coreutils rm -rf tmp_d ran
    1.00 ± 0.05 times faster than rm -rf tmp_d
```

**Comment by Benjscho** [comment]
I was testing using the [Linux source tree](https://github.com/torvalds/linux), so according to `tree`: `5439 directories, 86632 files`.

Yeah I'd assume much the same with `cp`

**Comment by Benjscho** [comment]
After using `samply` on `rm` to view the flamegraph, it was clear that all of the time was immediately spent in [remove_dir_all](https://doc.rust-lang.org/std/fs/fn.remove_dir_all.html). This means that jwalk might improve the performance of `cp` given that util doesn't use the same function at all. I'll look into this

**Comment by Benjscho** [comment]
Just looked at the flamegraph for `cp -r` as well, appears most of the time is in the copyat syscall, and only a little in `walkdir` operations (5.8%). Based on that any speedups in dirwalking would probably be quite minor. 

![image](https://github.com/uutils/coreutils/assets/47790940/76b61dc6-42ae-4c19-8216-ac013259fd47)

**Comment by tertsdiepraam** [comment]
Thanks for investigation @Benjscho! Should we close this issue in your opinion?

**Comment by tertsdiepraam** [comment]
Alright, thanks!
