### ISSUE TITLE
cat: wrong concatenation binary content

### ISSUE THREAD

**Issue by d-enk** [uutils/coreutils#5186]
```

$ cat -A /proc/1/cmdline /proc/version
/sbin/init^@splash^@Linux version 6.2.0-26-generic (buildd@bos03-amd64-042) (x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2$

$ coreutils cat -A /proc/1/cmdline /proc/version
/sbin/init^@splash^@Linux version 6.2.0-26-generic (buildd@bos03-amd64-042) (x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2$


```

But

```
$ coreutils cat /proc/1/cmdline /proc/version    
Linux version 6.2.0-26-generic (buildd@bos03-amd64-042) (x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2
/sbin/initsplash

$ cat /proc/1/cmdline /proc/version
/sbin/initsplashLinux version 6.2.0-26-generic (buildd@bos03-amd64-042) (x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2

```

**Comment by tertsdiepraam** [comment]
Something strange is going on here 🤔 It only happens in the `write_fast` branch. There's probably some misuse of `splice` or `unistd::read` or `unistd::write` there somewhere.

**Comment by gim913** [comment]
It seems that in first call to `splice()` here (when dealing with `/proc/1/cmdline`)
https://github.com/uutils/coreutils/blob/1adca622e9e1af4cbf2e6d520f7902131000dbf8/src/uu/cat/src/splice.rs#L30C48-L30C59

splice fails`[*]` and `write_fast_using_splice` exits with `Ok(true)` (so `write_fast` falls back to read + write),

there's a lock around stdout, however, lock won't cause stdout to flush, until newline appears... (and /proc/1/cmdline does not have newline)

now there comes next splice this time the one for `/proc/version` - this time it succeeds and output is written via splice_exact.

Finally something (likely process exiting?) flushes first write outputting `/sbin/init`

`[*]` - I haven't identified the cause of that failure.

This could be solved by adding explicit flush just before exiting here:
https://github.com/uutils/coreutils/blob/1adca622e9e1af4cbf2e6d520f7902131000dbf8/src/uu/cat/src/cat.rs#L447

I'm not sure if that's the right fix though

**Comment by tertsdiepraam** [comment]
Oh right, that also explains why it's only newline-less content that causes this. `flush` sounds like a pretty good solution. Would you like to submit a PR for this?

**Comment by gim913** [comment]
Here you go, I'm not sure if test makes sense / is good enough, I'm not quite sure how to replicate it in some nicer way.
(can take a look tomorrow)

**Comment by oech3** [comment]
I switched to raw-write syscall on `cat` and `tee` to bypass buffering to close different issues.
`head` and `tail` does not have the issue by some reason (because `==> /proc/1/cmdline <==` has newline?).
Ideally, we should bypass std's buffering layer and manually buffer when we diredcly touch fd (which is helpful also for `stdbuf` compatibility), or use raw-write syscall after splice always.
