### ISSUE TITLE
`uucore`: put more deps behind feature flags (for nushell)

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#5202]
Context: https://github.com/nushell/nushell/pull/10097#issuecomment-1692344427

`uucore` is quite modular in that large parts can be enabled or disabled via features. However, this does go far enough yet. There are many modules in the [mods](https://github.com/uutils/coreutils/tree/main/src/uucore/src/lib/mods) folder, that should be put behind feature flags.

This would make it so that `uucore` becomes smaller and faster to compile when only compiling a subset of utils. This is of particular interest for nushell, where we are introducing just a single util (`cp`), but have to include the entirety of `uucore`.

Fixing this should not be too hard. However, we should pay special attention to verify that every util still compiles on its own. That is, that they individually enable all the features they need. Every util should compile like this:
```
cargo build --no-default-features --features {util}
```
Ideally, we would also test this in the CI. See also https://github.com/uutils/coreutils/issues/4032

PS: Ultimately, I think `uucore` should be split into multiple crates, but that's an issue for another time. If we make it more modular now, we can also more easily split it up in the future.

**Comment by cakebaker** [comment]
Is there more work necessary for this ticket to be considered as "done" or can I close it?

**Comment by sylvestre** [comment]
is it possible to add a check in the CI to make sure we don't regress?

**Comment by cakebaker** [comment]
@sylvestre there's https://github.com/uutils/coreutils/issues/4032 or do you mean something else?

**Comment by tertsdiepraam** [comment]
@cakebaker I'm happy with this! The only thing "missing" is that clap is still required, but that is a larger issue and covered by the "compile cp without clap" issue. Thanks for working on this!
