### ISSUE TITLE
Next MSRV Bump (1.70?)

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#5214]
Our next release should be fairly soon, then we can bump the MSRV again. As @cakebaker has been diligently noting in the renovate PRs, the latest versions of some crates need a higher MSRV:

- [nix 0.27](https://github.com/uutils/coreutils/pull/5212): 1.65
- [clap 4.4](https://github.com/uutils/coreutils/pull/5200): 1.70
- [blake3 1.4.1](https://github.com/uutils/coreutils/pull/5049): 1.66
- [half 2.3](https://github.com/uutils/coreutils/pull/5005): 1.70

Furthermore, here are some reasons for upgrading ourselves:
- 1.65 brings `let`-`else` statements
- 1.66 brings inclusive ranges (`..=X`) in patterns
- 1.70 brings `OnceCell` and `OnceLock`, allowing us to remove the `once_cell` dependency
- 1.70 also brings `IsTerminal`, allowing us to remove the `is-terminal` dependency

Other considerations:
- nushell has a N-2 policy for MSRV, which means that they are currently on MSRV 1.70. So to be included in nushell we can't go beyond 1.70 at the moment.

My vote is for bumping to 1.70.

**Comment by cakebaker** [comment]
Shouldn't we also consider the Rust version used by the distros? For example, Debian unstable currently uses 1.66.

**Comment by tertsdiepraam** [comment]
Yeah we could take that into account. On the other hand, if Debian wants outdated Rust, they also get outdated uutils ;p

**Comment by sylvestre** [comment]
yeah, Debian latency on rustc isn't on purpose.
So, we should ignore this constraint

**Comment by tertsdiepraam** [comment]
Interesting! Are you planning on getting Debian more up to date?

**Comment by sylvestre** [comment]
yeah, but we need to do incremental updates , we can't skip versions
it takes time.

**Comment by sylvestre** [comment]
yeah, but we need to do incremental updates , we can't skip versions
it takes time to upgrade step by step

**Comment by cakebaker** [comment]
Ok, in that case I'm also in favor of bumping to 1.70.

**Comment by sylvestre** [comment]
we should do a new release of rust/coreutils in the next few days btw

**Comment by cakebaker** [comment]
Closing this ticket, MSRV bump was done in https://github.com/uutils/coreutils/pull/5239
