### ISSUE TITLE
`relpath` should be removed

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#5236]
`relpath` was (according to the PR that introduced it https://github.com/uutils/coreutils/pull/319) based on some FreeBSD package.

The only documentation for that I can find is this: https://www.freshports.org/sysutils/relpath/

Adding it has been discussed in GNU: https://lists.gnu.org/archive/html/coreutils/2011-11/msg00039.html, but the functionality is basically `realpath --relative-to` so a whole new util wasn't really necessary.

It seems to me that there's not a very high demand for this util if everybody seems to manage without it and FreeBSD even deprecated it.

**Comment by sylvestre** [comment]
yeah, let's remove it!
