### ISSUE TITLE
Just a link

### ISSUE THREAD

**Issue by tripleo1** [uutils/coreutils#5244]
https://github.com/jarun/advcpmv

**Comment by tertsdiepraam** [comment]
Is there anything in particular you wanted us to look at there? We used a similar repo as reference for our `cp` and `mv` progress bars (not the code but the flags used and the general behaviour): https://github.com/mrdrogdrog/advcpmv. It might even be the same patch?

**Comment by sylvestre** [comment]
Not actionable
