### ISSUE TITLE
`cp`: copy to readonly file should fail on mac

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#5257]
Found here: https://github.com/nushell/nushell/pull/10097#issuecomment-1709101338

This test should probably fail on mac too (it fails correctly on all other platforms). It is a port from a nushell test.

```rust
#[test]
fn dest_no_permissions() {
    let ts = TestScenario::new(util_name!());
    let at = &ts.fixtures;

    at.touch("valid.txt");
    at.touch("invalid_perms.txt");
    at.set_readonly("invalid_perms.txt");

    ts.ucmd()
        .args(&["valid.txt", "invalid_perms.txt"])
        .fails()
        .stderr_contains("invalid_perms.txt")
        .stderr_contains("denied");
}
```

**Comment by PGIII** [comment]
Checked on my mac and this test does fail. I added a check if the dest file is read only and that does fix it. I will open a PR with the changes i made. Also it seems `test_cp::test_cp_preserve_xattr` is failing on my mac not sure if theres an open issue for that or not
