### ISSUE TITLE
`mv`: expose main functionality for nushell

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#5293]
Part of: https://github.com/nushell/nushell/issues/10446

nushell wants access to our `mv` internals. Which means exposing the `exec` function and `Behavior` struct. Feel free to rename those to something more sensible for a public API (e.g. `move` & `Options`, to match the naming scheme from `cp`). There should be documentation for all the public items in the API as well.

This is an excellent first issue: feel free to claim this!

We did the same thing for `cp` already. You could use that PR as a guide: https://github.com/uutils/coreutils/pull/5152

**Comment by KAAtheWiseGit** [comment]
While `rm` refactoring is being discussed, I wanted to take on this issue.

I noticed `mv` uses a `Behavior` struct for options, whereas other commands use `Options`.  Would it be fine to change its name to `Options` in the PR?

**Comment by tertsdiepraam** [comment]
I think @PThorpe92 was working on this, but didn't mention that here yet. In the meantime, you could try to look at other utils. For example, the ones mentioned here: https://github.com/uutils/coreutils/issues/5088#issuecomment-1728252519. In general though, I think it's nice to make all utils as uniform as possible and I do encourage renaming as part of these PRs. Though more involved refactors should be done separately.

**Comment by PThorpe92** [comment]
Yeah I'll have a PR in today on this.

**Comment by KAAtheWiseGit** [comment]
Got it!
