### ISSUE TITLE
`cp -dR --no-preserve=links d c` should have different inodes

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5308]
```
rm -rf a b c d; mkdir d; (cd d; touch a; ln a b)
./target/debug/coreutils cp -dR --no-preserve=links d c

a_inode=$(ls -i c/a|sed 's,c/.*,,')
b_inode=$(ls -i c/b|sed 's,c/.*,,')
echo "$a_inode" = "$b_inode"
```

We should get different inodes

See https://github.com/uutils/coreutils/issues/5031 for a similar issue

On my system, why GNU:
`36311653  = 36341951`
with our impl:
`36311653  = 36311653`

Tested by
GNU test: tests/cp/link-preserve.sh
https://github.com/coreutils/coreutils/blob/master/tests/cp/link-preserve.sh#L63-L68

**Comment by tertsdiepraam** [comment]
I believe this is because `--no-preserve` is basically ignored right now 😄

**Comment by tommady** [comment]
Hi @sylvestre 
Yes I am interesting in this issue as you asked me.

May I take a shot to try this one?
Thanks.

**Comment by sylvestre** [comment]
Sure :)
