### ISSUE TITLE
fuzz: store the corpus 

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5312]
We have a few fuzzers running.
To maximize their impacts, we should store the corpus to be reused in a new run.

Maybe we could use a separate repo to store the corpus.

More info on:
https://github.com/rust-fuzz/cargo-fuzz/issues/194

**Comment by tommady** [comment]
I have a simple idea for using the GitHub action to store artifacts as the below doc described,
https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

then every time the action runs it
1. download the gziped corpus
2. running the test
3. upload a gziped corpus 

what do you think?

**Comment by sylvestre** [comment]
exactly what I had in mind :)

**Comment by tommady** [comment]
ok I'll try to create a PR for this 🙇🏻

**Comment by sylvestre** [comment]
Thanks!
