### ISSUE TITLE
`mkdir`: expose main functionality for nushell

### ISSUE THREAD

**Issue by KAAtheWiseGit** [uutils/coreutils#5321]
`mkdir`'s exec function should be exported, as per #5088.

**Comment by tertsdiepraam** [comment]
Yep we can't expose ValuesRef. Nushell wouldn't like to depend on clap if possible (we need to find a solution for other utils too). However, we can just make it accept `impl IntoIterator<OsString>` instead.

**Comment by KAAtheWiseGit** [comment]
I am doing a PR right now, and I wonder, if it makes more sense to expose `mkdir` function instead of `exec`.  It doesn't have the dot stripping GNU idiosyncrasy and it won't need a signature refactor.  Because the signature I came up with looks like this:

```Rust
pub fn exec<'a, I>(dirs: I, recursive: bool, mode: u32, verbose: bool) -> UResult<()>
where
    I: IntoIterator<Item = &'a OsString>,
```

I'll also ask the Nushell team about it.

**Comment by tertsdiepraam** [comment]
Interesting! Please make a PR. It's much easier to discuss if there's code we can reference.

**Comment by KAAtheWiseGit** [comment]
Closing this issue, as the PR got merged.

**Comment by tertsdiepraam** [comment]
Excellent, thanks!
