### ISSUE TITLE
` expr 1 \| a / 5` is producing different results than GNU

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5326]
With GNU:

```
 /usr/bin/expr 86 \> 1 \|  aR / 5
 echo $?
1
0
```

With our implementation:
```
./target/debug/coreutils expr 86 \> 1 \|  a / 5 
echo $?
expr: Expected an integer operand
2
```

**Comment by jfinkels** [comment]
It looks like the two sample command lines you shared in the description are different. Are they supposed to be the same?

**Comment by cakebaker** [comment]
The sample command can be simplified to:

```
$ expr 1 \| a / 5
1

$ ./target/debug/coreutils expr 1 \| a / 5
expr: Expected an integer operand
```

**Comment by sylvestre** [comment]
@jfinkels yeah, i should not open bugs that late :) I fixed it (and @cakebaker found a smaller test case :)
