### ISSUE TITLE
cp -a --no-preserve=mode doesn't keep fully the mode

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5327]
tested here: https://github.com/coreutils/coreutils/blob/master/tests/cp/link-preserve.sh#L82-L87 and following 
https://github.com/uutils/coreutils/issues/5308
```
rm -rf a b
touch a; chmod 731 a
umask 077
./target/debug/coreutils cp -a --no-preserve=mode a b
ls -l b|cut -b-10

```

With GNU:
`-rw-------`

with our:
`-rwx------`

**Comment by tommady** [comment]
Ya sure, let me finish this!
