### ISSUE TITLE
`rm`: reduce nesting in `prompt_file`

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#5345]
`prompt_file` is more complicated than it needs to be and can be cleaned up with some early returns and maybe with `let-else`. The behaviour should stay the same, but it needs to be cleaned up!

**Note**: There's more functions with a lot of nesting, I've cleaned those up already in https://github.com/uutils/coreutils/pull/5344

**Comment by terade** [comment]
Hello, I would like to work on this issue. Unfortunately I am inexperienced so I am sorry if I create additional work.

**Comment by cakebaker** [comment]
@terade sure, go ahead :)

**Comment by tertsdiepraam** [comment]
No worries, go ahead!
