### ISSUE TITLE
Implement setuidgid

### ISSUE THREAD

**Issue by ark6** [uutils/coreutils#535]
I'll work on this.

**Comment by nathanross** [comment]
This is part of the [daemontools](https://cr.yp.to/daemontools.html) tool collection, rather than the coreutils. If you do implement it, please do let us know, as there's a lot of shared interest / collaborative potential in endeavors to reimplement key system utilities in rust.

**Comment by knight42** [comment]
`setuidgid` doesn't seem to be part of coreutils. Plz see our new [TODO list](https://github.com/uutils/coreutils#to-do).
