### ISSUE TITLE
`ls` panicked

### ISSUE THREAD

**Issue by sanpii** [uutils/coreutils#5371]
```
$ ls
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/uu/ls/src/ls.rs:2819:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This error appears when I execute `ls` in a directory where files are rapidly created then deleted.

```
$ ls -V
uu-ls 0.0.21
```

**Comment by sylvestre** [comment]
fun, which version of ls do you have? 

(does not seem to be trunk https://github.com/uutils/coreutils/blob/main/src/uu/ls/src/ls.rs#L2819 )

**Comment by sanpii** [comment]
@sylvestre I just update my first message with my version.

https://github.com/uutils/coreutils/blob/main/src/uu/ls/src/ls.rs#L2891

**Comment by sylvestre** [comment]
ok, thanks

`            } else if file_type.is_file() && file_is_executable(path.md(out).as_ref().unwrap()) {`

we should probably not have an unwrap here and handle the error

**Comment by sanpii** [comment]
If I understand, it’s just cosmetic. I created a PR to ignore this error.
