### ISSUE TITLE
`ls -CF` should generate tab and not space

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5396]
Not far from 
https://github.com/uutils/coreutils/issues/3624

```
export C="./target/debug/coreutils "
rm -rf e
mkdir -p e/a2345 e/b
printf 'a2345/\tb/\n' > exp

${C}ls -CF e > out
diff -u out exp
```

tested by GNU:
`bash util/run-gnu-test.sh  tests/ls/stat-dtype.sh`

**Comment by sylvestre** [comment]
https://github.com/uutils/coreutils/pull/5397 might be a start

**Comment by tertsdiepraam** [comment]
This should be added to `uutils-term-grid`. I'm not a big fan of it myself, but we could support it, as long as formatting with only spaces is still possible.

**Comment by sylvestre** [comment]
I am wondering what is the use case to replace spaces by tabs in the terminal in general...

**Comment by tertsdiepraam** [comment]
Slightly less throughput of bytes maybe? I don't really know. The GNU docs just say "efficiency" (https://www.gnu.org/software/coreutils/manual/html_node/General-output-formatting.html).

**Comment by 5igh5** [comment]
Hello. Never contributed to anything before, and this seems like something I could do. How do I start?

**Comment by tertsdiepraam** [comment]
Cool! This would first need to be implemented in the uutils-term-grid crate (which is in another repository), so that's where you can start. I would like to confirm with the other maintainers that we actually want this though. I guess that if we want to be fully compatible, we should. @sylvestre @cakebaker what do you think?

**Comment by sylvestre** [comment]
Yeah,we should do it

**Comment by tertsdiepraam** [comment]
Alright! @5igh5 so we should first fix up uutils-term-grid so that it has an option for using tabs (with an option to specify how many spaces are replaced by a single tab). Then we can release that and use it in `ls`.

**Comment by allaboutevemirolive** [comment]
@tertsdiepraam @sylvestre 

[Add Tab option #24](https://github.com/uutils/uutils-term-grid/pull/24)

**Comment by 5igh5** [comment]
So the issue in uutils-term-grid is solved then?

**Comment by sylvestre** [comment]
@5igh5 sorry but why do you think it is fixed ? :)

**Comment by 5igh5** [comment]
Isn't that the purpose of this PR? [https://github.com/uutils/uutils-term-grid/pull/24](https://github.com/uutils/uutils-term-grid/pull/24)

**Comment by 5igh5** [comment]
so... i should go ahead and create my own version of it?
