### ISSUE TITLE
ci: code-quality workflow doesn't fail on clippy errors

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#5398]
For example, https://github.com/uutils/coreutils/actions/runs/6499112497/job/17651798583?pr=5395 shows "succeeded 11 hours ago in 1m 59s". However, when going to the "cargo clippy lint testing" step, some errors are shown:
```
[some clippy errors]

error: could not compile `uu_cp` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by miles170** [comment]
I would like to work on this.

**Comment by cakebaker** [comment]
@miles170 sure, go ahead :)
