### ISSUE TITLE
Tracking issue for fixing utils

### ISSUE THREAD

**Issue by kwantam** [uutils/coreutils#546]
@ctjhoa @Heather @Arcterus and others who have an interest in fixing utils:

Let's use this issue to track which utils we're currently fixing so that we don't get any more collisions. Protocol is something like "check that no one has yet claimed a util; add a new message to this issue claiming util; announce when it's done by opening a PR."

EDIT: We're getting close enough to done here that it makes more sense to track which utilities aren't done rather than which ones are.

Currently failing:

* timeout

**Comment by jbcrail** [comment]
I would add `echo` and `sync` since they both build without errors. They may or may not be functioning correctly since there are no tests.

**Comment by kwantam** [comment]
@jbcrail :+1: thanks!

**Comment by kwantam** [comment]
Claiming `yes`

**Comment by kwantam** [comment]
Claiming `uniq`

**Comment by jbcrail** [comment]
@kwantam The new `make build-check` command should help you find out which utilities are building without errors. I've been using it to decide which utility to work on next.

**Comment by jbcrail** [comment]
Claiming `head` and `tail`

**Comment by kwantam** [comment]
I'm about to open a PR that cleans up the `#!feature`s used in the working utils. I'd love if y'all could attempt to remove features where possible as well. A common one is that the `collections` feature is used to allow `args.tail()`, but that can just be replaced by `&args[1..]` and the `collections` feature removed.

**Comment by kwantam** [comment]
claiming `whoami`

**Comment by jbcrail** [comment]
Claiming `tee`

**Comment by kwantam** [comment]
Claiming `uptime`

**Comment by kwantam** [comment]
Claiming `unlink`, `unexpand`, `tr`, and `factor`

**Comment by jbcrail** [comment]
Claiming `tsort`

**Comment by jbcrail** [comment]
Claiming `truncate`

**Comment by kwantam** [comment]
@ctjhoa claimed and fixed `cksum`, PR pending

**Comment by kwantam** [comment]
> @kwantam The new make build-check command should help you find out which utilities are building without errors. I've been using it to decide which utility to work on next.

@jbcrail finally tried this out, this is awesome :+1:

**Comment by jbcrail** [comment]
Thanks, @kwantam!

**Comment by jbcrail** [comment]
Claiming `dirname`

**Comment by kwantam** [comment]
Claiming `touch`, `timeout`, `test`

**Comment by jbcrail** [comment]
Claiming `tty`

**Comment by ctjhoa** [comment]
Claiming `comm`

**Comment by kwantam** [comment]
It turns out that neither `std::process` nor `std::thread` are sufficient to implement `timeout`. I'm unclaiming this for now, because it seems like it's impossible to make it cross-platform (since we basically have to drop down to libc to get this to work at all).

**Comment by kwantam** [comment]
Claiming `tac`.

**Comment by jbcrail** [comment]
Claiming `groups` and `logname`.

**Comment by kwantam** [comment]
Claiming `shuf`

**Comment by jbcrail** [comment]
Claiming `printenv`.

**Comment by kwantam** [comment]
Claiming `sleep`

**Comment by jbcrail** [comment]
Claiming `hostid` and `pwd`.

**Comment by jbcrail** [comment]
Claiming `sort`.

**Comment by jbcrail** [comment]
Claiming `cp`, `realpath`, and `relpath`.

**Comment by jbcrail** [comment]
Claiming `link` and `sum`.

**Comment by jbcrail** [comment]
Claiming `env`.

**Comment by jbcrail** [comment]
Claiming `paste`.

**Comment by jbcrail** [comment]
Claiming `fold`.

**Comment by jbcrail** [comment]
Claiming `split`.

**Comment by kwantam** [comment]
Claiming `rm` and `rmdir`

**Comment by jbcrail** [comment]
Claiming `nl`.

**Comment by jbcrail** [comment]
Claiming `od`.

**Comment by jbcrail** [comment]
Claiming `nice`.

**Comment by kwantam** [comment]
claiming `cut`

**Comment by jbcrail** [comment]
Claiming `readlink`.

**Comment by jbcrail** [comment]
Claiming `mkdir`.

**Comment by jbcrail** [comment]
Claiming `mv`.

**Comment by jbcrail** [comment]
Claiming `mkfifo`.

**Comment by jbcrail** [comment]
Claiming `du`.

**Comment by jbcrail** [comment]
Claiming `hashsum`.

**Comment by jbcrail** [comment]
Claiming `id`.

**Comment by ctjhoa** [comment]
Claiming hostname

**Comment by jbcrail** [comment]
Claiming `nohup`.

**Comment by kwantam** [comment]
I think this issue is pretty much done now. `timeout` is a special case that's going to require rethinking, but this issue doesn't have to stay open just for that.
