### ISSUE TITLE
mv: misleading error messages for `mv file1 file2/` and `mv file1/ file2`

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#5463]
GNU `mv` shows a "Not a directory" error when adding a `/` to a filename:
```
$ touch file1 file2
$ mv file1 file2/
mv: cannot stat 'file2/': Not a directory
$ mv file1/ file2
mv: cannot stat 'file1/': Not a directory
```
uutils `mv`, on the other hand, shows an "Is a directory" error in one case and a "No such file or directory" error in the other case:
```
$ touch file1 file2
$ cargo run mv file1 file2/
mv: Is a directory (os error 21)
$ cargo run mv file1/ file2
mv: cannot stat 'file1/': No such file or directory
```

**Comment by mickvangelderen** [comment]
I'm going to look into this for fun but don't expect anything to come out of it :)

**Comment by mickvangelderen** [comment]
@cakebaker how do the tests look https://github.com/uutils/coreutils/pull/5464 to you?

**Comment by cakebaker** [comment]
@mickvangelderen they look good, though `fmt` complains

**Comment by mickvangelderen** [comment]
@cakebaker PR is ready for review.
