### ISSUE TITLE
mv: fails if source dir name is subset of target dir name

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#5481]
This issue was mentioned by @allaboutevemirolive in https://github.com/uutils/coreutils/issues/4833#issuecomment-1786554523:
```
$ mkdir test test2
$ cargo run mv test test2
mv: cannot move 'test' to a subdirectory of itself, 'test2/test'
```
Using different directory names, the same steps work fine:
```
$ mkdir aa bb
$ cargo run mv aa bb
$ ls bb
aa
```

**Comment by allaboutevemirolive** [comment]
Probably related:

Started: [Issue #5102](https://github.com/uutils/coreutils/issues/5102)

Pull request: [Pull request #5104](https://github.com/uutils/coreutils/pull/5104)

If the pull request doesn't fix this ticket, then I guess it's a separate problem.

**Comment by cakebaker** [comment]
No, I don't think it is related to #5102. The issue is caused by  https://github.com/uutils/coreutils/blob/main/src/uu/mv/src/mv.rs#L369 and that code is relatively new.
