### ISSUE TITLE
`uniq` does not do Unicode case folding

### ISSUE THREAD

**Issue by kwantam** [uutils/coreutils#550]
I don't know whether, by default, case insensitivity should be Unicode case folding or just ASCII case folding. Perhaps the right way forward is to add a `-I` flag that does Unicode case folding, and leave the `-i` flag as-is.

**Comment by krozycki** [comment]
Can you explain what do you mean by 'Unicode case folding'?

As far as I know, case insensitivity is handled moreless like this right now :

```
if self.ignore_case => ((c as u8) - 32) as char
```

**Comment by kwantam** [comment]
Right, but that assumes that the input is ASCII.

If the input is Unicode, then the rules for case insensitivity are much more complicated.

http://unicode.org/faq/casemap_charprop.html
http://unicode.org/charts/case/

The Unicode standard [section 5.18](http://www.unicode.org/versions/Unicode7.0.0/ch05.pdf) defines compliant caseless matching (version 8 isn't out yet, but it probably hasn't changed a whole lot since 7 other than updating the corresponding tables of case mappings).

Of course, it's a good question whether, by default, uniq should assume UTF-8 or 8-bit ASCII input. Perhaps such a switch would instantly clarify the correct behavior of the `-i` flag.
