### ISSUE TITLE
node-build fails on macOS if uutils override built-in coreutils

### ISSUE THREAD

**Issue by AlexCzar** [uutils/coreutils#5500]
I have placed uutils in the PATH before the built-in coreutils, until recently I did not encounter any issues.
Found one now though, node-build won't compile if uutils are used.
Here are descriptions of the issues, which I initially misattributed to node-build:

https://github.com/nodenv/node-build/issues/839
https://github.com/nodenv/node-build/issues/840

**Comment by sylvestre** [comment]
@AlexCzar please produce some test cases 
build X with rust/coreutils is too complex / painful to do anything

thanks :)

**Comment by sylvestre** [comment]
please reopen when you have been able to isolate the issue, thanks!
