### ISSUE TITLE
`zip` dependency uses `default_features = false` instead of `default-features = false`

### ISSUE THREAD

**Issue by polarathene** [uutils/coreutils#5562]
When using `cargo remove` on another dep, this was output:

```
error: Use of `default_features` in `zip` is unsupported, please switch to `default-features`
```

Probably a typo?:

https://github.com/uutils/coreutils/blob/58087df02a30bb4c7d6e474dfeee20b9faa51b93/Cargo.toml#L333

**Comment by cakebaker** [comment]
Good catch, thanks for reporting.
