### ISSUE TITLE
expr: `unexpected argument` error for missing arguments is misleading

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#5573]
The following commands lead to `unexpected argument` errors with uutils `expr`:
```
$ cargo run expr length
expr: syntax error: unexpected argument 'length'
$ cargo run expr index hello
expr: syntax error: unexpected argument 'index'
$ cargo run expr substr hello 1
expr: syntax error: unexpected argument 'substr'
```
This is a bit misleading because the problem is not the argument shown in the error message but missing arguments.

GNU `expr` shows a `missing argument` error in such cases:
```
$ expr length
expr: syntax error: missing argument after ‘length’
$ expr index hello
expr: syntax error: missing argument after ‘hello’
$ expr substr hello 1
expr: syntax error: missing argument after ‘1’
```

**Comment by Luv-Ray** [comment]
Now they all leading to `expr: syntax error (premature end of expression)` on the main branch of uutils:
```
$ cargo run expr length
expr: syntax error (premature end of expression)
$ cargo run expr index hello
expr: syntax error (premature end of expression)
$ cargo run expr substr hello 1
expr: syntax error (premature end of expression)
```
Is this acceptable?

**Comment by tertsdiepraam** [comment]
That doesn't sound like the right behaviour. I'm reworking the parsing at the moment though. I'll try to get that PR up soon.

**Comment by tertsdiepraam** [comment]
Fixed by https://github.com/uutils/coreutils/pull/5586
