### ISSUE TITLE
expr: gnu generates a division by zero when we don't

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5576]
with GNU:
```
$ /usr/bin/expr  "85" "/" "983" ":" "83"
/usr/bin/expr: division by zero
```

With our implementation:
```
$ ./target/debug/coreutils expr  "85" "/" "983" ":" "83"  
42
```

Found by the fuzzer

**Comment by cobaweel** [comment]
I'm gonna take a look.

**Comment by cobaweel** [comment]
Seems like the problem has nothing to do with division and instead is about the regex match operator (`:`). 

According to [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/expr.html) and the [GNU manual](https://www.gnu.org/software/coreutils/manual/html_node/String-expressions.html), the regex on the right side of the operator needs to be read with an implicit `^` at the start, i.e., it should only match at the beginning of the string.

Indeed, running `/usr/bin/expr abc : bc` gives 0, but `./target/debug/coreutils expr abc : bc` gives 2. The code does indeed seem to not prepend the `^`. I'm working on a fix now.
