### ISSUE TITLE
Compilation Failure for `selinux-sys v0.6.2` in Cargo Clippy

### ISSUE THREAD

**Issue by allaboutevemirolive** [uutils/coreutils#5587]
While running `cargo clippy --all-targets --all-features --workspace -- -D warnings` in the project directory, a compilation failure occurred for the `selinux-sys v0.6.2` crate. 

<details>
  <summary>Click to expand the error output</summary>

```
nemesis@nemesis:~/Documents/Github/Focus/util/coreutils_master$ cargo clippy --all-targets --all-features --workspace -- -D warnings
   Compiling selinux-sys v0.6.2
   Compiling clap v4.4.2
    Checking indicatif v0.17.3
   Compiling os_display v0.1.3
   Compiling nix v0.27.1
   Compiling const-random-macro v0.1.16
    Checking fundu v2.0.0
   Compiling crossbeam-epoch v0.9.14
    Checking parse_datetime v0.5.0
   Compiling lock_api v0.4.9
   Compiling num-traits v0.2.17
    Checking platform-info v2.0.2
   Compiling parking_lot_core v0.9.8
   Compiling pkg-config v0.3.26
    Checking quick-error v2.0.1
   Compiling wild v2.2.0
error: failed to run custom build command for `selinux-sys v0.6.2`

Caused by:
  process didn't exit successfully: `/home/nemesis/Documents/Github/Focus/util/coreutils_master/target/debug/build/selinux-sys-80184f04ad84d5c3/build-script-build` (exit status: 101)
  --- stdout
  cargo:root=/home/nemesis/Documents/Github/Focus/util/coreutils_master/target/debug/build/selinux-sys-a45aa3c7026edd8f/out
  cargo:rerun-if-env-changed=SELINUX_STATIC_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SELINUX_STATIC_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_SELINUX_STATIC
  cargo:rerun-if-env-changed=SELINUX_STATIC
  cargo:rerun-if-env-changed=SELINUX_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SELINUX_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_SELINUX_PATH
  cargo:rerun-if-env-changed=SELINUX_PATH
  cargo:rerun-if-env-changed=SELINUX_INCLUDE_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SELINUX_INCLUDE_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_SELINUX_INCLUDE_DIR
  cargo:rerun-if-env-changed=SELINUX_INCLUDE_DIR
  cargo:rerun-if-env-changed=SELINUX_LIB_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SELINUX_LIB_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_SELINUX_LIB_DIR
  cargo:rerun-if-env-changed=SELINUX_LIB_DIR
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_CC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  cargo:rerun-if-env-changed=CFLAGS
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-changed=/usr/include/selinux
  cargo:rerun-if-changed=/usr/include/selinux/avc.h
  cargo:rerun-if-changed=/usr/include/selinux/selinux.h
  cargo:rerun-if-changed=/usr/include/selinux/label.h
  cargo:rerun-if-changed=/usr/include/selinux/get_context_list.h
  cargo:rerun-if-changed=/usr/include/selinux/get_default_type.h
  cargo:rerun-if-changed=/usr/include/selinux/restorecon.h
  cargo:rerun-if-changed=/usr/include/selinux/context.h
  cargo:include=/usr/include
  cargo:rerun-if-changed=/usr/lib/x86_64-linux-gnu/libselinux.so
  cargo:lib=/usr/lib/x86_64-linux-gnu
  cargo:rustc-link-search=native=/usr/lib/x86_64-linux-gnu
  cargo:rustc-link-lib=dylib=selinux
```

</details>

```
  --- stderr
  /usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found
  thread 'main' panicked at /home/nemesis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/selinux-sys-0.6.2/build.rs:355:39:
  selinux-sys: Failed to generate Rust bindings for 'selinux/selinux.h' and other headers: ClangDiagnostic("/usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Steps to Reproduce:**

Run `cargo clippy --all-targets --all-features --workspace -- -D warnings`.

**Local Machine:**

<details>
  <summary>Click to expand the local machine information</summary>

```
Linux nemesis 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      39 bits physical, 48 bits virtual
CPU(s):                             8
On-line CPU(s) list:                0-7
Thread(s) per core:                 2
Core(s) per socket:                 4
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              142
Model name:                         Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Stepping:                           10
CPU MHz:                            800.162
CPU max MHz:                        3400.0000
CPU min MHz:                        400.0000
BogoMIPS:                           3600.00
Virtualization:                     VT-x
L1d cache:                          128 KiB
L1i cache:                          128 KiB
L2 cache:                           1 MiB
L3 cache:                           6 MiB
NUMA node0 CPU(s):                  0-7
```
</details>

**Comment by tertsdiepraam** [comment]
You need `libselinux` installed to compile that. There's not really anything we can do to fix that. You can try `--features unix` to run clippy with everything but selinux enabled. Could you confirm that either of these fixes your issue?

**Comment by allaboutevemirolive** [comment]
Command: 

cargo clippy --all-targets --all-features --workspace -- -D warnings --features unix

```
  --- stderr
  /usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found
  thread 'main' panicked at /home/nemesis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/selinux-sys-0.6.2/build.rs:355:39:
  selinux-sys: Failed to generate Rust bindings for 'selinux/selinux.h' and other headers: ClangDiagnostic("/usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details>
  <summary>Full Output</summary>
nemesis@nemesis:~/Documents/Github/Focus/util/coreutils_master$ cargo clippy --all-targets --all-features --workspace -- -D warnings --features unix
   Compiling uuhelp_parser v0.0.23 (/home/nemesis/Documents/Github/Focus/util/coreutils_master/src/uuhelp_parser)
   Compiling selinux-sys v0.6.2
   Compiling uu_stdbuf_libstdbuf v0.0.23 (/home/nemesis/Documents/Github/Focus/util/coreutils_master/src/uu/stdbuf/src/libstdbuf)
   Compiling fts-sys v0.2.4
   Compiling uu_factor v0.0.23 (/home/nemesis/Documents/Github/Focus/util/coreutils_master/src/uu/factor)
error: Unrecognized option: 'features'

error: could not compile `uuhelp_parser` (lib)
warning: build failed, waiting for other jobs to finish...
error: Unrecognized option: 'features'

error: could not compile `uu_stdbuf_libstdbuf` (build script)
error: Unrecognized option: 'features'

error: could not compile `uu_factor` (build script)
error: failed to run custom build command for `fts-sys v0.2.4`

Caused by:
  process didn't exit successfully: `/home/nemesis/Documents/Github/Focus/util/coreutils_master/target/debug/build/fts-sys-171fd70e4da21ddc/build-script-build` (exit status: 101)
  --- stdout
  cargo:root=/home/nemesis/Documents/Github/Focus/util/coreutils_master/target/debug/build/fts-sys-a1b65ec09b470cb8/out

  --- stderr
  /usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found
  thread 'main' panicked at /home/nemesis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fts-sys-0.2.4/build.rs:76:10:
  fts-sys: Failed to generate Rust bindings for 'fts.h'.: ClangDiagnostic("/usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `selinux-sys v0.6.2`

Caused by:
  process didn't exit successfully: `/home/nemesis/Documents/Github/Focus/util/coreutils_master/target/debug/build/selinux-sys-80184f04ad84d5c3/build-script-build` (exit status: 101)
  --- stdout
  cargo:root=/home/nemesis/Documents/Github/Focus/util/coreutils_master/target/debug/build/selinux-sys-a45aa3c7026edd8f/out
  cargo:rerun-if-env-changed=SELINUX_STATIC_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SELINUX_STATIC_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_SELINUX_STATIC
  cargo:rerun-if-env-changed=SELINUX_STATIC
  cargo:rerun-if-env-changed=SELINUX_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SELINUX_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_SELINUX_PATH
  cargo:rerun-if-env-changed=SELINUX_PATH
  cargo:rerun-if-env-changed=SELINUX_INCLUDE_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SELINUX_INCLUDE_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_SELINUX_INCLUDE_DIR
  cargo:rerun-if-env-changed=SELINUX_INCLUDE_DIR
  cargo:rerun-if-env-changed=SELINUX_LIB_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=SELINUX_LIB_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_SELINUX_LIB_DIR
  cargo:rerun-if-env-changed=SELINUX_LIB_DIR
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_CC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  cargo:rerun-if-env-changed=CFLAGS
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-changed=/usr/include/selinux
  cargo:rerun-if-changed=/usr/include/selinux/avc.h
  cargo:rerun-if-changed=/usr/include/selinux/selinux.h
  cargo:rerun-if-changed=/usr/include/selinux/label.h
  cargo:rerun-if-changed=/usr/include/selinux/get_context_list.h
  cargo:rerun-if-changed=/usr/include/selinux/get_default_type.h
  cargo:rerun-if-changed=/usr/include/selinux/restorecon.h
  cargo:rerun-if-changed=/usr/include/selinux/context.h
  cargo:include=/usr/include
  cargo:rerun-if-changed=/usr/lib/x86_64-linux-gnu/libselinux.so
  cargo:lib=/usr/lib/x86_64-linux-gnu
  cargo:rustc-link-search=native=/usr/lib/x86_64-linux-gnu
  cargo:rustc-link-lib=dylib=selinux

  --- stderr
  /usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found
  thread 'main' panicked at /home/nemesis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/selinux-sys-0.6.2/build.rs:355:39:
  selinux-sys: Failed to generate Rust bindings for 'selinux/selinux.h' and other headers: ClangDiagnostic("/usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</details>

I already run:
```
sudo apt-get install build-essential
```

```
sudo apt-get install libselinux1-dev libfts-dev
```

```
sudo apt-get install libc6-dev
```

Then, try:
```
root@nemesis:/home/nemesis# apt search libselinux
Sorting... Done
Full Text Search... Done
android-libselinux/oldstable 10.0.0+r36-1 amd64
  Security-Enhanced Linux for Android

android-libselinux-dev/oldstable 10.0.0+r36-1 amd64
  Security-Enhanced Linux for Android - Development files

libselinux1/oldstable,now 3.1-3 amd64 [installed]
  SELinux runtime shared libraries

libselinux1-dev/oldstable,now 3.1-3 amd64 [installed]
  SELinux development headers

libsemanage1/oldstable,now 3.1-1+b2 amd64 [installed]
  SELinux policy management library
```

**Comment by sylvestre** [comment]
this isn't an issue with the coreutils anyway.
please follow up with the selinux crate project

**Comment by tertsdiepraam** [comment]
> cargo clippy --all-targets --all-features --workspace -- -D warnings --features unix

Yeah it doesn't work if you still pass `--all-features` ;p

I don't think this requires any action here or in the `selinux-sys` project. It is completely reasonable for the `selinux-sys` crate to error if it cannot find the libraries.
