### ISSUE TITLE
touch does not respect the -h flag

### ISSUE THREAD

**Issue by kwantam** [uutils/coreutils#560]
`touch` uses the `set_file_times()` function from Rust's stdlib, which follows symlinks. Thus, the `-h` function does not work correctly.

The solution is to call [`lutimes`](https://www.linux.com/learn/docs/man/lutimes3) on platforms that support it (which would appear to be all platforms except Windows).

**Comment by retep998** [comment]
On Windows, just open the file with the `FILE_FLAG_OPEN_REPARSE_POINT` flag and then call `SetFileTime`.
