### ISSUE TITLE
`ls`: Don't reject multiple use of `--color`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5643]
```
./target/debug/coreutils ls --color=auto --color=always   
error: the argument '--color[=<color>]' cannot be used multiple times

Usage: ./target/debug/coreutils ls [OPTION]... [FILE]...
```

GNU accepts it

**Comment by rabbull** [comment]
Hi,

Can I propose a PR to this issue? My plan is to set parsing action of color argument to `Append`, which allows clap to parse multiple duplicating tags. After that, when extract the option, select only the last color tags. In addition, a test case for multiple use of `--color` will be added.

Best,
rabbull

**Comment by cakebaker** [comment]
https://github.com/uutils/coreutils/pull/5641 resolves this issue as a side effect by setting `args_override_self(true)`
