### ISSUE TITLE
Implement `cksum --check`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5705]
According to GNU:
```
       -c, --check
              read checksums from the FILEs and check them
```
Tested in GNU with tests/cksum/cksum-a.sh
Source:
https://github.com/uutils/coreutils/blob/main/src/uu/cksum/src/cksum.rs

**Comment by sylvestre** [comment]
some work started here: https://github.com/uutils/coreutils/pull/5122

**Comment by biplab5464** [comment]
can i try to implement it?

**Comment by sylvestre** [comment]
sure, please give it a try
