### ISSUE TITLE
install: no output when running `-s --strip-program`

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#5718]
While reviewing https://github.com/uutils/coreutils/pull/5697, I noticed that GNU `install` outputs `./-dest` when running `install -s --strip-program ./no-hyphen -- source -dest` whereas uutils `install` doesn't output anything.

The `no-hyphen` program is (from [test_install_and_strip_with_program_hyphen](https://github.com/uutils/coreutils/blob/main/tests/by-util/test_install.rs#L681)):
```
#!/bin/sh
printf -- '%s\n' "$1" | grep '^[^-]'
```

**Comment by cre4ture** [comment]
I tried to reproduce. But to me it looks like the file is created as expected. Can you please re-check or describe more in detail?
```
uli@hp13-ulix:~/dev_rust/coreutils/testdir_install$ ls     
no-hyphen  src
uli@hp13-ulix:~/dev_rust/coreutils/testdir_install$ ~/dev_rust/coreutils/target/debug/install -s --strip-program ./no-hyphen -- src -dest
uli@hp13-ulix:~/dev_rust/coreutils/testdir_install$ ls -lah
total 12K
-rwxr-xr-x  1 uli uli    0 Jan 15 21:58 -dest
drwxrwxr-x  2 uli uli 4.0K Jan 15 21:58 .
drwxrwxr-x 15 uli uli 4.0K Jan 15 21:35 ..
-rwxrwxr-x  1 uli uli   48 Jan 15 21:39 no-hyphen
-rw-rw-r--  1 uli uli    0 Jan 15 21:40 src
uli@hp13-ulix:~/dev_rust/coreutils/testdir_install$ ls
-dest  no-hyphen  src
uli@hp13-ulix:~/dev_rust/coreutils/testdir_install$ 
```

**Comment by cakebaker** [comment]
The issue is that the following statement produces no output on stdout:
```
uli@hp13-ulix:~/dev_rust/coreutils/testdir_install$ ~/dev_rust/coreutils/target/debug/install -s --strip-program ./no-hyphen -- src -dest
```
GNU `install` outputs `./-dest`. And if the destination doesn't start with a `-`, it simply outputs the destination.

I hope this clarifies the issue.

**Comment by cre4ture** [comment]
Ok, thanks for clarification. I think I finally understood the test.
Next problem: I can't reproduce the described GNU behavior on my machine:

```
$ install -s --strip-program ./no-hyphen -- src -dest
install: strip process terminated abnormally
```

After forcing the return code of "./no-hypen" to 0, I get this:

```
$ install -s --strip-program ./no-hyphen -- src -dest
uli@hp13-ulix:~/dev_rust/coreutils/testdir_install$ install -s --strip-program ./no-hyphen -- src dest
dest
$ install -s --strip-program ./no-hyphen -- src -dest
$ install -s --strip-program ./no-hyphen -- src ./-dest
./-dest
$ install --version
install (GNU coreutils) 8.32
...
```

So GNU only outputs "./-dest" when this is provided exactly like this as input.

```
$ ~/dev_rust/coreutils/target/debug/install -s --strip-program ./no-hyphen -- src -dest
$ ~/dev_rust/coreutils/target/debug/install -s --strip-program ./no-hyphen -- src ./-dest
$ install -s --strip-program ./no-hyphen -- src ./-dest
./-dest
```

Sadly, uutils doesn't even output it in that case.

a) It seems to me that the more critical issue is that uutils is not validating the return code of "./no-hyphen".
b) I don't get why the starting "-" is such a important usecase? The destinatio file is created the correct way, or?

**Comment by cre4ture** [comment]
I think I found the issue. uutils does the right thing. It just doesn't forward the stdout accordingly.
I'll provide a fix.
