### ISSUE TITLE
fuzzing `Running test ["seq", "-49.450798063728875", "3458"]` is staled 

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#5724]
cargo +nightly fuzz run fuzz_seq -- -max_total_time=600 -detect_leaks=0 
freeze on:
Running test ["seq", "-49.450798063728875", "3458"]
rust-gdb -p <pid> shows that it is on:
            write!(stdout, "{separator}")?;
https://github.com/uutils/coreutils/blob/052f38f14d5e9f7e100aa8f1c40feefbcc5e3418/src/uu/seq/src/seq.rs#L220
i don't know what is going on ?!

**Comment by samueltardieu** [comment]
It looks like `fuzz_common::generate_and_run_uumain()` in the fuzzing framework sets up pipes for stdout/stderr and reads them afterwards. However, the default pipe size on Linux is 16 pages, i.e. 64kiB on most systems. The output of `seq -49.450798063728875 3458` is more than 70kiB, so the write size of the pipe will block until the pipe is read from, which never happens before the command completes.

I can see at least two ways to fix this:

- limit the command output/error to 64kiB in any case
- use two separate threads, one for running the command and one for reading its output
