### ISSUE TITLE
ls: --color= should default to auto

### ISSUE THREAD

**Issue by LDprg** [uutils/coreutils#5748]
I just tried uutils-coreutils to possibly replace it with coreutils. First of all great work guys.

However I was quite confused why ls does not default to --color=auto and instead just do not display any colors at all?
Probably it should be changed since coreutils ls is as far as I know defaulting to --color=auto and users (like me) are just confused. Setting the option manually works as expected.

**Comment by LDprg** [comment]
I did just some more testing. It seems to have something to do that I have an prefix for the executables (ls for to normal one and uutils-ls for the coreutils one). If I rename it from uutils-ls to ls the colors just work as expected.

**Comment by cakebaker** [comment]
The default of GNU `ls` is `--color=none` (https://www.gnu.org/software/coreutils/manual/html_node/General-output-formatting.html), though you likely have an alias defined in your `.bashrc` that is `alias ls='ls --color=auto'`

**Comment by LDprg** [comment]
Oh, sorry thats my fault. Thanks for the help.
