### ISSUE TITLE
cksum: show error if a directory is specified

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#5805]
GNU `cksum` shows an error and returns an exit code of `1` if a directory is specified:
```
$ cksum dir file
cksum: dir: Is a directory
4294967295 0 file
$ echo $?
1
```
uutils `cksum`, on the other hand, doesn't show an error and returns an exit code of `0`:
```
$ cargo run cksum dir file
4294967295 0 dir
4294967295 0 file
$ echo $?
0
```
The same applies to `-a`/`--algorithm` with all algorithms.

**Comment by tertsdiepraam** [comment]
Is this a generalization of https://github.com/uutils/coreutils/pull/5804? I was just thinking there that blake2b wouldn't be the only case. In https://github.com/uutils/coreutils/pull/5804, the error is generated manually, but "Is a directory" usually comes from an io error. I think it's probably worth investigating what our `cksum` is even doing on directories.

**Comment by cakebaker** [comment]
Yes, it is a generalization of it.

**Comment by Ato2207** [comment]
I could take on this issue too if it is ok, should be a small modification.

**Comment by cakebaker** [comment]
Sure, go ahead :)
