### ISSUE TITLE
cksum: stops when one of given files doesn't exist

### ISSUE THREAD

**Issue by D9nni** [uutils/coreutils#5809]
GNU `cksum` shows an error message when a file does not exist and continues work with the next given arguments, while uutils cksum stops when error occurs.
GNU:
```
$ cksum README.md nothing Cargo.toml 
4037539306 8038 README.md
cksum: nothing: No such file or directory
3830277208 20970 Cargo.toml
```
uutils:
```
$ coreutils cksum README.md nothing Cargo.toml 
4037539306 8038 README.md
cksum: nothing: No such file or directory
```

**Comment by Hwatwasthat** [comment]
I could take this issue on, should be a quick fix to just match on the attempt to open the file and then carry on.

**Comment by cakebaker** [comment]
@Hwatwasthat sure, go ahead :)

**Comment by biplab5464** [comment]
i am sorry i am new to open source contribution am i doing right is their any other way

**Comment by Hwatwasthat** [comment]
No no that's fine, I was just offering to help out, nothing more :)
