### ISSUE TITLE
uucore: warning for clippy::if_not_else in features/format/num_format.rs

### ISSUE THREAD

**Issue by lcheylus** [uutils/coreutils#5837]
During some lint tests on OpenBSD (Rust 1.72.1) with rust-clippy, I found a warning/error for [clippy::if_not_else](https://rust-lang.github.io/rust-clippy/master/index.html#/if_not_else) in `uucore/src/lib/features/format/num_format.rs` (line 149, function ``Formatter::fmt``).
```rust
// The prefix that rust uses is `0o`, but GNU uses `0`.
// We also need to take into account that 0 should not be 00
// Since this is an unsigned int, we do not need to take the minus
// sign into account.
if x != 0 {
    format!("0{x:o}")
} else {
   format!("{x:o}")
}
```

I don't understand why this warning is not detected by CI job for Lint (clippy run with `-D warning` flag): clippy::if_not_else is included in warnings by default.

This warning could be removed with `#[allow(clippy::if_not_else)]` or maybe by modifying the if not/else logic.

**Comment by cakebaker** [comment]
I think there is no warning because it is a "pedantic" lint.

**Comment by lcheylus** [comment]
Yes, clippy::if_not_else is in "pedantic" warnings.

On OpenBSD-stable (version 7.4) with Rust 1.72.1, running clippy with `-D warnings` flag (as in FreeBSD workflow "Style and Lint" job), I have the error message "note: `-D clippy::if-not-else` implied by `-D warnings`".

I need to add `#[allow(clippy::if_not_else)]` in `uucore/src/lib/features/format/num_format.rs` to fix this warning.

**Comment by lcheylus** [comment]
@cakebaker Thanks for your fix

**Comment by cakebaker** [comment]
@lcheylus You are welcome, and thanks for reporting!
