### ISSUE TITLE
unexpand: show error message if a directory is specified

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#5845]
GNU `unexpand` shows an error if the user specifies a directory and returns `1` as exit code:
```
$ echo "content" > file
$ unexpand dir file
unexpand: dir: Is a directory
content
$ echo $?
1
```
uutils `unexpand`, on the other hand, doesn't output anything and returns `0` as exit code:
```
$ echo "content" > file
$ cargo run unexpand dir file
$ echo $?
0
```

**Comment by biplab5464** [comment]
i will try to fix the issue

**Comment by biplab5464** [comment]
biplab@BIPLAB:~/project/coreutils/src/uu/unexpand/src$ cat file
content
biplab@BIPLAB:~/project/coreutils/src/uu/unexpand/src$ cat file1
a      b
biplab@BIPLAB:~/project/coreutils/src/uu/unexpand/src$ unexpand file1 file
a      b
content
biplab@BIPLAB:~/project/coreutils/src/uu/unexpand/src$ cargo run file1 file
   Compiling uu_unexpand v0.0.23 (/home/biplab/project/coreutils/src/uu/unexpand)
    Finished dev [unoptimized + debuginfo] target(s) in 0.92s
     Running `/home/biplab/project/coreutils/target/debug/unexpand file1 file`
a      b

uutils unexpand only talking the first argument and ignoring the subsequent element 
i think this issue need to be fixed first

**Comment by biplab5464** [comment]
i am beginner so better open a ticket

**Comment by sudhackar** [comment]
Hey @biplab5464 

See https://github.com/uutils/coreutils/blob/55b7b2fcb5627f80c2b8404ef5bcc797444ed115/src/uu/unexpand/src/unexpand.rs#L108

the fix to get all the files to process would be here


Another recommendation - use triple backticks ``` to start a code block when you are trying to share some code - [more help on markdown](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by biplab5464** [comment]
Thank you for Help

I have fix the issue for multiple files 

now i am trying to fix the original issue

**Comment by cakebaker** [comment]
I think you can return a `USimpleError`.

**Comment by cakebaker** [comment]
@biplab5464 I opened a ticket for the issue you mentioned in a comment above: https://github.com/uutils/coreutils/issues/5852
