### ISSUE TITLE
msys2: GNUmakefile error 139 while installing completions and manpages

### ISSUE THREAD

**Issue by ognevny** [uutils/coreutils#5888]
in https://github.com/msys2/MINGW-packages/actions/runs/7667600251/job/20901971263?pr=19871 we encountered error 139. for other msys2 environments it works fine. I'm not completely sure whether it's coreutils' failure

**Comment by sylvestre** [comment]
could you please provide a test case showing the error ?
The log that you are shared don't show any error on our side.

(also, please do some diagnostic on your side before opening an issue here)

please reopen when you have confirmed that it is an issue on our side

**Comment by ognevny** [comment]
I've recently rebuild 0.0.23. it worked fine

**Comment by ognevny** [comment]
it's now fixed because all CLANG* msys2 environments now use `*-pc-windows-gnullvm` target, which is proper for them
