### ISSUE TITLE
dd: incorrect seek on oseek=1Bx2x4

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#5903]
Coreutils `dd` v9.4.113-c01ee:
```shell
$ echo abcdefghijklm | ../gnu/src/dd oseek=1Bx2x4 bs=5 > out 2> /dev/null && cat out
^@^@^@^@^@^@^@^@abcdefghijklm
```
(The `^@` are null bytes.)

On uutils `dd`:
```
$ echo abcdefghijklm | ./target/debug/dd oseek=1Bx2x4 bs=5 > out 2> /dev/null && cat out
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@abcdefghijklm
```

This is from the GNU test suite file `tests/dd/bytes.sh`.

**Comment by matrixhead** [comment]
seems like coreutil's dd treats the `oseek` operand  as bytes if it contains a 'B' anywhere in the argument, even though it's says in the man page that  it will only do so if the argument ends in a 'B'  but in our implementation we only check for the 'B' at the end of the string. In this case `1Bx2x4`  'B' appears not at the end of the string so it treats it as blocks and failing the test case
