### ISSUE TITLE
dd: error message on count=KBb doesn't match GNU dd, but should

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#5905]
GNU dd:
```
$ : | dd count=KBb
dd: invalid number: ‘KBb’
```

uutils dd:
```
$ : | ./target/debug/dd count=KBb
./target/debug/dd: Unrecognized byte multiplier -> KB
```
This should be `invalid number: 'KBb'`, just like the GNU version of dd.

This is from the GNU test suite file `tests/dd/bytes.sh`.

**Comment by just-an-engineer** [comment]
Working on this in #6622. From looking over the code, it looks like it's based on how we parse it, which results in more differences if anything comes after the first 'c', 'w', or 'b'. As such, `dd count=kBb555` also yields different messages on GNU versus here. I'm making that change right now, but I figure I'd add that difference onto this thread
