### ISSUE TITLE
echo: prints version when input is "--ver" different from GNU echo

### ISSUE THREAD

**Issue by SaHHiiLL** [uutils/coreutils#5910]
GNU echo 
```shell
$ /bin/echo --ver
--ver
```

coreutills
```shell
$ cargo run --features unix -- echo --ver
echo 0.0.24
```
other coreutils have the same behavior, but they match the output of their counterparts, tested `ls`, `touch` and `sleep`

**Comment by tertsdiepraam** [comment]
Oh that's funny 😄 I'll try to fix this in my new argument parser too. For the `clap` parser, I think this is just a matter of removing `infer_long_args`. Let me give that a shot.
