### ISSUE TITLE
release artifacts for v0.0.24 and v0.0.25 are missing

### ISSUE THREAD

**Issue by malt3** [uutils/coreutils#5929]
It looks like something went wrong here: https://github.com/uutils/coreutils/actions/runs/7596318857

EDIT: I'm seeing this error between a mountain of weird output:

```
2024-01-20T19:21:23.9087255Z [0m          C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows_x86_64_gnu-0.42.2\lib/libwindows.a(ntdll_dll_s00082.o): illegal symbol index -1869611008 in relocs
```

Pipeline is green now but release artifacts are still missing.

**Comment by tertsdiepraam** [comment]
See also: https://github.com/uutils/coreutils/discussions/5915

**Comment by malt3** [comment]
I found something: the variable `steps.vars.outputs.DEPLOY` was not set to true. This is why the release with artifacts was never triggered: https://github.com/uutils/coreutils/actions/runs/7596318857/job/21112947690#step:6:135


This is the case since the CICD workflow was never triggered on the release tag.

**Comment by malt3** [comment]
Do you think it is possible to either fix the release artifacts for v0.0.24 manually or do a new release soon?

**Comment by tertsdiepraam** [comment]
We're about halfway until the next release, so I don't see a particular rush to fix this at the moment. Do you really need them in addition to all the other installation methods?

**Comment by malt3** [comment]
With #5694 (which is in 0.0.24), I was trying to get a larger set of statically linked release artifacts. I need this for another PR in another repo which depends on those binary artifacts: https://github.com/aspect-build/bazel-lib/pull/706

But I also totally understand if you prefer to just wait until the next release.

**Comment by loeffel-io** [comment]
v0.0.25 and the artifacts are still missing
i need this for [github.com/loeffel-io/ls-lint](ls-lint)

**Comment by sylvestre** [comment]
yeah, dunno why :( 
help welcome!

**Comment by malt3** [comment]
This time it was an issue with the cargo.lock file, as can be seen here: https://github.com/uutils/coreutils/actions/runs/8404507913

I think this issue was resolved with the next commit on main: https://github.com/uutils/coreutils/commit/68c77b4bd129bdc12d03cc74fe0f817d2df75894

**Comment by sylvestre** [comment]
I have been trying to do a 0.0.26 for artifact but some Windows systems have been failing. I am waiting for them to be fixed upstream (github)

**Comment by QuentiumYT** [comment]
Is it possible to attach the binaries to the previous 0.0.24 and 0.0.25 releases? Would be useful for not searching through CICD random commit builds :)

**Comment by tertsdiepraam** [comment]
I'd rather focus on fixing it. Artifacts generated by GH actions are always better than something uploaded manually so you at least get a bit of assurance that it's correct (especially considering the recent news around security issues in release tarballs :) )

**Comment by QuentiumYT** [comment]
I agree, but once the build action is fixed, these 2 releases will not be updated automatically right?
I was thinking about publishing the actions artifacts anyway :) Better for security indeed!

**Comment by sylvestre** [comment]
They probably won't be regenerated. We start try to restart the tasks but not idea if it will work or not

**Comment by rivy** [comment]
I believe that https://github.com/uutils/coreutils/pull/6270 will fix the issue.
It's working correctly on [a test clone](https://github.com/rivy-t/rs.coreutils).

Ping me when the next release is on deck and I'll be happy to help debug any issues.
