### ISSUE TITLE
Powershell completions coreutils __ completes files.

### ISSUE THREAD

**Issue by LucasLehmann** [uutils/coreutils#5933]
This seems to be caused by powershells completion not being capable of having a paramater value of '' this happens with the completion for seq and causes all completions coreutils __ to not be applied anything else such as coreutils seq __ works and will complete. This stops happening if the string is changed to anything else such as ' ' or 'Print a sequence of numbers'.

**Comment by tertsdiepraam** [comment]
I'm honestly do not quite understand what you are trying to say. Is the problem that the argument of `coreutils` is not being limited to the list of utils? It would also be very helpful if you could figure out whether this is a problem on our side or on the side of `clap-complete`. Could you maybe show an example of the current behaviour and the desired behaviour?

**Comment by tertsdiepraam** [comment]
Ah I see now. Thanks for the explanation. Is there a way to fix this without passing a a description? I think this should probably be fixed in `clap_complete` in the `clap` repository. Could you open an issue there?
