### ISSUE TITLE
should mv maintain attributes?

### ISSUE THREAD

**Issue by fdncred** [uutils/coreutils#6002]
I'm chasing down an issue in nushell, linked below, and I'm wondering what the standard is for moving files to/from internal/external drives and preserving file/directory attributes like timestamps. The OP reports that nushell's mv, nor nushell's uutils umv, nor your mv command maintain these attributes but the native mv does. Thoughts?

https://github.com/nushell/nushell/issues/11943

Kind of related
https://github.com/uutils/coreutils/issues/4192

**Comment by tertsdiepraam** [comment]
It probably should yeah. I haven't tested this myself.

**Comment by fdncred** [comment]
Thanks @tertsdiepraam. Closing this issue as you answered the question but I opened a related feature request issue #6004.
