### ISSUE TITLE
cp: Wrong handling of -i -u

### ISSUE THREAD

**Issue by BenWiederhake** [uutils/coreutils#6019]
When copying an old file over a new file, cp still needs to ask: `-u` is `--update=older`, which according to the man page only influences which files are *considered* for overwriting. In other words, `-u` does not work by automatically allowing anything, but rather by disregarding some copy actions.

Minimal example:

```console
$ touch old; sleep 2; touch new; echo N | LC_ALL=C cp -i -u new old
cp: overwrite 'old'? [$? = 1]
$ touch old; sleep 2; touch new; echo N | cargo run cp -i -u new old
$
```

Found while trying to fix #4725.

**Comment by Vikrant2691** [comment]
I am ready to take this issue. please let me know..

**Comment by tertsdiepraam** [comment]
@Vikrant2691 I haven't verified this myself, but I trust @BenWiederhake :) Feel free to pick this up!

**Comment by BenWiederhake** [comment]
@Vikrant2691 I'm glad you're helping, yes, please do! :D

**Comment by Vikrant2691** [comment]
Thank you @BenWiederhake and @tertsdiepraam, I will try to replicate the issue at my end and check out! :)

**Comment by Vikrant2691** [comment]
I was able to replicate the issue
```shell
$ echo "hello">old; touch new
$ coreutils cp -i -u new old  # no prompt
$ cp -i -u new old
cp: overwrite 'old'? N
```
Additionally, `coreutils` is not overwriting the file.

**Comment by Vikrant2691** [comment]
Hi @BenWiederhake and @tertsdiepraam please let me know if the PR is ok to be merged or needs more work. :)

**Comment by BenWiederhake** [comment]
Closing, because #6069 was factually merged.
