### ISSUE TITLE
Duplicate tests in test_sort::test_buffer_sizes

### ISSUE THREAD

**Issue by Nahor** [uutils/coreutils#6062]
The test for "1000G" and "10T" are repeated for each of the smaller buffer sizes because of an incorrectly placed curly brace:
(error introduced by commit 6b8de1dd)

```
for buffer_size in <small buffers> {
   <test small buffer>
   
   {
     <test big buffers>
   }
}
```

**Comment by cakebaker** [comment]
Good catch, thanks!
