### ISSUE TITLE
ci: build crates independently to verify that all features are declared

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#6113]
Here, as part of the push to crates.io, the build failed because a feature declaration was missing. See:
https://github.com/uutils/coreutils/commit/dcb53b6c9989b956ed4ebc4122cc85de0b384726

we should have a task which will build all the programs separately

**Comment by tertsdiepraam** [comment]
\*sigh\* this happens every single release 😄

**Comment by cakebaker** [comment]
How is this issue different from https://github.com/uutils/coreutils/issues/6097?

**Comment by sylvestre** [comment]
oh, sorry :(
only 4 days ago ...
