### ISSUE TITLE
MacOS builds are failing due to sccache

### ISSUE THREAD

**Issue by BenWiederhake** [uutils/coreutils#6116]
This seems to affect the `cargo clippy` step, with the only output being:

```
(… many other lines of "checking" …)
    Checking uu_printf v0.0.25 (/Users/runner/work/coreutils/coreutils/src/uu/printf)
    Checking uu_cat v0.0.25 (/Users/runner/work/coreutils/coreutils/src/uu/cat)
    Checking uu_expr v0.0.25 (/Users/runner/work/coreutils/coreutils/src/uu/expr)
    Checking uu_nl v0.0.25 (/Users/runner/work/coreutils/coreutils/src/uu/nl)
sccache: Compile terminated by signal 6
error: could not compile `coreutils` (test "tests")
Error: Process completed with exit code 1.
```

This affects at least #6112 and #6115.

**Comment by cre4ture** [comment]
```
    Checking uu_comm v0.0.26 (/Users/runner/work/coreutils/coreutils/src/uu/comm)
    Checking uu_uptime v0.0.26 (/Users/runner/work/coreutils/coreutils/src/uu/uptime)
sccache: Compile terminated by signal 6
error: could not compile `uu_numfmt` (lib test)
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 1.
```

**Comment by sylvestre** [comment]
not sure it is caused by sccache itself?!

**Comment by BenWiederhake** [comment]
How does MacOS behave around out-of-memory? If that's the root cause, that would explain the Stardew Valley crash (i.e. your linked apple-forum discussion) and why the crashing package in our CI is seemingly random.

Is there a way to increase the available memory to test this theory? I don't use MacOS, how reasonable is that?

Btw, I really don't like the "just retry until it works" approach, we shouldn't always default to it as the first and best idea. Sure, sometimes it can['](https://www.youtube.com/watch?v=pHVf_a0qHsA&pp=ygUXaXQgY2Fubm90IGJlIGhlbHBlZCBzY3A%3D)t be helped, but let's try at least *some* other approach first.

**Comment by cre4ture** [comment]
success on the second try:
https://github.com/uutils/coreutils/actions/runs/8499288912/job/23279932438?pr=6156

didn't take time to reproduce.

if we find a better solution i'm fully in. But till now there is nothing better.
