### ISSUE TITLE
docs: Compatibility table is wrong

### ISSUE THREAD

**Issue by BenWiederhake** [uutils/coreutils#6117]
I have no idea what happened, but at first glance it seems like every platform was "overwritten" by something else, perhaps Windows:

![Bildschirmfoto_2024-03-24_01-19-53](https://github.com/uutils/coreutils/assets/2690845/95e6923e-1545-4292-8d23-5ea0ebc67cc7)

([source](https://uutils.github.io/coreutils/book/platforms.html))

Observe in particular how the text claims that `chgrp` is not supported on Windows, implying that it *is* supported by some other platform; meanwhile, the table claims that `chgrp` is not supported at all.

I have no idea where this code lives or how to fix it.

**Comment by tertsdiepraam** [comment]
The table is generated by the uudoc binary. I'll take a look tomorrow.
