### ISSUE TITLE
Date: make a new release of parse_datetime to fix date-sec gnu test case

### ISSUE THREAD

**Issue by matrixhead** [uutils/coreutils#6137]
Hi everyone,
I was trying to solve `date-sec` gnu test case in date utility and I made a pr in `parse_datetime`  [#65](https://github.com/uutils/parse_datetime/pull/65), so I was hoping we could have a new release of `parse_datetime` so that it would make the test case pass in our gnu test coverage.

**Comment by cakebaker** [comment]
Fixed with https://github.com/uutils/coreutils/pull/6423
