### ISSUE TITLE
`env`: implement `--ignore-signal`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#6164]
```

       --ignore-signal[=SIG]
              set handling of SIG signal(s) to do nothing
```

**Comment by wjhoward** [comment]
I can take a look at implementing this feature.

**Comment by radhesh1** [comment]
interesting issue

**Comment by radhesh1** [comment]
Uhm did someone leave a comment for me?

**Comment by Walid-Kh** [comment]
> Uhm did someone leave a comment for me?

I'm sorry were you working on this?

**Comment by radhesh1** [comment]
You can work on this, I wanted to know about the deleted comment notification I got 
![Uploading IMG_1972.jpeg…]()

**Comment by cakebaker** [comment]
@Walid-Kh sure, go ahead :)

@radhesh1: if I remember correctly your comment was rather generic, something along "an interesting feature", and so it was probably removed for not adding anything to the issue at hand.
