### ISSUE TITLE
`env -u=2EKt` should generate an error

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#6165]
Found working on a fuzzer.
With our impl, it returns the env variable:

```
$  ./target/debug/coreutils env -u=2EKt  
ALACRITTY_LOG=/tmp/Alacritty-56177.log
[...]
```

With GNU:
```
$ LANG=C /usr/bin/env -u=2EKt
/usr/bin/env: cannot unset '=2EKt': Invalid argument
```

**Comment by karlmcdowall** [comment]
Hey folks, I'm new here and was thinking of picking this up as a first effort. Please let me know if I should do otherwise!
Karl

**Comment by cakebaker** [comment]
@karlmcdowall sure, go ahead :)

**Comment by karlmcdowall** [comment]
I see similar discrepancies on other tools between the Rust and GNU implementations. e.g...

#### Tail
Rust
<code>
$ ./target/debug/tail -n=1
pedantic = { level = "deny", priority = -1 }
</code>
GNU
<code>
$ /usr/bin/tail -n=1
/usr/bin/tail: invalid number of lines: ‘=1’
</code>

#### Touch
Rust
<code>
~/Rust/coreutils$ ./target/debug/touch -r=Cargo.lock Cargo.toml
</code>
GNU
<code>
$ /usr/bin/tail -n=1
~/Rust/coreutils$ /usr/bin/touch -r=Cargo.lock Cargo.toml
touch: failed to get attributes of '=Cargo.lock': No such file or directory
</code>

Seems there's a difference between clap and GNU-getopts. Worth raising as a bug/feature-request on clap??

**Comment by karlmcdowall** [comment]
Raised a discussion about this on the clap discussion board [here](https://github.com/clap-rs/clap/discussions/5824)
