### ISSUE TITLE
Contributing Link in Docs of coreutils is broken

### ISSUE THREAD

**Issue by riesentoaster** [uutils/coreutils#6186]
Link on the docs page of coreutils (https://uutils.github.io/coreutils/), pointing here (https://uutils.github.io/coreutils/CONTRIBUTING.md) is broken (returns 404).

**Comment by tertsdiepraam** [comment]
Indeed! Turns out it's pretty hard to automatically turn a readme into a proper webpage :smile: We're much better off separating those.

**Comment by cakebaker** [comment]
Fixed by https://github.com/uutils/uutils.github.io/pull/34
