### ISSUE TITLE
kill: --list output format differs from GNU

### ISSUE THREAD

**Issue by jfinkels** [uutils/coreutils#6197]
Environment: Ubuntu 20.04, uutils main branch (git commit 415de28fedcd66ae3482f22d4ba274fe77c9d3d8), GNU coreutils version 9.5.3-8f39 (from git commit coreutils/coreutils@8f3989d586a88d182700050b435d2f6c393ec27b).

The uutils version of `kill --list` prints all the signal names in one line, whereas recent GNU versions prints each signal name on its own line. (There are also more signals listed on my system, but this issue is only about the formatting.) This difference is causing the GNU test file `tests/misc/kill.sh` to ERROR.

uutils kill:
```
$ ./target/debug/kill -l
EXIT HUP INT QUIT ILL TRAP ABRT BUS FPE KILL USR1 SEGV USR2 PIPE ALRM TERM STKFLT CHLD CONT STOP TSTP TTIN TTOU URG XCPU XFSZ VTALRM PROF WINCH POLL PWR SYS
```

GNU kill:
```
$ ./kill -l
HUP
INT
QUIT
ILL
TRAP
ABRT
BUS
FPE
KILL
USR1
SEGV
USR2
PIPE
ALRM
TERM
STKFLT
CHLD
CONT
STOP
TSTP
TTIN
TTOU
URG
XCPU
XFSZ
VTALRM
PROF
WINCH
POLL
PWR
SYS
RTMIN
RTMIN+1
RTMIN+2
RTMIN+3
RTMIN+4
RTMIN+5
RTMIN+6
RTMIN+7
RTMIN+8
RTMIN+9
RTMIN+10
RTMIN+11
RTMIN+12
RTMIN+13
RTMIN+14
RTMIN+15
RTMAX-14
RTMAX-13
RTMAX-12
RTMAX-11
RTMAX-10
RTMAX-9
RTMAX-8
RTMAX-7
RTMAX-6
RTMAX-5
RTMAX-4
RTMAX-3
RTMAX-2
RTMAX-1
RTMAX
```

**Comment by m-haisham** [comment]
I would like to contribute, shall I make a PR?

**Comment by BenWiederhake** [comment]
That would be great!

**Comment by cakebaker** [comment]
Fixed in https://github.com/uutils/coreutils/pull/6201.

Thanks for the hint, @Carbrex
