### ISSUE TITLE
kill: should fail if no PID is specified

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#6221]
When running GNU `kill` without a PID, it fails and shows an error message:
```
$ ~/projects/gnu/src/kill
/home/dho/projects/gnu/src/kill: no process ID specified
Try '/home/dho/projects/gnu/src/kill --help' for more information.
$ echo $?
1
```
uutils `kill`, on the other hand, doesn't fail and there is no output:
```
$ cargo run --features=unix kill
$ echo $?
0
```

**Comment by jadijadi** [comment]
working on this. will add related tests and will send a PR after tests are done.
