### ISSUE TITLE
sort: unknown lint clippy::suspicious_open_options on OpenBSD

### ISSUE THREAD

**Issue by lcheylus** [uutils/coreutils#6290]
On OpenBSD stable (current version 7.5), Rust version  = 1.76.0

During CI lint with `cargo clippy`, I have the error `unknown lint: clippy::suspicious_open_options` in `src/uu/sort/src/sort.rs`, line 254.

Indeed, the check for `suspicious_open_options` is supported only with Rust >= 1.77.0 => https://rust-lang.github.io/rust-clippy/master/index.html#/suspicious_open_options

On OpenBSD 7.5 with Rust 1.76, this check must be disabled in `src/uu/sort/src/sort.rs`.

**Comment by tertsdiepraam** [comment]
This feels kind of like something we could just ignore for now. With clippy we just follow stable and even with this warning it still compiles and they might even upgrade fairly soon and then the warning will disappear.

**Comment by lcheylus** [comment]
I'm working to add CI for OpenBSD, based on [vmactions/openbsd-vm](https://github.com/vmactions/openbsd-vm). This action uses OpenBSD stable (current = 7.5) version.

**`rustup` is not supported on OpenBSD** :( and I need to install the `rustc/cargo` packages from OpenBSD ports. rustc/cargo version = 1.76 on OpenBSD stable/7.5 and **will not be updated before the next stable release** (future version 7.6, release ~ October 2024).

To have a working "Style/Lint" job on OpenBSD, I need to disable `clippy::suspicious_open_options` in `src/uu/sort/src/sort.rs` on OpenBSD. Otherwise, my "Style/Lint" job fails on OpenBSD.

I will push a PR to fix this issue (tested on OpenBSD and FreeBSD in my forked repo).
