### ISSUE TITLE
GNU test FAIL: tests/uniq/uniq.pl

### ISSUE THREAD

**Issue by cre4ture** [uutils/coreutils#6297]
This gnu test is failing. 
I will look into it.
I create a ticket as I didn't find one.

**Comment by sylvestre** [comment]
we don't open bug for every GNU test failing
we investigate why and we open a bug
some might be easy but some will require a lot of different fixes

**Comment by cre4ture** [comment]
aha. I opened the issue to avoid that me and someone else would work on the issue in parallel without knowing.

**Comment by sylvestre** [comment]
unlikely :)
