### ISSUE TITLE
fmt: Error priorities could be improved

### ISSUE THREAD

**Issue by BenWiederhake** [uutils/coreutils#6352]
```console
$ fmt -g apple -g7 tests/fixtures/fmt/one-word-per-line.txt
this is a
file with one
word per line
$ fmt -g apple -g7 -w banana tests/fixtures/fmt/one-word-per-line.txt
fmt: invalid width: 'banana'
[$? = 1]
$ fmt -g apple -w banana tests/fixtures/fmt/one-word-per-line.txt
fmt: invalid width: 'banana'
[$? = 1]
$ fmt -w apple -g banana tests/fixtures/fmt/one-word-per-line.txt
fmt: invalid width: 'apple'
[$? = 1]
```

This means:
- A non-numeric value for a numeric argument is okay *IF* it is later overridden by a numeric argument.
- `--width`-related errors take priority over `--goal`-related errors, no matter the order.

I have some questions:
- To what extent do we want to be error-message compatible?
- This probably affects other utils, too. What's our standpoint, in general?

**Comment by tertsdiepraam** [comment]
"Terrible" is not support helpful 😄 Do you mean GNU or uutils here? We could do this quite easily, by supporting a string and then passing them after argument parsing.

**Comment by BenWiederhake** [comment]
Oh, sorry! I meant GNU, as in "This is terribly difficult to match".

re parsing: Oh! I only now notice that the error message is indeed simple enough. Dips!
