### ISSUE TITLE
ls: Unexpected space before stdout in TTY output

### ISSUE THREAD

**Issue by RenjiSann** [uutils/coreutils#6386]
I was fixing [TODOs](https://github.com/uutils/coreutils/blob/8078fca99b71946ff5865c097d0d42bd6818ee92/tests/by-util/test_ls.rs#L2659C12-L2659C16) in the testsuite to check TTY outputs.

And I realized that there is a seemingly unexpected character (presumably a space) that gets printed.

```
❯ /bin/ls "$(echo -e 'a\nb')" --hide-control-chars  
'a'$'\n''b'

❯ target/debug/ls "$(echo -e 'a\nb')" --hide-control-chars
 'a'$'\n''b'
^
Unexpected space
```

The default escaping strategy when outputing to a TTY is `shell-escape`. Strangely, the bug does not appear when output is not a TTY but with `--quoting-style=shell-escape` set, as already [checked by the testsuite](https://github.com/uutils/coreutils/blob/8078fca99b71946ff5865c097d0d42bd6818ee92/tests/by-util/test_ls.rs#L2678)

**Comment by RenjiSann** [comment]
I modified the assertion code to dump the bytes of expected/got stdouts on failure, and I ended up with this:
```
---- test_ls::test_ls_quoting_and_color stdout ----
touch: /tmp/.tmpyfPDjs/one two
run: /home/renji/projects/coreutils/target/debug/coreutils ls --color one two
run: /home/renji/projects/coreutils/target/debug/coreutils ls --color one two
EXPECTED: [32, 39, 111, 110, 101, 32, 116, 119, 111, 39, 10]
GOT     : [32, 39, 111, 110, 101, 32, 116, 119, 111, 39, 13, 10]
thread 'test_ls::test_ls_quoting_and_color' panicked at tests/by-util/test_ls.rs:2905:10:
explicit panic
```

So it appears that the prefix character is indeed a `0x20` space, but the code also includes a trailing carriage return `\r` (`0x0D`) before the linefeed `\n`.

I still don't have a clue for why is this happening though.

**Comment by RenjiSann** [comment]
Found: [this](https://github.com/uutils/coreutils/blob/97f8361737ce1295627537617108b660e8d35ab2/src/uu/ls/src/ls.rs#L2622) is where the space is added.

No searching why is the behavior only triggered by TTY

**Comment by RenjiSann** [comment]
I removed the "adding space if quoted and starts with `'`" logic [here](https://github.com/uutils/coreutils/blob/97f8361737ce1295627537617108b660e8d35ab2/src/uu/ls/src/ls.rs#L2618C1-L2630C11) and it didn't break any test.

I am not sure what it is made for, but so far, removing it fixes my problem.

@tertsdiepraam I see you changed this code in `3346b4147aa7c9dd5e5ad822ac927407010eb8de`, maybe you'll have some insights.

**Comment by tertsdiepraam** [comment]
For anyone else, link to that commit: https://github.com/uutils/coreutils/commit/3346b4147aa7c9dd5e5ad822ac927407010eb8de

Seems like I made a mistake? The logic should be that there's a space if the quoting style does not add a quote, but I seem to have flipped that behaviour? That's not good :)

Negating the condition should fix it. But, we also need to think about when it's quoted with `"` maybe. We might need to come up with a more robust check. Do you want to give that a shot?

**Comment by RenjiSann** [comment]
> For anyone else, link to that commit: [3346b41](https://github.com/uutils/coreutils/commit/3346b4147aa7c9dd5e5ad822ac927407010eb8de)
> 
> Seems like I made a mistake? The logic should be that there's a space if the quoting style does not add a quote, but I seem to have flipped that behaviour? That's not good :)
> 
> Negating the condition should fix it. But, we also need to think about when it's quoted with `"` maybe. We might need to come up with a more robust check. Do you want to give that a shot?

I can, but I don't have all the context. I don't know in what case a space is required in the first place.
Would you have an example to share, or some doc that talk about this behavior ?

**Comment by tertsdiepraam** [comment]
It's just an alignment thing. Here's an example using GNU:
```
> ls
'bla bla'   Cargo.lock   CODE_OF_CONDUCT.md   deny.toml        docs   GNUmakefile   Makefile        oranda.json   renovate.json   target   util
 build.rs   Cargo.toml   CONTRIBUTING.md      DEVELOPMENT.md   fuzz   LICENSE       Makefile.toml   README.md     src             tests
```
Note how all the files have a space to compensate for not having quotes and that `'bla bla'` doesn't have a space.

**Comment by RenjiSann** [comment]
Oh, I think I get it.

I'll give it a try !
