### ISSUE TITLE
date: `--date` doesn't recognize negative timestamps

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#6415]
GNU `date` allows negative timestamps whereas uutils `date` fails:
```
$ LC_ALL=C date --date="@-1"
Thu Jan  1 00:59:59 CET 1970

$ cargo run date --date="@-1"
date: invalid date '@-1'
```

**Comment by cakebaker** [comment]
Probably fixed in https://github.com/uutils/parse_datetime/pull/43, though its changes are not included in the current version `0.5.0` of `parse_datetime`.

**Comment by sylvestre** [comment]
@cakebaker should we make a new release?

**Comment by cakebaker** [comment]
@sylvestre Yes, it has been a while since the latest release. And there is also https://github.com/uutils/coreutils/issues/6137 asking for a release.

**Comment by cakebaker** [comment]
Fixed with https://github.com/uutils/coreutils/pull/6423
