### ISSUE TITLE
ls: gnu test case `color-ext` compatibility

### ISSUE THREAD

**Issue by matrixhead** [uutils/coreutils#6536]
The GNU test case `color-ext`  was failing because our ls command doesn't handle suffix letter cases.

#### example 1

```shell
touch img1.jpg IMG2.JPG img3.JpG file1.z file2.Z
LS_COLORS="*.jpg=01;35:*.JPG=01;35;46" ls -U1 --color=always   img1.jpg IMG2.JPG img3.JpG
```
our ls would produce output 
```
^[0m^[01;35;46mimg1.jpg^[0m
^[01;35;46mIMG2.JPG^[0m
^[01;35;46mimg3.JpG^[0m

``` 
but it should be 
```
^[0m^[01;35mimg1.jpg^[0m
^[01;35;46mIMG2.JPG^[0m
img3.JpG

``` 
like wise
#### example 2
```shell
LS_COLORS="*.jpg=01;35;46:*.jpg=01;35:*.JPG=01;35;46"   ls -U1 --color=always img1.jpg IMG2.JPG img3.JpG 
```
our ls would give  
```
^[0m^[01;35;46mimg1.jpg^[0m
^[01;35;46mIMG2.JPG^[0m
^[01;35;46mimg3.JpG^[0m
``` 
but it should be 
```
^[0m^[01;35mimg1.jpg^[0m
^[01;35;46mIMG2.JPG^[0m
img3.JpG
``` 
In both cases, this is happening because `lscolors` doesn't care about the case sensitivity of the entries in the env.

**Comment by sylvestre** [comment]
> ls command doesn't handle suffix letter cases

what do you mean by this ? :)

**Comment by matrixhead** [comment]
sorry, I was typing it and accidentally pressed Ctrl+enter

**Comment by matrixhead** [comment]
I already made an [issue](https://github.com/sharkdp/lscolors/issues/48#issuecomment-2203281707) in `lscolors`'s repo and working on a [fix](https://github.com/sharkdp/lscolors/pull/86)
