### ISSUE TITLE
unable to use docopt

### ISSUE THREAD

**Issue by neolem** [uutils/coreutils#654]
I am working on 'cp' and am looking to use ``docopt``, https://github.com/docopt/docopt.rs as a substitute for ``getopt``. However, I am getting numerous errors. As a quick test I replaced the ``src/cp.rs`` with the code fragment below.

```
extern crate rustc_serialize;
extern crate docopt;

use docopt::Docopt;

// Write the Docopt usage string.
static USAGE: &'static str = "
Usage: cp [-a] <source> <dest>
       cp [-a] <source>... <dir>

Options:
    -a, --archive  Copy everything.
";

#[derive(RustcDecodable, Debug)]
struct Args {
    arg_source: Vec<String>,
    arg_dest: String,
    arg_dir: String,
    flag_archive: bool,
}

fn main() {
    let args: Args = Docopt::new(USAGE)
                            .and_then(|d| d.decode())
                            .unwrap_or_else(|e| e.exit());
    println!("{:?}", args);
}
```
I also modified the ``deps/Cargo.toml`` with the following
```
...
docopt = "0.6.67"
...
```
and created ``src/cp/deps.mk`` as following
```
DEPLIBS += docopt rustc-serialize
```
Running ``make BUILD='cp'`` gives the error below. 
>coreutils/src/cp/cp.rs:2:1: 2:21 error: can't find crate for `regex` which `docopt` depends on
/home/projects/r-coreutils/src/cp/cp.rs:2 extern crate docopt;
                                                ^~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Makefile:300: recipe for target '/home/projects/r-coreutils/build/libcp.rlib' failed
make: *** [/home/projects/r-coreutils/build/libcp.rlib] Error 101

**Comment by christianbundy** [comment]
This may work better as a pull request rather than an issue.

**Comment by knight42** [comment]
`getopts` works fine at present and I guess there is no need to switch to `docopt`.
