### ISSUE TITLE
0.0.27 release retagged?

### ISSUE THREAD

**Issue by gromgit** [uutils/coreutils#6552]
Hi! I'm a volunteer with the [Homebrew package management project](https://brew.sh), and noticed that the release tarball checksum has changed since we packaged it shortly after release:
```
$ brew install -s uutils-coreutils
[...]
==> Downloading https://github.com/uutils/coreutils/archive/refs/tags/0.0.27.tar.gz
==> Downloading from https://codeload.github.com/uutils/coreutils/tar.gz/refs/tags/0.0.27
Error: uutils-coreutils: SHA256 mismatch
Expected: 28d537a5210e8593ff30c566192c7f63eb60db9ae76cd4612c2ab131e2c112d2
  Actual: 3076543a373c8e727018bd547cc74133f4a6538849e4990388f2bbea9a9aff6b
```

Was this release retagged? If so, it would be better to just cut a new release in future, to avoid confusing downstream packagers, and raise fears of a supply chain compromise. Thanks much!

**Comment by tertsdiepraam** [comment]
I believe it was indeed. We tagged it outside of any public branch and fixed that later once another package maintainer notified us about it. @sylvestre could you confirm?

**Comment by sylvestre** [comment]
yeah, only Cargo.lock changed. Sorry about that :(

**Comment by gromgit** [comment]
OK thanks, we'll update our formula accordingly.
