### ISSUE TITLE
sync build broken on non-windows

### ISSUE THREAD

**Issue by ebfe** [uutils/coreutils#659]
47f82f0de broke the non-windows build for sync.

    uutils/src/sync/sync.rs:40:42: 40:46 error: couldn't read "/home/m/src/uutils/src/sync/platform/../../common/wide.rs": No such file or directory (os error 2)
    uutils/src/sync/sync.rs:40     #[path = "../../common/wide.rs"] mod wide;

Not sure why this is happening since that code is in a windows only module.
Also kernel32-sys and avapi32-sys are build on unix. Are these really
necessary?

cc @retep998

**Comment by retep998** [comment]
`winapi` and its `-sys` crates are all no-ops on non-Windows. It's easier to just depend on them unconditionally since they build everywhere anyway.
