### ISSUE TITLE
Broken Links in Documentation Website

### ISSUE THREAD

**Issue by Rdna123** [uutils/coreutils#6602]
I have found some broken links in the docs. They are caused by the direct copying of markdown files from other parts of the repo into the docs folder, such as [CONTRIBUTING.MD](https://github.com/uutils/coreutils/blob/main/CONTRIBUTING.md) to [contributing.md](docs/src/contributing.md). Making the references to DEVELOPMENT.md and CODE_OF_CONDUCT.md break when viewing the website.

**Comment by just-an-engineer** [comment]
Hey, are you able to say which link on which page? I just took a look and the ones I found worked, but I could just be in the wrong places and didn't do a thorough enough job. Or perhaps someone made a PR that fixed it, in which case we can close this.

**Comment by cakebaker** [comment]
It's on the following page: https://uutils.github.io/coreutils/docs/contributing.html . The first two links cause a 404.
