### ISSUE TITLE
``rm`` : Removes parent directory 

### ISSUE THREAD

**Issue by AnirbanHalder654322** [uutils/coreutils#6620]
Coreutils 
```
mkdir d
rm -rf d/..
 ```
This removes all the files in parent directory of ``d``.

GNU

```
mkdir d
rm -rf d/..
```

This fails and produces the error message below.
``rm: refusing to remove '.' or '..' directory: skipping 'd/..``

This is related to the **rm/r-4.sh** compatibility test.

**Comment by just-an-engineer** [comment]
I'll take this one
