### ISSUE TITLE
`misc/invalid-opt.pl` is missing on test coverage page

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#6660]
While looking at https://github.com/uutils/coreutils/pull/6657 I noticed that `misc/invalid-opt.pl` is missing on our [test coverage page](https://uutils.github.io/coreutils/docs/test_coverage.html).

**Comment by sylvestre** [comment]
bizarre:
```
./util/remaining-gnu-error.py|grep misc/invalid-opt.pl
../gnu/tests/misc/invalid-opt.pl: 2157
```

**Comment by sylvestre** [comment]
here is why:
https://github.com/uutils/coreutils/blob/main/util/build-gnu.sh#L177
