### ISSUE TITLE
Define standards

### ISSUE THREAD

**Issue by ashleyh** [uutils/coreutils#67]
What exactly are we aiming for in these implementations: are we aiming to replicate the quirks of the GNU implementations exactly? Or trying to be POSIXly correct? Or just doing our best for now and worrying about the details later?

My 2p: the GNU quirks aren't all good, e.g. GNU `uniq -i` thinks 'Γ' and 'γ' are distinct.

**Comment by sylvestre** [comment]
I think the project is now trying to match GNU's behavior. Closing
