### ISSUE TITLE
RFC: Impossible to verify checksum on Windows for any binary file that has the sequence `\r\n`

### ISSUE THREAD

**Issue by Pistonight** [uutils/coreutils#6805]
hashsum with `--check` always run in text mode on Windows:
https://github.com/uutils/coreutils/blob/3f694faa2e9399bcc7838322113cbf4c93575e8e/src/uu/hashsum/src/hashsum.rs#L236-L247
And you can't specify `--binary`
https://github.com/uutils/coreutils/blob/3f694faa2e9399bcc7838322113cbf4c93575e8e/src/uu/hashsum/src/hashsum.rs#L225-L227

Since text mode replaces `\r\n` with `\n`, this leads to unusual behavior:
In Linux:
```bash
$ cat sha256sums.txt | rg "2024.10.01-x86_64.iso"
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db  archlinux-2024.10.01-x86_64.iso

$ sha256sum archlinux-2024.10.01-x86_64.iso --binary
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db *archlinux-2024.10.01-x86_64.iso

$ sha256sum archlinux-2024.10.01-x86_64.iso --text
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db  archlinux-2024.10.01-x86_64.iso

$ sha256sum -c sha256sums.txt
archlinux-2024.10.01-x86_64.iso: OK

$ sha256sum archlinux-2024.10.01-x86_64.iso --binary | sha256sum -c
archlinux-2024.10.01-x86_64.iso: OK

$ sha256sum archlinux-2024.10.01-x86_64.iso --text | sha256sum -c
archlinux-2024.10.01-x86_64.iso: OK

$ sha256sum archlinux-2024.10.01-x86_64.iso | sha256sum -c
archlinux-2024.10.01-x86_64.iso: OK
```

In Windows:
```bash
$ cat sha256sums.txt | rg "2024.10.01-x86_64.iso"
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db  archlinux-2024.10.01-x86_64.iso

$ sha256sum archlinux-2024.10.01-x86_64.iso --binary
b72dd6ffef7507f8b7cddd7c69966841650ba0f82c29a318cb2d182eb3fcb1db *archlinux-2024.10.01-x86_64.iso

$ sha256sum archlinux-2024.10.01-x86_64.iso --text
e91465b21fa5f556c1015a3e8f44aef94301b2f742e56f23c6256c1bc9eb2855  archlinux-2024.10.01-x86_64.iso

$ sha256sum -c sha256sums.txt
archlinux-2024.10.01-x86_64.iso: FAILED
sha256sum: sha256sums.txt: no file was verified
sha256sum: WARNING: 1 computed checksum did NOT match

$ sha256sum archlinux-2024.10.01-x86_64.iso --binary | sha256sum -c
archlinux-2024.10.01-x86_64.iso: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

$ sha256sum archlinux-2024.10.01-x86_64.iso | sha256sum -c
archlinux-2024.10.01-x86_64.iso: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

$ sha256sum archlinux-2024.10.01-x86_64.iso --text | sha256sum -c
archlinux-2024.10.01-x86_64.iso: OK
```

I can think of 3 ways this might be fixed:
1. Make `--binary` the default on Windows (might break some workflows for checking text files)
2. Derive the mode for `--check` from previous output on Windows
    - Might require adding `*` manually before passing the input to hashsum, since the output might be obtained previously on GNU system without specifying `--binary`
3. Allow specifying `--binary` for `--check` on Windows

**Comment by sylvestre** [comment]
could you please replace the screenshot by text ? They are terrible for search and accessibility. Thanks

**Comment by Pistonight** [comment]
> could you please replace the screenshot by text ? They are terrible for search and accessibility. Thanks

Sorry about that, it's updated now

**Comment by Pistonight** [comment]
I added some thoughts for how I think this could be fixed:
> Make --binary the default on Windows (might break some workflows for checking text files)

I assume there's a reason why `--text` is the default on Windows?

> Derive the mode for --check from previous output on Windows

Would keep CLI the same but internal behavior will differ from GNU

> Allow specifying --binary for --check on Windows

CLI would differ from GNU

Would love to know your thoughts, and I can take a stab at implementation

**Comment by sylvestre** [comment]
> I assume there's a reason why --text is the default on Windows?

Yes, it is a bug :) I was testing this on linux & mac 

> CLI would differ from GNU

On windows, if documented, it is probably fine :)
