### ISSUE TITLE
cp: skip duplicate source check when --backup is given

### ISSUE THREAD

**Issue by matrixhead** [uutils/coreutils#6827]
When duplicate sources and the --backup option are provided to `cp`, GNU `cp` skips the duplicate source check and proceeds with copying the files. However, `uu-cp` does not currently behave this way.

**For example**
```shell
touch a; mkdir d;
cp --backup a a d/ 
``` 
GNU's `cp` would skip duplicate source check and tries to overwrite the "just-created" file and give us the error, (if `backup--numbered` is given then this won't file).
```
cp: will not overwrite just-created 'd/a' with 'a'
``` 
While `uu-cp` would give us
```
cp: warning: source file 'a' specified more than once
```

**Comment by cakebaker** [comment]
Fixed by https://github.com/uutils/coreutils/pull/6825
