### ISSUE TITLE
cp: Duplicate source error message should specify the type of file.

### ISSUE THREAD

**Issue by matrixhead** [uutils/coreutils#6832]
When a source directory is specified more than once, the error message should clearly indicate that it’s a directory, not a file.

**Example:**
```shell
mkdir b; mkdir d;
cp -r b b d/
``` 

GNU’s `cp` produces the following message:
```
warning: source directory 'b' specified more than once
``` 

Whereas `uu-cp` outputs:
```
warning: source file 'b' specified more than once
```

**Comment by cakebaker** [comment]
Fixed by https://github.com/uutils/coreutils/pull/6825
