### ISSUE TITLE
Please include the release notes in the releases

### ISSUE THREAD

**Issue by williamdes** [uutils/coreutils#6859]
Because you are missing `draft: true` on https://github.com/uutils/coreutils/blob/1d9e1626377cbaea3b21842a3525a62ba60f905f/.github/workflows/CICD.yml#L755

The release is sent to Github subscribers via email without the nice and interesting content.
![Image](https://github.com/user-attachments/assets/f0a4ecac-ea23-4c20-bd81-b83fcd4e55e8)

Could you adjust that so users have nice and informative emails?

**Comment by sylvestre** [comment]
sure, thanks
See: https://github.com/uutils/coreutils/releases/tag/0.0.28

**Comment by williamdes** [comment]
> sure, thanks See: https://github.com/uutils/coreutils/releases/tag/0.0.28

Yeah sure I click the link to read them, but offline that does not work haha
