### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by vks** [uutils/coreutils#687]
> Contributions are very welcome, and should target Rust's master branch until Rust 1.0 is released.

Rust 1.0 has been released, and it does not seem that Rust stable is targeted. A possible clarification would be that Rust nightly is currently targeted.

**Comment by Heather** [comment]
I think we should have some branch just for nightly ...

**Comment by Arcterus** [comment]
Do you mean like a development branch that we merge into master whenever there's a new Rust stable?

**Comment by Heather** [comment]
Yes, maybe that could be good workflow to deal with rust updates

**Comment by Arcterus** [comment]
I agree.

**Comment by awestroke** [comment]
This can be closed now, I think. The information has moved to [CONTRIBUTING.md](https://github.com/uutils/coreutils/blob/master/CONTRIBUTING.md) and is no longer out of date.
