### ISSUE TITLE
seq: zero gets padded if specified with scientific notation

### ISSUE THREAD

**Issue by cakebaker** [uutils/coreutils#6926]
I noticed that if I specify zero with scientific notation (and without specifying `-w`), the zero gets padded. With GNU `seq`, there is no padding:
```
$ cargo run -q seq 0e15 1
0000000000000000
1
$ seq 0e15 1
0
1
```

**Comment by aimerlief** [comment]
I would like to work on this issue if it's not already being handled.

**Comment by sylvestre** [comment]
sure :)
