### ISSUE TITLE
Expand scope to include other, non-coreutils utilities

### ISSUE THREAD

**Issue by aarzee** [uutils/coreutils#696]
GNU also provides versions of some other common Unix utilities which could also be implemented in Rust, so I'm curious if items which do this would be welcome in this project. (I'm specifically interested in implementing GNU which).

**Comment by nathanross** [comment]
pinging #738

**Comment by nathanross** [comment]
The dev reporting the issue pinged above has also expressed interest in developing a drop-in replacement for a common GNU system utility not packaged in coreutils.

I have no opinion on uutils expanding its scope beyond this repository. 

I will say though that either way, it makes sense for rust drop-in-replacement projects to be aware of each other and cross-promote - people interested in one drop-in cross-platform memory-safe replacement for a popular system utility are the most likely demographic to be interested in another. Possibly there could be a repository with a markdown page that functioned as a directory of such projects, their development progress, build status, and which distros they have packages for.

Keep us in the loop if you do develop ```which``` or another utility.

**Comment by Arcterus** [comment]
I would be willing to create a new project under the uutils organization that handles other drop-in replacements, but I would rather that coreutils remains as it is now (_i.e._ only dealing with the rewrite of GNU coreutils).
