### ISSUE TITLE
rm: gentoo sandbox violation when emerging certain python packages

### ISSUE THREAD

**Issue by elde-n** [uutils/coreutils#7002]
When replacing GNU rm with uutils-rm (`cp /usr/bin/uu-rm /usr/bin/rm`) I get an error when emerging certain python packages.
However when replacing GNU rm with busybox-rm everything is fine.

```sandbox.log```
```
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /var/tmp/portage/dev-python/pip-24.3.1-r2/work/pip-24.3.1-python3_12/install//usr/bin/python3.12
A: /var/tmp/portage/dev-python/pip-24.3.1-r2/work/pip-24.3.1-python3_12/install/usr/bin/python3.12
R: /usr/bin/python3.12
C: rm /var/tmp/portage/dev-python/pip-24.3.1-r2/work/pip-24.3.1-python3_12/install//usr/bin/python3.12 /var/tmp/portage/dev-python/pip-24.3.1-r2/work/pip-24.3.1-python3_12/install//usr/bin/python3 /var/tmp/portage/dev-python/pip-24.3.1-r2/work/pip-24.3.1-python3_12/install//usr/bin/python /var/tmp/portage/dev-python/pip-24.3.1-r2/work/pip
-24.3.1-python3_12/install//usr/bin/pyvenv.cfg
```

**Comment by sylvestre** [comment]
please provide some steps to reproduce.
thanks

**Comment by elde-n** [comment]
1. `su` 
2. `echo "sys-apps/uutils-coreutils ~amd64" >> /etc/portage/package.accept_keywords/uutils-coreutils`
3. `emerge "=sys-apps/uutils-coreutils-0.0.28"`
4. `rm /usr/bin/rm`
5. `ln -s /usr/bin/uu-coreutils /usr/bin/rm`
6. `emerge dev-python/pip`

**Comment by sylvestre** [comment]
Sorry, i meant some simple commands with rm and the other steps that triggered the issue 
not something that requires installing Gentoo.

**Comment by elde-n** [comment]
looking at `strace` you can see that `uu-rm` uses calls `open("path", O_RDWR|O_LARGEFILE|O_CLOEXEC)`, while the gnu rm/busybox rm don't, the `open_wr` is what triggers the portage sandbox

**Comment by sylvestre** [comment]
Please provide steps to reproduce :)
it is way too hard to fix otherwise

**Comment by elde-n** [comment]
1. run this script
```sh
touch test.txt
strace -o gnu.log /usr/bin/rm test.txt

touch test.txt
strace -o uu.log /usr/bin/uu-rm test.txt

touch test.txt
strace -o busybox.log /usr/bin/busybox rm test.txt
```

2. compare the files

`std::fs::remove_file()` itself doesn't call `open`, you're using `std::fs::OpenOptions` which calls `open`
busybox rm and gnu rm use `access`/`faccessat2` to check for write permissions

**Comment by sylvestre** [comment]
how do i setup the sandbox?
