### ISSUE TITLE
factor: panic attempting to factorise powers of two.

### ISSUE THREAD

**Issue by RGafiyatullin** [uutils/coreutils#702]
Like that
```
rgmbp:coreutils rg$ ./build/factor 2
thread '<main>' panicked at 'Range::new called with `low >= high`', /Users/rg/.cargo/registry/src/github.com-0a35038f75765ae4/rand-0.3.11/src/distributions/range.rs:60
2:rgmbp:coreutils rg$
```

**Comment by KeyboardFire** [comment]
I can't reproduce this issue.

    llama@llama:...Code/rust/coreutils$ rcu-factor 2
    2: 2
    llama@llama:...Code/rust/coreutils$ rcu-factor 4
    4: 2 2
    llama@llama:...Code/rust/coreutils$ rcu-factor 8
    8: 2 2 2

Ubuntu 15.04, with the latest nightly.

**Comment by RGafiyatullin** [comment]
Sorry I've overbureaucratized this issue: #703 -- is the pull request that fixes that.
* b04796 -- panics;
* 545549 -- does not panic.
