### ISSUE TITLE
Implement mktemp

### ISSUE THREAD

**Issue by KeenS** [uutils/coreutils#713]
I'll try to implement `mktemp`.

BTW I have some questions:

1. Is the recommended reference is [coreutils/coreutils](https://github.com/coreutils/coreutils)?
2. Can I use external library (such as [tempfile](https://crates.io/crates/tempfile)?

**Comment by jbcrail** [comment]
Yes to both. My only caveat for the first question is to make a clean-room implementation (copy behavior, not code), since GNU coreutils is GPL and this implementation isn't.

Good luck! Feel free to ask for help if needed.
