### ISSUE TITLE
Move common code into a separate crate

### ISSUE THREAD

**Issue by ebfe** [uutils/coreutils#717]
The code in common is linked into several utils as module. This probably should
be a separate crate.

**Comment by jbcrail** [comment]
I have a private branch that started this. I was waiting for #715 to land before submitting a pull request.

My implementation moves `src/common` to `src/uucore` and uses Cargo to create a local library. Once the internal library is more stable, we can decide to extract the library to a separate repository.

**Comment by Heather** [comment]
@jbcrail thanks, I like the idea of extracting library
