### ISSUE TITLE
No option to cross-compile

### ISSUE THREAD

**Issue by alexchandel** [uutils/coreutils#746]
LLVM, rustc, and cargo are capable of cross-compilation with the right environment, but there's no way to set the target of the Makefile.

For example, to cross from x86_64-apple-darwin to i686-pc-windows-msvc:
- Install LLVM+Clang+LLD and add symlinks for `cl.exe`, `link.exe`, and `lib.exe` to `clang-cl`, `lld`, and `llvm-lib` resp.
- Copy the Win10 SDK to `~/i686-pc-windows-msvc-w10`, copy the VC6 SDK to `i686-pc-windows-msvc-vc6`
- Add the `lib` & `include` subdirectories of each SDK to the LIB & INCLUDE environment variables before `cl.exe` or `link.exe` is invoked.

At this point rustc and cargo are ready to cross-compile, although you'll need to use LTO because VC6 is missing some math functions.

However, the Makefile doesn't accept a target. The best I can do is hack it onto PROFILE_CMD, comment out the `ifneq ($(OS),Windows_NT)` comparison, and stick `TARGET_CC=cl.exe` before all the `${CARGO}` invocations (though that last one is only because gcc-rs sends the wrong args to `cc`, and I think `CC=cl.exe make` might be enough). But the `$(OS),Windows_NT` comparison should definitely use the target OS, not the host OS which `make` reports.

**Comment by ebfe** [comment]
You don't have to use the Makefile. Just run `cargo` with whatever options you like.

**Comment by alexchandel** [comment]
Cargo fails to build the binaries for anything but uutils (the multicall binary).

**Comment by ebfe** [comment]
Oh my. Sorry the build is still a mess...

With #748 `CARGOFLAGS="--target=<...>" make` should allow to specify your target

The OS check is indeed suboptimal,  it is only used to  disable utils that do not work on windows. You can override it on the commandline/environment (OS=<bla>).

This all should be improved/easier to use (I was hoping for target based feature flags in cargo...)

**Comment by nathanross** [comment]
@alexchandel to build binaries using cargo for an individual package, run ```cargo build -p <utilname>``` or run ```cargo build``` in that package/utility's directory. 

Anything you could do with cargo without a makefile, you can do right now.
