### ISSUE TITLE
tail performance on big files

### ISSUE THREAD

**Issue by ebfe** [uutils/coreutils#764]
tail is very slow when operating on large files. It reads the whole file from
the beginning when it probably should count newlines starting from the end of
file.

    $ wc -l lines
    100000000 lines
    
    $ time tail -n 1 lines
    blabla
    
    real	0m0.002s
    user	0m0.000s
    sys	0m0.000s
    
    $ time target/release/uutils tail -n 1 lines
    
    blabla
    
    real	0m6.349s
    user	0m6.247s
    sys	0m0.107s

**Comment by fitzgen** [comment]
I have some local changes that look pretty promising, but they are still WIP:

```
$ time tail ./tests/fixtures/tail/big.txt
line 999991
line 999992
line 999993
line 999994
line 999995
line 999996
line 999997
line 999998
line 999999
line 1000000

real	0m0.005s
user	0m0.001s
sys	0m0.002s

$ time ./target/release/deps/tail ./tests/fixtures/tail/big.txt
line 999991
line 999992
line 999993
line 999994
line 999995
line 999996
line 999997
line 999998
line 999999
line 1000000

real	0m0.008s
user	0m0.001s
sys	0m0.002s
```
