### ISSUE TITLE
chmod -+<octal> is broken

### ISSUE THREAD

**Issue by ebfe** [uutils/coreutils#788]

**Comment by yodalee** [comment]
I'm curious about this issue. Since even GNU coreutils doesn't provide such usage.
I try 
$ chmod +0020 file
only get: `chmod: invalid mode: `+0020'`

**Comment by ebfe** [comment]
> Since even GNU coreutils doesn't provide such usage.
It (chmod (GNU coreutils) 8.25) does.

**Comment by yodalee** [comment]
My GNU chmod on Debian is `chmod (GNU coreutils) 8.5`, and it doesn't provide such usage.
However it can be added, of course.

**Comment by yodalee** [comment]
I found that in rust coreutils
`chmod +octal file` works fine, `-octal` will fail with same reason as `chmod -x`. The arguments are invalid with lib `getopts`

**Comment by lucaotta** [comment]
I'm about to issue a pull request that fixes the behaviour.
