### ISSUE TITLE
Use buffered IO where approriate

### ISSUE THREAD

**Issue by huonw** [uutils/coreutils#8]
E.g. I think `cat -n` is particularly slow because it is doing a syscall to read 2 bytes at a time, wrapping the file reader in a [`std::rt::io::buffered::BufferedReader`](http://static.rust-lang.org/doc/master/std/rt/io/buffered/struct.BufferedReader.html) would likely fix this. (NB this is probably unnecessary overhead for `cat` without an arguments.)

**Comment by awestroke** [comment]
This is implemented and merged here: #138 
This issue can be closed
