### ISSUE TITLE
Use Homu

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#801]
Should we start using [this](https://github.com/barosl/homu)?

**Comment by ebfe** [comment]
It has a rather long issue list and not a lot of recent activity. Do you have any experience with it? What's the benefit?

**Comment by Arcterus** [comment]
I have not tried using it for anything yet (I was actually hoping someone else may have had some experience with it).  I noticed that it apparently replaced the original [bors](https://github.com/graydon/bors) used by Rust though.  Seems that it tests commits using Travis (or another CI service) before merging them, so I think this would be more useful when begin targeting the stable version of Rust rather than the nightlies.
