### ISSUE TITLE
AppVeyor build is ridiculously slow

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#804]
It's more than 10 times slower (according to the one build that has managed to successfully complete before another commit preempts it).

**Comment by ebfe** [comment]
It's downloading and installing a whole lot of stuff. Maube some of that can be skipped by switching to `cargo build`, `cargo test` instead of using the Makefile.

**Comment by shalupov** [comment]
Also probably https://www.appveyor.com/docs/build-cache will help
