### ISSUE TITLE
Broken utils (according to BusyBox)

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#806]
According to BusyBox, the following tests are either missing features or are now broken (I'm pretty sure `echo` used to pass all the tests, for example):
- cp
- du
- ~~echo~~
- expand
- fold
- hostname
- ~~mv~~
- ~~tail~~
- tr
- unexpand

**Comment by nathanross** [comment]
important to note: many GNU coreutils tools fail one or more of the tests on their corresponding busybox test.

I don't have the list on me right now, it can be generated from the makefile in [this branch](https://github.com/nathanross/coreutils-printf/blob/busytest-gnu-standalone/Makefile) by compiling coreutils 8.2.4, placing the resultant binaries in tmp/gnu (relative to the repo) and running ```make busytest```

I'll see if I can post the output tonight.

**Comment by ebfe** [comment]
echo, mv and tail don't fail for me.

**Comment by Arcterus** [comment]
I realized a little while ago that some of these failures are because I'm currently using a Mac, and BusyBox is using Mac OS X's version of coreutils to check the output of our utils.

**Comment by nathanross** [comment]
Detailed instructions for reproducing the results below are now available on the readme of [the branch](https://github.com/nathanross/coreutils-printf/tree/busytest-gnu-standalone)

#### Busybox test failures run against GNU Coreutils
(cp, date, du, expand, fold, hostname printf, unexpand)

```
FAIL: cp
FAIL: cp -d
FAIL: cp -P
FAIL: cp -L
FAIL: cp -H
FAIL: cp -RHP
FAIL: cp -RLH
FAIL: date-format-works
FAIL: date-u-works
FAIL: date-works
FAIL: date-works-1
FAIL: du-m-works
FAIL: expand-works-like-GNU
FAIL: expand with unicode characher 0x394
FAIL: fold -sw66 with unicode input
FAIL: hostname-d-works
FAIL: hostname-i-works
FAIL: hostname-s-works
FAIL: printf understands %d '"x' "'y" "'zTAIL"
FAIL: printf handles %d bad_input
FAIL: printf aborts on bare %
FAIL: printf aborts on %r
FAIL: unexpand-works-like-GNU
FAIL: unexpand case 7
FAIL: unexpand with unicode characher 0x394
```

#### Context

```
OS: debian 8.2.0 x64 running in the Virtualbox hypervisor
coreutils: v8.24
busybox: v1.24.1 (same as in current makefile)
configuration: ./configure --prefix=$repo/tmp/gnu/
```
