### ISSUE TITLE
Question: Consistent output across all platforms vs maximum fidelity on a single platform

### ISSUE THREAD

**Issue by nathanross** [uutils/coreutils#817]
Say we have behavior X it is possible to approximate it achieving the same consistent behavior on every platform (and approximate it to the extent that anyone using the program correctly or in a numerically sound way will not have a problem), but you can also achieve its exact behavior by linking to glibc (in this case stdio's printf for floating point behavior)

I.e. in the environment that nearly all of coreutils is used today, you have the possibility to achieve the exact same output as coreutils (better drop in replacement!), but it would mean minor differences in the output of your program on linux vs windows or os X etc. 

In a scenario like this:
- is it better to opt for the behavior that has maximum fidelity to the original program in the context the original program was used the most?
- or is it better to try to achieve consistent output across all platforms. (Using libc on one platform for one libc and not on others seems unexpected)

With printf floating point output, I've leaned towards consistent output across all platforms as opposed to being more drop-in replacement friendly on linux. But I understand that makes drop-in a little more questionable.

**Comment by Arcterus** [comment]
I think having consistent output across all platforms is probably a good idea, although I would still try to make it as drop-in replacement friendly as possible for Linux.  Basically make it as drop-in friendly as you can while still having consistent output.

**Comment by Shados** [comment]
I'm definitely in support of 'consistent output across all platforms'. That said, enabling drop-in replacement of GNU coreutils would be excellent: maybe make 'maximum fidelity' behaviour optional at compile-time?

**Comment by Arcterus** [comment]
I've been thinking for stuff like this it may make more sense to do something like `POSIXLY_CORRECT` but for enabling even more GNU-like output/behavior.  We could call it `GNULY_CORRECT` or something.  Utilities can then just check whether the variable is set before checking for certain command-line options or determining how to format output.
