### ISSUE TITLE
Standardize the interfaces of the various utilities

### ISSUE THREAD

**Issue by Arcterus** [uutils/coreutils#83]
For example, some utilities display errors like `utilname: error msg`, while others do it like `error: error msg`, while yet more do `error msg`.

IMHO, they should all be `utilname: error: error msg` or something of the sort.  That way, people will know which utility failed if multiple are executed in a shell script and for normal usage people will be able to tell that there was an error.

**Comment by tertsdiepraam** [comment]
I think this has been fixed for a while with the `show_{warning, error}` macros and `UResult` error handling.
