### ISSUE TITLE
Implement `tail -F`, which is the same as supplying both `-f` and `--retry`

### ISSUE THREAD

**Issue by fitzgen** [uutils/coreutils#848]
From `tail`'s man page:

```
       -F     same as --follow=name --retry
```

Depends on #847 to implement `--retry`.

**Comment by mrmiywj** [comment]
@fitzgen 
Hi, I read through the man page, it shows that --follow is allowed to be with `name` or `descriptor`, which means different ways to print the file. But our implementation, it looks like only `descriptor` mode is supported, which is not compatible with `--retry`.
I do think `name` and `descriptor` modes should be separated.

**Comment by mrmiywj** [comment]
Hmm, actually the files' metadata API is unstable now, is there any solution to know whether the file changes or not?
