### ISSUE TITLE
tail: -f only follows the last file

### ISSUE THREAD

**Issue by ProgVal** [uutils/coreutils#864]

**Comment by mdsn** [comment]
Hello, I got some code to fix this issue and follow multiple files. I'd like to get reviews on it as it's the first rust code I write.

**Comment by ProgVal** [comment]
My first Rust code was for this repo too :)

Feel free to send a PR

**Comment by ProgVal** [comment]
The `follow-multiple` branch on your repo looks good.
Could you write a test for this feature?

**Comment by mdsn** [comment]
Thank you, I will. I'll send the PR as it is, since it has some other issues I'd like to get some advice on, and follow up with commits for tests and other changes. Is that ok?

**Comment by awestroke** [comment]
Pull request: #890
