### ISSUE TITLE
Implement numfmt

### ISSUE THREAD

**Issue by smigle00** [uutils/coreutils#911]
I would like to implement numfmt utility.

**Comment by ykrivopalov** [comment]
it seems that this task is abandoned. I'll take it

**Comment by dirac3000** [comment]
Hi, is there a reason why this issue is still open?

**Comment by ykrivopalov** [comment]
Hi, util was implemented, but doesn't include all features, that GNU numfmt have.

**Comment by Arcterus** [comment]
The new policy is that unimplemented features should be opened as new issues, as I can understand how it's confusing having these "Implement X" issues still open when they already exist in the source tree.
