### ISSUE TITLE
Can I be added to the uutils organization?

### ISSUE THREAD

**Issue by nathanross** [uutils/coreutils#930]
* I've shown continual, rather than once-off dedication to the project's mission through continual contributions in the back-of-the-restaurant work of integration tests and tooling.
* I'm familiar with a lot of the codebase and with more complex aspects of rust, and think I'm in a good position to judge pull requests, especially those pertaining to integration tests. 
* I've made an effort to respond informatively, and only when I have something to add, to a not-small number of issues and think I could help with tagging them. 
* I've demonstrated continual adaptability to other contributors' suggestions on PRs I've made, and willingness to rework the code to address the concerns they have.

I couldn't find a better medium to ask this, so I'm asking here. @Arcterus @ebfe @jbcrail @mpkh

**Comment by mpkh** [comment]
If could vote I'd vote for this, so far only @jbcrail can make such changes

**Comment by knight42** [comment]
@mpkh Thanks :heart_eyes:! It is my great honor if I could join this project!

**Comment by Arcterus** [comment]
I just invited both of you to join, so I'm going to close this issue now.
