### ISSUE TITLE
Discussion: tracking issues on implemented utilities

### ISSUE THREAD

**Issue by nathanross** [uutils/coreutils#949]
Even for implemented utilities (where the *new impl claim* issue has closed), there are to-dos that definitely remain for them, such as:

1. writing integration tests for the utility
2. writing original help text and error messages for the utility (see #818)
3. reporting, and resolving bugs or incorrect behaviors in utilities.

As this work gets underway on these, it would be nice to be able to quickly ascertain, for a given utility, what remains to be done for it. Or, for a given issue that applies separately to multiple utilities, quickly ascertain which utilities it is resolved for.

Here are two ways we could do that. Please comment with if there is one you are in favor of, if you think these approaches are fine, or both are unnecessary, or to propose a different approach, etc. I'd be fine with either approach though I lean in favor of the second.

### Approach 1. Repurpose implementation claim issues to be general "tracking" issues for all bugs and enhancements to a utility 

In this approach, implementation claim issues will be repurposed to track all planned enhancements and bug reports for the utility.

Issues that apply separately to multiple utilities could be given their own tracking issues with checkmarks for each utility it needs to be resolved for.

### Approach 2. Use label categories to allow organization of labels across crossing axes (utility, purpose, etc)

An example category schema is below, it draws from those used by major rust projects (e.g. [servo](https://github.com/servo/servo/labels) and [rust](https://github.com/rust-lang/rust/labels)) so it will be familiar to many people in the rust community.

-  A - domain of the issue. Values are
    - **A-all**
    - **A-tooling**
    - **A-uucore**
    - **A-{{utility name}}** (one for each utility)
- C - issue status
    - **C-implemented** (closed, implemented)
    - **C-fixed** (closed, fixed)
    - **C-duplicate** (closed, duplicate)
    - **C-wontfix** (closed, non-goal of project)
- I - Purpose of issue
    - **I-crash**
    - **l-documentation**
    - **I-discussion**
    - **I-enhancement**
    - **I-incorrect**
    - **I-new util claim**
    - **I-perf-memory**
    - **I-perf-power**
    - **I-perf-slow**
    - **I-question**
    - **l-refactoring**
    - **l-tests**
    - **l-tracking** (for tracking a minor change that must be made to many utilities without having to create one issue for each utility)
- P - platform
    - **P-all**
    - **P-linux**
    - **P-macOS**
    - **P-windows GNU**
    - **P-windows MSVC**

**Comment by nathanross** [comment]
@Arcterus @ebfe @jbcrail @knight42 @mpkh summoning to see if there's any feedback on this

**Comment by mpkh** [comment]
I understand how first approach will help but not sure about second, still prefer second thought if you know that it will really help there.

**Comment by jbcrail** [comment]
I prefer the second approach since I've found projects (like Rust) that use this approach are easier to contribute to. It's especially helpful for newcomers to find issues that match their interest.

**Comment by knight42** [comment]
The second approach looks great, I am in favor of it.

**Comment by Arcterus** [comment]
I agree that the second approach is better.

**Comment by nathanross** [comment]
Alright, the second approach is the choice. 

I've created a category schema that I kept very close to the example schema given above, with some minor additions and differences, the key ones being:

- (A) is now (U), so that people now to the project don't have to scroll down so much to see what the other categories are.
- The label "low priority," had previously been used, so instead of deleting it, I grouped it with other "priority" labels into (B)
