### ISSUE TITLE
Fix chgrp

### ISSUE THREAD

**Issue by Anachron** [uutils/coreutils#982]
I am on mobile, so please forgive my bad bug report.

Inside chgrp the check for root is not sufficent:
if f == "/" && self.preserve_root && self.recursive {

One also has to check for // since that will be translated to / as well.

**Comment by knight42** [comment]
Good point :+1: ! Would you like to submit a PR?

**Comment by knight42** [comment]
@Anachron  I've opened a PR for this. Does it solve the problem?
