### ISSUE TITLE
unresolved import `nix::sys::termios`. Could not find `sys` in `nix`

### ISSUE THREAD

**Issue by zethra** [uutils/coreutils#990]
When building `more` I get this error
<pre>unresolved import `nix::sys::termios`. Could not find `sys` in `nix`.
src/more/more.rs:22:5
use nix::sys::termios;</pre>

I'm running Windows 10 and rust version 1.12 stable

**Comment by wimh** [comment]
I could reproduce that and created a pull request which should fix the error: #991 

Note that very little has been implemented. The status pages says: "[ ] more (in progress, needs lots of work)". On windows you even have to press enter after a space to scroll to the next page....

**Comment by nathanross** [comment]
@zethra if you still have similar trouble with more, let me know and this issue can be reopened

**Comment by zethra** [comment]
@nathanross Thank you.  I'll wait until more is more done.
